engine/hatchery/docker.go, engine/hatchery/http.go, engine/hatchery/swarm.go
Signed-off-by: Alexandre Paul <alexandre.paul@ovh.net>
=> Add if when fetch MAX_CONTAINER on config

README.md
=> fix(README): Typo in README.md

README.md
=> feat (doc): add caution in README

README.md
Signed-off-by: Thomas Maurice <thomas@maurice.fr>
=> fix(README): Typo. Make PostgreSQL well written again!

doc/overview/hatchery.md, doc/overview/model.md, doc/tutorials/first-hatchery.md, doc/tutorials/first-pipeline.md, engine/hatchery/main.go
Signed-off-by: Pierre Roullon <pierre.roullon@corp.ovh.com>
=> feat (hatchery): improve usage

doc/tutorials/link-cds-to-reposmanager.md
Signed-off-by: François Samin <francois.samin@corp.ovh.com>
=> chore (doc): add tutorials for stash and github

engine/api/application.go, engine/api/application/application.go, engine/api/application/application_pipeline.go, engine/api/application/application_variable.go, engine/api/application_pipeline.go, engine/api/application_variable.go, engine/api/keys/keys.go, engine/api/polling.go, engine/api/project.go, sdk/application.go
You have to merge this one too : https://github.com/ovh/cds-ui/pull/5
=> feat: return app updated + poller list after add/update/delete pollers

sdk/cli/cds/trigger/delete_params.go, sdk/cli/cds/trigger/list_params.go, sdk/cli/cds/trigger/params.go, sdk/cli/cds/trigger/show.go, sdk/cli/cds/trigger/trigger.go, sdk/cli/cds/trigger/update_params.go
Signed-off-by: Yannick briffa <yannick.briffa@corp.ovh.com>
=> feat: (cli) adds management trigger params

engine/api/application_group.go, engine/api/group/group.go, engine/api/pipeline/pipeline.go, engine/api/pipeline/pipeline_action.go, engine/api/pipeline/pipeline_importer.go, engine/api/pipeline/pipeline_stage.go, engine/api/pipeline_group.go, engine/api/pipeline_job.go, engine/api/pipeline_job_test.go, engine/api/project_group.go, sdk/job.go, sdk/stage.go
=> feat: return pipeline updated after add/update/delete pipeline permissions

engine/api/action.go, engine/api/action/action.go, engine/api/application.go, engine/api/application/application.go, engine/api/application/application_importer.go, engine/api/application/application_variable.go, engine/api/application_variable.go, engine/api/environment.go, engine/api/environment/environment.go, engine/api/environment_variable.go, engine/api/keys/keys.go, engine/api/keys/keys_test.go, engine/api/msg/messages.go, engine/api/pipeline/pipeline_action.go, engine/api/project/project.go, engine/api/project_variable.go, engine/api/scheduler/scheduler.go, engine/api/template/template.go, engine/api/templates.go, engine/api/worker/model_test.go, sdk/action_script.go, sdk/action_script_test.go
=> feat: refactor keys & default value to enabled attr in step : true

engine/api/application/application_importer.go
=> feat: allow adding a trigger in pipeline child (and not in parent)

engine/api/main.go, engine/api/testwithdb/test.go, engine/api/worker.go, engine/api/worker/worker.go, engine/api/worker_test.go, engine/worker/main.go, sdk/build.go, sdk/worker.go
...and downloading  plugin requirement...
=> feat (api, sdk, worker): status 'checking' for worker while checking queue

engine/worker/cmd_server.go, engine/worker/cmd_upload.go
=> fix: worker upload timeout vs timeout api

engine/api/pipeline/pipeline_build.go, engine/api/queue/run.go, sdk/parameter.go
:warning: Merge into pipelineHistory2
:roll_eyes:
=> feat (api): git url variable is inserted by InsertPipelineBuild from the repo manager

cli/cds/pipeline/hook.go, engine/api/repositories_manager.go
=> fix (api): delete hook in database, then try to delete hook on repomanager

engine/api/group/group.go, engine/api/group/public.go, engine/api/main.go, engine/api/user.go
=> feat (api): default group

engine/api/group/group.go
=> fix(api): default group if empty

engine/api/user/user.go
fix (api): user json is too big
=> fix (api): user json is too big

engine/api/mail/mail.go, engine/api/status.go
=> feat(api): refresh status mail

engine/api/pipeline/pipeline_build.go
=> fix(api): event success

sdk/bot/bot.go
=> feat (sdk): common func for bot

engine/api/build.go, engine/worker/builtin_junit.go, sdk/action.go, sdk/artifact.go, sdk/build.go, sdk/plugin.go, sdk/template.go, sdk/tests.go
=> fix (api): junit parser

cli/cds/pipeline/build.go, engine/worker/builtin_junit.go, engine/worker/builtin_junit_test.go
=> fix(api): junit compute

engine/venom/run/process.go
=> fix(venom): escape XML

cli/cds/action/remove.go, cli/cds/group/remove.go, cli/cds/project/remove.go, cli/cds/worker/model/remove.go, engine/venom/run/process.go, sdk/error.go, sdk/error_test.go, tests/cli_action.yml, tests/cli_application.yml, tests/cli_environment.yml, tests/cli_group.yml, tests/cli_pipeline.yml, tests/cli_project.yml, tests/cli_worker_model.yml, tests/sc_artifact.yml, tests/sc_branch_overwrite.yml, tests/sc_build_var_export.yml, tests/sc_builtin_action.yml, tests/sc_failing_pipeline.yml, tests/sc_git_hook.yml, tests/sc_join_action.yml, tests/sc_multiple_stage.yml, tests/sc_password_check.yml, tests/sc_right_exec_env.yml, tests/sc_ssh_keycheck.yml, tests/sc_trigger.yml, tests/sc_trigger_infinite_loop.yml
=> feat(tests): improve assert

sdk/group.go
=> fix(sdk): list group, avoid multiple calls

engine/api/action.go, engine/api/action/action.go
=> fix(api): delete action

tests/sc_branch_overwrite.yml, tests/sc_build_var_export.yml, tests/sc_multiple_stage.yml, tests/sc_password_check.yml, tests/sc_ssh_keycheck.yml, tests/sc_trigger.yml
=> fix: venom new assert result result.systemout

engine/api/action.go
=> fix(api): import action

AUTHORS
=> doc: update AUTHORS

contrib/plugins/plugin-venom/venom.go
=> doc(plugin-venom): extra step junit

engine/worker/builtin_junit.go, engine/worker/builtin_junit_test.go
=> fix (worker): default name for testSuite & testCase

engine/api/action/variable.go, engine/api/queue/queue.go, engine/api/suggest.go, engine/worker/run.go, tests/sc_builtin_action.yml
=> feat (api): add .cds.stage, .cds.worker and .cds.job

engine/api/build.go
=> fix (api): testsuite with same name: use a unique name

engine/api/application.go
=> fix (api): group on clone application

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/mesos/mesos.go, engine/hatchery/openstack/openstack.go, engine/hatchery/swarm/swarm.go, sdk/build.go, sdk/hatchery/register.go
hatchery marathon call sdk.GetWorkerModelStatus for each spawned app... 
=> fix (hatchery) : hatchery Marathon, avoid double call estimate 

contrib/plugins/plugin-kafka-publish/kafka.go
=> fix (plugin): plugin Kafka: config.Producer.Return.Successes = true

engine/api/repositoriesmanager/dao.go
=> fix (api): delete repo manager

engine/api/repositoriesmanager/repostash/client.go
=> fix (api): cache for unknown user

engine/api/build.go, engine/api/worker/gorp_model.go, engine/api/worker/model_test.go, engine/api/worker/worker.go, engine/api/worker/worker_test.go, engine/api/worker_model.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
=> fix (api): get worker models for hatcheries

engine/worker/main.go
=> fix(worker) : avoid registry after unregister

engine/worker/main.go
=> fix (worker): keep heartbeat if not single_use

engine/worker/main.go
=> fix(worker): init alive on start

engine/worker/main.go
=> fix(worker): sleep before check alive, avoid log

contrib/plugins/plugin-venom/venom.go
=> feat (plugin venom): add loglevel & details args

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/cmd.go, engine/hatchery/openstack/openstack.go, engine/hatchery/swarm/swarm.go, sdk/hatchery/hatchery.go, sdk/worker.go
=> feat (hatchery): provisioning workers

engine/hatchery/openstack/openstack.go
=> fix (hatcheryOpenStack): no cache for getServers

engine/worker/main.go
=> fix (worker): do not wait if no hatchery

cli/cds/dashboard/dashboard.go, cli/cds/dashboard/home.go, cli/cds/dashboard/monitoring.go, cli/cds/dashboard/status.go, cli/cds/dashboard/ui.go
=> feat (ui): improve layout status

engine/hatchery/marathon/marathon.go
=> fix (hatcheryMarathon): req memory

engine/api/build.go
=> feat (api): translate spawnworker in queue

engine/hatchery/marathon/marathon.go
=> feat (hatcheryMarathon): check in canSpawn

cli/cds/dashboard/status.go, cli/cds/dashboard/ui.go
=> feat (cli): add workers resume & status

engine/hatchery/swarm/swarm.go, vendor/github.com/fsouza/go-dockerclient/AUTHORS, vendor/github.com/fsouza/go-dockerclient/LICENSE, vendor/github.com/fsouza/go-dockerclient/appveyor.yml, vendor/github.com/fsouza/go-dockerclient/auth.go, vendor/github.com/fsouza/go-dockerclient/client.go, vendor/github.com/fsouza/go-dockerclient/client_unix.go, vendor/github.com/fsouza/go-dockerclient/client_windows.go, vendor/github.com/fsouza/go-dockerclient/container.go, vendor/github.com/fsouza/go-dockerclient/exec.go, vendor/github.com/fsouza/go-dockerclient/image.go, vendor/github.com/fsouza/go-dockerclient/network.go, vendor/github.com/fsouza/go-dockerclient/node.go, vendor/github.com/fsouza/go-dockerclient/service.go, vendor/github.com/fsouza/go-dockerclient/swarm.go, vendor/github.com/fsouza/go-dockerclient/volume.go, vendor/vendor.json
=> fix (hatchery): update dockerclient lib

engine/hatchery/swarm/swarm.go, vendor/github.com/fsouza/go-dockerclient/network.go
=> feat (hatcherySwarm): more logs, new network attr

engine/hatchery/swarm/swarm.go
=> fix (hatcherySwarm): disabled remove network

engine/hatchery/docker/cmd.go, engine/hatchery/docker/docker.go, engine/hatchery/local/cmd.go, engine/hatchery/local/local.go, engine/hatchery/main.go, engine/hatchery/marathon/cmd.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/cmd.go, engine/hatchery/openstack/openstack.go, engine/hatchery/swarm/cmd.go, engine/hatchery/swarm/swarm.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
=> refactor (hatchery): common check before specifical check canSpawn

sdk/hatchery/hatchery.go
=> fix (hatchery): compute canSpawn Binary

engine/api/worker/heartbeat.go
=> fix (api): WorkerHeartbeatTimeout -> 20min

cli/cds/dashboard/ui.go
=> fix (ui): header shortcut

engine/api/auth/auth.go
=> feat (api): log username auth failed

engine/api/pipeline.go, engine/api/pipeline/pipeline_build.go, engine/api/pipeline/pipeline_build_job.go, engine/api/worker/worker.go
=> fix (api): stop pipeline with waiting job

cli/cds/dashboard/monitoring.go
=> feat (cli): monitoring view: compact stage failed / success

tests/cli_action.yml, tests/cli_application.yml, tests/cli_environment.yml, tests/cli_group.yml, tests/cli_pipeline.yml, tests/cli_pipeline_export_import.yml, tests/cli_project.yml, tests/cli_user.yml, tests/cli_version.yml, tests/cli_worker_model.yml, tests/sc_artifact.yml, tests/sc_branch_overwrite.yml, tests/sc_build_var_export.yml, tests/sc_builtin_action.yml, tests/sc_failing_pipeline.yml, tests/sc_git_hook.yml, tests/sc_gitclone.yml, tests/sc_join_action.yml, tests/sc_multiple_stage.yml, tests/sc_password_check.yml, tests/sc_right_exec_env.yml, tests/sc_ssh_keycheck.yml, tests/sc_trigger.yml, tests/sc_trigger_infinite_loop.yml
=> test (api): use .cds.build... var to use with CDS plugin-venom

engine/hatchery/openstack/openstack.go
=> fix (hatchery): openstack - wait 10

LICENSE, README.md, engine/api/README.md
=> doc: fix link

engine/api/main_init.go
=> fix (api): remove db.log from toml config

engine/hatchery/openstack/cmd.go
=> fix (hatcheryCloud): default value for flag openstack-ip-range

engine/hatchery/openstack/cmd.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/openstack_test.go
=> feat (hatcheryCloud): allow many networks

contrib/plugins/plugin-download/README.md, contrib/plugins/plugin-download/download.go, contrib/plugins/plugin-download/download_test.go
=> feat (contrib/plugins): add plugin download

contrib/plugins/plugin-download/download.go, contrib/plugins/plugin-marathon/marathon.go
=> fix (plugin): vet & name

contrib/templates/README.md, contrib/templates/cds-template-deploy-marathon-app/README.md, contrib/templates/cds-template-deploy-marathon-app/template.go, contrib/templates/cds-template-plain/README.md
=> feat (template): new template cds-template-deploy-marathon-app

ui/src/app/model/worker.model.ts, ui/src/app/service/services.module.ts, ui/src/app/service/worker/worker.model.service.ts, ui/src/app/shared/action/action.component.spec.ts, ui/src/app/shared/action/action.component.ts, ui/src/app/shared/requirements/form/requirements.form.component.ts, ui/src/app/shared/requirements/form/requirements.form.html, ui/src/app/shared/requirements/form/requirements.form.spec.ts, ui/src/app/shared/requirements/list/requirements.list.component.spec.ts, ui/src/app/shared/requirements/list/requirements.list.component.ts, ui/src/app/shared/requirements/list/requirements.list.html
=> feat (ui): display a list of worker model in action requirement.

contrib/templates/cds-template-deploy-marathon-app/template.go, contrib/templates/cds-template-only-git-clone-job/.gitignore, contrib/templates/cds-template-only-git-clone-job/README.md, contrib/templates/cds-template-only-git-clone-job/template.go, contrib/templates/cds-template-plain/template.go
=> feat (template): template with a simple GitClone Step

ui/src/app/views/pipeline/show/pipeline.show.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix (ui): key pipeline_application

engine/api/action/children.go, engine/api/pipeline/pipeline_action.go, engine/api/templates.go
=> fix (api): import pipeline -> import parameter + parameter type list default value

contrib/actions/cds-go-build.hcl, contrib/templates/cds-template-cds-plugin/.gitignore, contrib/templates/cds-template-cds-plugin/README.md, contrib/templates/cds-template-cds-plugin/template.go, contrib/templates/cds-template-cds-template/.gitignore, contrib/templates/cds-template-cds-template/README.md, contrib/templates/cds-template-cds-template/template.go
add GOPATH to CDS_GoBuild: this allow user to set a GOPATH != GOPATH from worker host
=> feat(templates): build plugin / template, review CDS_GoBuild

engine/api/scheduler_test.go, engine/api/templateextension/templateextension.go, engine/api/templates_test.go
=> fix (*): ineffassign

vendor/github.com/gambol99/go-marathon/application.go, vendor/github.com/gambol99/go-marathon/client.go, vendor/github.com/gambol99/go-marathon/cluster.go, vendor/github.com/gambol99/go-marathon/events.go, vendor/github.com/gambol99/go-marathon/health.go, vendor/vendor.json
Signed-off-by: François Samin <francois.samin@corp.ovh.com>
=> fix (vendor): go-marathon healthcheck

ui/src/app/app.component.ts, ui/src/app/service/notification/notification.service.ts, ui/src/app/service/notification/notification.type.ts, ui/src/app/service/services.module.ts, ui/src/app/views/application/show/workflow/application.workflow.component.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.spec.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts, ui/src/app/views/run/workflow/workflow.component.ts, ui/src/app/views/run/workflow/workflow.spec.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
Display a push notification in browser when your build status change to 'Failing' or 'Success'
=> feat(ui): add push notification on pipeline status

ui/src/app/views/pipeline/show/admin/pipeline.admin.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
Not really inspired for the title, if you have better idea let me know :)  🍺
=> fix(ui): fix typo in header of pipeline admin

engine/hatchery/openstack/cmd.go, engine/hatchery/openstack/openstack.go
=> feat (hatcheryCloud): remember spawned ip

engine/api/repositoriesmanager/events.go
=> fix (api): remove sleep before retry

sdk/action_script.go, sdk/action_script_test.go
=> fix (api): hcl, allow use gitClone

sdk/action_script_test.go
=> test: fix check gitClone params

doc/tutorials/run-with-docker-compose.md, doc/tutorials/variables.md
=> doc: add more on docker-compose tutorial

.gitignore, ui/package.json
Could be interesting for contributors in order to understand code architecture of the UI :)
=> docs(ui): add compodoc to visualise ui architecture

contrib/plugins/plugin-kafka-publish/plugin.go, contrib/templates/cds-template-deploy-marathon-app/template.go, docs/content/building-pipelines/building-pipelines.variables.md, docs/content/installation/installation.ready-to-run.docker-compose.md
=> doc (*): fix mispells

sdk/action_script_test.go
=> test (sdk): CDS_GitClone -> now a builtin action.

engine/api/trigger/trigger.go
Examples:
not gh-pages
not (gh-pages|devfoo)
=> feat (api): allow "not " in trigger condition.

sdk/plugin/dummy/dummy_plugin.go
=> fix (plugin): fix pointer receiver

tests/sc_gitclone.yml
=> fix (test): assert with .cds.workspace on url param

docs/content/advanced/advanced.worker.md
These are just minor corrections on a few words that hit my eyes while reading ;)
By the way: great work on the documentation and the nice drawings !
=> Minor grammatical fixes

contrib/actions/cds-go-build.hcl
usefull for build CDS worker and run it on alpine
=> feat (action): CDS_GoBuild with CGO_ENABLED

engine/api/pipeline/pipeline_importer.go, tests/cli_pipeline_export_import.yml
=> fix (test): clean prj before add / user output on err

engine/api/pipeline/pipeline_importer.go
=> fix (test): output err to user

cli/cds/worker/model/list.go, engine/api/action.go, engine/api/database/cli.go, engine/api/database/database.go, engine/api/main_routes.go, engine/api/pipeline.go, engine/api/pipeline_job.go, engine/api/worker/model.go, engine/api/worker/worker.go, engine/api/worker_model.go, engine/hatchery/docker/cmd.go, engine/hatchery/docker/docker.go, engine/hatchery/local/cmd.go, engine/hatchery/local/local.go, engine/hatchery/main.go, engine/hatchery/marathon/cmd.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/cmd.go, engine/hatchery/openstack/openstack.go, engine/hatchery/swarm/cmd.go, engine/hatchery/swarm/swarm.go, engine/sql/018_worker_model.sql, engine/worker/register.go, sdk/action.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go, sdk/worker.go
=> feat (worker, api, hatchery): auto-update w model

engine/hatchery/swarm/swarm.go
=> fix (hatchery): swarm - fix regsiter only worker

engine/hatchery/openstack/init.go, engine/hatchery/openstack/ip.go, engine/hatchery/openstack/spawn.go
=> fix (hatcheryOpenstack): check err

engine/hatchery/openstack/ip.go
=> fix (hatcheryOpenstack): compute ip

engine/hatchery/openstack/cmd.go, engine/hatchery/openstack/ip.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go, sdk/hatchery/register.go
=> feat (hatchery): call worker register if wm UserLastModified > LastRegistration

engine/hatchery/openstack/get.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go, sdk/hatchery/hatchery.go
=> feat (hatcheryOpenstack): more logs if cannot spawn worker

engine/hatchery/openstack/ip.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go
=> feat (hatcheryOpenstack): more logs if err on create

engine/hatchery/openstack/spawn.go
=> feat (hatcheryOpenstack): CDS_FROM_WORKER_IMAGE in udata

engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go
=> feat (hatcheryCloud): add worker_model_last_modified on image

engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go
=> feat (hatcheryOpenstack): use bash

ui/src/app/views/navbar/navbar.html
=> fix (ui): check current user

ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/app/views/settings/worker-model/list/worker-model.list.html
Check admin or admin on grp to show btn
=> fix (ui): settings / worker models

cli/cds/dashboard/monitoring.go
=> fix (cli): Internal Events Queue color

engine/api/templates.go, ui/src/app/service/application/application.store.ts, ui/src/app/service/project/project.store.ts
=> fix (api, ui): load prj after create first app with pipeline

cli/cds/admin/plugin/plugin.go, engine/api/actionplugin/plugin.go, engine/api/plugin.go, sdk/plugin/common.go, sdk/plugin/plugin.go
=> fix (api): add / update plugin

ui/karma.conf.js, ui/src/app/model/action.model.ts, ui/src/app/service/action/action.service.ts, ui/src/app/shared/action/action.component.spec.ts, ui/src/app/shared/action/action.component.ts, ui/src/app/shared/action/action.html, ui/src/app/shared/action/action.scss, ui/src/app/shared/button/delete/delete.button.ts, ui/src/app/shared/button/delete/delete.html, ui/src/app/shared/parameter/form/parameter.form.html, ui/src/app/shared/parameter/form/parameter.form.spec.ts, ui/src/app/views/pipeline/show/workflow/stage/pipeline.stage.component.ts, ui/src/app/views/settings/action/add/action.add.component.ts, ui/src/app/views/settings/action/add/action.add.html, ui/src/app/views/settings/action/add/action.add.scss, ui/src/app/views/settings/action/edit/action.edit.component.ts, ui/src/app/views/settings/action/edit/action.edit.html, ui/src/app/views/settings/settings.module.ts, ui/src/app/views/settings/settings.routing.ts, ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/add/worker-model.add.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json, ui/src/test.ts
=> fix (ui): create & update an action

engine/api/group/group.go, engine/api/main_routes.go, engine/api/user.go, ui/src/app/model/group.model.ts, ui/src/app/service/user/user.service.ts, ui/src/app/views/settings/user/edit/user.edit.component.ts, ui/src/app/views/settings/user/edit/user.edit.html
new endpoint /user/{username}/groups
close #683
=> feat (api, cli): display groups on user settings

ui/src/app/shared/action/action.component.spec.ts
=> fix (ui): test check addbtn

engine/api/build.go, engine/api/main_routes.go, engine/api/router.go, engine/worker/cmd_main.go, engine/worker/polling.go, engine/worker/requirement.go, sdk/messages.go
=> feat (worker, api): spawn infos err prerequisites

engine/worker/cmd_main.go, engine/worker/requirement.go
=> fix (worker): use checkRequirements on wjobs

contrib/actions/cds-docker-package.hcl
You can use such variables in a script:
echo {{.cds.build.image.id}}
echo {{.cds.build.image.digest}}
=> feat (contrib/action): Update cds-docker-package.hcl #755

contrib/plugins/plugin-venom/venom.go, engine/worker/cmd_upload.go
=> fix (worker): upload and add logs

contrib/plugins/plugin-venom/README.md, contrib/plugins/plugin-venom/venom.go
IT CDS Tests with plugin-venom are ok with this PR.
=> feat (plugin/venom): let limit rewriting some vars

sdk/exportentities/pipeline.go, sdk/exportentities/pipeline_test.go
=> fix (sdk): import pipeline with only 1 job with requirements

ui/src/app/model/action.model.ts, ui/src/app/shared/action/action.component.ts, ui/src/app/shared/action/action.html, ui/src/app/shared/action/action.scss, ui/src/app/shared/action/step/form/step.form.component.spec.ts, ui/src/app/shared/action/step/form/step.form.component.ts, ui/src/app/shared/action/step/form/step.form.html, ui/src/app/shared/action/step/form/step.form.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (ui): new add step box

cli/cds/application/list.go
=> fix (cli): consistent list display #748

ui/src/app/views/navbar/navbar.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (ui): home click

ui/src/app/service/warning/warning.store.ts
=> fix (ui): new warningUI()

engine/api/application/application_group.go, engine/api/group/application_group.go, engine/api/project_group.go
=> fix (api): update lastModified app on add grp

ui/src/app/views/project/add/project.add.html
=> fix (ui): check group

ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
=> fix(ui): fix pipeline workflow settings

vendor/github.com/ovh/go-ovh/LICENSE, vendor/github.com/ovh/go-ovh/ovh/configuration.go, vendor/github.com/ovh/go-ovh/ovh/consumer_key.go, vendor/github.com/ovh/go-ovh/ovh/error.go, vendor/github.com/ovh/go-ovh/ovh/ovh.go, vendor/github.com/runabove/venom/executors/ovhapi/README.md, vendor/github.com/runabove/venom/executors/ovhapi/executor.go, vendor/gopkg.in/ini.v1/LICENSE, vendor/gopkg.in/ini.v1/Makefile, vendor/gopkg.in/ini.v1/README.md, vendor/gopkg.in/ini.v1/README_ZH.md, vendor/gopkg.in/ini.v1/error.go, vendor/gopkg.in/ini.v1/ini.go, vendor/gopkg.in/ini.v1/key.go, vendor/gopkg.in/ini.v1/parser.go, vendor/gopkg.in/ini.v1/section.go, vendor/gopkg.in/ini.v1/struct.go, vendor/vendor.json
=> chore: update plugin-venom vendor

ui/package.json, ui/src/app/shared/shared.module.ts, ui/src/app/views/run/pipeline.build.html
=> feat (ui): logs autoscroll

engine/worker/cmd_server.go, engine/worker/cmd_tmpl.go, engine/worker/main.go, engine/worker/run.go
=> feat (worker): tmpl builtin command

ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.html
=> feat(ui): add done date of pipeline

engine/api/repositories_manager.go, ui/src/app/model/repositories.model.ts, ui/src/app/shared/parameter/list/parameter.component.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.html
=> fix(ui): fix create hook and poller when you haven't ability

engine/api/environment/environment_variable.go, engine/api/project/project_variable.go
=> fix(api): password variable name update is now enabled

cli/cds/project/info.go, sdk/project.go
=> feat(cli): add more infos for project info #844

ui/src/app/views/application/show/admin/repository/application.repo.component.ts, ui/src/app/views/application/show/admin/repository/application.repo.html
=> fix (ui): fix first loading of repository in admin

ui/src/app/service/notification/notification.service.ts
=> fix(ui): don't crash the app when notification is blocked

engine/api/action/children.go, engine/api/action/requirement.go, engine/api/pipeline.go, engine/api/pipeline/pipeline.go, engine/api/pipeline/pipeline_action.go, engine/api/pipeline/pipeline_stage.go, engine/api/pipeline_group.go, engine/api/pipeline_job.go, engine/api/pipeline_parameter.go, engine/api/stage.go, engine/api/worker_model.go
do not squash several commits in there
=> fix-2017-07-18-15-07-26

ui/src/app/service/auth/authenAdminRouteActivate.ts, ui/src/app/service/auth/authenRouteActivate.ts, ui/src/app/service/http-service.service.ts, ui/src/app/views/account/login/login.component.spec.ts, ui/src/app/views/account/login/login.component.ts
=> feat(ui): add redirection when you are not logged

engine/api/application.go, engine/api/application_group.go, engine/api/application_pipeline.go, engine/api/application_pipeline_notif_test.go, engine/api/application_variable.go, engine/api/businesscontext/context.go, engine/api/environment_group.go, engine/api/pipeline.go, engine/api/pipeline_parameter.go, engine/api/project.go, engine/api/project_group.go, engine/api/project_notif.go, engine/api/project_variable.go, engine/api/repositories_manager.go, engine/api/router.go, engine/api/scheduler.go
This reverts commit 1579b8f53c29b40dccf3d1888a0fd50b8ce779f7.
=> fix (api): Revert "feat (api): make business context great again (#866)"

engine/api/environment/environment_variable.go, ui/package.json, ui/src/app/app.component.ts, ui/src/app/views/project/show/environment/list/item/environment.component.ts, ui/src/app/views/workflow/graph/workflow.graph.component.ts
=> fix (api): Error 500 on addVariableInEnvironmentHandler on conflicts #680

engine/api/cache/redis.go, engine/api/lastupdate.go, ui/src/app/app.component.ts, ui/src/app/views/application/show/application.component.ts, ui/src/app/views/pipeline/show/pipeline.show.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(api): fix bug with redis

ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts
=> fix(ui): boolean pipeline parameters on trigger form

cli/cds/application/variable.go, cli/cds/environment/variable.go, cli/cds/project/variable.go
=> feat(cli): add --force on variable add #786

ui/src/app/views/application/show/workflow/application.workflow.component.ts
=> fix (ui): save orientation in localStorage #897

sdk/vcs/git/git.go
when a opts.CheckoutCommit is set
=> feat (worker): add log on git clone

ui/resources/cds-hint.js, ui/src/app/shared/parameter/value/parameter.value.component.ts
=> fix (ui): }} in script editor #924

engine/api/notification/user.go, engine/worker/builtin_junit.go, engine/worker/cmd_export.go, sdk/build.go
=> fix (api,worker): url.QueryEscape envName

vendor/github.com/fsamin/go-dump/README.md, vendor/github.com/fsamin/go-dump/dump.go, vendor/github.com/mndrix/tap-go/LICENSE, vendor/github.com/mndrix/tap-go/Makefile, vendor/github.com/mndrix/tap-go/README.md, vendor/github.com/mndrix/tap-go/tap.go, vendor/github.com/runabove/venom/assertion.go, vendor/github.com/runabove/venom/executors/http/README.md, vendor/github.com/runabove/venom/executors/imap/README.md, vendor/github.com/runabove/venom/executors/imap/executor.go, vendor/github.com/runabove/venom/venom.go, vendor/vendor.json
=> chore: update venom / go-dump

engine/api/pipeline/pipeline_stage.go
As it was done on trigger condition
=> feat (api): allow 'not foo' in stage condition

engine/hatchery/main.go, vendor/github.com/google/gops/LICENSE, vendor/github.com/google/gops/agent/agent.go, vendor/github.com/google/gops/internal/internal.go, vendor/github.com/google/gops/signal/signal.go, vendor/vendor.json
=> feat (hatchery): debug with gops

engine/api/environment.go, engine/api/main_routes.go, sdk/environment.go, ui/src/app/service/project/project.service.ts, ui/src/app/service/project/project.store.ts, ui/src/app/views/project/show/environment/list/item/environment.component.ts, ui/src/app/views/project/show/environment/list/item/environment.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): add the ability to clone an environment

engine/hatchery/docker/cmd.go, engine/hatchery/local/cmd.go, engine/hatchery/main.go, engine/hatchery/marathon/cmd.go, engine/hatchery/openstack/cmd.go, engine/hatchery/swarm/cmd.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
=> feat (hatchery): use provision from worker model

docker-compose.yml, docs/content/advanced/advanced.hatcheries.swarm.md, engine/hatchery/openstack/cmd.go
=> doc (hatchery): remove CDS_PROVISION

ui/src/app/app.service.ts
=> fix(ui): fix cache for applications linked to pipeline

ui/src/assets/worker/common.js
=> fix(ui): stop webworker when 404

cli/cds/pipeline/parameter.go, engine/api/pipeline/pipeline_parameter.go, sdk/pipeline.go, tests/cli_pipeline.yml
=> fix(cli): fix update pipeline param

ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.spec.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.html, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.scss
=> feat(ui): add the ability to stop a pipeline from workflow

engine/api/application.go, engine/api/application/dao.go
=> fix (api): create app with a existing name #912

ui/src/app/views/project/show/admin/repomanager/form/project.repomanager.form.component.ts, ui/src/app/views/project/show/admin/repomanager/form/project.repomanager.form.html, ui/src/app/views/project/show/admin/repomanager/form/project.repomanager.form.spec.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
IMO there is a mistake here. But I'm not sure about that. In my personal computer it doesn't make sense to hide this when the name is github. But should we display this input code for bitbucket too ? 
Maybe @sguiheux could help me about that :) 
=> fix(ui): link github to project

cli/cds/admin/repositoriesmanager/add.go, cli/cds/admin/repositoriesmanager/list.go, cli/cds/admin/repositoriesmanager/repositories_manager.go, docs/content/advanced/advanced.repositories_manager.github.md, engine/api/repositories_manager.go, engine/api/repositoriesmanager/repogithub/oauth.go, engine/api/repositoriesmanager/repositories_manager.go, sdk/repositories_manager.go, ui/src/app/views/project/show/admin/repomanager/form/project.repomanager.form.html
=> fix (api): loading client-secret for github

engine/api/router.go
=> feat (api): useful logs in router

ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.html, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.scss
=> fix(ui): fix style of stop button

cli/cds/ui/monitoring.go
=> fix (cli): url on new UI (enter key on a job)

engine/api/project.go
=> fix(api): display good error when you delete a project with app #705

docs/content/introduction/introduction.concepts.step.md
=> docs(concepts): fix style

engine/worker/builtin.go, engine/worker/builtin_script.go, engine/worker/cmd_main.go, engine/worker/requirement.go, engine/worker/run.go
=> feat (worker): use basedir for tmpfile too.

ui/src/app/views/application/show/application.component.ts, ui/src/app/views/application/show/application.html, ui/src/app/views/application/show/workflow/application.workflow.component.ts, ui/src/app/views/run/pipeline.build.component.ts
=> fix(ui): fix display logs with history

engine/hatchery/cmd_version.go, engine/hatchery/main.go
=> feat (hatchery): version cmd

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/main.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go
=> fix (hatchery): use new graylog attr for worker

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/main.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go
=> feat (hatchery): grpc flag

sdk/hatchery/hatchery.go, sdk/hatchery/register.go
allow spawn event if wm is in error, if hatchery group = worker model group
=> feat (hatchery): hatchery grp=wm grp->alway spawn

engine/api/poller/cleaner.go, engine/api/poller/dao.go, engine/api/poller/dao_execution.go, engine/api/poller/executer.go, engine/api/poller/gorp_model.go
=> refactor (api): wrap on poller pck

ui/src/app/shared/pipeline/launch/pipeline.launch.modal.component.ts
=> fix(ui): fix list parameters on launch modal

ui/src/app/views/settings/worker-model/list/worker-model.list.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (ui): warn icon on err wm

engine/api/pipeline/pipeline_build_job.go, engine/api/poller/cleaner.go, engine/api/queue/queue.go, engine/api/queue/run.go, engine/api/scheduler/cleaner.go, engine/api/scheduler/executer.go, engine/api/scheduler/gorp_model.go, engine/api/scheduler/scheduler.go
=> refactor(api): queue wrap log

engine/hatchery/swarm/swarm.go
=> fix (hatchery/swarm): useful logs

sdk/exportentities/pipeline.go, sdk/exportentities/pipeline_test.go
=> fix(api): fix import for new flags

contrib/actions/ovh-publish-metrics
This action push metrics to an OVH Metrics Data Platform account
=> feat(action): add ovh-publish-metrics

engine/hatchery/openstack/init.go, engine/hatchery/swarm/swarm.go, sdk/cdsclient/client_hatchery.go, sdk/cdsclient/interface.go, sdk/hatchery/register.go
=> fix (hatchery): uptodate version

contrib/actions/cds-publish-ovh-metrics.hcl
=> refactor (action): rename ovh public metrics

ui/src/app/service/pipeline/pipeline.service.ts, ui/src/app/views/warnings/show/warning.show.html
=> fix (ui): job url warning

docs/build.sh, docs/content/building-pipelines/building-pipelines.actions.plugins.plugin-venom.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-go-build.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-perl-test.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-publish-ovh-metrics.md
=> doc (actions): regenerate doc

sdk/version.go
=> fix: version. -ldflags "-X..." -> var

engine/api/queue/queue.go, vendor/github.com/docker/docker/pkg/namesgenerator/names-generator.go
and dedicace to our new maintainer :)
=> fix (api): timeout sql

engine/worker/builtin.go
=> fix (worker): cds.build.cds.build.a -> cds.build.a

engine/api/sanity/dao.go
=> feat (api): show warnings fo RWX group only

engine/api/application_key_test.go
Signed-off-by: François SAMIN <francois.samin@gmail.com>
=> test (api): fix assert lib which isn't vendored

engine/worker/builtin.go, sdk/plugin/common.go, sdk/plugin/types.go
=> fix (plugin): sendLog

ui/src/app/service/application/application.service.ts
=> fix (ui): add scheduler without an environment

cli/cds/ui/monitoring.go, cli/cds/worker/worker.go, cli/cdsctl/monitoring.go, engine/api/build.go, engine/api/main_routes.go, engine/api/router.go, engine/api/worker.go, engine/api/worker/worker.go, engine/api/worker_model.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, engine/worker/cmd_main.go, engine/worker/cmd_register.go, engine/worker/init.go, engine/worker/main.go, engine/worker/register.go, engine/worker/requirement.go, sdk/cdsclient/client_worker.go, sdk/cdsclient/interface.go, sdk/hatchery/worker.go, sdk/worker.go
=> fix (worker): check if model can run job (grps)

engine/worker/builtin_artifact.go, engine/worker/builtin_script.go
=> feat (action): builtin script: set -e default

contrib/actions/cds-python-pylint.hcl
Hello,
I'll need to do a python pep8 check on multiple applications, I've written an action to do it properly with pylint. 
Louis
=> feat (action): action CDS_PythonPylint

cli/cds/pipeline/show.go, sdk/pipeline.go
=> fix(cli): fix pipeline show with attached applications

engine/api/environment_import.go
=> fix (api): wrap log env import

cli/cds/environment/import.go, engine/api/environment/environment_importer.go, engine/api/environment_import.go
=> fix (api, cli): pipeline import into. Closes #1001

contrib/plugins/plugin-kafka-publish/README.md
Fixes for README of plugin-kafka-publish
Signed-off-by: Paweł Sadowski <pawel.sadowski@corp.ovh.com>
=> plugin-kafka-publish README.md fixes

engine/api/environment_key_test.go, engine/api/keys/keys_test.go, engine/api/project_key_test.go
=> test(api): change imports for assert

engine/worker/cmd_main.go, engine/worker/take_pipeline_build_job.go
=> fix (worker): avoid worker zombie, pbJob only

ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.html
=> fix (ui): hide rollback for now

docs/content/tutorials/tutorials.worker-model-openstack.md, docs/content/tutorials/tutorials.worker-model-vsphere.md
=> doc: no need to declare capabilities anymore

engine/api/worker/model.go, engine/api/worker_model.go, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
and save worker model when disable / enable it
=> fix (api,ui): clear NbSpawnErr when updating wm

ui/src/app/service/logout.interceptor.service.ts
=> fix (ui): display err on http > 401

docs/content/building-pipelines/building-pipelines.actions.builtin.script.md
=> doc (action): builtin script - set -e

ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix (ui): trad workflow

ui/src/app/views/project/project.module.ts
api will be dev after refacto starter
=> feat (ui): workflows list

ui/src/app/views/project/show/project.spec.ts
=> fix (ui): TU project

ui/src/app/app.component.spec.ts
=> test(ui): explicitly declare AuthentificationStore

ui/e2e/create.project.template
and this avoid it failed with fuzzy search, on a db with existing data
=> test (ui): create group: use default value

vendor/github.com/yesnault/go-toml/LICENSE, vendor/github.com/yesnault/go-toml/README.md, vendor/github.com/yesnault/go-toml/benchmark.json, vendor/github.com/yesnault/go-toml/benchmark.sh, vendor/github.com/yesnault/go-toml/benchmark.toml, vendor/github.com/yesnault/go-toml/benchmark.yml, vendor/github.com/yesnault/go-toml/doc.go, vendor/github.com/yesnault/go-toml/example-crlf.toml, vendor/github.com/yesnault/go-toml/example.toml, vendor/github.com/yesnault/go-toml/keysparsing.go, vendor/github.com/yesnault/go-toml/lexer.go, vendor/github.com/yesnault/go-toml/marshal.go, vendor/github.com/yesnault/go-toml/marshal_test.toml, vendor/github.com/yesnault/go-toml/parser.go, vendor/github.com/yesnault/go-toml/position.go, vendor/github.com/yesnault/go-toml/test.sh, vendor/github.com/yesnault/go-toml/token.go, vendor/github.com/yesnault/go-toml/toml.go, vendor/github.com/yesnault/go-toml/tomltree_create.go, vendor/github.com/yesnault/go-toml/tomltree_write.go, vendor/vendor.json
=> chore: toml with comment

engine/api/workflow/dao_node.go
=> fix (api): workflows - load cds.app

ui/e2e/create.application.template, ui/e2e/create.pipeline.template, ui/e2e/create.project.template, ui/e2e/create.workflow.template, ui/e2e/login.template
=> test (ui): sort screenshots

vendor/github.com/ovh/venom/README.md, vendor/github.com/ovh/venom/executors/imap/decode.go, vendor/github.com/ovh/venom/venom.go, vendor/vendor.json
=> chore: vendor venom

engine/Makefile
=> chore: use tests.cfg.json if exists

engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go
=> fix(api): sync stage workflow

ui/src/app/views/navbar/navbar.component.ts, ui/src/app/views/navbar/navbar.html, ui/src/assets/i18n/en.json
header project list / recent / search
for "normal user" (not admin), project list is really usefull
recently viewed and then search -> this encourages users to use the latest, and it's great (as more useful than search)
=> feat (ui): more consistent menu

engine/sql/037_idx_status_pipeline_build.sql
=> fix (api): index on pipeline_build.status

engine/worker/builtin_artifact.go, sdk/cdsclient/client.go, sdk/cdsclient/http.go
=> fix (sdk): no timeout on stream

sdk/cdsclient/client.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/http.go
=> fix (sdk): stream -> use timeout or not

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/init.go, engine/hatchery/swarm/swarm.go, engine/hatchery/vsphere/init.go, engine/worker/init.go, sdk/cdsclient/client.go, sdk/cdsclient/http.go
=> feat (sdk): add optional name

engine/Makefile
=> chore (make): add sql.tar.gz on make build

engine/api/workflow/execute_node_job_run.go
=> fix (api): var workflows

cli/cds/user/reset.go, cli/cdsctl/user.go, engine/api/mail/mail.go, sdk/cdsclient/client_user.go, sdk/cdsclient/interface.go
=> fix (sdk, cdsctl): user reset & user confirm

engine/api/workflow/execute_node_job_run.go
=> fix (api): workflow var prefix

cli/cdsctl/login.go
=> fix (cdsctl): cds login - remove double question

engine/api/api.go
=> fix (api): need x on dir to be w/r on host

cli/cds/artifact/upload.go, cli/cdsctl/user.go, cli/cdsctl/workflow.go, cli/cdsctl/workflow_artifact.go, cli/cobra.go, cli/types.go, engine/worker/builtin_artifact.go, sdk/artifact.go
=> feat (cdsctl): workflow artifact list | download

cli/cdsctl/application.go, cli/cdsctl/application_key.go, cli/cdsctl/environment.go, cli/cdsctl/environment_key.go, cli/cdsctl/project.go, cli/cdsctl/project_key.go, cli/cdsctl/workflow.go
=> feat (cdsctl): use dash in arg

cli/cdsctl/application.go, sdk/cdsclient/client_application.go
=> feat (cdsctl): cdsctl application create / delete

cli/cdsctl/main.go, cli/cdsctl/version.go, engine/api/status.go, sdk/cdsclient/client_version.go, sdk/cdsclient/interface.go, sdk/version.go
=> feat (cdsctl): version

engine/worker/builtin_artifact.go
=> feat (worker): more logs on artifact download

cli/cdsctl/Makefile
=> chore (cdsctl): makefile

engine/api/api_routes.go
=> feat (api): download routes

engine/Dockerfile
=> chore (engine): dockerfile

engine/types.go
=> fix (hatchery): conf key

engine/config.go, engine/types.go
=> fix (api): env variables load

cli/cdsctl/Makefile, contrib/plugins/Makefile, engine/Makefile, engine/worker/Makefile
=> chore: use semver per default in Makefile

engine/worker/builtin_gitclone.go
=> feat (gitClone): 0.0.1 -> default semver if no tag

engine/api/api.go, engine/types.go, vendor/github.com/yesnault/go-toml/marshal.go, vendor/github.com/yesnault/go-toml/parser.go, vendor/github.com/yesnault/go-toml/toml.go, vendor/github.com/yesnault/go-toml/tomltree_write.go, vendor/vendor.json
=> fix (conf): comment on conf file

engine/worker/Dockerfile
=> chore (worker): dockerfile with new binary name

engine/worker/builtin_gitclone.go, sdk/vcs/git/git_tag.go
=> fix (gitClone): use git ls-remote --tags --refs

cli/cdsctl/Makefile, contrib/plugins/Makefile, engine/worker/Makefile
=> chore (worker/cli/plugins/cdsctl): fix cross compilation in Makefile

cli/cds/login/login.go, cli/cdsctl/signup.go, engine/api/mail/mail.go
=> fix (cdsctl/cds): callback command send by mail

docker-compose.yml, engine/config.go, engine/main.go, engine/types.go
Load Environment value even if the key is commented in configuration.
=> fix (engine): load env for commented key too

engine/worker/builtin_artifact.go
=> fix (worker): (workflow) download dest of artifact

engine/worker/builtin.go, sdk/plugin/common.go, sdk/plugin/types.go
=> fix (worker): plugin log with workflow

engine/api/action/requirement_cache.go, engine/api/build.go, engine/api/worker.go, engine/api/worker/model_capabilities.go, engine/worker/cmd_main.go, engine/worker/requirement.go, sdk/cdsclient/client_queue.go, tests/cli_pipeline_export_import.yml
=> fix (worker): waiting status instead of checking

engine/Makefile
=> chore: fix redis host in Makefile

ui/e2e/create.project.template, ui/src/app/views/navbar/navbar.html
=> fix (ui): it test

engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/run_workflow.go, engine/api/workflow_run.go, engine/sql/044_workflow_run_status.sql, sdk/workflow_run.go, ui/src/app/model/workflow.run.model.ts, ui/src/app/views/workflow/run/node/summary/run.summary.component.ts, ui/src/app/views/workflow/sidebar/workflow.sidebar.component.html, ui/src/app/views/workflow/sidebar/workflow.sidebar.component.ts
=> feat(api): add workflow_run status

engine/api/api_routes.go
=> feat (api): i386 worker download

sdk/cdsclient/client.go
=> feat (worker): retry 5 http

engine/api/api_routes.go
=> fix (api): :%s/i386/386/g

ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/shared/workflow/node/workflow.node.scss, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.html, ui/src/app/views/workflow/graph/workflow.graph.component.ts, ui/src/app/views/workflow/run/workflow.run.component.ts, ui/src/app/views/workflow/run/workflow.run.html, ui/src/app/views/workflow/sidebar/workflow.sidebar.component.ts
=> feat(ui): add manual stop

engine/api/workflow/execute_node_run.go, engine/api/workflow/process_parameters.go, engine/api/workflow_trigger.go, sdk/workflow.go
=> feat (api): Improve workflow trigger condition

engine/api/workflow/execute_node_job_run.go, engine/api/workflow/test/run_workflow_test.go, engine/api/workflow_queue.go
=> fix (api): load secrets on take (workflow)

engine/api/build.go, engine/api/workflow/execute_node_job_run.go
=> fix(api): better error for logs

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/shared/workflow/node/workflow.node.scss
=> fix(ui): fix ui for loading and stop button on workflow node

engine/api/workflow_trigger.go, ui/src/app/shared/workflow/trigger/condition-form/trigger.condition.form.html
=> fix(ui): sort trigger condition and add search

ui/src/app/shared/workflow/join/delete/workflow.join.delete.html, ui/src/app/shared/workflow/join/trigger/src/trigger.src.html, ui/src/app/shared/workflow/join/trigger/trigger.join.component.ts, ui/src/app/shared/workflow/join/trigger/workflow.trigger.join.html, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/shared/workflow/trigger/condition-form/trigger.condition.form.html, ui/src/app/shared/workflow/trigger/workflow.trigger.component.ts
=> fix(ui): add manual trigger for join

engine/main.go, engine/types.go, sdk/hatchery/hatchery.go
=> feat (engine): option to activate gops

engine/api/workflow/process_parameters.go
all is already interpolate after
no infinite loop detected
=> fix (api): no need to interpolate at this moment

engine/worker/cmd_main.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/hatchery/register.go
and no wait 60s to run a job if there is no provision.
=> fix (hatchery): take care of gracetime for wjob

sdk/artifact.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/http.go
=> fix (sdk): no timeout on upload

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/resync_workflow.go, engine/api/workflow_run.go, ui/src/app/views/workflow/run/summary/workflow.run.summary.html
=> fix(api): fix stop node run and workflow run

engine/api/project/dao.go
=> fix (api): avoid select the world

engine/api/workflow/dao_node_run.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/resync_workflow.go, engine/api/workflow_run.go, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/views/run/workflow/workflow.html, ui/src/app/views/workflow/run/node/summary/run.summary.component.ts, ui/src/app/views/workflow/run/summary/workflow.run.summary.html
=> refactor(api): refactor stop workflow handlers

engine/sql/046_action_deprecated.sql, sdk/action.go, ui/src/app/model/action.model.ts, ui/src/app/shared/action/action.html, ui/src/app/shared/action/action.scss, ui/src/app/shared/action/step/form/step.form.html, ui/src/app/shared/action/step/form/step.form.scss, ui/src/app/shared/action/step/step.html, ui/src/app/shared/action/step/step.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json, ui/src/common.scss
=> feat(api): add deprecated flag on actions

cli/cdsctl/workflow.go, engine/api/workflow_run.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go, sdk/workflow_run.go, vendor/github.com/buger/goterm/README.md, vendor/github.com/buger/goterm/box.go, vendor/github.com/buger/goterm/plot.go, vendor/github.com/buger/goterm/table.go, vendor/github.com/buger/goterm/terminal.go, vendor/github.com/buger/goterm/terminal_nosysioctl.go, vendor/github.com/buger/goterm/terminal_sysioctl.go, vendor/vendor.json
=> feat (cdsctl): workflow run

ui/src/app/views/workflow/run/node/summary/run.summary.component.ts
=> refactor(ui): delete trailing whitespace

engine/api/scheduler/dao.go
=> fix (api): scheduler

engine/api/workflow_queue_test.go, engine/api/workflow_run_test.go
=> test (api): fix WorkflowRunPostHandlerOption

engine/api/permission.go, engine/api/worker.go, engine/api/worker/worker.go
=> feat (api): more logs on worker refresh

engine/api/action/action.go, engine/api/suggest.go, ui/src/app/service/variable/variable.service.ts, ui/src/app/views/pipeline/show/audit/pipeline.audit.html, ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
=> fix(*): some fix after demo

ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts, ui/src/app/views/workflow/graph/workflow.graph.component.ts
=> fix(ui): fix lint

engine/api/objectstore/openstack_handlers.go
=> fix (pcs): region choice

engine/api/workflow/dao.go, engine/api/workflow/dao_node_run_job.go
=> fix(api): fix queue SELECT

engine/hatchery/docker/types.go, engine/hatchery/local/types.go, engine/hatchery/marathon/marathon.go, engine/hatchery/marathon/types.go, engine/hatchery/openstack/types.go, engine/hatchery/swarm/types.go, engine/hatchery/vsphere/types.go, engine/main.go
mapstructure tag to say to Viper how to deserialize conf - mandatory
=> fix (hatchery): load configuration

engine/api/poller/dao_execution.go, engine/api/scheduler/dao.go, engine/api/scheduler/executer.go, engine/api/scheduler/scheduler.go
=> fix (api): scheduler, sleep & db time

engine/api/auth/auth.go, engine/api/grpc_server.go, engine/api/permission.go
This will be convenient to contact potential owner of worker is there an err on auth
=> feat (api): display workerName in log on err auth

sdk/interpolate.go, sdk/interpolate_test.go, vendor/github.com/Masterminds/sprig/CHANGELOG.md, vendor/github.com/Masterminds/sprig/LICENSE.txt, vendor/github.com/Masterminds/sprig/Makefile, vendor/github.com/Masterminds/sprig/README.md, vendor/github.com/Masterminds/sprig/crypto.go, vendor/github.com/Masterminds/sprig/date.go, vendor/github.com/Masterminds/sprig/defaults.go, vendor/github.com/Masterminds/sprig/dict.go, vendor/github.com/Masterminds/sprig/doc.go, vendor/github.com/Masterminds/sprig/functions.go, vendor/github.com/Masterminds/sprig/glide.lock, vendor/github.com/Masterminds/sprig/glide.yaml, vendor/github.com/Masterminds/sprig/list.go, vendor/github.com/Masterminds/sprig/numeric.go, vendor/github.com/Masterminds/sprig/reflect.go, vendor/github.com/Masterminds/sprig/regex.go, vendor/github.com/Masterminds/sprig/semver.go, vendor/github.com/Masterminds/sprig/strings.go, vendor/vendor.json
Keep value '{{.cds.foo}}' if foo is a app secret var to let worker use it
This use http://masterminds.github.io/sprig/defaults.html for default value if var is not replace with an existing variable
all funcs from http://masterminds.github.io/sprig/ are now available \o/
=> fix (api): load variable containing secret from worker

ui/src/app/views/workflow/run/node/node.html, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
=> fix (ui): this is a pipeline, not a workflow here

engine/hatchery/local/local.go, engine/hatchery/local/types.go
=> fix (hatchery:local): avoid killing baby worker

engine/api/pipeline.go
=> test(api): fix test

engine/hatchery/swarm/swarm.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
=> fix (hatchery:swarm): clean networks & check ratio

engine/api/repositoriesmanager/repogithub/client.go, engine/api/repositoriesmanager/repogithub/client_event.go
Use uiURL wich is in the package and remove the 2 useless field in the struct
=> Fix uiUrl and apiUrl

engine/api/workflow/process.go, engine/api/workflow/process_test.go, ui/src/app/views/workflow/sidebar/workflow.sidebar.component.html
=> fix(api): fix workflow run status when a task fail in a new subversion

contrib/actions/cds-docker-package.hcl
=> fix (action): dockerPackage - don't rename attr

engine/api/api.go, engine/api/database/cli.go, engine/api/database/database.go, engine/api/test/test.go
=> feat (api): db connectTimeout in conf. default: 10s

cli/cdsctl/Makefile, contrib/plugins/Makefile, engine/Makefile, engine/api/api_routes.go, engine/worker/Makefile
This PR need merged of #1286
close #1287
=> fix(api): package 386, download routes with uname -m

engine/api/pipeline/pipeline_build.go
=> fix(api): order pipeline build by id instead by version first

vendor/github.com/ovh/venom/assertion.go, vendor/github.com/ovh/venom/executors/exec/executor.go, vendor/github.com/ovh/venom/extract.go, vendor/github.com/ovh/venom/process_testcase.go, vendor/github.com/ovh/venom/process_teststep.go, vendor/github.com/ovh/venom/venom.go, vendor/vendor.json
=> feat (plugin/venom): update venom vendor

engine/api/workflow/dao_artifact.go, engine/api/workflow/dao_hook.go, engine/api/workflow/dao_hook_model.go, engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/process_test.go, engine/api/workflow/resync_workflow.go, engine/api/workflow/run_workflow.go, engine/api/workflow_run.go, sdk/workflow_run.go
=> feat (api): err interpolate -> workflowRunInfo

ui/src/app/views/workflow/run/node/summary/run.summary.html, ui/src/app/views/workflow/run/summary/workflow.run.summary.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): improve summary

engine/api/application/application_pipeline.go, engine/api/application/dao.go, engine/api/application/test/dao_test.go, engine/api/environment.go, engine/api/environment/environment.go, engine/api/pipeline.go, engine/api/pipeline/pipeline.go, engine/api/pipeline/test/pipeline_test.go, engine/api/workflow.go, engine/api/workflow_test.go, sdk/environment.go, sdk/pipeline.go, sdk/workflow.go, ui/src/app/model/workflow.model.ts, ui/src/app/service/workflow/workflow.service.ts, ui/src/app/views/pipeline/show/pipeline.show.html, ui/src/app/views/workflow/show/workflow.component.ts, ui/src/app/views/workflow/show/workflow.html, ui/src/app/views/workflow/show/workflow.scss, ui/src/assets/i18n/fr.json
=> feat(ui): add workflow usage

engine/api/workflow_queue_test.go, engine/api/workflow_run_test.go
=> fix (api): 202 on UT

ui/package.json
=> chore(ui): add lint-staged to only when .ts files change

engine/api/workflow/execute_node_run.go, engine/api/workflow/process_parameters.go, engine/api/workflow/process_requirements.go, sdk/action.go, sdk/error.go, sdk/requirement.go
=> feat (api): interpolate on requirements

ui/src/app/views/application/show/workflow/application.workflow.component.ts
=> fix(ui): reset filter when change application

tests/sc_git_hook.yml
=> test (engine): 1 retry on pipeline history

engine/api/application_pipeline.go, engine/api/application_variable.go, engine/api/environment_import.go, engine/api/environment_variable.go, engine/api/pipeline_import.go, engine/api/templates.go
=> fix (api): goroutine on check warnings

cli/cds/ui/monitoring.go, cli/cdsctl/monitoring.go, engine/api/event/event.go, engine/api/status.go
This is useful to quick check if instances have not the same time
=> feat (cli): add time/hostname/cdsname in status

engine/worker/builtin_junit.go, ui/src/app/model/pipeline.model.ts, ui/src/app/views/run/test/table/test.table.component.ts, vendor/github.com/ovh/venom/process_files.go, vendor/github.com/ovh/venom/process_testsuite.go, vendor/github.com/ovh/venom/types.go, vendor/github.com/ovh/venom/venom.go
A PR on Venom will be open with fix about skipped block
=> fix (ui, engine): compute skipped tests

ui/src/app/shared/action/action.html, ui/src/app/shared/requirements/form/requirements.form.component.ts, ui/src/app/shared/requirements/form/requirements.form.html, ui/src/app/shared/requirements/list/requirements.list.component.ts, ui/src/app/shared/requirements/list/requirements.list.html
Linked to #1321 (merge #1321 before)
=> feat(ui): add suggest into model list for requirements interpolation

sdk/cdsclient/client_application_variable.go, sdk/cdsclient/client_environment_variable.go, sdk/cdsclient/client_project_variable.go, sdk/cdsclient/interface.go
Add project, environment and application variable management to cdsclient sdk
=> feat (sdk): variables

vendor/github.com/ovh/venom/README.md, vendor/github.com/ovh/venom/assertion.go, vendor/github.com/ovh/venom/executors/dbfixtures/README.md, vendor/github.com/ovh/venom/executors/dbfixtures/executor.go, vendor/github.com/ovh/venom/templater.go, vendor/vendor.json
=> chore: venom

ui/src/app/shared/workflow/node/run/node.run.param.component.ts
=> fix (ui): 404 on get pipelines if renamed

ui/src/app/views/workflow/sidebar/workflow.sidebar.component.ts, ui/src/assets/worker/web/workflow-run.js
=> feat(ui): increase limit for workflow runs

engine/api/api_routes.go, engine/api/status.go, engine/hooks/hooks_router.go, engine/vcs/vcs_router.go
=> feat (uservice): /mon/version & common versionHandler

engine/api/application_group.go, engine/api/environment_group.go, engine/api/group/group.go, engine/api/group/public.go, engine/api/pipeline_group.go, engine/api/project_group.go, sdk/error.go
=> feat (api): default group -> allow read only

engine/worker/init.go, sdk/log/log.go
=> feat (sdk,worker): add log fields CDSName / CDSVersion

vendor/github.com/donovanhide/eventsource/decoder.go, vendor/github.com/donovanhide/eventsource/server.go, vendor/github.com/donovanhide/eventsource/stream.go, vendor/vendor.json
=> fix: vendor github.com/donovanhide/eventsource

engine/api/workflow/test/dao_test.go
=> fix (api): ut worklow

ui/src/app/shared/workflow/node/hook/form/hook.form.html
=> fix(ui): fix hook edit modal

ui/src/app/shared/requirements/form/requirements.form.component.ts, ui/src/app/shared/requirements/form/requirements.form.html, ui/src/app/shared/requirements/list/requirements.list.component.ts, ui/src/app/shared/requirements/list/requirements.list.html
=> fix(ui): add loading on requirements type model

engine/api/pipeline/pipeline_build.go, engine/api/workflowv0/workflow.go
=> fix(api): fix run pipeline linked to application inside another app

engine/api/workflow/process.go, engine/api/workflow/process_parameters.go, engine/hooks/tasks.go, vendor/github.com/fsamin/go-dump/dump.go, vendor/github.com/fsamin/go-dump/encoder.go, vendor/github.com/fsamin/go-dump/helper.go, vendor/github.com/ovh/venom/assertion.go, vendor/github.com/ovh/venom/executors/dbfixtures/executor.go, vendor/github.com/ovh/venom/executors/exec/executor.go, vendor/github.com/ovh/venom/executors/http/README.md, vendor/github.com/ovh/venom/executors/http/executor.go, vendor/github.com/ovh/venom/executors/imap/executor.go, vendor/github.com/ovh/venom/executors/ovhapi/executor.go, vendor/github.com/ovh/venom/executors/readfile/executor.go, vendor/github.com/ovh/venom/executors/smtp/executor.go, vendor/github.com/ovh/venom/executors/ssh/executor.go, vendor/github.com/ovh/venom/executors/web/web.go, vendor/github.com/ovh/venom/extract.go, vendor/github.com/ovh/venom/process_teststep.go, vendor/github.com/ovh/venom/process_testsuite.go, vendor/github.com/ovh/venom/types.go, vendor/vendor.json
=> chore(vendor): update vendor for venom

engine/api/api.go, engine/main.go, engine/types.go, sdk/hatchery/hatchery.go
=> feat (engine): graylog on engine

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/init.go, engine/hatchery/openstack/openstack.go, engine/hatchery/swarm/swarm.go, engine/hatchery/vsphere/init.go, engine/hatchery/vsphere/vsphere.go, engine/hooks/hooks.go, engine/main.go, engine/vcs/vcs.go, sdk/hatchery/register.go
=> feat (services): use name from configuration

docker-compose.yml
=> fix (engine): name mandatory for hatchery

engine/worker/cmd_main.go, engine/worker/take_pipeline_build_job.go, engine/worker/take_workflow_node_run_job.go
=> feat (worker): useful logs

cli/cdsctl/environment.go, cli/cdsctl/environment_group.go, engine/api/api_routes.go, engine/api/application_group.go, engine/api/environment_group.go, engine/api/pipeline_group.go, engine/api/project_group.go, sdk/cdsclient/client_environment.go, sdk/cdsclient/interface.go, tests/cli_ctl_environment.yml
=> feat(api): add import groups in environment

sdk/error.go, ui/src/assets/i18n/en.json
=> fix (ui): Environnment -> Environment

contrib/templates/cds-template-deploy-marathon-app/.gitignore
=> fix (template): gitignore on cds-template-deploy-marathon-app

engine/api/workflow.go, engine/api/workflow/dao_run.go, ui/src/app/views/pipeline/show/workflow/pipeline.workflow.html, ui/src/app/views/run/workflow/workflow.html
=> fix: :%s/worfklow/workflow/g

contrib/plugins/plugin-marathon/marathon.go
=> feat (plugin/marathon): more logs

ui/src/app/views/run/workflow/step/step.log.component.ts, ui/src/app/views/run/workflow/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/pipeline.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
=> fix(ui): display pipeline step logs #1416

engine/api/application_pipeline.go
=> perf (api): goroutine on sanity.CheckPipeline

engine/api/router.go
Signed-off-by: François Samin <francois.samin@corp.ovh.com>
=> fix (api): asynchronous handlers retries read EOF buffers

engine/worker/register.go, engine/worker/requirement.go, sdk/hatchery/register.go
=> feat (hatchery,worker): improve some logs

engine/api/application.go, ui/src/app/app.service.ts, ui/src/app/service/application/application.service.ts, ui/src/app/service/application/application.store.ts, ui/src/app/views/application/show/application.component.ts
=> fix(ui): fix last pipeline build for branch and remote

ui/src/app/app.component.html, ui/src/app/service/auth/authentification.store.ts
=> fix(ui): fix account verify page

ui/src/app/model/pipeline.model.ts, ui/src/app/views/run/workflow/step/step.log.component.spec.ts, ui/src/app/views/run/workflow/step/step.log.component.ts, ui/src/app/views/run/workflow/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
=> feat(ui): add more informations on step logs

engine/api/build.go, engine/api/pipeline/awol.go, engine/api/worker/heartbeat.go, engine/api/worker/worker.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go, engine/hatchery/local/local.go, engine/sql/061_pipeline_build_job_retry.sql, sdk/build.go, sdk/job.go, sdk/worker.go, sdk/workflow_run.go
Please CHECK SQL MIGRATION NUMBER before merge :)
=> Feat workflow collector

engine/api/hatchery.go, engine/api/hatchery/hatchery.go, engine/sql/062_hatchery_name_constraint.sql
=> fix(api): update hatchery when the name is the same

cli/cds/application/variable.go, cli/cds/environment/variable.go, cli/cds/project/variable.go
=> fix(cli): fix force flag on add variable

ui/src/app/views/run/workflow/step/step.log.component.ts, ui/src/app/views/run/workflow/step/step.log.html, ui/src/app/views/run/workflow/step/step.log.scss, ui/src/app/views/run/workflow/workflow.html, ui/src/app/views/workflow/run/node/pipeline/pipeline.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
I don't find a better hack to copy into clipboard the logs (see copyRawLog function)
close #436
=> feat(ui): add copy raw logs

engine/worker/cmd_server.go, engine/worker/cmd_tmpl.go, engine/worker/run.go
Signed-off-by: François Samin <francois.samin@corp.ovh.com>
=> fix (worker): add info on err with tmpl. Closes #935

vendor/github.com/ovh/venom/executors/imap/executor.go
=> fix (plugin-venom): update vendor

engine/api/workflow/dao_run.go
=> fix(api): fix workflow purge

sdk/cdsclient/client_application.go, sdk/cdsclient/interface.go
=> feat (sdk): AttachApplicationToReposistoriesManager

engine/api/status.go, engine/api/test/assert.go, engine/api/test/test.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_queue_test.go
=> fix (api): lint

engine/api/application_pipeline.go
=> fix (api): speedup attachPipelinesToApplication

ui/src/app/model/pipeline.model.ts, ui/src/app/views/run/workflow/step/step.log.component.ts, ui/src/app/views/run/workflow/workflow.html, ui/src/app/views/workflow/run/node/pipeline/pipeline.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
=> fix(ui): fix step logs

cli/cds/application/info.go
=> fix(cli): add withTrigger in application info

engine/api/pipeline_import.go
=> fix(api): change error in wrap

sdk/cdsclient/deprecated.go, sdk/cdsclient/interface.go
=> feat (sdk): deprecated routes

engine/api/pipeline/pipeline_build.go
=> fix(api): fix pipeline build limit

ui/src/app/views/workflow/graph/workflow.graph.component.ts
=> fix(ui): cast d3 dagre params to any

ui/src/app/service/application/application.service.ts, ui/src/app/service/project/project.service.ts
this is useless since bff71a9883b6bf8f20d20804bf6d0a006cc56da5
=> fix (ui): remove load withRepo

engine/api/api.go, engine/api/application/dao_key.go, engine/api/bootstrap/bootstrap.go, engine/api/environment/dao_key.go, engine/api/project/dao.go, engine/api/project/dao_key.go, engine/sql/064_project_builtin_gpg_key.sql, sdk/key.go
=> feat (api): builtin project gpg key

cli/cdsctl/health.go, cli/cdsctl/main.go, engine/api/api_routes.go, engine/api/mon_db.go, sdk/cdsclient/client_mon.go, sdk/cdsclient/interface.go, sdk/health.go
=> feat (api, cdsctl): handler to get some DB Times

engine/api/workflow/process.go, engine/worker/cmd_tag.go
=> fix(api): fix workflow manual run

ui/src/app/model/pipeline.model.ts, ui/src/app/views/run/test/table/test.table.component.ts, ui/src/app/views/run/test/table/test.table.html, ui/src/app/views/workflow/run/node/test/table/test.table.component.ts, ui/src/app/views/workflow/run/node/test/table/test.table.html
=> fix (ui): display testsuite/tescases

engine/api/api.go, engine/hooks/hooks.go, engine/hooks/types.go, engine/vcs/types.go, engine/vcs/vcs.go
=> feat (api): allow listen on an addr only (ex:127.0.0.1)

engine/hooks/hooks.go
=> fix (api): non-canonical

ui/src/app/shared/action/action.component.ts
=> fix (ui): trim req value

engine/api/api.go, engine/api/user.go, engine/api/user/user.go, engine/api/user/user_test.go, sdk/error.go
=> feat (api): allow some domains at signup

engine/hatchery/swarm/swarm.go
=> fix (hatchery/swarm): dockerOpts could be nil

engine/api/workflow/dao_node_run_job.go, engine/worker/take_pipeline_build_job.go, engine/worker/take_workflow_node_run_job.go, sdk/error.go
=> feat (worker): give chance to worker

engine/api/api_routes.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, engine/worker/cmd_export.go, engine/worker/run.go
=> fix (api, worker): no async test result step

engine/worker/take_pipeline_build_job.go
=> fix (worker): 404

ui/src/app/model/scheduler.model.ts, ui/src/app/views/application/show/scheduler/form/scheduler.form.component.ts, ui/src/app/views/application/show/scheduler/form/scheduler.form.html, ui/src/app/views/application/show/scheduler/item/scheduler.item.html, ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts
=> feat(ui): add pipeline parameters for scheduler (close #1537)

ui/src/app/shared/action/action.component.ts
=> fix (ui): edit req opts

ui/src/app/shared/parameter/form/parameter.form.ts, ui/src/app/shared/parameter/list/parameter.html
=> fix(ui): display description for edit in pipeline params

ui/src/app/service/project/project.resolver.ts, ui/src/app/service/services.module.ts, ui/src/app/views/project/show/environment/list/environment.list.component.ts, ui/src/app/views/workflow/workflow.routing.ts
=> fix(ui): create workflow with pipeline

ui/src/app/app.service.ts, ui/src/app/model/project.model.ts, ui/src/app/service/project/project.resolver.ts, ui/src/app/service/project/project.service.ts, ui/src/app/service/project/project.store.ts, ui/src/app/service/services.module.ts, ui/src/app/views/admin/migration/project/migration.project.component.ts, ui/src/app/views/application/add/application.add.component.ts, ui/src/app/views/application/add/application.add.html, ui/src/app/views/application/application.routing.ts, ui/src/app/views/pipeline/add/pipeline.add.html, ui/src/app/views/pipeline/pipeline.routing.ts, ui/src/app/views/project/show/project.component.ts
=> fix(ui): fix creation for pipeline and application

engine/api/pipeline/pipeline_build.go
=> fix(api): fix uppercase remote

engine/api/pipeline/pipeline.go
=> fix(api): fix pipeline load names

engine/api/bootstrap/bootstrap.go, engine/vcs/bitbucket/http.go
=> fix (vcs): create hook on bitbucket

contrib/plugins/plugin-venom/venom.go, vendor/github.com/ovh/venom/process.go, vendor/github.com/ovh/venom/process_files.go, vendor/github.com/ovh/venom/venom.go, vendor/vendor.json
Ignore check cds variables when using the var argument list
=> fix (contrib/plugin): venom plugin

cli/cdsctl/health.go, engine/api/api_routes.go, engine/api/mon_db.go, sdk/cdsclient/client_mon.go, sdk/cdsclient/interface.go, sdk/health.go
this returns list of applied migrations
useful to see is a CDS Installation had apply or not db migrate
=> feat (api,cli): cdsctl health dbmigrate

ui/src/app/service/project/project.resolver.ts
=> fix(ui): load applications to create a pipeline

engine/api/notification/user.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_queue.go
=> fix (api): compare change status notif

engine/api/workflowv0/workflow.go, ui/src/app/views/application/show/workflow/application.workflow.component.ts
=> fix(ui): load version without remote filter if no repository linked

engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/resync_workflow.go, engine/api/workflow/run_workflow.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_run.go, ui/src/app/shared/workflow/node/workflow.node.component.ts
=> refactor(api): stop workflow run with goroutines

docs/content/installation/installation.configuration.md
=> doc(api): add database creation in configuration section

engine/api/mail/mail.go, engine/api/notification/user.go, engine/api/pipeline/pipeline_build.go
=> fix (api): notif on "change" status

docker-compose.yml
=> chore: fix env hatchery:swarm

ui/src/app/views/application/show/application.component.ts
=> fix(ui): select branch doesn't clear branch filter anymore

engine/api/worker/model.go, engine/api/worker_model.go, engine/sql/068_worker_model_description.sql, sdk/worker.go, ui/src/app/model/worker-model.model.ts, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
=> feat (api, ui): add description on worker model

ui/src/app/views/project/show/environment/list/environment.list.component.ts, ui/src/app/views/project/show/environment/list/item/environment.component.ts
=> fix(ui): display new cloned env and keep good permission (close #1571)

engine/api/environment_group.go
=> fix(api): delete env and load group with good name

ui/package-lock.json, ui/package.json, ui/src/app/shared/diff/diff.component.ts, ui/src/app/shared/diff/diff.html, ui/src/app/shared/diff/span-colored/span-colored.component.ts, ui/src/app/shared/diff/span-colored/span-colored.html, ui/src/app/shared/shared.module.ts, ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts, ui/src/app/views/pipeline/show/audit/pipeline.audit.html, ui/src/app/views/pipeline/show/audit/pipeline.audit.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): add better diff view for pipeline audit

engine/api/workflow/dao_run.go
=> fix (api): remove dead func

engine/api/api_routes.go, engine/api/application.go, engine/api/application/dao.go, engine/api/environment.go, engine/api/environment/environment.go, engine/api/pipeline/pipeline.go, engine/api/workflow/dao.go, sdk/application.go, ui/src/app/model/application.model.ts, ui/src/app/service/application/application.service.ts, ui/src/app/service/environment/environment.service.ts, ui/src/app/views/application/show/application.component.ts, ui/src/app/views/application/show/application.html, ui/src/app/views/project/show/environment/list/item/environment.component.ts, ui/src/app/views/project/show/environment/list/item/environment.html
=> feat(ui): add more usage (close #1560)

engine/api/environment_group.go, ui/src/app/service/project/project.store.ts, ui/src/app/views/project/project.module.ts, ui/src/app/views/project/show/environment/list/environment.list.html, ui/src/app/views/project/show/permission/permission.component.ts, ui/src/app/views/project/show/permission/permission.html, ui/src/app/views/project/show/project.component.ts, ui/src/app/views/project/show/project.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): load env permission on ui on load

engine/api/workflow_run.go
=> fix(api): fix tu run wf run

ui/src/app/views/project/show/permission/permission.component.ts, ui/src/app/views/project/show/permission/permission.html
=> fix(ui): lint issues

engine/api/workflow/run_workflow_test.go
go test
PASS
ok      github.com/ovh/cds/engine/api/workflow  18.920s
=> fix (api): ut workflow

tests/clictl_application.yml
=> test(tests): delete useless script

engine/api/application.go, engine/api/pipeline/pipeline_build.go
=> fix(api): display remotes and old remotes

engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go
=> fix (api): node run job -> NoWait

engine/api/api_routes.go, engine/api/debug.go
just here because it's annoying to use an extension
=> fix (api): API Debug UI

engine/hatchery/marathon/marathon.go, engine/hatchery/swarm/swarm.go, sdk/hatchery/hatchery.go
=> fix (hatchery): register with 128Ram (Container)

engine/api/workflow/execute_node_run.go, engine/api/workflow/process_parameters.go, engine/api/workflow/process_requirements.go, engine/api/workflow/process_requirements_test.go
=> feat (api): add job reqs in job param

cli/cdsctl/monitoring.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go
=> feat (cli): monitoring response times queue

sdk/hatchery/register.go
=> feat (hatchery): goroutine on register 🍻

engine/api/api_routes.go, engine/api/worker/model.go, engine/api/worker_model.go, sdk/cdsclient/client_worker_model.go, sdk/cdsclient/interface.go, sdk/error.go, sdk/hatchery/register.go
=> feat (api, hatchery): book for register

contrib/plugins/plugin-venom/venom.go, vendor/github.com/ovh/venom/README.md, vendor/github.com/ovh/venom/executors/dbfixtures/executor.go, vendor/github.com/ovh/venom/executors/exec/executor.go, vendor/github.com/ovh/venom/executors/http/executor.go, vendor/github.com/ovh/venom/executors/imap/executor.go, vendor/github.com/ovh/venom/executors/ovhapi/executor.go, vendor/github.com/ovh/venom/executors/readfile/executor.go, vendor/github.com/ovh/venom/executors/smtp/executor.go, vendor/github.com/ovh/venom/executors/ssh/executor.go, vendor/github.com/ovh/venom/executors/web/web.go, vendor/github.com/ovh/venom/package.sh, vendor/github.com/ovh/venom/process.go, vendor/github.com/ovh/venom/process_files.go, vendor/github.com/ovh/venom/release.sh, vendor/github.com/ovh/venom/types.go, vendor/github.com/ovh/venom/venom.go, vendor/github.com/ovh/venom/venom_output.go, vendor/vendor.json
=> feat (plugin/venom): parallel is back

engine/api/action/builtin.go
=> doc: git clone

cli/cdsctl/monitoring.go, engine/api/api_routes.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/workflow.go
=> feat (cdsctl): use workflow run count

engine/worker/builtin.go, engine/worker/cmd_server.go, engine/worker/logger.go, sdk/log.go, sdk/plugin/common.go, sdk/plugin/types.go
=> fix (worker): send plugin log to API from Worker

sdk/exportentities/workflow.go
Example:
```yaml
version: v1.0
workflow:
build:
pipeline: build
application: mon-appli
build_2:
depends_on:
- build
when:
- success
pipeline: build
application: mon-appli-2
build_3:
depends_on:
- build_2
when:
- success
pipeline: build
application: mon-appli-3
```
=> feat (sdk): workflow export sugar

ui/src/app/views/application/show/workflow/tree/item/application.workflow.item.component.ts
=> fix(ui): fix scheduler add with boolean parameters

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/process_parameters.go, engine/api/workflow_trigger.go
=> fix (api): build param db, store

cli/cdsctl/monitoring.go
=> feat (cdsctl): worker list not useful

engine/api/workflow/process_parameters.go, engine/worker/builtin_gitclone.go
=> feat (worker): use default branch from VCS

ui/src/app/views/application/show/application.component.ts, ui/src/app/views/application/show/workflow/trigger/trigger.component.ts, ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html, ui/src/app/views/workflow/workflow.compoment.ts, ui/src/app/views/workflow/workflow.html
=> fix(ui): load dest pipeline only if an application is subscribed

ui/src/app/shared/variable/list/variable.component.ts, ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/views/project/show/environment/form/environment.form.component.ts, ui/src/app/views/project/show/environment/list/item/environment.component.ts, ui/src/app/views/workflow/run/node/summary/run.summary.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.scss, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
=> fix(ui): reset page num when you change environment (close #1701)

ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.scss, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.scss, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.scss, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.scss
=> feat(ui): add dblclick on edit and improve ui

engine/api/application_migration.go, engine/api/migrate/migrate_workflow.go
=> fix (api): migrate wf -> save groups

cli/cdsctl/workflow_artifact.go, engine/api/objectstore/objectstore.go, engine/api/project/dao_dependencies.go, engine/api/workflow_run.go, engine/worker/builtin_artifact_download.go, sdk/artifact.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/http.go, sdk/cdsclient/interface.go
=> Feat workflow artifact

ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): add priority order to display tags in order in sidebar

engine/api/workflow/dao_run.go, engine/api/workflow_run.go
=> fix(api): create a workflow run num if not exist

engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/dao_node.go, engine/api/workflow/hook.go, sdk/workflow.go, sdk/workflow_hook.go
when we add a RepositoryWebhook and default payload empty
=> feat (api): default payload

ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.scss, ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
=> feat(ui): add dblclick on node run on each stage, job and step

engine/api/application.go
=> fix(api): fix version builds on loading application with workflowv0

ui/src/app/views/workflow/show/workflow.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
=> fix(ui): fix some titles

engine/hooks/tasks.go, engine/worker/builtin_gitclone.go, sdk/vcs/git/git.go, sdk/vcs/git/git_info.go
=> feat (worker): get git info, create var if necessary

ui/src/app/views/workflow/show/workflow.component.ts, ui/src/app/views/workflow/show/workflow.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (ui): launch wf -> always display modal

engine/worker/builtin_gitclone.go
=> fix (api): ignore git extract info for now

engine/api/event/publish.go, engine/vcs/bitbucket/client_status.go, engine/vcs/github/client_status.go, engine/vcs/gitlab/client_status.go
=> fix (vcs): status link to CDS

engine/worker/builtin_gitclone.go, sdk/vcs/git/git_info.go
=> fix (worker): gitClone, noerr on extractInfo

ui/src/app/model/navbar.model.ts, ui/src/app/service/application/application.store.ts, ui/src/app/service/workflow/workflow.store.ts, ui/src/app/views/navbar/navbar.component.ts, ui/src/app/views/navbar/navbar.html, ui/src/app/views/workflow/show/workflow.component.ts, ui/src/app/views/workflow/workflow.compoment.ts
=> feat (ui): navbar with workflows

cli/cds/pipeline/history.go, cli/cds/pipeline/parameter.go, engine/api/pipeline.go, engine/api/pipeline/pipeline_build.go, sdk/pipeline.go
```
cds pipeline parameter history 00SIM myapp mypip 54
NAME                       TYPE                       VALUE
cds.version                string                     54
cds.triggered_by.username  string                     admin
cds.triggered_by.fullname  string                     admin
cds.application            string                     myapp
cds.buildNumber            string                     54
cds.project                string                     00SIM
cds.environment            string                     NoEnv
cds.triggered_by.email     string                     admin@localhost.local
git.branch                 string                     master
cds.pipeline               string                     mypip
```
=> feat (api, cli): get pb parameters on old wf

sdk/interpolate.go, sdk/interpolate_test.go
=> fix (api): interpolate with '-' in var name

docs/content/building-pipelines/building-pipelines.actions.builtin.artifact-download.md, docs/content/building-pipelines/building-pipelines.actions.builtin.artifact-upload.md, docs/content/building-pipelines/building-pipelines.actions.builtin.gitclone.md, docs/content/building-pipelines/building-pipelines.actions.builtin.junit.md, docs/content/building-pipelines/building-pipelines.actions.builtin.md, docs/content/building-pipelines/building-pipelines.actions.builtin.script.md, docs/content/building-pipelines/building-pipelines.actions.md, docs/content/building-pipelines/building-pipelines.actions.plugins.plugin-download.md, docs/content/building-pipelines/building-pipelines.actions.user-actions.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-docker-package.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-go-build.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-nexus-upload.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-perl-test.md, docs/content/building-pipelines/building-pipelines.actions.user.cds-publish-ovh-metrics.md, docs/content/building-pipelines/building-pipelines.configuration-file.md, docs/content/building-pipelines/building-pipelines.first-pipeline-cli.md, docs/content/building-pipelines/building-pipelines.requirements.md, docs/content/building-pipelines/building-pipelines.templates.cds-template-cds-plugin.md, docs/content/building-pipelines/building-pipelines.variables.md, docs/content/getting-started/getting-started.first-pipeline-ui.md, docs/content/installation/installation.ready-to-run.docker-compose.md, docs/content/introduction/introduction.concepts.job.md, docs/content/introduction/introduction.concepts.md, docs/content/introduction/introduction.concepts.pipeline.md, docs/content/introduction/introduction.concepts.stage.md, docs/content/introduction/introduction.concepts.step.md, docs/content/introduction/introduction.md
First shot of documentation typos fixes.
=> doc: fix typos in the documentation

cli/cdsctl/workflow.go, cli/cobra.go, cli/types.go, engine/api/workflow_run.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go, sdk/workflow_run.go
```
cdsctl workflow show CDS w-cds 1088
tags           git.hash:290f9ec7d2301803e02388dc180417e4e0ebd61f git.branch:removeSanity git.author:sguiheux
num            1088
status         Success
start          2017-12-19 18:58:02.595008 +0100 CET
last_execution 2017-12-19 19:13:15.656149 +0100 CET
payload        git.author:sguiheux git.author.email:steven.guiheux@corp.ovh.com git.branch:removeSanity git.hash:290f9ec7d2301803e02388dc180417e4e0ebd61f git.repository:ovh/cds
```
=> feat (cdsctl): cdsctl workflow show

vendor/github.com/ovh/venom/executors/ovhapi/README.md, vendor/github.com/ovh/venom/executors/ovhapi/executor.go, vendor/vendor.json
=> chore (venom): update

cli/cdsctl/login.go, cli/cdsctl/main.go, contrib/plugins/plugin-marathon/marathon.go, engine/api/workflow/process.go, ui/src/assets/i18n/en.json, vendor/github.com/gambol99/go-marathon/client.go, vendor/google.golang.org/grpc/clientconn.go
=> fix: typos

vendor/github.com/ovh/go-ovh/ovh/configuration.go, vendor/github.com/ovh/go-ovh/ovh/ovh.go, vendor/vendor.json
=> chore: update go-ovh

engine/worker/builtin_artifact_download.go
=> feat (worker): fast download with skipped artifacts

sdk/parameter.go
=> fix (api): do not concat empty with something

ui/src/app/shared/action/action.html
=> fix (ui): edit action page

ui/src/assets/worker/web/log.js, ui/src/assets/worker/web/runpipeline.js, ui/src/assets/worker/web/workflow-log.js, ui/src/assets/worker/web/workflow.js
=> fix (ui): encodeURIComponent

engine/worker/builtin_artifact_download.go
=> fix (api): download artifact

engine/worker/builtin_artifact_download.go
=> Fix (worker): download artifact

ui/src/app/views/application/show/workflow/application.workflow.html, ui/src/app/views/application/show/workflow/pipeline/link/pipeline.link.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
Only if Worflows are enabled on Project
=> feat (ui): user info about new CDS Workflow

ui/package-lock.json, ui/package.json, ui/src/app/shared/workflow/node/context/node.context.html, ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts
close (#1787)
When this PR https://github.com/ng2-ui/auto-complete/pull/318 will be merged, we'll come back to this repo in package.json
=> fix(ui): when dropdown of suggest was empty the dropdown is now hidden #1787

ui/src/app/shared/workflow/node/run/node.run.param.html, ui/src/app/shared/workflow/node/run/node.run.param.scss
=> fix(ui): add scroll in list commit in modal run #1784

engine/api/workflow/dao_hook_model.go, engine/api/workflow_hook_test.go
It causes 500 as it's not developed yet
=> fix (api): hide GitPoller for now

ui/src/app/shared/workflow/node/form/workflow.node.form.component.ts
=> fix(ui): fix node form

ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): change wording about usage s/linked/used

engine/api/pipeline/pipeline_exporter.go, engine/api/pipeline_import.go, sdk/exportentities/action.go, sdk/exportentities/common.go, sdk/exportentities/pipeline.go, sdk/exportentities/pipeline_test.go, sdk/exportentities/types.go
example for a single job pipeline : 
````yaml
name: MyPipeline
jobs:
- job: MyJob
stage: MyStage
steps:
- script:
- echo lol
- '#This is a script'
- script:
- echo lel
- artifactUpload:
path: path1
tag: tag1
````
example for a multi stage pipeline
````yaml
name: MyPipeline t2_2
stages:
- stage 1
- stage 2
options:
stage 2:
conditions:
param1: value1
jobs:
- job: Job 1
stage: stage 1
steps:
- script:
- echo lol
- script:
- echo lel
- job: Job 2
stage: stage 1
steps:
- script:
- echo lol
- always_executed: true
enabled: false
script:
- echo lel
- job: Job 3
stage: stage 2
steps:
- script:
- echo lol
- script:
- echo lel
- job: Job 4
stage: stage 2
steps:
- script:
- echo lol
- always_executed: true
enabled: false
script:
- echo lel
````
=> feat (sdk): new pipeline format

engine/api/api_routes.go, engine/api/download.go, engine/api/router.go, sdk/download.go, sdk/error.go, ui/src/app/model/download.model.ts, ui/src/app/service/download/download.service.ts, ui/src/app/service/services.module.ts, ui/src/app/views/navbar/navbar.html, ui/src/app/views/settings/download/download.component.ts, ui/src/app/views/settings/download/download.html, ui/src/app/views/settings/settings.module.ts, ui/src/app/views/settings/settings.routing.ts, ui/src/app/views/settings/sidebar/settings-sidebar.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (api, ui): downloads page

ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/views/application/show/workflow/application.workflow.component.ts
=> fix(ui): some fixes about workflow and pipeline

engine/api/workflow/dao_node_run.go
=> fix(api): fix api without run

cli/cdsctl/main.go, cli/cdsctl/update.go, engine/worker/cmd_update.go, sdk/cdsclient/client_download.go, sdk/download.go
=> feat (cdsctl): ./cdsctl update [--from-github]

ui/src/app/views/settings/download/download.html
=> fix (ui): url api download

engine/main.go, engine/update.go
=> feat (engine): engine update [--from-github|--api]

engine/api/workflow/dao_node_run.go
=> fix(api): fix workflow node run commits for children nodes

ui/resources/cds-hint.js, ui/src/app/shared/workflow/node/run/node.run.param.component.ts
=> feat(ui): refresh commits list when you change branch in your default payload

ui/src/app/shared/status/status.component.ts, ui/src/app/shared/status/status.icon.html, ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/run/node/pipeline/pipeline.html, ui/src/app/views/workflow/run/node/pipeline/pipeline.scss, ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.ts
=> fix(ui): display warning when optional step failed

sdk/interpolate.go, sdk/interpolate_test.go
=> fix (api): interpolate unknown key with '-' in name

engine/api/workflow/process.go, engine/api/workflow_trigger.go, ui/src/app/views/workflow/run/node/pipeline/pipeline.html
=> fix(api): add cds.manual

contrib/plugins/plugin-marathon/marathon.go
=> feat (plugin/marathon): more logs on err

sdk/download.go
=> fix (api): :%s/window/windows

contrib/plugins/plugin-marathon/marathon.go, sdk/plugin/rpc_client.go
=> fix (plugins): do not panic on plugin run / init

ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix (ui): application_workflow_migration_ok

sdk/parameter.go
=> fix (api): do not concat parameters values

ui/src/app/shared/breadcrumb/breadcrumb.html, ui/src/app/shared/commit/commit.list.scss, ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/views/pipeline/show/pipeline.show.component.ts, ui/src/app/views/workflow/run/node/test/table/test.table.component.ts, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
=> feat(ui): some enhancements about ui

contrib/plugins/plugin-group-tmpl/plugin_test.go, contrib/plugins/plugin-kafka-publish/kafka_consummer.go, contrib/plugins/plugin-kafka-publish/plugin_run.go, contrib/plugins/plugin-tmpl/plugin_test.go, engine/worker/builtin.go, engine/worker/run.go, sdk/plugin/common.go
=> feat (plugins): more logs

sdk/plugin/common.go
=> fix (plugin): init trace

sdk/event.go, sdk/interpolate/interpolate_helper.go, sdk/workflow.go
=> fix (sdk): lint

ui/src/app/shared/workflow/node/conditions/node.conditions.component.ts, ui/src/app/shared/workflow/node/context/node.context.scss, ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts
=> fix(ui): add scroll in modal

ui/src/app/shared/workflow/node/run/node.run.param.html, ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix (ui): add description on button resync and fix display popover tags in sidebar #1863

ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
=> fix(ui): when you switch in history in a node run log view, logs aren't always refreshed #1876

engine/api/workflow_run.go, ui/src/app/service/workflow/run/workflow.run.service.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts
=> fix(api): fix get commits before launch

ui/src/app/shared/commit/commit.list.html, ui/src/app/shared/parameter/list/parameter.html, ui/src/app/shared/workflow/node/form/workflow.node.form.html, ui/src/app/shared/workflow/node/form/workflow.node.form.scss, ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.html
=> fix(ui): better display of tags in sidebar and fix description update

ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/views/workflow/run/summary/workflow.run.summary.html, ui/src/app/views/workflow/run/summary/workflow.run.summary.scss
=> refactor(ui): change style of refactor workflow run infos

engine/worker/cmd_main.go
=> fix (worker): detect flag single-use

ui/src/app/views/workflow/run/summary/workflow.run.summary.scss
=> fix(ui): center chevron and low font-size

engine/worker/cmd_main.go
=> fix (worker): env arg

engine/worker/cmd_main.go, engine/worker/cmd_run.go
=> fix (worker): check env before

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/process_test.go, engine/api/workflow/resync_workflow.go
=> fix(api): set node run skipped if all stages are skipped

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go
* Inject git.branch, git.hash, git.repository, git.auhor in build parameters from VCS infos if not present in jobParams
* Add git.hash (short version) as a tag
Next will be `cdsctl workflow track`
=> feat (api): VCSInfos

vendor/github.com/fsamin/go-dump/encoder.go, vendor/vendor.json
=> chore: go-dump

cli/cdsctl/main.go
=> doc: do not load conf on doc cmd

engine/api/download.go, sdk/download.go, sdk/error.go, ui/src/app/model/download.model.ts, ui/src/app/views/settings/download/download.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
Display if binary is available or not on UI
=> feat (api,ui): improve download page.

LICENSE, docs/content/contribute/_index.md
=> doc: contribute page

docs/config.toml
=> doc: enable search

cli/cdsctl/Makefile, contrib/plugins/Makefile, engine/Makefile, engine/api/download.go, engine/worker/Makefile, sdk/download.go, ui/src/app/views/settings/download/download.html
=> fix (engine): take care of extension

README.md, cli/cds/pipeline/import.go, ui/src/app/shared/requirements/form/requirements.form.html, ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html, ui/src/app/views/settings/action/add/action.add.html, ui/src/app/views/settings/action/edit/action.edit.html
=> doc: update link to new doc site

engine/api/workflow/process.go
=> fix(api): fix join status after skipped node run

engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go, engine/hatchery/vsphere/spawn.go
=> feat (hatchery): use new download routes

docs/static/css/theme-custom.css
=> fix (doc): remove double scrollbar

vendor/github.com/ovh/venom/types.go
=> fix (engine): remove assertions on testcase

engine/api/metrics/metrics.go
=> feat (api): add metrics on wf runs / jobs / node

engine/api/environment/environment_importer.go, engine/api/environment/environment_parser.go, engine/api/workflow_import.go
=> fix (engine): workflow push with env

sdk/artifact.go
=> fix (worker): upload with fallback on CDS API

sdk/download.go
=> feat (engine): remove old cli from download

engine/worker/cmd_main.go
to avoid :
```
INFO[0000] running worker CDS_SINGLE_USE:false...
INFO[0000] Current binary: /home/cds/worker
```
=> fix (worker): init log on root process

sdk/artifact.go
=> fix (worker): upload, check err

cli/cdsctl/Makefile, contrib/plugins/Makefile, engine/Makefile, engine/worker/Makefile, sdk/download.go
=> chore: fix Makefile for windows

cli/cdsctl/Makefile, contrib/plugins/Makefile, engine/Makefile, engine/worker/Makefile
=> chore: Makefile test

engine/sql/076_token_infos.sql
=> fix(sql): fix create index

docs/content/introduction/scopes/permissions.md
=> docs(permissions): refactor

engine/api/workflow_import.go
=> fix(api): fix mispell about content type yaml

engine/api/workflow/dao_node.go, engine/api/workflow_run.go, ui/src/app/shared/parameter/list/parameter.component.ts, ui/src/app/shared/parameter/list/parameter.html, ui/src/app/shared/workflow/node/context/node.context.html, ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts, ui/src/app/views/settings/user/edit/user.edit.component.ts, ui/src/app/views/settings/user/edit/user.edit.html
=> fix(ui): permit to delete pipeline parameters from node context

engine/api/metrics/metrics.go
=> feat (api): add metrics old workflows

engine/api/download.go
=> fix (api): download .exe

ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix (ui): missing translation

engine/api/workflow/execute_node_run.go, sdk/vcs/git/git_info.go
=> fix (api,vcs): inject git.message and full body

ui/src/app/service/workflow/workflow.store.ts
=> fix: return on error when getting workflow

cli/cobra.go
=> fix (cli): panic on monitoring

docs/content/hosting/download.md, docs/static/js/custom.js
=> doc: download pages with direct links to binaries

engine/README.md
=> doc: Update README.md

ui/src/app/model/pipeline.model.ts
=> fix(ui): fix merge pip params and ctx params

ui/src/app/views/settings/group/edit/group.edit.component.ts, ui/src/app/views/settings/group/edit/group.edit.html, ui/src/app/views/workflow/run/summary/workflow.run.summary.html, ui/src/app/views/workflow/run/summary/workflow.run.summary.scss, ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): fix token generated and some other bugs

ui/src/app/shared/permission/environment/form/permission.env.form.component.ts
=> fix (ui): let API returns "Group Already Exists"

engine/api/project/dao_dependencies.go
=> fix (api): ignore workflow load error on project load

engine/hooks/tasks.go
=> feat (hooks): git.tag if it's a tag event

ui/src/app/shared/parameter/value/parameter.value.component.ts, ui/src/app/shared/workflow/node/context/node.context.html, ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts
=> fix(ui): fix list parameters

engine/api/migrate/migrate_workflow.go
=> fix (api): workflow migrate permissions

engine/api/project/gorp_model.go
=> fix (api): update project shouldn't erase vcs server

engine/hooks/tasks.go, sdk/cdsclient/client_environment.go, ui/src/app/views/application/show/application.html, ui/src/app/views/workflow/show/workflow.html
=> fix (hooks): cds.triggered_by.*

engine/api/notification/user.go
=> fix (api): send notifications on specified pipelines

ui/src/app/views/settings/group/edit/group.edit.html
=> fix (ui): info on edit group with only one admin

cli/cdsctl/worker_model.go, docs/content/workflows/pipelines/requirements/worker-model/openstack.md, sdk/cdsclient/client_worker_model.go, sdk/cdsclient/interface.go, sdk/common.go
=> feat(cli): add worker model add command

ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts, ui/src/app/shared/workflow/trigger/workflow.trigger.component.ts, ui/src/app/shared/workflow/trigger/workflow.trigger.html
=> fix(ui): fix wizard to add a node into workflow

engine/api/application/dao.go, engine/api/application/dao_dependencies.go, engine/api/environment/environment.go, engine/api/workflow/dao.go, engine/api/workflow/dao_node.go, engine/api/workflow/process.go, engine/api/workflow_run.go, ui/src/app/views/workflow/run/summary/workflow.run.summary.component.ts, ui/src/app/views/workflow/run/summary/workflow.run.summary.html, ui/src/app/views/workflow/show/workflow.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
=> fix (ui): play / relaunch / stop workflow & pipeline btn displayed for readers

ui/src/app/shared/prerequisites/form/prerequisites.form.html
=> fix(ui): add the ability to add custom prerequisite (waiting for migration of new checkCondition from workflow)

cli/cdsctl/monitoring.go, engine/api/auth/auth.go, engine/api/build_test.go, engine/api/hatchery/hatchery.go, engine/api/test/assets/assets.go
=> fix (api): auth hatchery - book jobs

engine/api/router.go, engine/api/router_util.go, sdk/cdsclient/client_application.go, sdk/cdsclient/client_application_key.go, sdk/cdsclient/client_application_variable.go, sdk/cdsclient/client_environment.go, sdk/cdsclient/client_environment_key.go, sdk/cdsclient/client_environment_variable.go, sdk/cdsclient/client_export.go, sdk/cdsclient/client_group_user.go, sdk/cdsclient/client_import.go, sdk/cdsclient/client_pipeline.go, sdk/cdsclient/client_project.go, sdk/cdsclient/client_project_key.go, sdk/cdsclient/client_project_variable.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/http.go, sdk/cdsclient/interface.go
close #2091
feat (api): add process time in response headers
=> fix (worker): use API Remote Time

engine/api/workflow/dao_hook_model.go
=> feat (api): ensure default hooks config

cli/cdsctl/workflow.go, cli/cdsctl/workflow_advanced.go, engine/api/workflow_run.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go, sdk/workflow_run.go
``` cdsctl workflow advanced number get 00SIM MyWorkflow 20 cdsctl workflow
advanced number set 00SIM MyWorkflow 50 cdsctl workflow advanced number get
00SIM MyWorkflow 50
```
close #2108
=> feat (cdsctl): update run number

ui/README.md, ui/package.json
Add missing requirements to start smoothly in the [JAW](http://is2.mzstatic.com/image/thumb/Video18/v4/3c/ce/31/3cce31a9-ff9e-bc6b-f17d-a20c55d50db0/source/1200x630bb.jpg) (Javascript Awesome World 🌈 )
=> Doc - update getting started

engine/worker/run.go
=> fix (worker): expand env before running the builtin action

ui/src/app/views/workflow/add/workflow.add.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): change the pattern of a workflow name in the admin section #2100

engine/api/workflow/dao.go, engine/api/workflow/workflow_exporter_test.go, engine/api/workflow/workflow_importer_test.go, sdk/exportentities/workflow.go
=> feat (api): workflow export import metadata & purge_tags

engine/vcs/bitbucket/client_branch.go
=> fix (vcs): get branch from bitbucket

ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts
=> fix(ui): use a clone instead of a ref

engine/api/workflow/dao_hook_model.go, engine/api/workflow/workflow_importer.go, engine/api/workflow/workflow_importer_test.go, engine/vcs/github/client_hook.go, engine/vcs/github/github.go, engine/vcs/github/github_test.go, engine/vcs/github/oauth_consumer.go, engine/vcs/vcs.go, sdk/workflow_hook.go
=> fix(api): fix import workflow with hook

engine/api/pipeline/pipeline_importer.go, engine/api/pipeline/pipeline_importer_test.go, sdk/exportentities/pipeline.go, sdk/exportentities/types.go, ui/src/app/shared/workflow/node/wizard/node.wizard.html, ui/src/app/views/workflow/add/workflow.add.html
=> fix(api): fix pipeline import for parameters

ui/src/app/shared/workflow/join/trigger/trigger.join.component.ts, ui/src/app/shared/workflow/join/trigger/workflow.trigger.join.html, ui/src/app/shared/workflow/trigger/workflow.trigger.component.ts, ui/src/app/shared/workflow/trigger/workflow.trigger.html
=> feat(ui): add new pipeline wizard after a join #2135

engine/api/workflow/dao_run.go
=> fix(api): add joins ref to old workflow runs

ui/package.json
fix from https://github.com/angular/angular-cli/issues/9307
=> fix (ui): angular/cli

engine/api/migrate/clean_old_workflow.go, engine/api/workflow_import.go, ui/src/app/service/workflow/workflow.store.ts, ui/src/app/views/workflow/add/workflow.add.component.ts, ui/src/app/views/workflow/add/workflow.add.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): import a new workflow from ui #2154

engine/api/mail/mail.go, engine/api/notification/mail.go, engine/api/status.go, ui/src/app/views/workflow/run/summary/workflow.run.summary.html
=>  feat(api): add HTML support for emails

docs/content/workflows/design/hooks/_index.md, docs/content/workflows/design/hooks/git-repo-webhook.md, docs/content/workflows/design/hooks/scheduler.md, docs/content/workflows/design/hooks/webhook.md, ui/src/app/shared/workflow/node/hook/form/hook.form.html, ui/src/app/shared/workflow/node/hook/form/hook.form.scss
=> doc(hooks): add more docs on hook and add link inside UI #2161

ui/src/app/views/project/show/admin/project.admin.html
=> fix(project): rename a project had a wrong regex #2174

ui/src/styles.scss
=> fix(ui): fix style of codemirror

engine/api/application.go, ui/src/app/shared/workflow/node/workflow.node.component.ts
=> fix(ui): refresh application in node context after attach a repo #2168

engine/api/workflow/dao_hook.go
=> fix(api): for previous scheduler add default payload

ui/src/app/shared/action/action.component.ts, ui/src/app/shared/action/action.html, ui/src/app/shared/action/step/step.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): add collapse all button on job #2185

engine/api/workflow_run.go, ui/src/app/service/application/application.service.ts
=> fix (api): launch a workflow with bad git payload shouldn't instantiate a run 

ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
even if there was no run.
close #2193
=> fix (ui): display tag imported with workflow import

engine/api/api_routes.go, engine/api/lastupdate.go, engine/api/permission.go, engine/api/router_util.go
=> refactor (api): sse - db access in lock

docs/content/hatchery/_index.md, docs/content/workflows/pipelines/variables.md, engine/worker/run.go
=> fix (variables): use helpers in worker

ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.ts
=> fix(ui): fix add pipeline after trigger in specific case

engine/api/workflow/process.go, ui/src/app/views/application/show/application.component.ts
=> fix(api): update last execution time and change default tab for application in ui

Gopkg.lock, docs/content/workflows/design/run-conditions.md, sdk/luascript/luascript.go, sdk/luascript/luascript_test.go, vendor/github.com/yuin/gluare/LICENSE, vendor/github.com/yuin/gluare/gluare.go
=> feat (api): support lua regex

engine/worker/builtin_script.go
=> fix (worker): replace - with _ in expored env

docs/content/workflows/pipelines/variables.md, sdk/interpolate/interpolate.go, sdk/interpolate/interpolate_helper.go, sdk/interpolate/interpolate_test.go
=> feat (sdk): allow empty {{.cds.app.foo|default ''}}

contrib/actions/cds-go-build.hcl
=> fix (contrib/actions): gobuild & interpolate var

engine/api/action/builtin.go, engine/worker/builtin.go, sdk/action.go, sdk/action_script.go, sdk/exportentities/action.go, sdk/exportentities/pipeline.go, sdk/exportentities/pipeline_test.go
=> fix(sdk): export checkout application as code

ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
=> fix(ui): change reference of existing tag to rerender into select

engine/api/api.go, engine/api/database/cli.go
=> fix (api): remove unused key "secret" in db section

engine/api/notification/user.go, engine/api/workflow/run_workflow.go
=> fix(api): send notifications to initiator when it comes from a hook

engine/api/workflow/process.go
=> feat(api): put the node name of the current node run inside variables

engine/api/workflow/hook.go
=> fix(api): log error if you can't delete hook from vcs but don't return error

engine/worker/cmd_download.go, engine/worker/cmd_server.go, engine/worker/main.go
=> feat (worker): worker download

engine/hooks/hooks_handlers.go, engine/hooks/tasks.go
=> fix(hooks): fix stop task for poller

Gopkg.lock, Gopkg.toml, vendor/github.com/docker/docker-credential-helpers/credentials/error.go, vendor/github.com/docker/docker-credential-helpers/credentials/version.go, vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go, vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go, vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
=> fix (sdk): build with osx / go1.10

ui/src/app/shared/requirements/form/requirements.form.html
=> fix(ui): open new tab for worker models settings

engine/api/workflow_hook.go
=> fix (ui): don't always display repo poller #2258

cli/cdsctl/shell.go, engine/api/api_routes.go, engine/api/navbar.go, engine/api/navbar/navbar.go, engine/api/navbar_test.go, sdk/cdsclient/client_navbar.go, sdk/cdsclient/interface.go, sdk/navbar.go, ui/src/app/service/navbar/navbar.service.ts
https://asciinema.org/a/H67HlKNS2r0daQaEcuNfZhZZd
=> feat (cdsctl): cdsctl shell speed nav and find cmd

engine/api/workflow_hook_test.go
=> test(api): fix tu about workflow hook

ui/src/app/views/workflow/sidebar/edit/hook/workflow.sidebar.hook.component.ts, ui/src/app/views/workflow/sidebar/run/hook/workflow.sidebar.run.hook.component.ts
=> fix(ui): fix refresh ui log hooks

engine/hooks/tasks.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
=> fix(api): add better error handling for hooks and improve hatchery spawn attempts

ui/src/app/views/workflow/add/workflow.add.component.ts, ui/src/app/views/workflow/add/workflow.add.html, ui/src/app/views/workflow/add/workflow.add.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): add pattern of workflow name in UI

ui/src/app/views/workflow/workflow.component.ts
=> fix(ui): fix select on join

docker-compose.yml
like the rest of the docker-compose.yml file
Signed-off-by: Antoine GIRARD <sapk@sapk.fr>
=> chore(docker-compose): use dictionary yaml for environment in comments

engine/api/token/token.go, engine/api/user.go
=> fix(api): fix permission on get token list for user

ui/src/app/service/user/user.service.ts, ui/src/app/views/account/verify/verify.component.ts, ui/src/app/views/account/verify/verify.html
=> fix(ui): fix account verify modal and don't display permissions

ui/src/app/shared/action/action.component.ts
=> fix(ui): fix refresh configRequirements on modal requirements

engine/api/lastupdate.go
=> fix(api): flush lastupdate buffer by default

engine/api/workflow/run_workflow.go, engine/hooks/hooks.go, engine/hooks/types.go
=> feat(hooks): add hook disable configuration

engine/api/workflow/process.go
=> feat(api): fetch commit infos for bitbucket repository webhook to let user check git.message in run conditions

engine/api/repositoriesmanager/events.go, engine/api/repositoriesmanager/repositories_manager.go, engine/api/workflow/process.go, engine/api/workflow/workflow_run_event.go, engine/vcs/bitbucket/client_status.go, engine/vcs/bitbucket/client_status_test.go, engine/vcs/bitbucket/types.go, engine/vcs/github/client_status.go, engine/vcs/gitlab/client_status.go, engine/vcs/gitlab/gitlab.go, engine/vcs/vcs_handlers.go, engine/vcs/vcs_handlers_test.go, engine/vcs/vcs_router.go, sdk/repositories_manager.go, sdk/vcs.go
=> feat(api): resync noderun vcs statuses

cli/cdsctl/shell.go, cli/cdsctl/workflow_import.go, cli/cdsctl/workflow_push.go, cli/cdsctl/workflow_stop.go, docs/content/hosting/ready-to-run/docker-compose.md, docs/content/hosting/repositories-manager/_index.md, docs/content/hosting/repositories-manager/bitbucket.md, docs/content/hosting/repositories-manager/github.md, docs/content/hosting/repositories-manager/gitlab.md, engine/vcs/types.go
=> doc (vcs): upgrade doc with new conf file

ui/resources/cds-hint.js
=> fix(ui): autocompletion in advanced run conditions don't autocomplete correctly with git_... #2278

engine/api/migrate/migrate_workflow.go
=> fix(api): application migration condition operator

engine/api/services/http.go, engine/vcs/github/http.go, engine/vcs/vcs_handlers.go
=> fix(api): fix path escape

sdk/stage.go
=> feat (api): allow using workflow.* var in stage conditions

engine/api/workflow/dao_run.go, engine/api/workflow/process.go
=> fix(api): workflow status compute

engine/api/workflow/dao_run.go, engine/api/workflow_queue.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go
=> fix (api): update some logs level

ui/src/app/views/workflow/graph/workflow.graph.component.ts
=> fix(ui): refresh display hook when add or remove one

engine/hatchery/swarm/swarm.go
=> feat (hatchery): update log level

contrib/plugins/plugin-marathon/marathon.go
=> feat (plugin/marathon): add new labels

docs/content/hosting/repositories-manager/bitbucket.md
=> doc (vcs): how to generate keys for bitbucket

engine/api/application/application_parser.go, engine/api/application_import_test.go, engine/api/environment/environment_parser.go, engine/api/environment_import_test.go, engine/api/workflow_import_test.go, sdk/error.go
=> fix(api): check app and env name on import

docs/content/introduction/concepts/_index.md, docs/content/workflows/design/hooks/_index.md, docs/content/workflows/design/hooks/kafka-hook.md
=> doc: add doc on kafka hook

engine/api/error.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go
=> feat (api, hatchery): info -> debug common logs

engine/hooks/tasks.go, sdk/hook.go
=> fix(api): add default payload on git pollers

cli/cdsctl/action.go, cli/cdsctl/workflow_push.go, engine/api/action.go, engine/api/action/action_exporter.go, engine/api/action/builtin.go, engine/api/action_test.go, engine/api/api_routes.go, engine/api/pipeline/pipeline_build.go, engine/api/workflow/process.go, sdk/cdsclient/client_action.go, sdk/cdsclient/interface.go, sdk/exportentities/action.go, sdk/exportentities/application.go
=> feat(api,cli): import, export action

engine/api/environment_import.go, engine/api/pipeline_import.go
=> fix(api): import error management

contrib/uservices/cds2xmpp/service/bot.go
=> fix (service/cds2xmpp): init xmlRegexp

ui/src/app/views/application/show/application.html, ui/src/app/views/pipeline/show/pipeline.show.html, ui/src/app/views/workflow/show/workflow.html
=> fix(ui): change usage icon

engine/api/workflow_queue_artifact.go, sdk/workflow_run.go
=> fix (api): upload artifact - compare obj

ui/src/app/shared/workflow/join/trigger/trigger.join.component.ts, ui/src/app/shared/workflow/node/conditions/condition-form/condition.component.ts, ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html, ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.component.ts, ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.html, ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.scss, ui/src/app/shared/workflow/trigger/workflow.trigger.component.ts
=> fix(ui): add pipeline after a join add default condition with cds.status #2324

ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): put payload to read-only when you launch non root node

ui/src/app/shared/workflow/node/hook/form/hook.form.html, ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
=> fix(ui): display value of config even if type is empty

ui/src/app/views/navbar/navbar.component.ts
=> fix(ui): fix navbar search for workflow

ui/src/app/shared/workflow/node/delete/workflow.node.delete.component.ts, ui/src/app/shared/workflow/node/delete/workflow.node.delete.html, ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): add warning when user want to delete root pipeline with all childs #2206

docs/content/hosting/ready-to-run/from-binaries.md
=> doc: from binaries

ui/src/app/shared/workflow/node/hook/form/hook.form.component.ts
=> fix(ui): add scroll to modal hook

sdk/hatchery/register.go
=> fix (hatchery): use execGroups with wf

engine/types.go, sdk/hatchery/hatchery.go, sdk/log/log.go
=> feat (engine): allow many extra keys/values logs

engine/api/workflow.go
=> fix(api): workflow creation default permissions

sdk/log/log.go
=> fix (engine): init log

docs/content/worker/_index.md, docs/content/worker/setup-your-worker.md, docs/content/workflows/pipelines/requirements/_index.md, docs/content/workflows/pipelines/requirements/service/_index.md, docs/content/workflows/pipelines/requirements/worker-model/_index.md, engine/api/api_routes.go, engine/api/worker/worker.go, engine/api/worker_model.go, engine/sql/085_worker_model_restricted.sql, sdk/worker.go, sdk/worker_easyjson.go, ui/src/app/model/worker-model.model.ts, ui/src/app/shared/action/action.html, ui/src/app/views/admin/admin.html, ui/src/app/views/admin/sidebar/admin-sidebar.scss, ui/src/app/views/project/add/project.add.html, ui/src/app/views/settings/settings.component.html, ui/src/app/views/settings/sidebar/settings-sidebar.scss, ui/src/app/views/settings/user/edit/user.edit.html, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (engine,ui,hatchery): worker model restricted

engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_util_create_test.go, engine/hatchery/swarm/swarm_util_get.go, engine/hatchery/swarm/swarm_util_get_test.go, engine/hatchery/swarm/swarm_util_kill.go
=> fix (hatchery/swarm): count workers started

engine/worker/cmd_cache.go, sdk/doc/generate.go
=> doc (worker): doc about cache

engine/worker/cmd_cache.go
=> doc (worker): add if on cache pull

engine/api/worker/model.go
=> fix (engine): column restricted on wm get

engine/hatchery/marathon/types.go, sdk/hatchery/hatchery.go
=> fix (engine): provisioning

engine/api/group.go, engine/api/group/group.go, engine/api/group/public.go, engine/api/notification/permission.go, engine/api/notification/user.go, engine/api/permission/permission.go, engine/api/project.go, ui/src/app/service/group/group.service.ts, ui/src/app/views/project/add/project.add.component.ts
=>  fix (api): avoid sending notif on default group

ui/src/app/app.service.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): add a group on a workflow

contrib/uservices/cds2es/README.md
=> doc (uservices/cds2es): configuration file example

cli/cdsctl/update.go, engine/main.go, engine/update.go, engine/uptodate.go, engine/worker/cmd_update.go, sdk/cdsclient/client_download.go, sdk/cdsclient/client_mon.go, sdk/cdsclient/interface.go
=> feat (engine): --is-uptodate flag on engine update

ui/src/app/shared/action/action.component.ts, ui/src/app/shared/action/action.html, ui/src/app/shared/parameter/form/parameter.form.html, ui/src/app/shared/parameter/list/parameter.component.ts, ui/src/app/shared/parameter/list/parameter.html
=> fix(ui): fix edit action page

engine/api/workflow/dao_run.go, engine/api/workflow/init.go
=> fix(api): fix delete purge

tests/sc_workflow_run_cache.yml
=> test: retry 10 on worker cache

ui/src/app/service/application/application.store.ts, ui/src/app/service/logout.interceptor.service.ts, ui/src/app/service/pipeline/pipeline.store.ts, ui/src/app/service/workflow/workflow.store.ts, ui/src/app/views/application/show/application.component.ts, ui/src/app/views/pipeline/show/pipeline.show.component.ts, ui/src/app/views/workflow/show/workflow.component.ts
=> fix (ui): manage error on 404

sdk/workflow_hook.go
=> fix(api): rename workflow update hooks

engine/api/sessionstore/sessionstore.go, ui/src/app/shared/requirements/form/requirements.form.html, ui/src/app/views/application/show/admin/application.admin.html, ui/src/app/views/project/show/admin/project.admin.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.html
=> fix(ui): rename app or workflow show error

cli/cdsctl/workflow_push.go
=> fix(cli): workflow push skip directory

cli/cdsctl/monitoring.go, engine/api/mon_db.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/workflow.go
=> feat (engine,sdk): X-CDS-Until header queue count

ui/src/app/views/project/show/environment/form/environment.form.component.ts
1. Description
When adding a new environment, he is duplicated on menu
close #1753 
1. Mentions
@ovh/cds
=> fix: do not duplicate env

ui/src/app/shared/usage/environments/usage.environments.html
1. Description
Go to environment from environment usage does not work
N/A
1. About tests
1. Mentions
@trnsnt
@ovh/cds
=> fix (ui): query params on env usage

ui/src/app/views/project/show/admin/project.admin.component.ts, ui/src/app/views/project/show/admin/project.admin.html
1. Description
NaN in workflow migration progress bar
close #2070 
1. About tests
Manual
1. Mentions
@ovh/cds
=> fix (ui): workflow migration progressbar

sdk/cache.go, tests/fixtures/ITSCWRKFLW4/tag-push-pull.pip.yml
close #2451
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): worker cache with symlink

ui/src/app/shared/action/step/step.component.ts, ui/src/app/shared/parameter/value/parameter.value.component.ts, ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.ts
=> fix: keep sidebar intact

engine/api/workflow/dao.go, engine/api/workflow/dao_run.go, engine/api/workflow/dao_run_test.go, engine/api/workflow/run_workflow.go, sdk/workflow.go, ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test(api): add tests on purge

ui/src/app/views/project/list/project.list.component.html, ui/src/app/views/project/show/application/application.list.component.ts, ui/src/app/views/project/show/application/application.list.html, ui/src/app/views/project/show/pipeline/pipeline.list.component.ts, ui/src/app/views/project/show/pipeline/pipeline.list.html, ui/src/app/views/project/show/workflow/workflow.list.component.ts, ui/src/app/views/project/show/workflow/workflow.list.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
Add search input on each list pages
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add search on list (applications, pipelines, workflows)

ui/src/app/shared/action/action.html, ui/src/app/shared/action/step/step.html, ui/src/app/shared/workflow/node/form/workflow.node.form.html, ui/src/app/shared/workflow/node/wizard/node.wizard.html, ui/src/app/views/application/show/workflow/trigger/trigger.html, ui/src/app/views/pipeline/show/workflow/pipeline.workflow.html, ui/src/app/views/pipeline/show/workflow/stage/form/pipeline.stage.form.html
1. Description
Add info on read only job, add optional & always_exacted
Edit stage: remove add prerequisites & delete btn in ro mode
close #1063 too 
1. About tests
manual
1. Mentions
@ovh/cds
Signed-off-by: Yvonnick Esnault <yvonnick.esnault@corp.ovh.com> #
=> fix (ui): view edit job with read only rights

cli/cdsctl/action.go
1. Description
on err import, successfully imported was displayed
none
1. About tests
manual
1. Mentions
@ovh/cds
=> fix (cdsctl): action import - display err

ui/src/app/views/workflow/add/workflow.add.html
1. Description
code formating to be able to merge WasC
n/a
1. About tests
n/a
1. Mentions
@ovh/cds
=> refactor(ui): code format

engine/hooks/scheduler.go
=> fix (hook): saveTaskExecution

ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
Sidebar is loading forever
1. About tests
1. Mentions
@ovh/cds
=> fix (ui): need to set current workflow run

engine/hooks/scheduler.go, engine/hooks/tasks.go
=> fix (engine): scheduler restart

engine/worker/cmd_cache.go, sdk/cache.go, tests/fixtures/ITSCWRKFLW4/tag-push-pull.pip.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): worker cache pull with good cwd

ui/src/app/service/workflow/workflow.core.service.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix sidebar for node run

ui/src/app/shared/action/action.html, ui/src/app/shared/action/step/step.component.ts, ui/src/app/shared/action/step/step.html, ui/src/app/views/application/show/workflow/trigger/trigger.html, ui/src/app/views/pipeline/show/workflow/stage/form/pipeline.stage.form.html
1. Description
avoid check other checkbox...
none
1. About tests
Manual done (edit pipeline, stage, action)
1. Mentions
@ovh/cds
=> fix (ui): label on checkbox

engine/api/migrate/default_payload.go, engine/api/workflow.go, engine/api/workflow/dao_hook.go, engine/api/workflow/hook.go, engine/api/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not write default payload with an empty git.branch

engine/api/workflow/workflow_importer.go, engine/api/workflow_import.go
1. Description
In case of "pipeline not found error", the error was not raised
n/a
1. About tests
manual
1. Mentions
@ovh/cds
=> fix(api): workflow import error message

ui/src/app/shared/workflow/node/workflow.node.component.ts
1. Description
Must not load each application when loading a workflow
1. About tests
1. Mentions
@ovh/cds
=> fix: not load application

cli/cdsctl/monitoring.go
1. Description
display run, node, workflow
none
1. About tests
Manual done, with old and new workflows
1. Mentions
@ovh/cds
and display data from CDS workflows
=> fix (cdsctl): monito - enter to open browser on workflow

engine/api/workflow/process.go
1. Description
pass git values to child if it's the same repository to keep single hash for all workflow run
1. About tests
1. Mentions
@blaryjp 
@ovh/cds
=> fix(api): pass git values to child if it's the same repository

engine/api/repositoriesmanager/repositories_manager.go, engine/api/workflow.go, engine/api/workflow/hook.go, engine/api/workflow/workflow_importer.go, sdk/application.go
1. Description
Unable to create repository webhook
1. About tests
1. Mentions
@ovh/cds
=> fix (api): create webhook + remove code duplicate

engine/hatchery/swarm/swarm_util_kill.go
1. Description
%d -> %s, and display err in log error
none
1. About tests
none
1. Mentions
@ovh/cds
=> fix (hatchery/swarm): log format on remove network

engine/.debpacker.yml
1. Description
Change config file name
n/a
1. About tests
n/a
1. Mentions
@ovh/cds
=> fix(engine): debian package

engine/api/migrate/default_payload.go, engine/api/workflow/dao_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add check in default payload migration

cli/cdsctl/worker_model.go, engine/api/worker_model.go, engine/worker/requirement.go, sdk/cdsclient/client_worker_model.go, sdk/cdsclient/interface.go, tests/clictl_worker_model.yml
1. Description
Add cdsctl worker model show
none
1. About tests
new IT
1. Mentions
@ovh/cds
=> fix (worker): get WM on checkRequirements

docs/content/hosting/_index.md, docs/content/workflows/pipelines/requirements/worker-model/_index.md
1. Description
1. About tests
hugo launched
1. Mentions
@ovh/cds
=> doc: vsphere -> vshpere

cli/cdsctl/worker_model.go
1. About tests
SUCCESS tests/clictl_worker_model.yml
1. Mentions
@ovh/cds
=> fix (cdsctl): check err on worker model delete

engine/.debpacker.yml, tools/debpacker/tmpl.go
1. Description
systemd environment variable wrong syntax
n/a
1. About tests
n/a
1. Mentions
@ovh/cds
=> fix(tools/debpacker): engine systemd config

ui/src/app/views/pipeline/add/pipeline.add.html, ui/src/app/views/pipeline/add/pipeline.add.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix scroll on import pipeline

engine/.debpacker.yml, engine/api/workflow/workflow_importer.go
1. Description
There was no default values on history length on workflow import
n/a
1. About tests
regression tests
1. Mentions
@ovh/cds
=> fix(api): workflow import default history length

ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
1. Description
sidebar not up to date + restart button disabled
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): sidebar not up to date

ui/src/app/shared/favorite-cards/favorite-cards.component.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix favorite workflow add

tests/sc_workflow_run_cache.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test: more retries it worker cache

ui/src/app/shared/favorite-cards/favorite-cards.component.html, ui/src/app/shared/favorite-cards/favorite-cards.component.scss, ui/src/app/shared/favorite-cards/favorite-cards.component.ts, ui/src/app/views/favorite/favorite.component.ts, ui/src/app/views/project/show/project.component.ts, ui/src/app/views/project/show/project.html, ui/src/app/views/workflow/workflow.component.ts, ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix favorite style

engine/api/api_routes.go, engine/api/environment.go, engine/api/environment/environment_importer.go, engine/api/environment/environment_variable.go, engine/api/environment_group.go, engine/api/environment_key.go, engine/api/environment_variable.go, engine/api/event/publish_environment.go, sdk/event_environment.go
1. Description
Add environment events
1. About tests
1. Mentions
@ovh/cds
=> feat (api): add environment events

engine/api/event/publish_workflow.go, engine/api/workflow.go, engine/api/workflow_group.go, sdk/event_workflow.go
1. Description
Add workflow event
1. About tests
1. Mentions
@ovh/cds
=> feat (api): add workflow event

docker-compose.yml
=> doc: docker-compose

engine/sql/088_default_mig.sql
=> fix(sql): new imported app: defaut mig DONE

contrib/uservices/cds2es/process.go
1. Description
add field related to project, application, pipeline, workflow and environment
1. About tests
1. Mentions
@ovh/cds
=> feat (cds2es): add fields

engine/api/migrate/default_payload.go, engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/hook.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_hook.go, engine/api/workflow_test.go, engine/api/workflow_trigger.go, sdk/workflow.go
1. Description
Pay attention ! Need to merge in wasc branch before merge wasc to master.
Related to the old PR https://github.com/ovh/cds/pull/2536
close #2532 
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not add default tags if there already some tags setted #2532

engine/Makefile, sdk/exportentities/workflow.go, sdk/exportentities/workflow_test.go, sdk/hook.go, sdk/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix parse workflow in import workflow for hook config

sdk/exportentities/pipeline_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): fix unit tests about pipeline export import

engine/api/workflow/dao_run.go
=> fix(api): avoid try store more than maxlength tags

engine/vcs/bitbucket/types.go, engine/vcs/github/client_event.go
=> fix (vcs): no warn log if Branch not found

engine/api/workflow.go
1. Description
close #2557 
1. About tests
1. Mentions
@ovh/cds
=> fix(api): if repository manager return an error for default payload it should not block the workflow update

docs/content/gettingstarted/_index.md, docs/content/gettingstarted/concepts/why_cds.md, docs/content/gettingstarted/import_workflow_with_webui.md, docs/content/gettingstarted/init_workflow_with_cdsctl.md, docs/content/gettingstarted/step_by_step_build_deploy.md, docs/layouts/shortcodes/expand.html
=> doc: style

engine/api/services/dao.go, sdk/cdsclient/client_services.go
+ unmarshal only if len content > 0
=> feat (engine): do not erase hash of hatchery

engine/hatchery/kubernetes/types.go, engine/hatchery/marathon/types.go, engine/hatchery/openstack/types.go, engine/hatchery/swarm/types.go, engine/hatchery/vsphere/types.go
=> fix (hatcher): router on hatcheryCommon

engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/openstack.go, engine/hatchery/serve.go, engine/hatchery/swarm/swarm_conf.go, engine/hatchery/vsphere/vsphere.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
=> fix (hatchery): call status on not fully initialized service

engine/api/services.go
=> fix (hatchery): register user's hatchery as service

engine/vcs/github/status.go
=> fix (services/vcs): default value of status

docs/content/cli/api/_index.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc: header on POST /login

engine/api/grpc_handlers.go, engine/api/workflow_queue.go
=> fix (engine): resync lock

engine/api/workflow/process.go, engine/worker/cmd_update.go, engine/worker/init.go, sdk/cdsclient/client.go
=> feat (worker): new timeout 120s
