ovh/cds

engine/worker/cmd_update.go, engine/worker/init.go, sdk/cdsclient/client.go
=> fix (worker): timeout 360s

engine/hooks/hooks_handlers.go
=> fix (service/hooks): ProcessingTimestamp==0 : todo

docs/content/workflows/pipelines/requirements/_index.md, docs/content/workflows/pipelines/requirements/network_access/_index.md
1. Doc for Network Access requirement
1. Related issues : none
1. About tests : n/a
1. Mentions
There was no example, I added a small one to hint user about port usage 
@ovh/cds
=> doc: requirement network access

ui/src/assets/worker/web/version.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix version polling time

engine/worker/take_workflow_node_run_job.go
=> fix (worker): retry after 15s

engine/api/workflow/dao_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix purge for empty pure tags

engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): filter purge for empty pure tags

engine/api/grpc_handlers.go, engine/api/workflow_queue.go
=> fix (engine): remove fixme - git branch

ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix bad run node

engine/api/api.go, engine/api/workflow/resync_workflow.go, engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): quick fix on db to add ctx on limited handlers

engine/api/api.go, engine/hooks/types.go, engine/repositories/types.go
1. Description
Error in configuration example for Redis
@ovh/cds
=> doc: fix typo in redis sentinel configuration

ui/src/app/shared/workflow/join/workflow.join.component.ts, ui/src/app/shared/workflow/join/workflow.join.html, ui/src/app/shared/workflow/join/workflow.join.scss, ui/src/app/views/workflow/graph/workflow.graph.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix run join and add loader

engine/api/grpc_handlers.go, engine/api/permission.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_queue.go, engine/api/workflow_run.go
=> fix (engine): log postLog + add prj in logs

engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/process_parameters.go, engine/api/workflow/resync_workflow.go, engine/api/workflow/run_workflow.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_application.go, engine/api/workflow_queue.go, engine/api/workflow_queue_artifact.go, engine/api/workflow_queue_test.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go, engine/api/workflow_trigger.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add load options for node run and tests

sdk/cdsclient/client_queue.go
1. Description
Add retry on POST artifact/url
We got some issues on container creation. 
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): add retry on artifact/url

engine/sql/090_unique_subnum.sql
1. Description
We have node run duplication
1. About tests
1. Mentions
@ovh/cds
=> fix: avoid node run duplication

Gopkg.lock, engine/api/api_routes.go, engine/api/router.go, vendor/github.com/rakyll/goutil/LICENSE, vendor/github.com/rakyll/goutil/opencensus/LICENSE, vendor/github.com/rakyll/goutil/pprofutil/grpc.go, vendor/github.com/rakyll/goutil/pprofutil/http.go
1. Description
to add label on go traces
none
1. About tests
run pprof on a cpu profile
1. Mentions
@ovh/cds
=> feat(api): add pprof http label  and enable GET method to run with pprof

engine/hooks/hooks_handlers.go
1. Description
if it's an existing hook delete task to recreate
close #2613 
1. About tests
1. Mentions
@ovh/cds
=> fix(hook): after a cron update the task which is already planned is not refresh close #2613

engine/sql/090_unique_subnum.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sql): move constraint for subnum

engine/api/workflow/dao_node_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix multiple same subnum, do not reprocess all workflow for nothing

engine/api/workflow.go
1. Description
1. About tests
1. Mentions
cc @blaryjp 
@ovh/cds
=> fix(api): fix edit default payload with application without repo linked

engine/api/workflow/process.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add permission for workflow and environment just for manual run

engine/api/workflow/execute_node_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): inc stageTerminated for empty stages

cli/cdsctl/main.go, cli/cdsctl/user.go
1. Description
close #2568 
1. About tests
1. Mentions
@ovh/cds
=> fix(cli): cdsctl bookmarks are not the right bookmarks

engine/api/action/action.go
1. Description
close #2545 
1. About tests
1. Mentions
@ovh/cds
=> fix(api): take care or optional flag when you import pipeline

cli/cdsctl/monitoring.go
=> feat (cdsctl): warn -> yellow

engine/api/auth/ldapclient.go
=> fix (api): one line check err

ui/src/app/shared/action/step/step.html
=> fix (ui): equals is not equals

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: do not send pipeline build event, eventjob on client

contrib/plugins/plugin-venom/venom.go
=> fix (plugin/venom): redis import

cli/cdsctl/workflow_artifact.go
=> fix (cdsctl): import not used

engine/api/api_routes.go, engine/api/event/event.go, engine/api/event/publish.go, engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: use redis pubsub for sse events

engine/worker/builtin_gitclone.go
=> fix (worker): compute cds.semver if git.describe is a tag

engine/api/action/builtin.go, engine/sql/092_gittag.sql, engine/worker/builtin_gitclone.go, engine/worker/builtin_gittag.go
=> feat (worker): gitTag, new parameters

engine/sql/092_gittag.sql
=> fix (engine): no worker_model_name column

engine/api/status.go, engine/vcs/types.go, engine/vcs/vcs.go, engine/vcs/vcs_handlers.go
none
1. About tests
manual done
1. Mentions
@ovh/cds
=> feat (engine): alert is there is 0 srv of one type

engine/api/workflow/dao_node_run.go, engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix update node run for a worker export

contrib/plugins/plugin-ssh-cmd/ssh.go
1. Description
could be linked to https://github.com/golang/go/issues/19767
1. About tests
1. Mentions
@ovh/cds
=> fix(plugin): fix ssh-cmd config

ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
missing translation
n/a
1. About tests
n/a
1. Mentions
@ovh/cds
=> fix(ui): deployment platform missing translation

engine/api/pipeline/pipeline_importer.go, engine/api/pipeline/pipeline_importer_test.go, engine/api/pipeline/pipeline_stage.go
1. Description
close #2661 
1. About tests
unit test
1. Mentions
@ovh/cds
=> fix(api): import pipeline with forceUpdate guarantee new order or stages

engine/worker/builtin_deploy_application.go
1. Description
We should not always return success 
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): deployment application action result

contrib/grpcplugins/deployment/arsenal/main.go, engine/worker/builtin_deploy_application.go
1. Description
* display manifest version
* fix marshalling on deployment followup
* logs
1. About tests
1. Mentions
@ovh/cds
=> fix(worker, contrib/arsenal): various fixes

engine/api/api_routes.go, engine/api/application.go, engine/api/project.go, engine/api/project_test.go
1. Description
Arsenal need to get writable projects only
1. About tests
get projects
1. Mentions
@ovh/cds
=> feat(api): get projects and applications with only write permission only

engine/api/application_deployment.go, sdk/platform.go
1. Description
merge platform config if modified by a provider
1. About tests
1. Mentions
@ovh/cds
=> fix(api): merge platform config if modified by provider

engine/api/api.go, engine/hooks/hooks.go, engine/hooks/types.go, engine/repositories/repositories.go, engine/vcs/vcs.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): add better logs for redis connection error

tools/debpacker/tmpl.go
=> chore (debpacker): create home for user cds-engine

sdk/cdsclient/client.go, sdk/cdsclient/client_provider.go, sdk/cdsclient/config.go, sdk/cdsclient/http.go, sdk/cdsclient/interface.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(sdk): provider dedicated interface

engine/api/workflow/execute_node_job_run.go, engine/api/workflow/process_parameters.go, sdk/exportentities/action.go, sdk/exportentities/pipeline.go, sdk/exportentities/workflow.go, sdk/parameter.go, sdk/plugin/common.go, sdk/plugin/types.go, sdk/stage.go, sdk/util.go, sdk/vcs/git/git.go, sdk/workflow.go
1. Description
close #2664 
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): optimise slice and map allocation

contrib/grpcplugins/deployment/arsenal/.gitignore, contrib/grpcplugins/deployment/arsenal/Makefile, contrib/grpcplugins/deployment/arsenal/arsenal.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore(contrib): arsenal makefile

engine/api/workflow/dao.go, engine/api/workflow/process.go
=> fix (api): update purge_tags

engine/api/api.go, engine/api/workflow/init.go, engine/api/workflow/process.go
1. Description
close #2683 
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add ui.run url in build parameters

ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html
1. Description
close #2688
1. About tests
1. Mentions
@ovh/cds
=> fix (ui): run condition too long close #2688

ui/src/app/views/broadcast/details/broadcast.details.component.html, ui/src/app/views/broadcast/list/broadcast.list.component.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix line break for broadcast

ui/src/app/service/pipeline/pipeline.service.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add withPermission for export pipeline

engine/api/workflow/process.go
=> fix (api): do not create var if sanitizedRepositoryFullname == ""

sdk/exportentities/workflow.go, sdk/exportentities/workflow_test.go
Associated platform was not exported as code in workflows
Close #2697 
Naive update from EnvironmentName export
@ovh/cds
=> fix (wf): wf as code does not export linked platforms

ui/src/app/views/application/show/admin/deployment/application.deployment.html, ui/src/app/views/application/show/admin/deployment/application.deployment.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): center buttons on application platform config

ui/src/app/shared/workflow/node/conditions/condition-form/condition.component.ts, ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add better ui for boolean manual on cds conditions

ui/src/app/shared/favorite-cards/favorite-cards.component.html, ui/src/app/views/broadcast/list/broadcast.list.component.html, ui/src/app/views/home/home.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(ui): change style of button in favorites

engine/api/migrate/hatchery_cmd.go, engine/api/worker/pattern.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api,hatchery): fix duplicate user data and add migration fix

engine/api/migrate/hatchery_cmd.go, engine/api/worker/pattern.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): delete grpc in userdata

engine/api/migrate/hatchery_cmd.go, engine/api/worker/pattern.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): delete force-exit for docker worker model

ui/src/app/shared/action/action.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix error on ui action page

docs/content/workflows/pipelines/requirements/worker-model/docker/docker-customized.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs(workflow): fix documentation on worker model docker

cli/cdsctl/monitoring.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cli): change color for warning

contrib/grpcplugins/deployment/arsenal/main.go
=> feat (plugin/arsenal): add body if err

cli/cdsctl/worker_model.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cli): lint variable name

engine/api/repositories_manager.go, engine/api/services/http.go, engine/api/workflow_run.go
=> fix (api): avoid 401 on ui for vcs

sdk/action.go, sdk/cache.go, sdk/event.go, sdk/event_pipeline.go, sdk/favorite.go, sdk/hook.go, sdk/platform.go, sdk/plugin.go, sdk/repositories_operation.go, sdk/requirement.go, sdk/user.go, sdk/workflow.go, sdk/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): lint

engine/api/broadcast.go, engine/api/cache/cache.go, engine/api/cache/redis.go, engine/api/event/publish_broadcast.go, engine/api/events.go, engine/repositories/dao.go, sdk/event_broadcast.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add broadcast on sse + improve cache lock

engine/api/platform.go, engine/api/platform/dao_model.go, engine/api/platform/dao_platform.go, engine/api/project.go, engine/api/project/dao.go, engine/api/project_platform.go, engine/sql/100_deployment_platform_shared.sql, sdk/platform.go, tests/cli_admin_platform_model.yml, tests/fixtures/platforms/arsenal.yml, ui/src/app/model/platform.model.ts, ui/src/app/views/project/show/platforms/form/platform.form.component.ts, ui/src/app/views/project/show/platforms/list/project.platform.list.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api,ui) public platforms

contrib/plugins/plugin-kafka-publish/cli.go, contrib/plugins/plugin-kafka-publish/cli_actions.go, contrib/plugins/plugin-kafka-publish/kafka_ack.go, contrib/plugins/plugin-kafka-publish/kafka_consumer.go, contrib/plugins/plugin-kafka-publish/kafkapublisher/types.go, contrib/plugins/plugin-kafka-publish/plugin.go, contrib/plugins/plugin-kafka-publish/plugin_run.go
1. Description
if --key used (and key parameter on action), use it for AES.
let user to use two kafka users
1. About tests
manual done, backward compatibility ok
1. Mentions
@ovh/cds
=> feat (plugin/kafka): --key flag

engine/hatchery/openstack/spawn.go, engine/hatchery/vsphere/spawn.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): fix userdata chaining

contrib/grpcplugins/deployment/arsenal/main.go, engine/worker/run_plugin.go
1. Description
trying to don't lost logs
1. About tests
1. Mentions
@ovh/cds
=> fix(plugin): drain logs from plugin

sdk/action_script.go, sdk/exportentities/action.go, sdk/exportentities/pipeline.go, sdk/exportentities/pipeline_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): deploy application as code

engine/api/api_routes.go, engine/api/application/application_variable.go, engine/api/application/application_vcs.go, engine/api/environment/environment.go, engine/api/warning.go, engine/api/warning/dao.go, engine/api/warning/warning.go, engine/api/warning/warning_key.go, engine/api/warning/warning_key_test.go, engine/api/warning/warning_message.go, engine/api/warning/warning_project.go, engine/api/warning/warning_variable.go, engine/api/warning_test.go, sdk/warning.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add missing project warning

cli/cdsctl/worker_model.go, engine/api/worker/model.go, engine/api/worker/model_test.go, engine/api/worker_model.go, sdk/cdsclient/client_worker_model.go, sdk/cdsclient/interface.go, tests/clictl_worker_model.yml, ui/src/app/service/worker-model/worker-model.service.ts, ui/src/app/views/admin/broadcast/list/broadcast.list.component.ts, ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts, ui/src/app/views/settings/worker-model/list/worker-model.list.html, ui/src/app/views/settings/worker-model/list/worker-model.list.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #2739
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add search for binary capabilities inside worker model

cli/cdsctl/admin_grpc_plugin.go, cli/cdsctl/workflow_artifact.go, engine/api/actionplugin/plugin.go, engine/api/artifact.go, engine/api/artifact/artifact.go, engine/api/workflow_queue_artifact.go, engine/api/workflow_queue_test.go, engine/sql/101_artifact_sha512.sql, sdk/action.go, sdk/artifact.go, sdk/cdsclient/client_queue.go, sdk/common.go, sdk/plugin.go, sdk/workflow_run.go, sdk/workflow_run_easyjson.go, ui/src/app/views/workflow/run/node/artifact/artifact.list.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (cli,engine,sdk): artifact sha512sum

engine/api/workflow/dao_artifact.go
=> fix (api): load artifact sha512 on old wf

engine/api/workflow/dao_artifact.go
=> fix (api): ambiguous column name

sdk/exportentities/action.go, sdk/exportentities/pipeline.go
1. Description
Some code is missing to properly handle deploy action in workflow as code.
None.
1. About tests
Not yet (where to test this?)
1. Mentions
@ovh/cds
=> Fix missing "as code" for deploy action

engine/api/workflow/dao_node_run.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): add more logs to debug commits

ui/src/app/views/admin/broadcast/add/broadcast.add.html, ui/src/app/views/admin/broadcast/edit/broadcast.edit.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add a preview mode on broadcast add/edit

engine/api/workflow/dao_artifact.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix query on artifacts

engine/api/api_routes.go, engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): sse events subscription cache => 10 minutes

cli/cdsctl/admin_grpc_plugin.go, cli/cdsctl/workflow_artifact.go, engine/api/actionplugin/plugin.go, sdk/artifact.go, sdk/cdsclient/client_queue.go, sdk/common.go
=> fix (api): compute md5/sha512

engine/api/group/public.go, engine/api/project.go, engine/api/project_test.go
1. Description
linked to #2720 
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix for group name and add test

engine/hooks/kafka.go
this let CDS Admin to propose a 'public' kafka platform
=> feat (engine/hooks): kafka, use KEY / UUID in cg

engine/api/action/builtin.go, engine/api/application.go, engine/api/group/public.go, engine/api/project.go, engine/api/project_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): load projets and application as a provider

sdk/cdsclient/client_import.go, sdk/exportentities/action.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): deploy application action as code format

engine/hatchery/swarm/swarm_util_create.go
=> fix (hatchery/swarm): trimspace on opts

sdk/log/log.go
=> fix (engine): take care of warning level

engine/hooks/tasks.go, engine/vcs/gitlab/client_hook.go, engine/vcs/gitlab/client_status.go, engine/vcs/vcs_handlers.go
=> fix (vcs/gitlab): fix git.repository values

ui/src/app/views/settings/worker-model/list/worker-model.list.html
Hello,
fix pagination alignment for the list in worker-model
Cf:
See you :)
=> fix(ui): fix pagination alignment for the list in worker-model

engine/api/workflow_import.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): import workflows with platforms

sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): worker model spawn error message

engine/api/workflow_application.go, engine/worker/builtin_gittag.go
and reset minor + patch to 0 if major
=> fix (worker): gitTag, reset path to 0 if minor

engine/api/api_routes.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_run.go, engine/api/workflow_run.go, engine/worker/cmd_cache.go, sdk/parameter.go, sdk/workflow_run.go, tests/sc_workflow_create_run_join.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): avoid whole node run load

engine/api/event/publish_workflow_run.go, sdk/event.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: remove workflow from workflow run event

engine/api/api.go, engine/api/event/event.go, engine/api/event/kafka.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add max message size on kafka configuration

engine/worker/logger.go
=> fix (worker): sendLog ticker review

engine/api/environment/environment.go, engine/api/project/dao_dependencies.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): loadProject with pipeline permissions

engine/hooks/scheduler.go
=> fix (hooks): delete taskExecutions if can't be executed

engine/api/tracing/tracing.go, engine/api/workflow/run_workflow.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): run from hooks

engine/api/group/pipeline_group.go, engine/api/pipeline/pipeline_importer.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): group permission on pipeline doesn't matter

engine/hooks/kafka.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hooks): kafka brokers

engine/api/workflow/execute_node_job_run.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow node run report with errors

engine/api/event/publish_project.go, engine/api/platform.go, engine/api/platform/dao_model.go, engine/api/platform/dao_platform.go, engine/api/platform/platform_model.go, engine/api/platform_test.go, sdk/platform.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): public platform configuration

engine/api/pipeline_test.go
1. Description
Add tests (following IAAS asks)
close #2541 
1. About tests
1. Mentions
@ovh/cds
=> test(api): add test for delete pipeline (close #2541)

engine/api/test/test.go, engine/api/workflow_test.go, sdk/log/log.go
1. Description
Partially #2540
1. About tests
1. Mentions
@ovh/cds
=> test(api): add benchmark for workflows

ui/src/app/shared/requirements/list/requirements.list.html
=> fix (ui): btn delete jobs disabled

engine/api/cache/redis.go, engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: add retry on redis

engine/api/workflow/workflow_exporter.go, engine/api/workflow_export_test.go, sdk/exportentities/workflow.go, sdk/exportentities/workflow_test.go
1. Description
close #2527
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add history length on workflow as code

ui/src/app/views/settings/queue/queue.component.html, ui/src/app/views/settings/queue/queue.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): update queue view in settings

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): check error on w.Write

engine/api/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test(api): skip bench

sdk/exportentities/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): sort depends on

engine/api/mon_db.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): display right queue for right user

engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go
=> feat (api): add some debug logs about async

ui/src/app/views/navbar/navbar.html
=> feat (ui): set disconnect into submenu

ui/src/app/shared/warning/mark-list/warning.mark.list.html, ui/src/app/shared/warning/mark-single/warning.mark.html
=> fix (ui): display warning

engine/api/cache/redis.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): retry on get lock

engine/api/application_group.go, engine/api/application_group_test.go, engine/api/group/application_group.go, engine/api/project_group.go
1. Description
close #2809 
1. About tests
unit tests
1. Mentions
@ovh/cds
=> fix(api): avoid delete the last rwx group on app/env/wf/pip #2809

ui/src/app/shared/parameter/value/parameter.value.component.ts, ui/src/app/views/workflow/run/node/history/history.component.ts, ui/src/app/views/workflow/run/node/node.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (ui): navigate into historic and fix workflow run pipeline parameters

sdk/application.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: skip last modified from mapstructure

ui/src/environments/environment.js, ui/src/environments/environment.test.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): remove js environment files

ui/src/app/views/navbar/navbar.component.ts, ui/src/app/views/navbar/navbar.html, ui/src/app/views/navbar/navbar.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #2718
close #2826 
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add better notification popup

engine/api/event/publish_application.go, engine/api/repositories_manager.go, engine/api/warning/warning_project_vcs.go, engine/api/warning/warning_project_vcs_test.go, sdk/event_application.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add application repo event

ui/src/app/views/navbar/navbar.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix style of bookmarks

engine/api/workflow/dao_node.go, ui/src/app/shared/audit/list/audit.list.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api):  node ID erased on old workflow

ui/src/app/views/workflow/graph/workflow.graph.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix width of workflow graph

ui/src/app/views/navbar/navbar.html, ui/src/app/views/navbar/navbar.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add link in broadcast list

sdk/workflow_run.go, sdk/workflow_run_test.go
1. Description
close #2850
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): fix add multiple tag value

engine/api/workflow/dao_node_run.go, engine/vcs/github/client_commit.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix commit list

engine/api/hook.go, engine/api/poller/executer.go, engine/api/repositoriesmanager/repositories_manager.go, engine/api/workflow_hook.go
to know which project is on error:
```
401  | /vcs/github/polling 	 not authenticated
```
=> feat (api): debug prj on 401|/vcs/github/polling

ui/src/app/model/workflow.run.model.ts, ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts, ui/src/app/views/workflow/run/node/artifact/artifact.list.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat (ui): add filter on artifact list

sdk/interpolate/interpolate.go, sdk/interpolate/interpolate_test.go
1. Description
No impact on benchmark
close #2808
1. About tests
unit tests
1. Mentions
@ovh/cds
=> fix(sdk): fix interpolate with dash into helper

ui/src/app/views/workflow/run/node/test/table/test.table.component.ts, ui/src/app/views/workflow/run/node/test/table/test.table.html
fix user issue CD-1862
before fix:
```
>       assert free_devices == host.flashcache_free_devices
E       AssertionError: assert [] == []
E         Left contains more items, first extra item:
E         Full diff:
E         - []
E         + []
```
with the fix:
```
>       assert free_devices == host.flashcache_free_devices
E       AssertionError: assert [<Mock id='139953411755408'>] == []
E         Left contains more items, first extra item: <Mock id='139953411755408'>
E         Full diff:
E         - [<Mock id='139953411755408'>]
E         + []
```
=> fix (ui): unit-test display results

engine/api/application/application_parser.go, engine/api/workflow/dao.go, engine/api/workflow/process_parameters.go, engine/api/workflow/workflow_importer.go, engine/api/workflow_queue.go, sdk/parameter.go, sdk/workflow.go
closes #2825
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow push with platform in context

engine/hatchery/swarm/swarm_util_kill.go
close #2733
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery/swarm): don't try to remove docker bridge

engine/api/cache.go, engine/worker/cmd_cache.go, sdk/cache.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix worker cache for symlink directory

ui/src/app/service/logout.interceptor.service.ts
1. Description
close #2423
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): login page redirect in all cases

engine/api/project/dao_dependencies.go, engine/api/workflow/dao.go, sdk/common.go, sdk/project.go, ui/src/app/model/project.model.ts, ui/src/app/views/project/show/application/application.list.html, ui/src/app/views/project/show/pipeline/pipeline.list.html, ui/src/app/views/project/show/workflow/workflow.list.component.ts, ui/src/app/views/project/show/workflow/workflow.list.html, ui/src/app/views/project/show/workflow/workflow.list.scss, ui/src/app/views/workflow/add/workflow.add.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #2674
1. About tests
1. Mentions
cc @blaryjp 
@ovh/cds
=> feat(ui): add better list view as project list

engine/hatchery/swarm/swarm_util_kill.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): fix network deletion

ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
In order to keep pipeline name for view title
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix tab link for node run

docs/content/hosting/repositories-manager/bitbucket.md, docs/content/hosting/repositories-manager/github.md, docs/content/hosting/repositories-manager/gitlab.md, engine/api/workflow/hook.go, engine/vcs/bitbucket/bitbucket.go, engine/vcs/bitbucket/bitbucket_test.go, engine/vcs/bitbucket/client_hook.go, engine/vcs/github/client_hook.go, engine/vcs/github/github.go, engine/vcs/github/github_test.go, engine/vcs/github/oauth_consumer.go, engine/vcs/gitlab/client_hook.go, engine/vcs/gitlab/gitlab.go, engine/vcs/gitlab/gitlab_test.go, engine/vcs/types.go, engine/vcs/vcs.go
1. Description
close #2865 
1. About tests
Need to be tested on the preprod
1. Mentions
@ovh/cds
=> feat(vcs): add proxy configuration for webhook (public url) close #2865

ui/src/app/shared/usage/applications/usage.applications.html, ui/src/app/shared/usage/environments/usage.environments.html, ui/src/app/shared/usage/pipelines/usage.pipelines.html, ui/src/app/shared/usage/workflows/usage.workflows.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix usage links

ui/src/app/views/account/account.routing.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): change title view of login page for keepass autocompletion

engine/api/workflow/dao_run.go, ui/src/app/shared/parameter/value/parameter.value.component.ts, ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/workflow.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix pipeline params display and slow UI

engine/api/application.go, engine/api/ascode.go, engine/api/repositories_manager.go, engine/api/repositoriesmanager/repositories_manager.go, engine/api/services/http.go, engine/api/workflow/dao_node_run.go, engine/api/workflow_run.go, sdk/error.go
=> fix (api): 404 commit not found is not an error

ui/src/app/service/auth/authenRouteActivate.ts, ui/src/app/service/logout.interceptor.service.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): do not redirect to the login page after login

engine/worker/builtin_junit.go
=> fix (worker): junit, replace before send result

engine/api/application_import_test.go, engine/api/ascode.go, engine/api/services/http.go, engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/dao_node.go, engine/api/workflow/hook.go, engine/api/workflow/repository.go, engine/api/workflow_run.go, engine/repositories/processor_checkout.go, engine/service/heartbeat.go, sdk/application.go, sdk/exportentities/workflow.go
you can keep the commits and merge instead of squash
=>  fix(api): workflow as code and beyond

engine/api/event/publish_workflow_run.go, engine/api/grpc_handlers.go, engine/api/notification/user.go, engine/api/workflow/dao_run.go, engine/api/workflow/run_workflow.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_queue.go, engine/api/workflow_run.go, sdk/build.go, sdk/event.go, sdk/stage.go, sdk/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: Improve node run event + send event on workflow run never built

engine/api/api.go, engine/api/broadcast/broadcast.go, engine/api/broadcast/init.go, engine/api/workflow/init.go
1. Description
close #2609 
1. About tests
1. Mentions
@ovh/cds
=> feat(api): clean old archived broadcasts

ui/src/app/shared/workflow/node/run/node.run.param.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): don't display 'no parameter' if there isn't any parameter

engine/api/ascode.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): import workflow as code with a platform

ui/src/app/views/project/show/warnings/project.warnings.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: build ui

engine/api/api.go, engine/api/database/cli.go, engine/api/database/database.go, engine/api/database/dbmigrate/migrate.go, engine/api/database/types.go, engine/api/services/const.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/process_parameters.go, engine/hooks/types.go, engine/main.go, engine/migrateservice/handlers.go, engine/migrateservice/migrate.go, engine/migrateservice/service.go, engine/repositories/types.go, engine/service/service.go, engine/sql/README.md, engine/types.go, engine/vcs/types.go, sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(engine): migrate service

sdk/build.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix log event warning

engine/api/api_routes.go, engine/api/application.go, engine/api/application_test.go, engine/api/project_test.go, engine/api/workflow.go, engine/api/workflow_test.go, sdk/cdsclient/client_provider.go, sdk/cdsclient/interface.go
1. Description
New provider sdk func: 
* List workflows
* List applications with usages (to see workflow linked to an application)
* Get a workflow (with all pipeline details)
* Update application metadata
n/a
1. About tests
see unit tests
1. Mentions
@ovh/cds
=> feat(sdk, api): new provider sdk functions

engine/api/application_deployment.go, engine/api/project/key.go, sdk/platform.go
1. Description
#2867 
1. About tests
1. Mentions
@ovh/cds
close #2867
=> fix (api): export application deployment strategies.

engine/hatchery/local/local.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery/local): don't call API in ApplyConfiguration function

engine/api/api_routes.go, engine/api/migrate/workflow_node_run_artifacts.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix resync vcs to postexecute and fix migrate artifact

engine/api/api_routes.go, engine/api/hatchery/hatchery.go, engine/api/repositoriesmanager/events.go, engine/api/worker/pattern.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go, engine/worker/cmd_run.go, engine/worker/requirement.go, sdk/build.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/error.go, sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): release a job when it can't start

sdk/platform.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): update deployment strategy

engine/api/api.go, engine/api/database/cli.go, engine/api/database/database.go, engine/api/database/types.go, engine/api/test/test.go, engine/migrateservice/migrate.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): set database role

sdk/exportentities/workflow.go, sdk/workflow.go
1. Description
trying to fix unit tests assertions on
`TestWorkflow_GetWorkflow/Complexe_workflow_with_joins_should_not_raise_an_error`
n/a
1. About tests
TestWorkflow_GetWorkflow
1. Mentions
@ovh/cds
=> fix(sdk): sort the workflow struct

ui/src/app/views/home/timeline/home.timeline.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add missing translate

sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (hatchery): fix max worker increment

ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.html, ui/src/app/views/home/timeline/home.timeline.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #2929 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): don't display no new commit when no repo is linked on run modal #2929

ui/src/app/views/home/timeline/home.timeline.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): loading timeline

engine/api/workflow/dao_node_run.go
1. Description
Now the commits list works. It's time to delete useless logs 💃 
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): delete useless logs

engine/api/api.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/init.go, sdk/hatchery/hatchery.go
1. Description
close #2938 
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add config for the default os and arch to launch

engine/api/workflow/execute_node_job_run_log_service.go, engine/hatchery/swarm/swarm.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix add service logs

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api) panic on flush

ui/src/app/model/pipeline.model.ts, ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/run/node/pipeline/pipeline.html, ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/service/service.log.html, ui/src/assets/worker/web/workflow-service-log.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add webworker for service logs

cli/cdsctl/workflow_as_code.go, engine/api/application/application_parser.go, engine/api/ascode.go, engine/api/workflow/process_parameters.go, sdk/application.go, sdk/exportentities/application.go, ui/src/app/model/vcs.model.ts, ui/src/app/shared/vcs/vcs.strategy.html, ui/src/app/views/application/show/admin/repository/application.repo.component.ts, ui/src/app/views/application/show/admin/repository/application.repo.html, ui/src/app/views/application/show/admin/repository/application.repo.scss, ui/src/app/views/workflow/add/workflow.add.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): delete branch and default branch from the ui and add warning

sdk/common.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(sdk): run a goroutine with panic recovery

sdk/exportentities/workflow.go, sdk/exportentities/workflow_test.go, ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/app/views/workflow/show/admin/workflow.admin.scss
1. Description
close #2915 
1. About tests
1. Mentions
cc @wi2L
@ovh/cds
=> feat(ui): add edit description on workflow #2915

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix panic on send sse msg

cli/cdsctl/worker_model.go, sdk/cdsclient/client_worker_model.go, sdk/cdsclient/interface.go
1. Description
1. About tests
1. Mentions
cc @d33d33 
@ovh/cds
=> fix(cli): fix worker model import with pattern name

ui/src/app/views/workflow/run/summary/workflow.run.summary.html, ui/src/app/views/workflow/show/workflow.html, ui/src/app/views/workflow/show/workflow.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add workflow as code label

engine/api/api.go, engine/api/warning/warning_project_permission.go, engine/api/warning/warning_project_permission_test.go, engine/api/warning/warning_project_variable.go, engine/api/warning/warning_project_variable_test.go, engine/api/warning/warning_variable.go, sdk/event_application.go, sdk/event_environment.go, sdk/event_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add new event on project variable warning

engine/api/api.go, engine/api/migrate/migrate_workflow.go, engine/api/purge/purge.go, engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/dao_node.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_run.go, engine/api/workflow/dao_test.go, engine/api/workflow/init.go, engine/api/workflow_run.go, engine/sql/109_workflow_delete.sql, sdk/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): async workflow deletion

engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): default payload from workflow as code

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): panic when client close sse

engine/api/repositoriesmanager/repositories_manager.go, engine/api/workflow/workflow_run_event.go, engine/vcs/bitbucket/client_pull_request.go, engine/vcs/bitbucket/client_pull_request_test.go, engine/vcs/bitbucket/types.go, engine/vcs/github/client_pull_request.go, engine/vcs/github/client_pull_request_test.go, engine/vcs/github/github_test.go, engine/vcs/gitlab/client_pull_request.go, engine/vcs/vcs_handlers.go, engine/vcs/vcs_router.go, sdk/repositories_manager.go, sdk/vcs.go, sdk/workflow_run.go, sdk/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api,vcs): push workflow report as pull request comments

engine/hatchery/marathon/marathon.go, engine/hatchery/marathon/types.go, sdk/hatchery/hatchery.go
=> fix(hatchery): too many routines in same time

engine/api/workflow/workflow_importer.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): load application with variables when running wf from repo

engine/api/api_test.go, engine/api/workflow/repository.go, engine/repositories/processor_checkout.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): run workflow from repository must keep repository fullname

engine/vcs/bitbucket/bitbucket.go, engine/vcs/bitbucket/bitbucket_test.go, engine/vcs/bitbucket/client_branch.go, engine/vcs/bitbucket/client_commit.go, engine/vcs/bitbucket/client_forks.go, engine/vcs/bitbucket/client_hook.go, engine/vcs/bitbucket/client_pull_request.go, engine/vcs/bitbucket/client_repos.go, engine/vcs/bitbucket/client_status.go, engine/vcs/bitbucket/client_user.go, engine/vcs/bitbucket/http.go, engine/vcs/bitbucket/oauth_consumer.go, engine/vcs/bitbucket/oauth_consumer_sign.go, engine/vcs/github/client_hook.go, engine/vcs/github/client_pull_request.go, engine/vcs/github/client_release.go, engine/vcs/github/client_status.go, engine/vcs/github/github.go, engine/vcs/github/github_test.go, engine/vcs/github/http.go, engine/vcs/types.go, engine/vcs/vcs.go
1. Description
First step is to be able to call vcs server REST API as a "CDS" user defined in configuration
Then use this user to push pull request comments
Next step will be automatic grant of the user on the repositories
and creation of pull requests for workflow as code
1. About tests
unit tests for bitbucket server
1. Mentions
@ovh/cds
=> feat(vcs): call vcs server API as a User

docs/content/workflows/pipelines/actions/builtin/script.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs(script): add worker cli inside script

engine/api/api_routes.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): remove deprecated route

engine/api/requirements.go, engine/api/worker/model.go, engine/api/worker/model_test.go, engine/api/worker/worker.go, engine/api/worker_model.go
1. Description
According to our dashboards, this routes represent 8% of all hits.
the response time is between 250ms and 1s
with the cache and on my local setup, the response time is divided by 5
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add cache on /worker/model and /worker/model/enabled

engine/api/application.go, engine/api/repositories_manager.go, engine/api/workflow/dao.go, engine/api/workflow/dao_hook.go, engine/api/workflow/hook.go, ui/src/app/service/application/application.store.ts
1. Description
1. About tests
close  #2913
1. Mentions
@ovh/cds
=> fix(api): when you update repomanager on an application, update workflow root linked

engine/api/workflow/dao_node_run_job.go, engine/api/workflow/execute_node_run.go, engine/sql/110_workflow_node_run_job.sql, sdk/cdsclient/client_queue.go, sdk/workflow_run.go, sdk/workflow_run_easyjson.go, sdk/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(sdk): order queue by project instance

engine/api/workflow/execute_node_job_run.go
this will avoid following logs: `resyncCommitStatus> Error sending status: sendVCSEventStatus> Unable to reload noderun xxxx: workflow.LoadNodeRunByID> Unable to load workflow_node_run node=xxxxx: context canceled
`
=> fix(api):  use the root context for sending commit status

engine/api/workflow/execute_node_job_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): ResyncCommitStatus with a fresh context

engine/api/grpc_handlers.go, engine/api/workflow/dao_run.go, engine/api/workflow/dao_run_test.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/run_workflow.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_queue.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go, sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): unable to load workflow_node_run because of context canceled

engine/api/workflow/workflow_run_event.go, sdk/workflow_run.go, sdk/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow run report

engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): erase useinfo from url fromRepository

engine/api/workflow/dao_node_run.go, engine/api/workflow/resync_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): be careful of nil commits list

ui/package.json, ui/src/app/app.component.ts, ui/src/app/shared/worker/shared.worker.ts, ui/src/app/shared/worker/web.worker.ts, ui/src/app/shared/worker/worker.ts, ui/src/app/views/application/show/application.component.ts, ui/src/app/views/run/pipeline.build.component.ts, ui/src/app/views/run/workflow/step/step.log.component.ts, ui/src/app/views/settings/queue/queue.component.ts, ui/src/app/views/workflow/add/workflow.add.component.ts, ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/assets/worker/sharedWorker.js, ui/src/assets/worker/webWorker.js, ui/src/environments/environment.prod.ts, ui/src/environments/environment.test.ts, ui/src/environments/environment.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add shared worker

ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix service job links for other job

engine/api/workflow/dao.go, engine/api/workflow/hook.go, ui/src/app/shared/workflow/node/hook/form/hook.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix repowebhook and workflow as code

ui/src/assets/worker/eventsource.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): reconnect sse on 500+

ui/src/app/app.service.ts, ui/src/app/shared/parameter/value/parameter.value.component.ts, ui/src/app/views/admin/broadcast/list/broadcast.list.component.ts, ui/src/app/views/application/show/application.component.ts, ui/src/app/views/broadcast/list/broadcast.list.component.ts, ui/src/app/views/navbar/navbar.component.ts, ui/src/app/views/pipeline/show/pipeline.show.component.ts, ui/src/app/views/project/show/project.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix external modification notification + sort broadcast

ui/src/assets/worker/sharedWorker.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add log for shared worker activity

engine/api/workflow_run.go, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/views/workflow/run/workflow.run.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
1. Description
#2914 
1. About tests
1. Mentions
@ovh/cds
=> feat: relaunch run after rename

ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
1. Description
Disable stop button
#1278 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): disabled stop button

engine/api/application/application_pipeline.go, engine/api/application/dao.go, engine/api/application/dao_key.go, engine/api/database/types.go, engine/api/environment/dao_key.go, engine/api/environment/environment.go, engine/api/environment/environment_variable.go, engine/api/pipeline/pipeline_parameter.go, engine/api/project/dao_key.go, sdk/error.go
1. Description
Fix error code on duplicate key
#2233 
1. About tests
1. Mentions
@ovh/cds
=> fix: better error code for duplicate key

engine/api/api_routes.go, engine/api/events.go
1. Description
Add disconnected map => now the writer close the channel 
Move manage event on client side instead of broker side
Remove unused code
1. About tests
1. Mentions
@ovh/cds
=> fix(api): reduce locktime + avoid deadlock

ui/src/app/views/project/list/project.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): load projects

README.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc(README): fix typo

contrib/grpcplugins/deployment/arsenal/Makefile, ui/src/app/shared/workflow/node/form/workflow.node.form.component.ts, ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts, ui/src/app/shared/workflow/node/wizard/node.wizard.html, ui/src/app/shared/workflow/trigger/workflow.trigger.component.ts, ui/src/app/shared/workflow/trigger/workflow.trigger.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #2991 
1. About tests
1. Mentions
cc @mama59 
@ovh/cds
=> fix(ui): add in workflow modal the platform link to a pipeline #2991

ui/src/app/app.component.ts, ui/src/assets/worker/eventsource.js, ui/src/assets/worker/sharedWorker.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add sharedworker reconnection

ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): stop node

ui/src/assets/worker/common.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: decrease sse connection duration to 5mn

engine/api/timeline.go, ui/src/app/app.service.ts, ui/src/app/model/environment.model.ts, ui/src/app/model/project.model.ts, ui/src/app/service/project/project.store.spec.ts, ui/src/app/service/project/project.store.ts, ui/src/app/shared/workflow/node/form/workflow.node.form.component.ts, ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts, ui/src/app/views/home/timeline/filter/home.timeline.filter.component.ts, ui/src/app/views/home/timeline/filter/home.timeline.filter.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): new design for timeline filter

engine/api/application.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix update icon application

ui/src/app/shared/workflow/join/trigger/trigger.join.component.ts, ui/src/app/shared/workflow/join/trigger/workflow.trigger.join.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix add a trigger on a join

engine/api/worker.go, engine/api/worker_model.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go, engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go, engine/hatchery/serve.go, engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_conf.go, engine/hatchery/swarm/swarm_util_get.go, engine/hatchery/swarm/swarm_util_kill.go, engine/hatchery/vsphere/client.go, engine/hatchery/vsphere/spawn.go, engine/hatchery/vsphere/vsphere.go, engine/worker/cmd_run.go, engine/worker/take_workflow_node_run_job.go, sdk/build.go, sdk/hatchery/hatchery.go, sdk/hatchery/heartbeat.go, sdk/hatchery/pool.go, sdk/hatchery/provisionning.go, sdk/hatchery/register.go, sdk/hatchery/starter.go, sdk/hatchery/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): improvements

engine/hatchery/marathon/marathon.go, engine/hatchery/serve.go, sdk/hatchery/hatchery.go, sdk/hatchery/provisionning.go, sdk/hatchery/register.go, sdk/hatchery/starter.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): various improvements

engine/api/workflow/awol.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/gorp_model.go, engine/api/workflow_queue.go, sdk/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): load queue improvements

engine/api/workflow/awol.go, engine/api/workflow/dao_node_run_job.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): restart awol

engine/api/api.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): rollback restart awol jobs

cli/types.go, engine/worker/cmd_run.go, sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): pipeline build jobs

engine/api/api_routes.go, engine/api/pipeline_import.go, engine/api/workflow_import.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix route for import as code via ui

ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/views/workflow/graph/workflow.graph.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix link to logs when you rename your workflow

engine/api/pipeline_import_test.go, engine/api/workflow_import_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test(api): fix unit tests

docs/content/workflows/pipelines/actions/builtin/script.md, engine/api/workflow/execute_node_job_run.go, engine/worker/cmd_key.go, engine/worker/take_workflow_node_run_job.go, tests/fixtures/ITSCWRKFLW5/key-install.pip.yml, tests/sc_workflow_key_install.yml, ui/src/app/shared/keys/list/keys.list.html, ui/src/app/shared/keys/list/keys.list.scss
1. Description
close #3023
1. About tests
IT
1. Mentions
@ovh/cds
=>  feat(worker): Install and use pgp key in a step script

engine/api/workflow/process.go, engine/api/workflow/process_parameters.go, sdk/workflow.go
1. Description
stop duplicating useless variables
1. About tests
1. Mentions
@ovh/cds
=> fix(api): process node run git variables

engine/api/workflow/dao_node_run.go, engine/api/workflow/gorp_model.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: null column

engine/api/workflow_run.go, engine/api/workflow_run_test.go, ui/src/app/service/workflow/run/workflow.run.service.ts, ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts, ui/src/app/views/workflow/workflow.component.ts, ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add infinite scroll on sidebar run list

engine/api/api_routes.go, engine/api/ascode.go, engine/api/migrate/gitclone_key_migration.go, engine/api/migrate/migrate_action.go, engine/api/migrate/migrate_workflow.go, engine/api/migrate/migrate_workflow_test.go, engine/api/user.go, engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/dao_coverage.go, engine/api/workflow/dao_run_test.go, engine/api/workflow/dao_test.go, engine/api/workflow/repository.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow/workflow_exporter.go, engine/api/workflow/workflow_exporter_test.go, engine/api/workflow/workflow_importer.go, engine/api/workflow/workflow_importer_test.go, engine/api/workflow/workflow_parser.go, engine/api/workflow/workflow_parser_test.go, engine/api/workflow_export.go, engine/api/workflow_export_test.go, engine/api/workflow_group.go, engine/api/workflow_hook.go, engine/api/workflow_import.go, engine/api/workflow_import_test.go, engine/api/workflow_queue_test.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go, engine/api/workflow_trigger.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): tracing on load workflow

engine/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: convert to cobertura file

engine/api/application_variable.go, engine/api/environment_variable.go, engine/api/project_variable.go, ui/src/app/shared/variable/list/variable.html
1. Description
Also useful for key migration
close #2940
1. About tests
1. Mentions
@ovh/cds
=> fix(api,ui): block all update of key variables

ui/src/app/shared/workflow/node/run/node.run.param.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): don't replace payload on resync

docs/content/workflows/design/run-conditions.md, sdk/luascript/luascript.go, sdk/luascript/luascript_test.go
1. Description
#2926
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add os.date into lua conditions

engine/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix run cobertura

engine/api/workflow/execute_node_run.go, ui/src/app/app.service.ts, ui/src/app/model/pipeline.model.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
close #3049 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): artifacts and tests not refreshed on node run view #3049

sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: max register is a ratio of max worker

sdk/exportentities/workflow.go, sdk/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): workflow pipelines with mapstructure

ui/src/app/views/workflow/sidebar/run/node/stage/job/action/action.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/job/job.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.html, ui/src/app/views/workflow/sidebar/run/node/stage/stage.summary.component.ts, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display correctly node name in title

engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_conf.go, engine/hatchery/swarm/swarm_test.go, engine/hatchery/swarm/swarm_util_create.go, engine/hatchery/swarm/swarm_util_create_test.go, engine/hatchery/swarm/swarm_util_get.go, engine/hatchery/swarm/swarm_util_get_test.go, engine/hatchery/swarm/swarm_util_kill.go, engine/hatchery/swarm/swarm_util_logs.go, engine/hatchery/swarm/swarm_util_pull.go, engine/hatchery/swarm/types.go, engine/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery/swarm): manage multiple docker engines

engine/api/worker/model.go, engine/sql/115_worker_model_check_registration.sql, sdk/hatchery/register.go, sdk/worker.go, sdk/worker_easyjson.go, ui/src/app/model/worker-model.model.ts, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): add check_registration when a new binary requirement is added

tools/os-ansible-inventory/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(tools): ansible-inventory

engine/worker/cmd_cache.go, engine/worker/cmd_upload.go
1. Description
close #3065 
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): add retry on worker upload cmd

sdk/broadcast.go, sdk/event.go, sdk/event_pipeline.go, sdk/hatchery.go, sdk/platform.go, sdk/repositories_manager.go, sdk/workflow.go
1. Description
I played with https://github.com/mdempsky/maligned :D 
1. About tests
1. Mentions
@ovh/cds
=> refactor(sdk): rearrange order of elements in struct in order to minimize memory footprint

engine/api/workflow/dao.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow.load don't load joins if onlyRoot is true

engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_conf.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery/swarm): swarm startup

engine/api/workflow/execute_node_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not interpolate workflow pipelines requirements

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add tracing span

ui/src/app/model/parameter.model.ts, ui/src/app/model/workflow.model.ts, ui/src/app/shared/parameter/list/parameter.component.ts, ui/src/app/shared/parameter/list/parameter.html, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.html, ui/src/app/views/run/workflow/variables/job.variables.component.ts, ui/src/app/views/workflow/run/node/pipeline/variables/job.variables.component.ts
1. Description
close #3083 
close #3084 
1. About tests
1. Mentions
cc @blaryjp 
@ovh/cds
=> fix(ui): don't try to load commit if no repo is linked and fix list parameters

engine/api/api_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test(api): attempt to fix test timeout

engine/hatchery/swarm/swarm.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery/swarm): http transport without tls configuration

engine/worker/cmd_cache.go, sdk/cache.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): fix worker cache for weird files

engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: docker swarm client version

engine/api/application.go, engine/api/ascode.go, engine/api/workflow/repository.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: hide some field on vcs strategy

ui/src/app/model/workflow.model.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fetch commits when it's useful

engine/api/application/application_pipeline.go, engine/api/application/application_pipeline_hook.go, engine/api/hook.go, engine/api/migrate/migrate_workflow.go, engine/api/pipeline.go, engine/api/pipeline/pipeline.go, engine/api/pipeline/pipeline_build.go, engine/api/pipeline/pipeline_parameter.go, engine/api/pipeline/pipeline_stage.go, engine/api/pipeline_group.go, engine/api/pipeline_job.go, engine/api/pipeline_parameter.go, engine/api/poller/executer.go, engine/api/poller/gorp_model.go, engine/api/queue/queue.go, engine/api/queue/run.go, engine/api/scheduler/executer.go, engine/api/stage.go, engine/api/suggest.go, engine/api/workflow/dao.go, engine/api/workflow/dao_node.go, engine/api/workflow_queue_test.go, engine/api/workflowv0/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add tracing on load pipeline

engine/api/workflow/process_requirements.go, engine/hatchery/kubernetes/kill_workers.go, engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/kubernetes/services.go, engine/hatchery/kubernetes/types.go, engine/hatchery/swarm/swarm_util_logs.go, sdk/requirement.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): add service logs for hatchery kubernetes

engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/kubernetes/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): add other kind of authentication for kubernetes

engine/api/workflow/workflow_importer.go
1. Description
close #3097 
1. About tests
1. Mentions
@ovh/cds
=> fix(api): edit as code don't erase the workflow icon

contrib/plugins/plugin-clair/clair.go, contrib/plugins/plugin-npm-audit-parser/npm-audit-parser.go, contrib/plugins/plugin-npm-audit-parser/types.go, engine/api/api_routes.go, engine/api/application/application_vunerability.go, engine/api/application/gorp_model.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_run.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go, engine/sql/116_application_vulnerability.sql, engine/worker/cmd_server.go, engine/worker/vulnerability.go, sdk/application_vulnerability.go, sdk/plugin/common.go, sdk/workflow_run.go, ui/src/app/model/application.model.ts, ui/src/app/shared/shared.module.ts, ui/src/app/shared/vulnerability/vulnerabilities.component.ts, ui/src/app/shared/vulnerability/vulnerabilities.html, ui/src/app/shared/vulnerability/vulnerabilities.scss, ui/src/app/views/workflow/run/node/node.html, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add npm audit parser + summary vulnerability view

ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
1. Description
close #3078 
1. About tests
1. Mentions
cc @frenautvh 
@ovh/cds
=> fix(ui): pipeline left menu is now clickable after element is selected

engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add tracing on postWorkflowJobResultHandler

engine/hatchery/swarm/swarm.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery/swarm): choose the docker engine algorithm

engine/api/pipeline/pipeline.go, engine/api/pipeline/pipeline_importer.go, engine/api/workflow/dao.go, ui/src/app/service/pipeline/pipeline.service.ts, ui/src/app/service/pipeline/pipeline.store.ts, ui/src/app/service/workflow/workflow.service.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix import as code

engine/api/workflow_queue_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test(api): fix unit test

engine/api/repositoriesmanager/repositories_manager.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): getVCSInfos with memoization

engine/api/workflow/dao_run.go, engine/api/workflow/dao_run_test.go
1. Description
close #3106 
1. About tests
1. Mentions
cc @geoffreybauduin 
@ovh/cds
=> fix(api): don't purge workflow run always running #3106

engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_util_pull.go, engine/hatchery/swarm/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery/swarm): remove pull mutex

engine/hatchery/serve.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): start the http server

engine/api/workflow/execute_node_job_run.go, engine/hatchery/swarm/swarm_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add tracing on workflow.UpdateNodeJobRunStatus

ui/src/app/model/workflow.model.ts, ui/src/app/shared/parameter/list/parameter.component.ts
1. Description
close #3116 
1. About tests
1. Mentions
cc @blaryjp 
@ovh/cds
=> fix(ui): fix parameters list for mode job #3116

ui/src/app/shared/shared.module.ts, ui/src/app/shared/vulnerability/list/vulnerabilities.list.html, ui/src/app/shared/vulnerability/list/vulnerabilities.list.scss, ui/src/app/shared/vulnerability/list/vulnerability.list.component.ts, ui/src/app/shared/vulnerability/vulnerabilities.component.ts, ui/src/app/shared/vulnerability/vulnerabilities.html, ui/src/app/shared/vulnerability/vulnerabilities.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat (ui): add vulnerabilities list

ui/src/app/shared/workflow/node/conditions/condition-form/condition.component.ts, ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix conditions list

engine/api/purge/purge.go, ui/src/app/shared/workflow/node/workflow.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): stop all workflows which are running more than 24hours

engine/api/workflow/dao_node.go, engine/api/workflow/dao_test.go, sdk/error.go
close #3123
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not let add run conditions with unknown operator

ui/src/app/service/router/router.service.ts, ui/src/app/shared/action/action.component.ts, ui/src/app/shared/action/action.html, ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/views/pipeline/show/admin/pipeline.admin.html, ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.component.ts, ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/app/views/workflow/show/workflow.component.ts, ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts, ui/src/app/views/workflow/sidebar/code/sidebar.code.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.ts, ui/src/app/views/workflow/workflow.component.ts
1. Description
BTW I added the cmd+s/ctrl+s to save a pipeline/workflow when you edit
1. About tests
1. Mentions
@ovh/cds
=>  fix(ui): fix events on sidebar

ui/src/app/shared/workflow/node/conditions/condition-form/condition.component.ts, ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html, ui/src/app/shared/workflow/node/conditions/condition-list/condition.list.component.ts, ui/src/app/shared/workflow/node/conditions/node.conditions.component.ts, ui/src/app/shared/workflow/node/conditions/node.conditions.html
close #3122
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): advanced conditon display bug sometimes

engine/worker/builtin_artifact_upload.go, engine/worker/cmd_upload.go, sdk/artifact.go
=> feat (worker): add retry on upload swift if error

Gopkg.lock, vendor/github.com/fsamin/go-repo/repo.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore(vendor): update go-repo to fix repositories.processCheckout

ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts, ui/src/app/shared/workflow/node/wizard/node.wizard.html
close #3132
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): do not list platform not attached to an application

engine/api/workflow/dao_node_run.go, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not return 404 if no coverage report

engine/api/purge/purge.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not compute stop from start but from last_execution

engine/api/build.go, engine/api/worker/worker.go, engine/api/workflow_queue.go, engine/worker/run.go, engine/worker/take_pipeline_build_job.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/worker.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): remove dependency with api/worker package

engine/api/workflow/run_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fill data in last_execution

ui/package.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add prismjs dependency

engine/api/application/application_parser.go, engine/api/project/dao.go, sdk/platform.go
closes #3129
1. Description
no need to add a regen: false
1. About tests
1. Mentions
@ovh/cds
=> fix(api): import application with deployment strategies secrets

engine/api/api.go, engine/api/purge/purge.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/init.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix stop workflow run for purge

engine/api/api_routes.go, engine/api/cache.go, engine/hatchery/kubernetes/kubernetes.go, engine/worker/cmd_cache.go, sdk/cache.go, sdk/cdsclient/client_workflow.go, tests/fixtures/ITSCWRKFLW4/tag-push-pull.pip.yml, ui/resources/cds-hint.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): add with temp url for worker cache and fix issues

sdk/cdsclient/client_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): delete jobsTicker log

ui/src/app/shared/workflow/node/run/node.run.param.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): check if piptorun exist

ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/run/workflow.run.component.ts
close #3138
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): Display workflow run tags in web pages title

docs/content/hosting/ready-to-run/from-binaries.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc(hosting): add info to add user without mail service

engine/hatchery/serve.go, engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_conf.go, sdk/hatchery/hatchery.go, sdk/status.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): /mon/status

engine/api/workflow/gorp_model.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): remove verbose log

engine/api/tracing/tracing.go, sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api, hatchery): remove tracing logs

sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): timeout of 10 minutes to start a worker

tests/fixtures/ITSCWRKFLW5/key-install.pip.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> test(worker): add requirement gpg for worker key install

sdk/vcs/git/git_clone.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): add no-single-branch for git clone with depth

sdk/hatchery/hatchery.go, sdk/hatchery/starter.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): context cancellation

engine/api/observability/init.go, engine/api/observability/stats.go, engine/hatchery/serve.go, engine/hatchery/stats.go, sdk/hatchery/hatchery.go, sdk/hatchery/pool.go, sdk/hatchery/starter.go, sdk/hatchery/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): metrics

engine/api/event/event.go, engine/api/test/test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(test): remove  circular dependency

engine/hatchery/serve.go, sdk/common.go, sdk/hatchery/starter.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): remove stacktraces older than 15 minutes

engine/hatchery/serve.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): try to create the panic dumps directory

engine/api/application.go, engine/api/application/dao.go, engine/api/application/dao_dependencies.go, engine/api/project.go, ui/src/app/service/application/application.service.ts
1. Description
Do not break the API with icons
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add withIcons on routes to not fetch icon if not needed

ui/src/app/views/workflow/sidebar/run/node/workflow.sidebar.run.node.component.html
close #3197
1. Description
1. About tests
1. Mentions
cc @ilesinge
@ovh/cds
=> fix(ui): artifact link from sidebar

engine/hatchery/swarm/swarm.go, engine/worker/cmd_run.go, engine/worker/requirement.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): exit after checking or running a job if ttl is null

engine/api/api.go, engine/api/api_routes.go, engine/api/observability/stats.go, engine/api/router.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): low level metrics

ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts, ui/src/app/shared/workflow/node/workflow.node.component.ts, ui/src/app/views/workflow/workflow.component.ts
close #3190
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): sidebar on node not refreshed in specific cases

ui/src/app/views/project/show/admin/project.admin.component.ts, ui/src/app/views/project/show/admin/project.admin.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
It wasn't well computed
Migration on application advanced section is always here.
=> feat(ui): remove Workflow migration progress

Gopkg.lock, engine/repositories/processor_checkout.go, vendor/github.com/fsamin/go-repo/repo.go, vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go, vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go, vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go, vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go, vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go, vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go, vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go, vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go, vendor/github.com/spf13/cobra/cobra/cmd/licenses.go, vendor/github.com/vmware/govmomi/simulator/license_manager.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(repositories): reset if repo has diverged

engine/api/worker.go, engine/api/worker/heartbeat.go, engine/api/worker/worker.go, engine/worker/cmd_run.go, engine/worker/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api, worker): limit hatcheries inconsistencies

engine/api/worker/heartbeat.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): revert WorkerHeartbeatTimeout to 300s

engine/api/artifact.go, engine/api/hatchery/hatchery.go, engine/api/hook/hook.go, engine/api/worker/worker.go, engine/vcs/github/oauth_consumer.go, engine/vcs/gitlab/oauth_consumer.go, engine/worker/cmd_run.go, sdk/cdsclient/client_worker.go, sdk/cdsclient/interface.go, sdk/worker.go, sdk/worker_easyjson.go
and add lastbeat in cdsctl worker list
=> fix(worker): heartbeat

engine/api/workflow/dao_run.go, engine/api/workflow/process.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix stop workflow run for purge, do not stop all nodes

engine/api/api_routes.go, engine/api/application.go, engine/api/repositoriesmanager/repositories_manager.go, engine/vcs/bitbucket/client_tags.go, engine/vcs/bitbucket/types.go, engine/vcs/github/client_tag.go, engine/vcs/github/types.go, engine/vcs/gitlab/client_branch.go, engine/vcs/gitlab/client_tag.go, engine/vcs/vcs_handlers.go, engine/vcs/vcs_router.go, sdk/repositories_manager.go, sdk/vcs.go, ui/resources/cds-hint.js, ui/src/app/model/repositories.model.ts, ui/src/app/service/application/application.workflow.service.ts, ui/src/app/service/workflow/run/workflow.run.service.ts, ui/src/app/shared/workflow/node/context/workflow.node.context.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/views/workflow/sidebar/run/list/workflow.sidebar.run.component.ts
1. Description
close #3218 
1. About tests
1. Mentions
@ovh/cds
=>  feat(ui): add autocomplete for git.repository and git.tag as git.branch

engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/marathon/marathon.go, engine/hatchery/swarm/swarm.go, ui/src/app/shared/breadcrumb/breadcrumb.component.ts, ui/src/app/shared/breadcrumb/breadcrumb.html, ui/src/app/views/project/show/project.html
close #3240
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): give the ability to override default env variables

engine/hatchery/kubernetes/kubernetes.go
close #3241
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): lower case on service requirement name for kubernetes

engine/api/pipeline/pipeline_importer.go, engine/api/pipeline_import.go
close #3232
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): import pipeline without permission via ascode create it with right permissions

engine/vcs/bitbucket/client_tags.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(vcs): replace /refs/tags/ with empty string for tag list

engine/vcs/github/client_tag.go, ui/resources/cds-hint.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display tags in desc order and fix autocomplete payload

engine/vcs/github/client_tag.go
close #3257
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(vcs): if no tags in github don't return error

ui/src/app/shared/workflow/node/workflow.node.html, ui/src/app/shared/workflow/node/workflow.node.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display platforms on node correctly

engine/api/action/children.go, engine/api/pipeline/pipeline_action.go, engine/api/pipeline/pipeline_stage.go, engine/api/workflow/process.go, engine/api/workflow/resync_workflow.go, engine/sql/123_action_custom_name.sql, sdk/action.go, sdk/exportentities/action.go, sdk/exportentities/pipeline.go, sdk/workflow_run_easyjson.go, tests/fixtures/action_disabled.yml, tests/fixtures/action_git_clone.yml, ui/src/app/model/action.model.ts, ui/src/app/shared/action/step/step.component.ts, ui/src/app/shared/action/step/step.html, ui/src/app/shared/action/step/step.scss, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
close #1408
1. Description
and inside a fix on workflow tag to not tag a branch if we specified tag and branch at the same time
1. About tests
1. Mentions
@ovh/cds
=> feat(api,ui): add custom step name

ui/src/app/shared/vulnerability/vulnerabilities.scss, ui/src/app/views/workflow/run/node/node.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): vulnerability css

contrib/plugins/plugin-clair/clair.go, contrib/plugins/plugin-npm-audit-parser/npm-audit-parser.go, engine/api/application/application_vunerability.go, engine/api/application_vulnerability_test.go, engine/api/workflow/dao_node_run_vulnerability.go, engine/sql/124_application_vulnerability_type.sql, sdk/application_vulnerability.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add type on vulnerabilities

engine/hatchery/swarm/swarm.go, sdk/hatchery/hatchery.go
=> fix(hatchery/swarm): don't rm service to young

docs/content/workflows/pipelines/actions/plugins/plugin-clair.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs: add plugin clair

ui/package.json, ui/src/app/shared/vulnerability/list/vulnerabilities.list.html, ui/src/app/shared/vulnerability/list/vulnerabilities.list.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): rxjs dep + add vulnerability type

ui/src/app/shared/vulnerability/list/vulnerabilities.list.html, ui/src/app/shared/vulnerability/list/vulnerabilities.list.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add origin and fix in version

engine/api/workflow/dao_run.go, ui/src/app/shared/action/step/form/step.form.component.ts, ui/src/app/shared/action/step/step.component.ts, ui/src/app/shared/action/step/step.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
close #3266
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix stop workflow purge

ui/src/app/views/project/show/workflow/labels/workflow.list.labels.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display a fake labels for all unlabeled workflows

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix getCommits when remote is different than the default one

engine/api/workflow/dao.go, engine/api/workflow_import_test.go
close #3189
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): in ascode with workflow import default_tags are correctly imported

ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
=> fix(ui): avoid js err if testsuite contains no testcase

engine/hatchery/local/local.go, engine/hatchery/serve.go, engine/main.go, engine/service/heartbeat.go, engine/service/service.go, sdk/cdsclient/client_hatchery.go, sdk/cdsclient/interface.go, sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(engine): Clean code and fix heartbeat, reset count only if no error

ui/src/app/shared/workflow/node/outgoinghook/outgoinghook.component.ts, ui/src/app/views/workflow/graph/workflow.graph.component.ts, ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix outgoing box

engine/api/api_routes.go, engine/api/mon_db.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go
=> feat(api): add trace on workflow queue

ui/src/app/model/workflow.model.ts, ui/src/app/shared/workflow/node/conditions/condition-form/condition.form.html
close #3311
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): let user put empty value in run condition

ui/src/app/views/navbar/navbar.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(ui): remove old entry admin about migration

cli/cdsctl/worker_model.go, engine/api/requirements.go, engine/api/worker/model.go, engine/api/worker/model_test.go, engine/api/worker_model.go, sdk/cdsclient/client_worker_model.go, sdk/cdsclient/interface.go, ui/src/app/service/worker-model/worker-model.service.ts, ui/src/app/shared/requirements/form/requirements.form.component.ts, ui/src/app/shared/requirements/list/requirements.list.component.ts, ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts, ui/src/app/views/settings/worker-model/list/worker-model.list.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api,ui): add state filter on worker model

engine/api/grpc_plugin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): update if action exist

sdk/cdsclient/client_queue.go, sdk/cdsclient/client_queue_test.go, sdk/hatchery/hatchery.go, sdk/workflow_run_test.go
and fix the time return for new jobs
=> fix(sdk,hatcherty): limit queue read to maxcontainers

contrib/uservices/cds2xmpp/service/bot.go
=> feat(contrib/cds2xmpp): allow using custom domain name

contrib/grpcplugins/deployment/arsenal/Makefile, ui/src/app/shared/workflow/node/wizard/node.wizard.component.ts
close #3325
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): wizard attach pipeline doesn't list platforms

ui/src/assets/worker/eventsource.js
1. Description
close #3327
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix sse on error at creation

contrib/grpcplugins/action/clair/.gitignore, contrib/grpcplugins/action/clair/clairctl/clair/analyze.go, contrib/grpcplugins/action/clair/clairctl/clair/clair.go, contrib/grpcplugins/action/clair/clairctl/clair/layering.go, contrib/grpcplugins/action/clair/clairctl/clair/push.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): fix gitignore for clair

contrib/grpcplugins/action/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(grpcplugins): fix Makefile for other os than mac

engine/worker/builtin.go, engine/worker/run_plugin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(grpcplugins): job build variables and environment variables are now available from plugin

contrib/grpcplugins/action/venom/main.go, engine/worker/run_plugin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(grpcplugins): force home directory

engine/worker/run_plugin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(grpcplugins): inherit environment variables

contrib/grpcplugins/action/kafka-publish/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(kafka-publish): don't fail silently

sdk/cdsclient/client_services.go
if service is not up to date -> display warning
=> fix(sdk): hatchery -> service

contrib/grpcplugins/action/clair/clairctl/clair/layering.go, contrib/grpcplugins/action/clair/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): fix clairctl contrib

engine/api/workflow/dao_node_run_job.go
=> fix(engine): check rights user hatcheries

engine/api/workflow/dao_node_run_job.go
=> fix(engine): fix rights user hatcheries

engine/worker/cmd_register.go, engine/worker/cmd_run.go, engine/worker/init.go, engine/worker/main.go
=> fix(worker): flag hatchery not needed

engine/api/cache.go, engine/worker/cmd_cache.go, engine/worker/cmd_server.go, sdk/cdsclient/client_workflow.go, sdk/error.go
1. Description
close #3335
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): worker cache display better errors

cli/cdsctl/monitoring.go, cli/scrollablelist.go, sdk/build.go
…ivity
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refact ctl monitoring

engine/sql/131_worker_model_hatchery.sql
=> fix(sql): remove export HATCHERY from existing wm

engine/api/services/dao.go, engine/hatchery/openstack/spawn.go, ui/src/app/views/admin/worker-model-pattern/add/worker-model-pattern.add.html, ui/src/app/views/admin/worker-model-pattern/edit/worker-model-pattern.edit.html, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
before: cmd have to contains a space at the end
with this fix: same behaviour as other hatcheries
=> fix(hatchery/openstack): register worker

engine/worker/run_plugin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): fix log on plugin

contrib/grpcplugins/action/clair/clairctl/config/config.go, contrib/grpcplugins/action/clair/clairctl/docker/dockerdist/dockerdist.go
=> fix(plugin/clair): remove some unuseful log for users

ui/src/app/shared/table/data-table.component.ts, ui/src/app/shared/table/data-table.html, ui/src/app/shared/table/table.ts
1. Description
Problem when too many pages
1. About tests
1. Mentions
@ovh/cds
=> fix-hook-tasks-page-pagination

sdk/hatchery/hatchery.go, sdk/hatchery/starter.go
=> fix(hatchery): fix routine deadlock

engine/worker/cmd_run.go, engine/worker/requirement.go, sdk/build.go
=> refactor(worker): no need to set checking on wf

sdk/exportentities/workflow.go
=> fix(sdk): import big workflows as code

Gopkg.lock, Gopkg.toml, contrib/grpcplugins/action/venom/main.go, vendor/github.com/bsm/sarama-cluster/LICENSE, vendor/github.com/bsm/sarama-cluster/balancer.go, vendor/github.com/bsm/sarama-cluster/client.go, vendor/github.com/bsm/sarama-cluster/cluster.go, vendor/github.com/bsm/sarama-cluster/config.go, vendor/github.com/bsm/sarama-cluster/consumer.go, vendor/github.com/bsm/sarama-cluster/doc.go, vendor/github.com/bsm/sarama-cluster/offsets.go, vendor/github.com/bsm/sarama-cluster/partitions.go, vendor/github.com/bsm/sarama-cluster/util.go, vendor/github.com/ovh/venom/executors/kafka/executor.go
=> feat(plugin/venom): add kafka executor from venom 0.22.0

engine/api/workflow.go
=> fix(api): transaction on delete worflow

engine/api/api.go, engine/api/observability/stats.go, engine/api/workflow_queue.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): expose started and failed workflow runs metrics

engine/api/services.go, engine/api/services/dao.go
=> fix(api): update heartbeat

engine/api/workflow/repository.go, engine/api/workflow_run.go
=> fix(api): check err on as code

engine/hooks/kafka.go, ui/src/app/shared/table/data-table.component.ts, ui/src/app/views/admin/hooks-tasks/details/hooks-task.component.ts, ui/src/app/views/admin/hooks-tasks/details/hooks-task.html, ui/src/app/views/admin/hooks-tasks/hooks-tasks.component.ts, ui/src/app/views/admin/hooks-tasks/hooks-tasks.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> Fix hook tasks page

ui/src/app/shared/table/data-table.component.ts, ui/src/app/views/admin/hooks-tasks/details/hooks-task.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): Remove useless ng-template, problem white page

engine/api/status.go
=> fix(api): global status version without diff

engine/api/services/external.go
=> fix(api): healthCheck port external service

engine/api/admin.go, engine/api/services/dao.go
=> fix(api): hash/token remove on handler only

engine/api/admin.go, engine/api/metrics.go, engine/api/services.go, ui/src/app/model/monitoring.model.ts, ui/src/app/service/monitoring/monitoring.service.ts, ui/src/app/views/admin/services/service/service.html, ui/src/app/views/admin/services/services.component.ts, ui/src/app/views/admin/services/services.html, ui/src/app/views/navbar/navbar.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): improve admin/services

contrib/grpcplugins/action/clair/main.go, contrib/grpcplugins/action/npm-audit-parser/main.go, contrib/grpcplugins/grpcplugins.go, sdk/plugin/common.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib/clair): move commons function from old plugin package

engine/api/api.go
=> fix(api): no need id feature flipping

engine/api/project.go
closes #3379
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not raise error 500 on getProjectsHandler from a provider

engine/hatchery/kubernetes/types.go, engine/hatchery/local/types.go, engine/hatchery/marathon/types.go, engine/hatchery/openstack/types.go, engine/hatchery/swarm/types.go, engine/hatchery/vsphere/types.go, sdk/hatchery/types.go
=> feat(hatchery): conf as json for /admin/services ui

engine/api/router.go
=> feat(api): observability end on err

sdk/cdsclient/client.go
=> fix(sdk): add dial timeout

docs/content/hosting/ready-to-run/docker-compose.md
=> doc: remove old cli from ready to run

cli/cdsctl/login.go
this fix an issue as:
``` bash
$ cdsctl health status
Error: (5, 1): unexpected token
```
after a fresh login with overwrite existing file.
=> fix(cdsctl): if config file exists, delete it before create

cli/cdsctl/monitoring.go
this avoid overwrite line issue on iterm2
Success and Failed status are not used
=> feat(cdsctl): remove icon from legend

contrib/grpcplugins/action/marathon/main.go, engine/hatchery/marathon/marathon.go, engine/vcs/bitbucket/http.go, engine/vcs/github/http.go, engine/worker/cmd_update.go, engine/worker/init.go, sdk/cdsclient/client.go
=> refactor: remove deprecated httpcontrol

engine/worker/cmd_run.go, engine/worker/run.go
=> fix(worker): adjust timeout on send step result

ui/src/app/model/project.model.ts, ui/src/app/service/helpers/helpers.service.ts, ui/src/app/service/services.module.ts, ui/src/app/views/project/show/project.component.ts, ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.component.ts, ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.html, ui/src/app/views/project/show/workflow/labels/workflow.list.labels.component.ts, ui/src/app/views/project/show/workflow/labels/workflow.list.labels.html, ui/src/app/views/project/show/workflow/lines/workflow.list.lines.component.ts, ui/src/app/views/project/show/workflow/lines/workflow.list.lines.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): adjust font color for brightness (close #3330)

ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
1. Description
close #3414 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): search binary in a worker model

engine/api/workflow/process.go, sdk/parameter.go
1. Description
close #3380
1. About tests
1. Mentions
@ovh/cds
=> fix(api): merge pipeline parameter and default value in workflow context

engine/api/action/action.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): update pipeline via edit as code take care of enabled (close #3366)

ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts, ui/src/app/views/settings/worker-model/list/worker-model.list.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display right icon for disabled worker models

sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): queue polling frequency

sdk/cdsclient/client.go
=> fix(sdk): default transport timeout

engine/api/workflow/process.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix pip parameters for manual run

sdk/cdsclient/client.go
=> fix(sdk): disable keepAlive

sdk/cdsclient/client.go, sdk/cdsclient/http.go, sdk/cdsclient/http_sse.go
=> feat(sdk): new httpSSEClient

contrib/grpcplugins/action/group-tmpl/main.go, contrib/grpcplugins/action/group-tmpl/plugin_test.go, contrib/grpcplugins/action/group-tmpl/templates.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(plugin): fix group-tmpl-plugin

sdk/cdsclient/http.go, sdk/cdsclient/http_sse.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(sdk): add pprof label on http client

engine/hatchery/stats.go, sdk/cdsclient/client_queue.go, sdk/hatchery/hatchery.go, sdk/hatchery/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): add SSE metrics

contrib/grpcplugins/action/examples/nodejs/package-lock.json, contrib/grpcplugins/action/examples/nodejs/package.json, ui/src/app/service/notification/notification.service.ts, ui/src/app/views/workflow/run/workflow.run.component.ts
and delete vulnerable dependency in contrib
close #3417 
1. Description
PLEASE DO NOT SQUASH COMMITS
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): do not display duplicate notifications on linux

engine/api/router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): http pprof labels

cli/cdsctl/monitoring.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix-cdsctl-ui-perf

engine/api/api_routes.go
=> fix(api): /user/me

sdk/cdsclient/http_sse.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): http sse ctx error

sdk/cdsclient/http_sse.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): http sse EOF

sdk/cdsclient/client_queue.go, sdk/cdsclient/http_sse.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): http sse client

contrib/grpcplugins/action/marathon/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib/plugin/marathon): log format

engine/api/api_routes.go, engine/api/events.go, engine/api/status.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): sse mutexes

ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add collapse on step logs to lazy display on ui (close #3298)

engine/api/events.go, engine/api/router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): sse metrics

engine/worker/builtin.go, engine/worker/builtin_deploy_application.go, engine/worker/run_plugin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): check to send all logs before terminate plugin (close #3448)

ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): change style of expand logs button

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): write on sse

ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix modal launch node with pipeline parameters when opened several times

docs/content/gettingstarted/step_by_step_build_deploy.md
Just fixed little tipo ;)
By the way, good job with CDS !
@ovh/cds
=> Tipo fix to step_by_step_build_deploy.md

contrib/helm/cds/Chart.yaml, contrib/helm/cds/OWNERS, contrib/helm/cds/OWNERS.todo, contrib/helm/cds/README.md, contrib/helm/cds/templates/NOTES.txt, contrib/helm/cds/templates/ingress.yaml, contrib/helm/cds/templates/ui-deployement.yaml, contrib/helm/cds/templates/ui-svc.yaml, contrib/helm/cds/values.yaml, docs/content/hosting/ready-to-run/from-binaries.md, docs/content/hosting/ready-to-run/helm.md
1. Description
1. About tests
1. Mentions
cc @jseguillon 
@ovh/cds
=> chore(contrib): fix some issues and add some docs form helm

sdk/hatchery/hatchery.go, sdk/hatchery/starter.go, sdk/messages.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): display warning in spawn info for deprecated model (close #3422)

contrib/grpcplugins/action/kafka-publish/README.md, contrib/grpcplugins/action/kafka-publish/cli_actions.go, contrib/grpcplugins/action/kafka-publish/kafka_consumer.go, contrib/grpcplugins/action/kafka-publish/main.go
=> fix(plugin/kafka-publish): windows compatibility

engine/hooks/outgoing_hooks.go
=> fix(hooks): similar outgoing hooks execution

engine/api/workflow/dao_hook.go, engine/api/workflow/dao_node.go, sdk/error.go, ui/src/app/shared/workflow/node/hook/form/hook.form.component.ts, ui/src/app/shared/workflow/node/hook/form/hook.form.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> fix(api, ui): outgoing hooks edition

contrib/uservices/cds2xmpp/service/bot.go, contrib/uservices/cds2xmpp/service/xmpp.go
=> feat(contrib/cds2xmpp): add ability to auto-recover from XMPP errors

contrib/grpcplugins/action/archive/.gitignore, contrib/grpcplugins/action/archive/archive.yml, contrib/grpcplugins/action/archive/main.go, contrib/grpcplugins/action/archive/plugin_test.go, docs/content/workflows/pipelines/actions/plugins/plugin-archive.md
This is a plugin to compress or uncompress an archive
Dependency: `github.com/mholt/archiver`
@ovh/cds
=> plugin-archive contribution

contrib/actions/cds-sonar-scanner.yml, docs/content/workflows/pipelines/actions/user/cds-sonar-scanner.md
This is a SonarScanner action to run code analysis.
Linked to  #3388
It relies on PR #3469
@ovh/cds
=> CDS_SonarScanner contribution

engine/api/workflow/dao.go, engine/api/workflow/dao_outgoing_hook_model.go, engine/api/workflow_run.go
=> fix(api): avoid two worflows files on push

engine/api/workflow_queue_artifact.go
=> fix(api): retry in postWorkflowJobArtifacWithTempURLHandler

ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.ts
=> fix(ui): add two outgoing hook

engine/worker/cmd_key.go
=> feat(worker): worker key install --env

engine/hatchery/kubernetes/kubernetes.go
1. Description
close #3487
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): for kubernetes replace special characters in pod name

docs/content/workflows/pipelines/variables.md
=> doc: interpolate

cli/cdsctl/main.go
=> fix(cdsctl): no need config for doc command

cli/cdsctl/main.go
=> fix(cdsctl): no need config for doc PATH too

engine/hooks/tasks.go, engine/hooks/webhook.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hook): fix repowebhook

ui/src/app/views/workflow/sidebar/run/hook/workflow.sidebar.run.hook.component.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display parent workflow run

contrib/actions/cds-sonar-scanner.yml
Fix a bug added by the PR #3474
I made a mistake when I polished in my previous PR.
Linked to issue  #3388
@ovh/cds
=> Fix bug in CDS_SonarScanner contribution

contrib/grpcplugins/action/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore(contrib): add better version naming

Makefile, cli/cdsctl/Makefile, contrib/grpcplugins/action/Makefile, contrib/grpcplugins/deployment/arsenal/Makefile, engine/Makefile, engine/worker/Makefile, tools/debpacker/Makefile, tools/os-ansible-inventory/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore(Makefile): disable 1.11 for now

engine/api/permission/permission.go, engine/api/router_permission.go, engine/api/workflow.go, engine/api/workflow/dao_group.go, ui/src/app/views/project/show/application/application.list.html, ui/src/app/views/project/show/keys/project.keys.html, ui/src/app/views/project/show/pipeline/pipeline.list.html, ui/src/app/views/project/show/platforms/project.platforms.html, ui/src/app/views/project/show/workflow/workflow.list.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.html, ui/src/app/views/workflow/sidebar/edit/node/workflow.sidebar.edit.node.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): better display for RO users (close #3475)

engine/api/events.go
1. Description
to handle:
```
api       | 2018-10-29 10:30:15 | err  | [PANIC_RECOVERY] Panic occurred on GET:/events?lastEventId=&r=5076636469124916, recover index > windowEnd
api       | 2018-10-29 10:30:15 | err  | [PANIC_RECOVERY] Stacktrace of 4096 bytes
```
1. About tests
1. Mentions
@ovh/cds
=> fix(api): better panic recovery in SSE

cli/cdsctl/workflow.go, cli/cdsctl/workflow_log.go, engine/worker/builtin_junit.go, engine/worker/cmd_check_secret.go, engine/worker/cmd_server.go, engine/worker/logger.go, engine/worker/main.go, sdk/variable.go, tests/fixtures/ITSCWCS/ITSCWCS.yml, tests/fixtures/ITSCWCS/check-secret.pip.yml, tests/sc_workflow_check_secret.yml, tests/sc_workflow_key_install.yml, tests/sc_workflow_run_cache.yml
=> feat(worker): worker check-secret command

engine/worker/builtin.go
=> feat(worker): add log on err plugin

sdk/exportentities/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): don't export empty metadata in workflow as code

engine/api/workflow/hook.go
1. Description
close #3524
1. About tests
1. Mentions
@ovh/cds
=> fix: wait loading application before testing nul

engine/api/workflow/process.go, ui/package.json
=> fix(api): take first value when no default value in pipeline parameter list (close #3520)

docs/content/contribute/error_management.md, engine/api/pipeline/pipeline_action.go, engine/api/pipeline/pipeline_importer.go, engine/api/pipeline_import.go, sdk/error.go, sdk/error_test.go, sdk/messages.go
1. Description
It was only about error message management
closes #3209
1. About tests
1. Mentions
@ovh/cds
=> fix(api): import pipeline error details

engine/worker/builtin.go, engine/worker/builtin_deploy_application.go, engine/worker/run_plugin.go, sdk/grpcplugin/grpcplugin.go
=> fix(worker): check if buffered before read

engine/api/events.go, engine/api/router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): recover events

engine/api/workflow/process.go, sdk/parameter.go, sdk/parameter_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): merge multiple payload (close #3550)

ui/angular.json, ui/package.json, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/tsconfig.lint.json
1. Description
close #3553 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display all logs after a click when job is running

contrib/uservices/cds2xmpp/service/bot.go
=> fix(contrib/cds2xmpp): add reconnect

contrib/uservices/cds2xmpp/service/bot.go
=> fix(contrib/cds2xmpp): add admin confs

engine/api/cache/cache.go, engine/api/cache/redis.go, engine/api/worker.go, engine/api/worker/model.go, engine/api/worker/worker.go, engine/api/workflow_queue_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): delete binary capabilities from worker model when it doesn't exist (close #3557)

contrib/grpcplugins/action/download/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): fix manifest of plugin-download

engine/api/worker/gorp_model.go, engine/api/worker/model.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add logs on getWorkerModelsEnabledHandler

engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/process_parameters.go, engine/api/workflow_hook.go, engine/hooks/poller.go, engine/worker/builtin.go, sdk/parameter.go, sdk/parameter_test.go, tests/fixtures/ITSCWRKFLW2/workflow.yml, tests/sc_workflow_payload_merge_run.yml, tests/sc_workflow_run_simple.yml, tests/sc_workflow_stop_simple.yml, tests/sc_workflow_update_run.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): override git value when it's coming from hook or manual run

engine/api/worker/gorp_model.go, sdk/worker.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): Load WorkerModel

sdk/exportentities/application.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): omit application description if empty

engine/api/events.go, engine/api/router.go
=> fix(api): do not log err managed

engine/api/workflow/dao_notification.go, engine/api/workflow_run.go, sdk/workflow_node.go, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.html, ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts, ui/src/app/views/workflow/show/notification/form/workflow.notifications.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api, ui): new model

engine/api/workflow/dao.go, engine/api/workflow/dao_join.go, engine/api/workflow/dao_notification.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): insert notification with new model

engine/api/workflow/dao.go, engine/api/workflow_run.go, sdk/exportentities/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): migrate old workflow run + fix resync hooks

engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: check application, get it from project

engine/api/workflow/process.go, engine/api/workflow/process_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix the merge of payload when there is a middle default payload

engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_node_run_job.go, engine/worker/builtin_junit.go, sdk/cdsclient/client_queue.go, sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): catch locked element and add retry in sdk if it's locked (close #3581)

ui/angular.json, ui/package.json, ui/src/app/shared/pipes/safeHtml.pipe.spec.ts, ui/src/app/shared/pipes/safeHtml.pipe.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): ansi and html in logs is now displayed (#3166)

engine/api/workflow.go, engine/api/workflow/execute_node_run.go, ui/src/app/shared/workflow/node/hook/form/hook.form.component.ts, ui/src/app/shared/workflow/sidebar/run-hook/workflow.sidebar.run.hook.component.html, ui/src/app/shared/workflow/wnode/hook/hook.html, ui/src/app/shared/workflow/wnode/join/node.join.scss, ui/src/app/views/workflow/graph/workflow.graph.component.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/run/workflow.run.component.ts, ui/src/app/views/workflow/workflow.component.ts, ui/src/styles.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): sidebar closing, hook details, join display

ui/src/app/views/workflow/run/node/history/history.component.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui) navigate in history + close sidebar

sdk/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): use name to find node instead of ID

ui/src/app/views/admin/hooks-tasks/hooks-tasks.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): Catch for Webhook with no config

ui/src/app/model/workflow.model.ts, ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix undefined parameters with fork launch

engine/api/workflow/dao.go, ui/src/app/views/workflow/graph/workflow.graph.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api,ui): fix fill map platform + switch run on workflow

sdk/workflow.go, ui/src/app/shared/workflow/wnode/join/node.join.html, ui/src/app/shared/workflow/wnode/join/node.join.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix join crud + link to join

contrib/uservices/cds2xmpp/service/bot.go
=> fix(contrib/cds2xmpp): call do

engine/api/workflow/process_data.go, engine/api/workflow/process_start.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): call right method to run join

ui/src/app/shared/workflow/wnode/join/node.join.html, ui/src/app/shared/workflow/wnode/join/node.join.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): join display on macOS + chromium

engine/worker/builtin_script.go
https://github.com/auchenberg/volkswagen
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): support volkswagen

engine/hooks/tasks.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: do not restart kafka hooks

engine/sql/137_fixconstraint.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: model constraint

ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): remove redirect

engine/api/services/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): services.findAll error sql no rows

engine/api/workflow/audit.go, engine/api/workflow/dao_hook.go, engine/api/workflow_import.go, sdk/exportentities/workflow.go, sdk/exportentities/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): hook as code

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): allow detailled node run from service call

engine/api/feature/flipping.go, engine/api/project/dao_dependencies.go, engine/api/project/features.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix-toggle-feature

ui/src/app/shared/workflow/sidebar/run-node/stage/job/action/action.summary.component.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): Pipeline sidebar display customised step name (close #3633)

engine/api/workflow/process_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): merge payload and pipeline params for new process

cli/cdsctl/admin_services.go, docker-compose.yml, engine/api/admin.go, sdk/cdsclient/client_admin.go, sdk/cdsclient/interface.go, tests/clictl_admin_services.yml
this will be useful to get the service goroutines
=> feat(cdsctl): GET on a service name

engine/api/workflow/dao.go, ui/src/app/shared/workflow/sidebar/edit-node/sidebar.edit.html, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.html, ui/src/app/shared/workflow/wnode/outgoinghook/node.outgoing.html
=> fix(api): compute outgoing name

contrib/actions/cds-sonar-scanner.yml
Add the git hash as sonar.projectVersion so that we can follow progress over each PR
=> feat(sonar): add version to sonar to follow evolution of repository

cli/cdsctl/Makefile, engine/Makefile, engine/worker/Makefile, tools/debpacker/.gitignore, tools/debpacker/Makefile, tools/debpacker/debpacker.go, tools/debpacker/debpacker_test.go, tools/debpacker/main.go, tools/debpacker/tmpl.go, tools/debpacker/writer.go, tools/debpacker/writer_test.go, tools/os-ansible-inventory/Makefile
1. Description
Allow to copy folder recursively with custom out dir
Allow to set the working directory
Allow to use root user
Auto enable created service
Add unit test for packer
=> Add some new features for debpacker

ui/package.json, ui/src/app/app.component.ts, ui/src/app/app.module.ts, ui/src/environments/environment.prod.ts, ui/src/environments/environment.test.ts, ui/src/environments/environment.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add sentry support

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds 
@neyaled
=> fix(api): conflict when running multiple node

ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts, ui/src/assets/worker/sharedWorker.js
1. Description
close #3542
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): as code preview + add try catch on json.parse

engine/api/workflow/process_node.go, engine/api/workflow/process_start.go, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): run manual join + do not run join when parent failed

sdk/exportentities/action.go, sdk/exportentities/pipeline_test.go
=> fix(api): artifactDownload as code

ui/src/app/app.module.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add CDS_USER tag in sentry config

sdk/cache.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): fix serve static files with absolute path

engine/api/application/application_exporter.go, engine/worker/cmd_export.go
=> fix(api): ignore old type key in app export

engine/api/pipeline/pipeline.go, engine/api/pipeline_job.go, engine/api/stage.go, engine/api/workflow/execute_node_run.go, ui/src/app/views/pipeline/show/pipeline.show.component.ts, ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix send nodeRunEvent + update pipeline last_modified date

ui/src/app/app.component.ts, ui/src/app/app.service.ts, ui/src/assets/worker/sharedWorker.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add healthcheck on sharedWorker

ui/src/app/service/auth.interceptor.service.ts, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix language awareness

engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): concurrency on http writer

engine/api/workflow/process.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): init list param

engine/api/feature/flipping.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): cache tracing feature

engine/api/workflow/process_start.go, engine/api/workflow_run.go, engine/api/workflow_trigger.go, sdk/workflow_node.go, sdk/workflow_node_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): manual run ancestors

engine/api/workflow/dao_run.go, engine/api/workflow_queue.go
Need test in preproduction environment before merging
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): get pipeline and node from workflow run instead of db

docs/content/workflows/pipelines/actions/builtin/serve-static-files.md, engine/api/action/builtin.go, engine/api/workflow_queue_staticfiles.go, engine/sql/140_static_files_key.sql, engine/sql/141_static_files_key.sql, engine/worker/builtin_serve_static_files.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/static_files.go, ui/package.json
1. Description
close #3657 
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): add static-key to keep the same public url for serve static files (close #3657)

sdk/messages.go, ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts, ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
=> fix(ui): fix reload spawninfo / service logs

sdk/action.go, ui/src/app/model/workflow.run.model.ts, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts, ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/app/views/workflow/run/workflow.run.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display correct step name (close #3668)

engine/api/workflow/resync_workflow.go, ui/src/app/app.service.ts
1. Description
close #3682
1. About tests
1. Mentions
@ovh/cds
=> fix(api): commits list are now correctly displayed in the node run view (close #3682)

cli/cdsctl/workflow_run.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go
1. Description
close #2469
1. About tests
1. Mentions
@ovh/cds
=> feat(cdsctl): Add a flag to resynchronize workflow from command line #2469

engine/vcs/bitbucket/client_repos.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(vcs): Increase limit for repo get on bitbucket

ui/src/app/service/workflow/workflow.event.store.ts, ui/src/app/shared/workflow/modal/hook-modal/hook.modal.component.ts, ui/src/app/shared/workflow/sidebar/run-hook/workflow.sidebar.run.hook.component.ts, ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts, ui/src/app/shared/workflow/wnode/hook/hook.component.ts, ui/src/app/shared/workflow/wnode/wnode.component.ts, ui/src/app/views/workflow/show/workflow.scss, ui/src/app/views/workflow/workflow.component.ts
1. Description
close #3687 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix hooks ui and sidebar improvements

engine/api/action/builtin.go, engine/api/workflow_run.go, engine/worker/builtin_coverage.go
1. Description
Allow to setup a minimal coverage threshold
#3502 
3. About tests
4. Mentions
@ovh/cds
Signed-off-by: Benjamin SANS <github@ziirish.info>
=> feat(api,worker): add minimum coverage threshold (#3502)

engine/api/action/builtin.go, engine/api/workflow/dao_node.go, engine/sql/142_min_coverage.sql, engine/worker/builtin_coverage.go, ui/src/app/shared/workflow/modal/context/workflow.node.context.component.ts, ui/src/app/shared/workflow/modal/trigger/workflow.trigger.component.ts, ui/src/app/shared/workflow/wnode/wnode.component.ts, ui/src/app/views/workflow/run/workflow.run.component.ts, ui/src/app/views/workflow/show/workflow.component.ts, ui/src/app/views/workflow/workflow.component.ts
1. Description
Please DO NOT squash COMMITs
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix sidebar for node run and add subscriptions and workflow update

ui/src/app/app.service.ts, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix some issues found in sentry

ui/src/app/shared/workflow/wnode/wnode.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix sidebar event

engine/api/workflow/dao_node.go, sdk/exportentities/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): don't return error for empty payload on non root node

ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts
1. Description
close #3690 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): unselect all node when update via edit as code (#3690)

engine/api/workflow/process_node.go, sdk/exportentities/workflow.go, sdk/exportentities/workflow_test.go, sdk/workflow.go, sdk/workflow_data.go, sdk/workflow_node.go, ui/src/app/shared/workflow/sidebar/edit-node/sidebar.edit.html
=> feat(api,ui): enable run condition for join and fork

engine/api/workflow/workflow_importer.go, sdk/workflow_data.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not regenerate temp hook uuid when editing workflow as code

engine/api/workflow/repository.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not erase hook uuid when running workflow as code manually

engine/api/workflow/process_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): get the right node id

ui/package.json, ui/src/app/shared/workflow/wnode/fork/node.fork.html, ui/src/app/shared/workflow/wnode/fork/node.fork.scss, ui/src/app/views/workflow/graph/workflow.graph.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display of fork on mac

cli/cdsctl/workflow_run.go, cli/cdsctl/workflow_run_interactive.go, engine/api/events.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/resync_workflow.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_application.go, engine/api/workflow_queue.go, engine/api/workflow_run.go, sdk/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix send pullrequest report + do not load node from old model

engine/api/metrics/elasticsearch.go, engine/elasticsearch/elasticsearch_handlers.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): sorting metrics

ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> docs(ui): update tooltip about resync workflow button

cli/cdsctl/admin.go, cli/cdsctl/admin_database.go, engine/api/api_routes.go, engine/api/database.go, engine/api/database/dbmigrate/migrate.go, engine/api/scheduler.go, sdk/cdsclient/client_admin.go, sdk/cdsclient/interface.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): unlockdb

ui/src/app/views/workflow/run/node/pipeline/step/step.log.html, ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
1. Description
close #3674
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): put toolbar over the logs

engine/hooks/outgoing_hooks.go
=> fix(hooks): interpolate outgoing hook

docs/content/workflows/template/_index.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs: add loop and autoplay for asciinema casts

ui/package.json
=> chore: upgrade node-sass

ui/src/app/shared/workflow-template/apply-form/workflow-template.apply-form.component.ts, ui/src/app/shared/workflow-template/apply-form/workflow-template.apply-form.html
1. Description
#3750 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add filter func to repo list for template apply form (#3750)

ui/src/app/shared/workflow/node/run/node.run.param.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): don't display raw payload

ui/src/app/views/workflow/run/workflow.run.component.ts, ui/src/app/views/workflow/run/workflow.run.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): use current workflow data for run summary with 'me' permission

engine/api/workflow/execute_outgoing_hook_run.go, engine/api/workflow/process_node.go, engine/api/workflow/process_outgoinghook.go, ui/src/app/shared/workflow/modal/trigger/workflow.trigger.component.ts
1. Description
close #3741
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add conditions handling for outgoing hook

ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.html, ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts, ui/src/app/shared/workflow/wnode/wnode.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add link to go to workflow for an outgoing hook workflow

engine/api/workflow/dao_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): bad concat of ids for run to delete

engine/api/api_routes.go, engine/api/templates.go, engine/api/workflow/dao.go, ui/src/app/service/workflow-template/workflow-template.service.ts, ui/src/app/shared/usage/workflows/usage.workflows.html, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api,ui): add workflow template usage

ui/src/app/app.service.ts, ui/src/app/service/timeline/timeline.store.ts, ui/src/app/views/home/home.component.ts, ui/src/app/views/home/timeline/home.timeline.component.ts
1. Description
Linked to a report from [Gitter](https://gitter.im/ovh-cds/Lobby)
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): don't fetch /timeline/filter if you are not connected

cli/cdsctl/action.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cdsctl): add action import from URL (#3770)

engine/api/api_routes.go, engine/api/bookmark.go, engine/api/bookmark/bookmark.go, sdk/bookmark.go, ui/src/app/model/bookmark.model.ts, ui/src/app/service/user/user.service.ts, ui/src/app/shared/favorite-cards/favorite-cards.component.html, ui/src/app/shared/favorite-cards/favorite-cards.component.ts, ui/src/app/views/favorite/favorite.component.html, ui/src/app/views/favorite/favorite.component.ts
1. Description
close #3760 
1. About tests
1. Mentions
Merry christmas @blaryjp 
@ovh/cds
=> feat(ui): see icons and descriptions on Bookmarks page (#3760)

cli/cdsctl/worker_model.go, engine/api/api_routes.go, engine/api/group/group.go, engine/api/worker/model_export.go, engine/api/worker/model_import.go, engine/api/worker_model.go, engine/api/worker_model_export.go, engine/api/worker_model_import.go, sdk/cdsclient/client_export.go, sdk/cdsclient/client_import.go, sdk/cdsclient/interface.go, sdk/exportentities/common.go, sdk/exportentities/worker_model.go, sdk/exportentities/worker_model_test.go, tests/clictl_worker_model.yml, tests/fixtures/my_worker_model_updated.yml
1. Description
close #3767 
1. About tests
1. Mentions
@ovh/cds
=> feat(api,cdsctl,sdk): add export worker model

cli/cdsctl/group_user.go, sdk/user.go
1. Description
close #3773 
1. About tests
1. Mentions
cc @blaryjp 
@ovh/cds
=> feat(cdsctl): add group user list command (#3773)

ui/src/app/shared/workflow/modal/conditions/condition-form/condition.component.ts, ui/src/app/shared/workflow/modal/conditions/condition-form/condition.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): no more christmas tree in run conditions

engine/api/api_routes.go, engine/api/pipeline/pipeline.go, engine/api/templates.go, engine/api/worker_model.go, engine/api/worker_model_test.go, engine/api/workflow/dao.go, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #3779 
1. About tests
1. Mentions
@ovh/cds
=> fix(api): display only usage for workflow templates and worker model with good rights (#3779)

ui/src/app/app.component.ts, ui/src/app/service/workflow/workflow.sidebar.store.ts, ui/src/app/shared/worker/web.worker.ts, ui/src/app/shared/workflow/sidebar/edit-node/sidebar.edit.component.ts, ui/src/app/shared/workflow/wnode/pipeline/wnode.pipeline.component.ts, ui/src/app/shared/workflow/wnode/wnode.component.ts, ui/src/app/views/workflow/run/workflow.run.component.ts, ui/src/app/views/workflow/show/workflow.component.ts, ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): optimise performance for sse and sidebar

cli/cdsctl/shell.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): ask for context in shell only if current directory is a repository

engine/api/bookmark/bookmark.go
=> fix(api): order bookmarks alphabetically (#3783)

engine/api/config.go, sdk/config.go, ui/src/app/model/config.model.ts, ui/src/app/service/config/config.service.ts, ui/src/app/service/services.module.ts, ui/src/app/views/settings/cdsctl/cdsctl.component.ts, ui/src/app/views/settings/cdsctl/cdsctl.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): get url from /config/user

ui/src/app/views/settings/cdsctl/cdsctl.component.ts
=> fix(ui): get url api from /config/user and not environment

engine/api/project.go, ui/src/app/shared/keys/form/keys.form.html, ui/src/app/views/project/add/project.add.component.spec.ts, ui/src/app/views/project/add/project.add.component.ts, ui/src/app/views/project/add/project.add.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
=> feat(ui): auto create ssh/gpg key at project creation

engine/api/worker/model_import.go, engine/api/worker_model.go, ui/src/app/service/worker-model/worker-model.service.ts, ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/add/worker-model.add.scss, ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #3768 
1. About tests
1. Mentions
@ovh/cds
=>  feat(ui): add edit/add worker model as code

ui/src/app/shared/permission/list/permission.list.component.spec.ts, ui/src/app/shared/permission/list/permission.list.html
1. Description
close #3794 
1. About tests
1. Mentions
@ovh/cds
=> feat(ui) : display group -> link to group page (#3794)

engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_run.go
=> fix(api): keep spawnInfos on stop

engine/hatchery/local/local.go, engine/worker/run.go
1. Description
Set the working directory from base64 encoded job name
closes #3584
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): deterministic worker working directory

cli/cdsctl/action.go, cli/cdsctl/application_group.go, cli/cdsctl/environment_group.go, cli/cdsctl/pipeline.go, cli/cdsctl/pipeline_group.go, cli/cdsctl/project_group.go, cli/cdsctl/template.go, cli/cdsctl/workflow_push.go, engine/api/workflowtemplate/export.go, sdk/exportentities/common.go, sdk/exportentities/template.go, sdk/exportentities/template_test.go, tests/fixtures/template/simple/example-simple.yml, tests/fixtures/template/with_repository/example-with-repository.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cdsctl,api): allow to push a template from url

engine/api/workflowv0/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix (api): LoadCDTree

contrib/workflow-templates/README.md, contrib/workflow-templates/demo-usage-service-postgresql/1.pipeline.yml, contrib/workflow-templates/demo-usage-service-postgresql/README.md, contrib/workflow-templates/demo-usage-service-postgresql/demo-usage-service-postgresql.yml, contrib/workflow-templates/demo-usage-service-postgresql/workflow.yml
=> contrib(workflow-templates): demo service pg

engine/api/workflow/hook.go, sdk/hook.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): set right icon for repowebhook

engine/api/worker/model_import.go, engine/api/worker_model_import.go
=> fix(api): clear cache wm after import

contrib/worker-models/README.md, contrib/worker-models/go-official-1.11.4-stretch.yml, contrib/worker-models/maven3-jdk10-official.yml, contrib/worker-models/maven3-jdk9-official.yml, contrib/worker-models/python-official-2.7.15-stretch.yml, contrib/worker-models/python-official-3.4.9-stretch.yml, contrib/worker-models/python-official-3.5.6-stretch.yml, contrib/worker-models/python-official-3.6.5-jessie.yml, contrib/worker-models/python-official-3.6.7-stretch.yml, contrib/worker-models/python-official-3.7.1-stretch.yml, contrib/worker-models/ruby-official-2.5.0-stretch.yml, ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts
it will be useful for Ready To Run Doc (in a next pull request)
=> contrib(worker-models): some examples

engine/api/workflow/run_workflow.go, engine/api/workflow_run.go, ui/src/app/shared/workflow/node/run/node.run.param.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api,ui): manual run and run join

ui/src/app/app.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add timeout argument on heartbeat interval

ui/src/app/app.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): lint

ui/src/app/views/settings/workflow-template/form/workflow-template.form.component.ts, ui/src/app/views/settings/workflow-template/form/workflow-template.form.html, ui/src/app/views/settings/workflow-template/form/workflow-template.form.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): remove code area to prevent user forgetting to add item before save

engine/api/application/application_vunerability.go, engine/api/metrics/elasticsearch.go, engine/elasticsearch/elasticsearch_handlers.go, sdk/metric.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(engine): overwrite metrics on same id

engine/api/workflow/dao_run.go, engine/worker/cmd_tmpl.go, tests/fixtures/ITSCWRKFLW9/ITSCWRKFLW9-WORKFLOW.yml, tests/fixtures/ITSCWRKFLW9/ITSCWRKFLW9.yml, tests/fixtures/ITSCWRKFLW9/worker-tmpl.pip.yml, tests/sc_workflow_run_cmd_tmpl.yml
=> fix(worker): worker tmpl with exported var

engine/api/migration_test.go, engine/api/platform/dao_platform.go, engine/api/project_platform.go, engine/api/project_platform_test.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/process_node.go, engine/sql/151_workflow_node_run_idx.sql
=> fix(api,sql): nodeExits function

ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): button disable on worker model is now working

engine/api/repositoriesmanager/repositories_manager.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): vcs call errors management

engine/api/event/publish.go, engine/api/event/publish_workflow_run.go, engine/api/pipeline/pipeline_build.go, sdk/event.go
=> feat(api): add tag in event for heatmap

engine/api/workflow/dao_run.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): migrate run on load

engine/api/templates.go, engine/api/workflowtemplate/execute.go, engine/api/workflowtemplate/execute_test.go, engine/api/workflowtemplate/import.go, sdk/error.go, sdk/workflow_template.go, ui/src/app/model/workflow-template.model.ts, ui/src/app/shared/diff/item/diff.item.component.ts, ui/src/app/views/admin/hook-task/show/hook-task.show.component.ts, ui/src/app/views/settings/settings.module.ts, ui/src/app/views/settings/workflow-template/add/workflow-template.add.component.ts, ui/src/app/views/settings/workflow-template/add/workflow-template.add.html, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.html, ui/src/app/views/settings/workflow-template/editor/workflow-template.editor.component.ts, ui/src/app/views/settings/workflow-template/editor/workflow-template.editor.html, ui/src/app/views/settings/workflow-template/editor/workflow-template.editor.scss, ui/src/app/views/settings/workflow-template/form/workflow-template.form.component.ts, ui/src/app/views/settings/workflow-template/form/workflow-template.form.html, ui/src/app/views/settings/workflow-template/form/workflow-template.form.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): return more info about workflow template parsing and execution errors

ui/src/app/views/settings/action/edit/action.edit.component.ts
in case of with many spaces in action name
=> fix(ui): link to official doc

contrib/helm/cds/README.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc(contrib): update readme of helm

contrib/helm/cds/templates/hatchery-k8s-deployment.yaml, contrib/helm/cds/values.yaml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): add namespace config for k8s hatchery in helm

tools/debpacker/debpacker.go, tools/debpacker/tmpl.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(tools): add post install

cli/cobra.go, cli/cobra_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): fix fields filter for list

go.mod, go.sum, vendor/github.com/fsamin/go-repo/cmd.go, vendor/github.com/fsamin/go-repo/keys.go, vendor/modules.txt
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore: update go-repo dependency

ui/src/app/model/heatmap.model.ts, ui/src/app/views/home/heatmap/home.heatmap.component.ts, ui/src/app/views/home/heatmap/home.heatmap.html, ui/src/app/views/home/heatmap/home.heatmap.scss, ui/src/app/views/home/heatmap/toolbar/toolbar.component.html, ui/src/app/views/home/heatmap/toolbar/toolbar.component.ts, ui/src/app/views/home/home.module.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): toolbar added on heatmap component

cli/cdsctl/admin.go, cli/cdsctl/admin_curl.go, cli/cdsctl/version.go, tests/clictl_template_bulk.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): create admin curl command and fix template bulk test

ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): use project key to init template from workflow

ui/src/app/views/workflow/run/node/pipeline/variables/job.variable.html, ui/src/app/views/workflow/run/node/pipeline/variables/job.variable.scss
1. Description
Set jobs variable modals size fit to screen & scroll its content
1. About tests
1. Mentions
@ovh/cds
=> feat(ui) Job variable into real scrollable modal

cli/cdsctl/application_group.go, cli/cdsctl/environment_group.go, cli/cdsctl/pipeline.go, cli/cdsctl/pipeline_group.go, cli/cdsctl/project_group.go, cli/cdsctl/template.go, cli/cdsctl/workflow_push.go, engine/api/database/gorpmapping/common.go, engine/api/templates.go, engine/api/workflowtemplate/import.go, engine/sql/155_template_import_url.sql, sdk/common.go, sdk/exportentities/common.go, sdk/exportentities/template.go, sdk/workflow_template.go, ui/src/app/model/workflow-template.model.ts, ui/src/app/views/settings/workflow-template/add/workflow-template.add.component.ts, ui/src/app/views/settings/workflow-template/add/workflow-template.add.html, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.html, ui/src/app/views/settings/workflow-template/editor/workflow-template.editor.component.ts, ui/src/app/views/settings/workflow-template/form/workflow-template.form.component.ts, ui/src/app/views/settings/workflow-template/form/workflow-template.form.html, ui/src/app/views/settings/workflow-template/form/workflow-template.form.scss, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui,api): allow to import a template from url

ui/src/app/shared/workflow/wnode/pipeline/node.pipeline.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): workflow not rendering bad integration_id key name

engine/api/status.go, engine/sql/154_remove_old_workflow.sql, engine/sql/157_remove_old_workflow.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor: delete workflow v0 tables

contrib/helm/cds/README.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs(helm): fix typo

engine/api/application/application_parser.go, engine/api/application_deployment.go, engine/api/application_import_test.go, sdk/integration.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): password was overrided by default empty value

README.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> README proofread 1

engine/worker/builtin_gitclone.go, sdk/vcs/keys.go
1. Description
close #3908 
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): do not panic when the secret is not found (close #3908)

engine/hooks/tasks.go, engine/hooks/tasks_test.go, engine/hooks/webhook.go
1. Description
close #3907 
1. About tests
1. Mentions
@ovh/cds
=> fix(hooks): run multiple events on a single push event from bitbucket

engine/api/workflow/repository.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(repository): display trusted operation in error logs

engine/api/observability/init.go, engine/api/observability/stats.go
=> fix(api): allow /mon/metrics without jaeger

engine/api/application/application_parser.go, engine/api/application_import_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): save previous key clear value when using regen to false

contrib/helm/cds/values.yaml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc(contrib): change default value for namespace hatchery in helm

contrib/grpcplugins/action/examples/nodejs/package-lock.json, contrib/grpcplugins/action/examples/nodejs/package.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): delete vulnerabilities of lodash

engine/api/workflow/dao_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): remove default payload when it's not on root node

engine/api/application_import_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): problem with assert on regen test case

engine/api/application.go, engine/api/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=>  fix(api): return project permission on application

contrib/helm/cds/Chart.yaml, contrib/helm/cds/values.yaml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore(contrib): bump version of helm app version

contrib/helm/cds/README.md, contrib/helm/cds/templates/hatchery-k8s-deployment.yaml, contrib/helm/cds/values.yaml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): delete some useless configurations on helm

contrib/helm/cds/.gitignore, contrib/helm/cds/Chart.yaml, contrib/helm/cds/README.md, contrib/helm/cds/templates/NOTES.txt
=> doc(helm): some improvements

engine/api/group/workflow_group.go, ui/src/app/shared/workflow/modal/permissions/node.permissions.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): let user add permission via ui on node

engine/api/application.go, engine/api/application_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): compute permission on application

tests/fixtures/ITSCWRKFLW6/ITSCWRKFLW6.yml, tests/sc_workflow_git_clone_tag.yml
=> fix(it): use new tag

.gitignore, engine/elasticsearch/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore: minor fixes

engine/api/permission/permission.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): purge panic

engine/api/workflow/dao_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): purge panic on workflow node deletion

README.md, engine/Makefile
=> chore: remove coveralls

engine/api/purge/purge.go, engine/api/workflow/dao_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): mark workflow runs to delete before trying to remove workflow

engine/api/api.go, engine/api/purge/purge.go, engine/api/status.go, engine/api/workflow/dao_run.go, engine/api/workflow/dao_run_test.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): metrics about workflow runs purge

engine/api/purge/purge.go, engine/api/purge/purge_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): delete one workflow run per request

engine/api/purge/purge.go
1. Description
close #3942
1. About tests
1. Mentions
@ovh/cds
=> fix(api): raise purge frequency

sdk/rust/sdk-cds/src/client.rs
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): add user agent in rust sdk

ui/src/app/store/store.module.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): disable logger on production env

ui/src/app/store/project.state.spec.ts, ui/src/app/store/project.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix create project key

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): return right commits list

docs/content/contribute/development.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc: update postgresql version

engine/api/status.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): process metric, negative index

engine/api/workflow/as_code.go, engine/repositories/processor_push.go, ui/src/app/shared/workflow/modal/hook-modal/hook.modal.html, ui/src/app/shared/workflow/modal/outgoinghook-edit/outgoing.modal.html, ui/src/app/shared/workflow/node/hook/form/hook.form.html, ui/src/app/shared/workflow/sidebar/edit-hook/workflow.sidebar.hook.component.html, ui/src/app/shared/workflow/sidebar/edit-node/sidebar.edit.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api, repo): migrate as code

go.mod, go.sum, vendor/github.com/fsamin/go-repo/repo.go, vendor/modules.txt
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore: update go-repo vendors

go.sum, vendor/k8s.io/client-go/pkg/version/base.go
=> chore: fix k8s dep

LICENSE, sdk/interpolate/interpolate.go, sdk/interpolate/interpolate_test.go
1. Description
1. About tests
1. Mentions
@mdouchement 
@ovh/cds
=> fix(api): interpolate and integer parameters

engine/vcs/bitbucket/client_pull_request.go, engine/vcs/bitbucket/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(vcs): no need to call get branch

cli/cdsctl/events.go, cli/cdsctl/main.go, sdk/cdsclient/client_events.go, sdk/cdsclient/interface.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cli,sdk): add listen cds events

sdk/rust/sdk-cds/Cargo.lock, sdk/rust/sdk-cds/Cargo.toml
1. Description
1. About tests
1. Mentions
@ovh/cds
=>  chore(sdk): bump rust sdk version

cli/cdsctl/config.go, cli/cdsctl/project_key.go, cli/cdsctl/workflow_as_code.go, engine/api/workflow/dao.go, engine/vcs/gitlab/client_hook.go, sdk/error.go
1. Description
#3998
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): set ssh key on application in workflow as code init

ui/src/app/views/settings/group/list/group.list.component.ts, ui/src/app/views/settings/group/list/group.list.html, ui/src/app/views/settings/group/list/group.list.scss, ui/src/app/views/settings/user/list/user.list.component.ts, ui/src/app/views/settings/user/list/user.list.html, ui/src/app/views/settings/user/list/user.list.scss
1. Description
#3807
1. About tests
1. Mentions
@ovh/cds
=> refact(ui): usage data table component for user and group lists

README.md
=> fixed particularly

cli/cdsctl/workflow_status.go, engine/api/workflow/dao_run.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go, tests/fixtures/ITSCWRKFLW3/ITSCWRKFLW3.yml, tests/sc_workflow_create_run_join.yml, tests/sc_workflow_payload_merge_run.yml, tests/sc_workflow_run_simple.yml, tests/sc_workflow_stop_simple.yml, tests/sc_workflow_update_run.yml, ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.html, ui/src/app/views/account/verify/verify.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not migrate worklow run on status pending

engine/api/application/application_delete.go, engine/api/application/application_variable.go, engine/api/database/gorpmapping/common.go, engine/api/environment/environment_variable.go, sdk/error.go
1. Description
#3808
1. About tests
1. Mentions
@ovh/cds
=> fix(api): returns better error when an application cannot be removed

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): use new context for async part

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): run from hook uservice

sdk/grpcplugin/actionplugin/nodejs/package-lock.json, sdk/grpcplugin/actionplugin/nodejs/package.json, ui/src/app/views/workflow/add/workflow.add.component.ts, ui/src/app/views/workflow/add/workflow.add.html
1. Description
Also update lodash for nodejs grpc plugin.
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add filter for template list in create workflow page

sdk/cdsclient/http_sse.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): data can be splitted

engine/api/pipeline.go, ui/src/app/store/pipelines.state.ts, ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts, ui/src/app/views/pipeline/show/pipeline.show.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix pipeline view with store

engine/api/event/publish_workflow_run.go, sdk/event.go
1. Description
Add node type ( pipeline, fork, join ..) on node run event
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add type of node on node run event

engine/api/pipeline/pipeline_stage.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not try to load useless group or audits on jobs

engine/api/database/gorpmapping/common.go, engine/api/migrate/workflow_run_old_model.go, engine/api/workflow/dao_run.go, engine/api/workflow/run_workflow.go, engine/api/workflow_run.go, sdk/error.go, sdk/messages.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix return condition ko AND fix stop migration on locked error

sdk/interpolate/go.mod, sdk/interpolate/go.sum
1. Description
1. About tests
1. Mentions
@ovh/cds
=> chore: interpolate package as go module

engine/api/group/node_group.go, engine/api/workflow/dao.go, engine/api/workflow_group.go
1. Description
close #4035
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fix permission coherence (close #4035)

cli/cdsctl/workflow_as_code.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cli): workflow init

sdk/exportentities/action.go
=> fix(sdk): do not export shared group name

cli/cdsctl/Makefile, contrib/grpcplugins/action/Makefile, contrib/grpcplugins/action/examples/nodejs/Makefile, contrib/integrations/arsenal/plugin-arsenal/Makefile, contrib/integrations/hello/plugin-hello-deployment/Makefile, contrib/integrations/kubernetes/plugin-kubernetes/Makefile, engine/Makefile, engine/worker/Makefile, sdk/download.go, tools/debpacker/Makefile, tools/os-ansible-inventory/Makefile, ui/src/app/views/settings/cdsctl/cdsctl.component.ts
=> chore: arm64

docs/content/docs/concepts/files/application-syntax.md
=> doc: application file format

docs/content/docs/concepts/files/environment-syntax.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc: environment files

docs/content/docs/concepts/files/environment-syntax.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> doc: environment config file precision

ui/src/app/service/pipeline/pipeline.service.ts, ui/src/app/store/pipelines.state.ts, ui/src/app/store/workflows.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): do not export pipeline and workflows with permissions

engine/vcs/github/http.go
=> fix(vcs): initialize github ratelimit values

engine/api/worker.go, engine/api/worker/model.go, engine/api/worker_model.go, engine/worker/cmd_register.go, sdk/worker.go
=> fix(api): release book after worker model registration or error

cli/cdsctl/Makefile, cli/cdsctl/configstore.go, cli/cdsctl/configstore_darwin.go, cli/cdsctl/configstore_linux_amd64.go, cli/cdsctl/configstore_windows_amd64.go, cli/cdsctl/main.go, cli/cdsctl/update.go, cli/cdsctl/version.go, engine/api/download.go, engine/update.go, engine/worker/cmd_update.go, sdk/cdsclient/client_download.go, sdk/cdsclient/interface.go, sdk/download.go, ui/src/app/model/download.model.ts, ui/src/app/service/download/download.service.ts, ui/src/app/views/settings/cdsctl/cdsctl.component.ts, ui/src/app/views/settings/cdsctl/cdsctl.html, ui/src/app/views/settings/download/download.component.ts, ui/src/app/views/settings/download/download.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
* new Makefile goal: `build-nokeychain`
* new binaries: `cdsctl-OS-ARCH-nokeychain`
close #3962
=> fix(cli): build cdsctl without keychain support

engine/api/worker/model.go, engine/api/worker_model.go
1. Description
close #4055
1. About tests
1. Mentions
@ovh/cds
=> fix(api): error inserting UpdateSpawnErrorWorkerModel with UTF8 0x00

engine/api/workflow/dao.go, engine/api/workflow/dao_hook.go
1. Description
close #4074
1. About tests
1. Mentions
@ovh/cds
=> fix(api): invalid payload error is not correctly raised

engine/worker/builtin_script.go, engine/worker/builtin_script_test.go
1. Description
handle shebang options correctly
close #2483
1. About tests
new unit tests
1. Mentions
@ovh/cds
=> fix(worker): shebang incorrectly interpreted in Script

engine/api/api.go
=> feat(api): check downloadable binaries on startup

sdk/cdsclient/client_workflow.go
=> fix(sdk): release action http timeout

cli/cdsctl/config.go, cli/cdsctl/login.go, cli/cdsctl/main.go, cli/cdsctl/signup.go, cli/cdsctl/template.go, cli/cdsctl/template_apply.go, cli/cdsctl/workflow_as_code.go, cli/cdsctl/workflow_pull.go, cli/cdsctl/workflow_push.go, cli/cobra.go
(verbose, insecure, ...)
close #3032
@ovh/cds
=> fix(cli): command persistant flags

engine/api/workflow/dao_data_hook.go
=> fix(api): import a workflow containing an app without a repository linked

engine/api/api.go, engine/api/pipeline/audit.go
1. Description
Keep the last 50 audits
#3941
1. About tests
1. Mentions
@ovh/cds
=> fix(api): purge pipeline audits

engine/hatchery/openstack/openstack.go, engine/hatchery/vsphere/vsphere.go, sdk/hatchery/pool.go
--> fix to avoid deleting VM created for registration in status disabled.
This will fix the image creation. Without this fix, the image creation
can work somethimes, depends on speed of image creation & timer.
Tests done
=> fix(hatchery/openstack): register & disabled

ui/src/app/views/workflow/graph/workflow.graph.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add delay to render the workflow

docs/layouts/_default/baseof.html
=> doc(fix): noburger en layout grid

engine/api/workflow/dao.go, engine/repositories/processor_checkout.go
=> fix(api, repositories): workflow as code

engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow as code and project variables

tools/debpacker/debpacker.go, tools/debpacker/debpacker_test.go, tools/debpacker/main.go, tools/debpacker/tmpl.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(tools): add set -e on post install

Makefile, go.mod, go.sum, vendor/github.com/fsamin/go-repo/repo.go, vendor/modules.txt
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: update go-repo to v0.1.1

engine/api/workflow/process_requirements.go
=> fix(api): load model with opts

engine/hooks/webhook.go
=> fix(vcs): avoid too big payload

ui/src/app/views/workflow/run/workflow.run.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): do not try to select a node if workflow is not already created

ui/src/app/store/pipelines.state.ts
1. Description
close #3898
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add a pipeline parameter refresh workflows store

engine/api/workflow_trigger.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): add git.tag in condition name

engine/api/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): return right permission for workflow created/updated

docs/content/docs/components/worker/download.md, engine/worker/cmd_download.go
=> feat(worker): worker download from latest workflow run

engine/worker/cmd_download.go
=> fix(worker): download in the current directory

engine/api/repositories_manager.go, sdk/error.go
=> fix(api): avoid remove VCS if still used by an application

tools/debpacker/debpacker_test.go, tools/debpacker/tmpl.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(tools): add set+e because status return 3 if service is down
