- engine/vcs/gitlab/client_status.go
1. Description
All described in the issue below
Related issue [https://github.com/ovh/cds/issues/4042](https://github.com/ovh/cds/issues/4042)  
1. About tests
I did the test on my dev environment, and then my preprod environment
1. Mentions
@ovh/cds
> fix(vcs): avoid duplicate set statuses requests on gitlab API

- engine/worker/logger.go
> fix(worker): respect logs formats

- sdk/interpolate/interpolate_helper.go
- sdk/interpolate/interpolate_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk): handle val struct given to helper for interpolate

- sdk/exportentities/workflow.go
- sdk/exportentities/workflow_tar.go
> fix(sdk): do not export default payload in as-code

- engine/hatchery/local/local.go
- sdk/hatchery/hatchery.go
> fix(hatchery/local): allow spawn job with req plugin

- engine/api/api.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): CleanArtifactBuiltinActions migration

- engine/api/ascode.go
- engine/api/ascode_test.go
- engine/api/feature/flipping.go
- engine/api/workflow_run.go
- engine/api/workflow_run_test.go
- ui/src/assets/i18n/en.json
> feat(api): rm feature flipping on as-code

- engine/api/grpc_plugin.go
- sdk/hatchery/hatchery.go
- tests/clictl_admin_plugin_and_integrations.yml
- tests/fixtures/plugins/hello-action-plugin-binary.yml
- tests/fixtures/plugins/hello-action-plugin.yml
> fix(api): import action plugin wihout integration

- ui/src/app/views/settings/worker-model/list/worker-model.list.html
- ui/src/assets/i18n/en.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): missing some translations

- engine/api/workflow/process.go
- engine/api/workflow/run_workflow.go
- engine/hooks/poller.go
- engine/hooks/webhook.go
- engine/worker/builtin_gitclone.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): add git hash short param on manual run

- engine/api/workflow/dao_run.go
- engine/api/workflow/dao_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): keep the ordering DESC of id to purge

- engine/api/cache/redis.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): cache Publish error logs

- docs/content/docs/tutorials/import_workflow_with_webui.md
- engine/types.go
> doc: fix link on hatcheries

- contrib/helm/cds/config.toml
- contrib/helm/cds/templates/api-deployment.yaml
cf #https://github.com/ovh/cds/issues/4159#issuecomment-480338137
> fix(helm): -o does not exist in base image

- engine/api/workflow/process_parameters.go
close #3290 
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): triggered variables sent to children

- contrib/helm/cds/config.toml
- contrib/helm/cds/templates/api-deployment.yaml
- engine/api/workflow/as_code.go
- engine/api/workflow/dao.go
- engine/repositories/processor_push.go
- engine/vcs/github/client_pull_request.go
- engine/vcs/github/client_rate_limit.go
- engine/vcs/github/github.go
- engine/vcs/github/github_test.go
- engine/vcs/github/http.go
- engine/vcs/github/oauth_consumer.go
- engine/vcs/types.go
- engine/vcs/vcs.go
- engine/vcs/vcs_handlers_test.go
1. Description
close #4037 
1. About tests
1. Mentions
@ovh/cds
> fix(api): some fixes about transform to as code (close #4037)

- engine/api/workflow/process_node_test.go
- engine/api/workflow/process_parameters.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not prefix non cds parameters

- cli/cdsctl/user.go
- cli/cobra.go
- cli/types.go
- engine/api/workflow/dao.go
- engine/api/workflow/dao_node.go
- engine/api/workflow/repository.go
- engine/api/workflow/workflow_importer.go
- engine/api/workflow/workflow_importer_test.go
- engine/api/workflow/workflow_parser.go
- engine/api/workflow/workflow_parser_test.go
- engine/api/workflow_import.go
- engine/api/workflow_run.go
- engine/hooks/hooks_handlers.go
- sdk/project.go
- tests/clictl_group.yml
and avoid deleting all hooks execution
close #4118
> fix(api,hooks): rename workflow as-code

- engine/api/workflow/process_node_test.go
- engine/api/workflow/process_parameters.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api):  .workflow params

- engine/api/workflow/process_node.go
- engine/api/workflow/process_node_test.go
- engine/api/workflow/run_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): git.server not sent to children

- engine/vcs/types.go
- engine/vcs/vcs.go
Warning: Users , you may need to update VCS your configuration
> fix(vcs): Gitlab oauth Application callback URL

- cli/cdsctl/project.go
- cli/cobra.go
- cli/display.go
- engine/api/application/dao.go
- engine/api/pipeline/pipeline.go
- engine/api/project.go
- engine/api/project/dao_dependencies.go
- engine/api/workflow/dao.go
- sdk/common.go
- sdk/project.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cli): project command improvements

- ui/src/app/shared/workflow/node/run/node.run.param.component.ts
- ui/src/app/store/applications.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): clear workflow cache when needed and don't fetch commits when no num

- engine/api/workflow/execute_node_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): ignore case when comparing vcs info for bibucket

- engine/api/workflow/workflow_exporter.go
> fix(api): do not export application, pipeline and environment coming from another repository

- engine/api/api_routes.go
- engine/api/workflow.go
- engine/api/workflow/dao.go
- ui/src/app/store/workflows.action.ts
- ui/src/app/store/workflows.state.spec.ts
- ui/src/app/store/workflows.state.ts
- ui/src/app/views/navbar/navbar.component.ts
- ui/src/app/views/workflow/show/admin/workflow.admin.component.html
- ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
- ui/src/app/views/workflow/show/admin/workflow.admin.scss
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
1. Description
+ Refactor of advanced view in workflow page
fix #4157 
1. About tests
UT
1. Mentions
@ovh/cds
> fix(ui,api): let users add/edit/delete workflow icon when as code

- ui/src/app/views/application/show/application.html
- ui/src/app/views/pipeline/show/pipeline.show.html
1. Description
close #4179 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): delete broken link in as code modal #4179

- engine/api/purge/purge.go
- engine/api/workflow/dao_node_run_job.go
- engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): db errors

- engine/api/workflow/process_node_test.go
- engine/api/workflow/process_parameters.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): add git param with prefix for children

- engine/api/workflow/process_start.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): let join trigger automatically even with different subnumber (close #3853)

- engine/api/workflow/workflow_exporter.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): workflow pull renders empty pipelines

- engine/api/workflow_import_test.go
- sdk/exportentities/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): import workflow with conditionnal join

- engine/api/database/database.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): fix set statement timeout option after connect

- contrib/helm/cds/Chart.yaml
- contrib/helm/cds/values.yaml
> chore: helm 0.39.0 version

- engine/api/application_variable.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not use nil value to create error

- cli/cdsctl/template_apply.go
- cli/cdsctl/template_bulk.go
- cli/cdsctl/workflow_as_code.go
- sdk/cdsclient/client_repositories_manager.go
- sdk/cdsclient/interface.go
1. Description
close #4127 
1. About tests
1. Mentions
@ovh/cds
> fix(cdsctl): clear cache of repomanager when workflow init (#4127)

- cli/cdsctl/monitoring.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdsctl): sort hatchery workers count by status for termui

- ui/src/app/views/workflow/add/workflow.add.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): remove feature flipping on wasc

- engine/api/workflow/dao.go
- sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): check if an application is available on the root node of a workflow as code

- engine/api/application/application_importer.go
- engine/api/workflow/as_code.go
- engine/api/workflow/repository.go
- engine/repositories/processor_push.go
- sdk/exportentities/application.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): reset application RepositoryStrategy against ConnectionType

- engine/api/ascode.go
- engine/api/repositoriesmanager/repositories_manager.go
- engine/api/workflow/as_code.go
- engine/vcs/bitbucket/client_pull_request.go
- engine/vcs/bitbucket/client_repos.go
- engine/vcs/bitbucket/client_repos_test.go
- engine/vcs/bitbucket/http.go
- engine/vcs/bitbucket/oauth_consumer_sign.go
- engine/vcs/gerrit/client_repos.go
- engine/vcs/github/client_repos.go
- engine/vcs/gitlab/client_repos.go
- engine/vcs/vcs_handlers.go
- sdk/vcs.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): grant bitbucket user before creating pr

- sdk/cdsclient/client_queue.go
- sdk/cdsclient/http.go
- sdk/hatchery/starter.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery): traces & retries

- cli/cdsctl/workflow_show.go
- engine/api/workflow.go
- sdk/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cli): improve cdsctl workflow show command

- engine/api/permission.go
- engine/api/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): error 404 if the workflow doesn't exist

- engine/api/workflow/process_node_test.go
- engine/api/workflow/process_parameters.go
1. Description
cc @ybriffa 
1. About tests
1. Mentions
@ovh/cds
> fix(api): keep cds release

- cli/cdsctl/workflow.go
- cli/cdsctl/workflow_transform_as_code.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: change to GetCommand + add silent

- engine/api/suggest.go
> fix(api): git.project does not exist

- engine/api/api_routes.go
- engine/api/workflow/as_code.go
- engine/api/workflow_ascode.go
- ui/src/app/service/workflow/workflow.service.ts
- ui/src/app/views/workflow/workflow.component.ts
- ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api, ui): resync as code pullrequest status

- sdk/hatchery/hatchery.go
> fix(hatchery): if already booked by someone, ignore the job

- cli/cdsctl/workflow_artifact.go
> feat(worker): to not re-download artifact if already here

- sdk/hatchery/register.go
- sdk/hatchery/starter.go
> fix(hatchery): count register

- README.md
- docs/content/about/articles.md
1. Description
1. About tests
1. Mentions
@ovh/cds
> docs: add youtube link for talks at Breizhcamp

- docs/content/docs/integrations/openstack/openstack_swift.md
- engine/api/worker/worker.go
> fix(api): clear cache after register

- sdk/hatchery/hatchery.go
1. Description
This PR should be merged and deployed before #4146. Will be useful in case of rollback.
1. About tests
1. Mentions
@ovh/cds
> feat(hatchery): clean group info in model name

- sdk/hatchery/register.go
> fix(hatchery): break on already registering

- cli/cdsctl/main.go
- cli/cdsctl/token.go
- cli/cobra.go
- docker-compose.yml
- docs/content/development/contribute/development.md
- docs/content/docs/components/cdsctl/_index.md
- docs/content/docs/components/cdsctl/token/generate.md
- docs/content/docs/components/engine/_index.md
- docs/content/docs/components/engine/config/new.md
- docs/content/hosting/ready-to-run/docker-compose.md
- engine/api/repositoriesmanager/repositories_manager.go
- engine/api/workflow/workflow_importer.go
- engine/api/workflow_import.go
- engine/hooks/hooks_handlers.go
- engine/hooks/kafka.go
- engine/main.go
- sdk/workflow_hook.go
- tests/fixtures/ITSCWRKFLW16/edit_a/pipeline.pip.yml
- tests/fixtures/ITSCWRKFLW16/edit_a/workflow.yml
- tests/fixtures/ITSCWRKFLW16/edit_b/pipeline.pip.yml
- tests/fixtures/ITSCWRKFLW16/edit_b/workflow.yml
- tests/sc_workflow_edit_scheduler.yml
- edit scheduler: next execution is deleted and re-scheduled
- edit as code / workflow push: take new hook config if present
- cdsctl: ignore case on filter
close #4250
> fix(api): update scheduler

- docs/content/hosting/requirements.md
1. Description
1. About tests
1. Mentions
@ovh/cds
> doc(requirement): update minimum requirements

- engine/api/workflow/process_requirements.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): ignore worker model group name in requirement

- sdk/download.go
> fix(api): download windows

- engine/hooks/tasks.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hooks): restart task for poller

- engine/hatchery/swarm/swarm_util_create.go
- engine/worker/requirement.go
- sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): ignore requirement model group name on worker start

- engine/elasticsearch/elasticsearch_handlers.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(elasticsearch): add logs when error appears

- engine/api/auth/ldapclient.go
> fix(api): ldap - first user is admin

- README.md
> fix(doc): links on doc

- contrib/integrations/hello/hello.yml
- contrib/integrations/hello/plugin-hello-deployment/Makefile
- contrib/integrations/hello/plugin-hello-deployment/main.go
- docs/content/docs/concepts/files/application-syntax.md
- engine/api/workflow_hook.go
- engine/config.go
- engine/main.go
- engine/vcs/types.go
- engine/vcs/vcs.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): fix gitlab config, show deployment password in hello platform

- ui/src/app/views/settings/workflow-template/add/workflow-template.add.component.ts
1. Description
Fix errors when no environments, pipelines or applications.
1. About tests
1. Mentions
@ovh/cds
> fix(ui): init template from workflow

- cli/cdsctl/workflow_init.go
- ui/src/app/views/pipeline/show/pipeline.show.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cli): workflow init: set the workflow and app name

- engine/repositories/processor_checkout.go
> fix(repositories): always reset hard

- engine/api/workflow/process.go
- engine/api/workflow/process_node_test.go
- engine/vcs/vcs_handlers.go
> fix(api): git.server in build param

- engine/api/workflow_run.go
> fix(api): log error only if not ErrConditionsNotOk

- engine/hooks/scheduler.go
- engine/hooks/webhook.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hooks): use another uuid for branch deletion task and autoclean them

- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): from repository options should be given to update as code workflow

- engine/repositories/processor.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(repo): return error cause

- ui/src/app/shared/table/data-table.component.ts
- ui/src/app/shared/table/data-table.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): only translate string values in data table

- cli/cdsctl/workflow_init.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cli): resync repo list on workflow init

- engine/api/workflow_trigger.go
- ui/src/app/model/workflow.model.ts
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.component.ts
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.html
- ui/src/app/shared/workflow/wnode/wnode.component.ts
- ui/src/app/shared/workflow/wnode/workflow.node.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: allow manual run

- engine/vcs/bitbucket/client_hook.go
- engine/vcs/bitbucket/client_hook_test.go
- engine/vcs/bitbucket/types.go
- engine/vcs/gerrit/client_hook.go
- engine/vcs/github/client_hook.go
- engine/vcs/gitlab/client_hook.go
- sdk/vcs.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hooks): do not create hook twice

- engine/Makefile
- engine/api/cache/redis.go
- engine/api/test/test.go
- engine/api/workflow_ascode_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore(engine): generate cross package cover report

- cli/cdsctl/workflow_artifact.go
- engine/worker/builtin_artifact_download.go
- engine/worker/cmd_download.go
> fix(cdsctl,worker): artifact download os.O_TRUNC

- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.component.ts
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.html
- ui/src/app/shared/workflow/wnode/fork/node.fork.scss
- ui/src/app/shared/workflow/wnode/pipeline/wnode.pipeline.component.ts
- ui/src/app/shared/workflow/wnode/wnode.component.ts
- ui/src/app/shared/workflow/wnode/workflow.node.common.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): use permission from workflow for run link

- engine/vcs/bitbucket/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): wrong bitbucket cache

- engine/worker/cmd_main.go
- engine/worker/cmd_run.go
- engine/worker/init.go
- engine/worker/main.go
- engine/worker/register.go
- engine/worker/run.go
- engine/worker/take_workflow_node_run_job.go
> fix(worker): keep auto-update for now

- ui/src/app/app.component.html
- ui/src/app/shared/workflow/wizard/context/wizard.context.component.ts
- ui/src/app/shared/workflow/wizard/hook/hook.form.component.ts
- ui/src/app/shared/workflow/wizard/outgoinghook/wizard.outgoinghook.component.ts
- ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
- ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): multiple modal

- cli/cdsctl/workflow.go
- cli/cdsctl/workflow_init.go
- cli/cdsctl/workflow_status.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cli): workflow init and workflow status

- engine/api/workflow/dao.go
1. Description
The function "Import" already create hooks
1. About tests
1. Mentions
@ovh/cds
> fix(api): remove useless code

- ui/src/app/shared/workflow/wizard/context/wizard.context.component.ts
- ui/src/app/shared/workflow/wizard/context/wizard.context.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: add/edit integration on pipeline

- engine/vcs/gitlab/client_hook.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): do not create gitlab hook if already exists

- ui/src/app/shared/workflow/node/hook/details/hook.details.component.html
- ui/src/app/shared/workflow/node/hook/details/hook.details.component.scss
- ui/src/app/shared/workflow/node/hook/details/hook.details.component.ts
- ui/src/app/shared/workflow/wizard/hook/hook.form.scss
- ui/src/app/views/settings/workflow-template/add/workflow-template.add.html
- ui/src/theme.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): read-only input style, some fixes

- engine/api/api_routes.go
- engine/api/workflow/dao_run.go
- engine/api/workflow_hook.go
- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): add tracing on getWorkflowRunHandler

- ui/src/app/views/workflow/run/node/test/table/test.table.html
> feat(ui): display message of failures/err junit

- ui/src/app/shared/diff/item/diff.item.component.ts
- ui/src/app/shared/workflow/wizard/conditions/wizard.conditions.component.ts
- ui/src/app/shared/workflow/wizard/hook/hook.form.component.ts
- ui/src/app/shared/workflow/wizard/input/wizard.input.component.ts
- ui/src/app/views/admin/hook-task/show/hook-task.show.component.ts
- ui/src/app/views/admin/service/show/service.show.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): init code mirror with input should be in onInit

- ui/src/app/shared/parameter/form/parameter.form.ts
- ui/src/app/shared/parameter/list/parameter.component.ts
- ui/src/app/shared/parameter/value/parameter.value.component.ts
- ui/src/app/shared/parameter/value/parameter.value.html
- ui/src/app/shared/variable/value/variable.value.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): missing shared service import generates js error

- engine/api/workflow_trigger.go
- ui/src/app/views/workflow/run/summary/workflow.run.summary.component.ts
- ui/src/app/views/workflow/run/workflow.run.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui,api): fix pipeline condition list + stop workflow permission

- cli/cdsctl/worker_model.go
> doc(cdsctl): some doc on worker model export/show

- docs/content/docs/actions/builtin-artifact-upload.md
- docs/content/docs/actions/builtin-coverage.md
- sdk/action/coverage.go
1. Description
close #4288 
1. About tests
1. Mentions
@ovh/cds
> doc: add example for coverage action

- contrib/helm/cds/templates/api-deployment.yaml
- contrib/helm/cds/templates/elasticsearch-deployment.yaml
- contrib/helm/cds/templates/hatchery-k8s-deployment.yaml
- contrib/helm/cds/templates/hooks-deployment.yaml
- contrib/helm/cds/templates/repositories-deployment.yaml
- contrib/helm/cds/templates/ui-deployment.yaml
- contrib/helm/cds/templates/vcs-deployment.yaml
1. Description
DO NOT SQUASH PLEASE
1. About tests
1. Mentions
@ovh/cds
> chore(contrib/helm): update deployment k8s api and enable rolling update (#4235)

- engine/api/database/gorpmapping/common.go
- engine/api/workflow/dao_node_run_job.go
- engine/api/workflow/run_workflow_test.go
- engine/api/workflow_queue.go
- engine/api/workflow_queue_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(api): getWorkflowJobQueueHandler

- sdk/hatchery/starter.go
> fix(hatchery/local): groupName in SpawnInfo

- cli/cdsctl/workflow_init.go
- engine/api/api_routes.go
- engine/api/application/application_parser.go
- engine/api/workflow/dao.go
- engine/api/workflow/workflow_parser.go
- engine/api/workflow_import.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): fix workflow init + workflow push + enable tracing on workflow push

- engine/api/workflow/dao.go
- engine/api/workflow/hook.go
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat: add observability on hook registration

- ui/src/app/shared/table/data-table.component.ts
- ui/src/app/shared/table/data-table.html
- ui/src/app/views/admin/hook-task/show/hook-task.show.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): link was missing in artifact list since refact

- engine/hatchery/local/local.go
- sdk/hatchery/starter.go
fix panic on hatchery.go:361
@ovh/cds
> fix(hatchery/local): use ServiceName as GroupName

- engine/api/workflow/dao.go
- engine/api/workflow/resync_workflow.go
- engine/api/workflow/workflow_parser.go
- engine/api/workflow_run.go
- sdk/workflow_run.go
- ui/src/app/app.service.ts
- ui/src/app/model/workflow.run.model.ts
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.html
- ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
- ui/src/app/views/workflow/run/node/pipeline/pipeline.html
1. Description
- Remove Resync workflow on old struct
- Remove run_job.parameter from getWorkflowRun
- Fix some js errors
- Fix WorkflowPush that erase hook config ( as code only )
1. About tests
1. Mentions
@ovh/cds
> fix(api, ui): workflow run optim, hook config fix

- engine/api/workflow/run_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: do no search hook on old model

- contrib/uservices/badge/.gitignore
- contrib/uservices/badge/Cargo.toml
- contrib/uservices/badge/README.md
- contrib/uservices/badge/diesel.toml
- contrib/uservices/badge/migrations/00000000000000_diesel_initial_setup/down.sql
- contrib/uservices/badge/migrations/00000000000000_diesel_initial_setup/up.sql
- contrib/uservices/badge/migrations/2019-04-09-192144_create_runs/down.sql
- contrib/uservices/badge/migrations/2019-04-09-192144_create_runs/up.sql
- contrib/uservices/badge/src/badge/handlers.rs
- contrib/uservices/badge/src/badge/mod.rs
- contrib/uservices/badge/src/configuration.rs
- contrib/uservices/badge/src/database.rs
- contrib/uservices/badge/src/error.rs
- contrib/uservices/badge/src/kafka.rs
- contrib/uservices/badge/src/main.rs
- contrib/uservices/badge/src/middlewares/auth.rs
- contrib/uservices/badge/src/middlewares/mod.rs
- contrib/uservices/badge/src/models.rs
- contrib/uservices/badge/src/run/handlers.rs
- contrib/uservices/badge/src/run/mod.rs
- contrib/uservices/badge/src/schema.rs
- contrib/uservices/badge/src/service.rs
- contrib/uservices/badge/src/web.rs
1. Description
close #546
1. About tests
1. Mentions
@ovh/cds
> feat(contrib): add badge uservice

- contrib/uservices/badge/src/main.rs
- contrib/uservices/badge/src/status/handlers.rs
- contrib/uservices/badge/src/status/mod.rs
- contrib/uservices/badge/src/web.rs
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(contrib): add /mon/status to uservice badge for healthcheck

- ui/src/app/views/workflow/run/workflow.run.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): load run after loading a failing workflow

- engine/vcs/vcs_auth.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): do not return error if no created field is available

- .gitignore
- engine/api/workflow_queue.go
- sdk/cdsclient/client_queue.go
1. Description
close #4342 
1. About tests
1. Mentions
@ovh/cds
> refactor(hatchery): get only queue for the right modeltype of hatchery

- ui/src/app/shared/conditions/conditions.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): create empty array when add first stage conditions

- engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): improve logs on postTakeWorkflowJobHandler errors

- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow_queue.go
- ui/src/app/shared/workflow/wizard/input/wizard.input.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load keys on take job

- ui/src/app/shared/conditions/conditions.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): add static param

- docs/content/development/contribute/development.md
1. Description
1. About tests
1. Mentions
@ovh/cds
> doc: update node information

- sdk/exportentities/step.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk): missing git tag and release in parsing step generate error

- engine/sql/169_delete_stage_prerequisites.sql
1. Description
close #4372 
1. About tests
1. Mentions
@ovh/cds
> fix(sql): delete useless pipeline_stage_prerequisite table #4372

- ui/src/app/views/home/heatmap/home.heatmap.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): do not use toolbar in OnInit

- .gitignore
- cli/cdsctl/admin.go
- cli/cdsctl/admin_metadata.go
- cli/cdsctl/project.go
- cli/cdsctl/project_integration.go
- cli/cdsctl/user.go
- docs/content/docs/concepts/_index.md
- docs/content/docs/concepts/permissions.md
- docs/content/docs/concepts/project.md
- engine/api/workflow.go
- engine/api/workflow/dao.go
- engine/api/workflow_group_test.go
- sdk/cdsclient/client_application.go
- sdk/cdsclient/client_project.go
- sdk/cdsclient/client_workflow.go
- sdk/cdsclient/interface.go
- tests/clictl_admin_metadata.yml
import / export csv - metadata
> feat(cdsctl): cdsctl admin metadata

- engine/api/workflow/dao.go
- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.html
- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.scss
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): css in sidebar and logs

- engine/api/workflow/workflow_parser.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load pipelines when parsing workflow for an as code workflow run

- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): delete workflow from  oldworkflow if possible

- engine/sql/170_clean_workflow_data_node.sql
- engine/sql/171_clean_workflow_data_node.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: add sql file to clean workflow_data

- engine/api/purge/purge.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: purge w_node_trigger && w_node before deleting workflow

- engine/hatchery/openstack/openstack.go
- engine/hatchery/openstack/spawn.go
> fix(hatchery/openstack): use snapshot

- docs/content/docs/concepts/job.md
1. Description
Some links are broken.
close #4419 
1. About tests
No tests needed. Documentation only.
1. Mentions
None.
@ovh/cds
> Set the right link to both artifact upload and download

- cli/cdsctl/admin_errors.go
- cli/cdsctl/admin_hooks.go
- cli/cdsctl/project.go
- cli/cdsctl/project_integration.go
- cli/cdsctl/project_repository_manager.go
- engine/api/repositories_manager.go
- sdk/cdsclient/client_project_repository_manager.go
- sdk/cdsclient/interface.go
- sdk/project.go
need force to re-enable it, next pr
> fix(api): allow delete vcs

- contrib/helm/cds/Chart.yaml
- contrib/helm/cds/values.yaml
> chore(helm): 0.40.0

- engine/hatchery/kubernetes/kubernetes.go
- engine/hatchery/swarm/swarm.go
- sdk/hatchery/requirement.go
- sdk/hatchery/requirement_test.go
1. Description
`PARAM='-c test'` now possible in service options.
@ovh/cds
> SpawnWorker params parsed more finely

- engine/api/workflow_ascode.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): postWorkflowAsCodeHandler return error

- ui/src/app/service/project/project.resolver.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fetch environment_names in project resolver

- sdk/cdsclient/client_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(worker): refactor on serve static files

- sdk/cdsclient/client_project_repository_manager.go
> fix(cdsctl): delete repo manager

- ui/src/app/shared/parameter/value/parameter.value.component.ts
- ui/src/app/shared/parameter/value/parameter.value.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display input text for unknown key

- ui/src/app/shared/workflow/modal/save-as-code/save.as.code.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fix if condition

- engine/worker/take_workflow_node_run_job.go
> fix(worker): timeout 120 send result

- ui/src/app/views/workflow/show/workflow.component.ts
- ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): improve render of graph

- engine/api/workflow.go
- engine/api/workflow_test.go
- sdk/error.go
> fix(api): add / remove label on a wf

- go.mod
- go.sum
- sdk/action/coverage.go
- vendor/github.com/sguiheux/go-coverage/coverage.go
- vendor/github.com/sguiheux/go-coverage/types.go
- vendor/github.com/sguiheux/go-coverage/types_clover.go
- vendor/modules.txt
close #4423
1. Description
#4423
1. About tests
1. Mentions
@ovh/cds
> feat(api): add clover format for codecoverage

- ui/package.json
- ui/src/app/shared/workflow/wizard/hook/hook.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): edit workflow hook as code

- engine/api/objectstore/swift.go
- sdk/action/serve-static-files.go
> refactor(api): ssf enabled false

- ui/src/app/shared/workflow/wizard/hook/hook.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): do not show 2 save buttons

- contrib/grpcplugins/action/examples/nodejs/package-lock.json
- contrib/grpcplugins/action/examples/nodejs/package.json
- sdk/grpcplugin/actionplugin/nodejs/package-lock.json
- sdk/grpcplugin/actionplugin/nodejs/package.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): upgrade lodash + regenerate package-lock

- ui/src/app/views/workflow/run/node/test/tests.component.ts
- ui/src/app/views/workflow/run/node/test/tests.result.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): wrong coverage trend

- sdk/grpcplugin/actionplugin/nodejs/package.json
- ui/src/app/shared/workflow/wizard/hook/hook.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): update hook button

- ui/src/app/service/project/project.resolver.ts
1. Description
close #4455 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): load environment names

- engine/worker/requirement.go
- sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery,worker): remove temporary condition for model requirement

- engine/hatchery/marathon/marathon.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(hatchery:marathon): increase cpu limitation for marathon containers

- engine/worker/requirement.go
- sdk/hatchery/hatchery.go
This reverts commit 5669676932bc2606ca400e15859d578450f16c81.
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery,worker): revert #4452

- engine/api/workflow/dao.go
- engine/api/workflow/hook.go
- engine/api/workflow/workflow_importer.go
- engine/api/workflow/workflow_parser.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): management hook as code

- engine/api/action/children.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): return better error for action not found

- ui/src/app/shared/workflow/wizard/hook/hook.form.html
- ui/src/app/shared/workflow/wizard/hook/hook.form.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(ui): display uuid

- go.mod
- go.sum
- vendor/github.com/fsamin/go-repo/repo.go
- vendor/modules.txt
1. Description
1. About tests
1. Mentions
@ovh/cds
> chores: update go-repo version

- contrib/helm/cds/templates/api-deployment.yaml
- contrib/helm/cds/templates/elasticsearch-deployment.yaml
- contrib/helm/cds/templates/hatchery-k8s-deployment.yaml
- contrib/helm/cds/templates/hooks-deployment.yaml
- contrib/helm/cds/templates/post-install-job.yaml
- contrib/helm/cds/templates/repositories-deployment.yaml
- contrib/helm/cds/templates/ui-deployment.yaml
- contrib/helm/cds/templates/vcs-deployment.yaml
- contrib/helm/cds/values.yaml
1. Description
Better to make a sed
1. About tests
1. Mentions
@ovh/cds
> refactor(helm): change tag to cdstag for image

- engine/worker/builtin_coverage.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: clover coverage

- ui/src/app/views/environment/add/environment.add.component.ts
- ui/src/app/views/environment/show/advanced/environment.advanced.component.ts
- ui/src/app/views/environment/show/environment.show.component.ts
- ui/src/app/views/environment/show/keys/environment.keys.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): onPush strategy on environment view

- ui/src/app/views/admin/admin.component.ts
- ui/src/app/views/admin/broadcast/add/broadcast.add.component.ts
- ui/src/app/views/admin/broadcast/edit/broadcast.edit.component.ts
- ui/src/app/views/admin/broadcast/list/broadcast.list.component.ts
- ui/src/app/views/admin/hook-task/list/hook-task.list.component.ts
- ui/src/app/views/admin/hook-task/show/hook-task.show.component.ts
- ui/src/app/views/admin/service/list/service.list.component.ts
- ui/src/app/views/admin/service/show/service.show.component.ts
- ui/src/app/views/admin/worker-model-pattern/add/worker-model-pattern.add.component.ts
- ui/src/app/views/admin/worker-model-pattern/edit/worker-model-pattern.edit.component.ts
- ui/src/app/views/admin/worker-model-pattern/list/worker-model-pattern.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate admin module to onpush strategy

- ui/src/app/views/application/add/application.add.component.ts
- ui/src/app/views/application/show/admin/application.admin.component.ts
- ui/src/app/views/application/show/admin/deployment/application.deployment.component.ts
- ui/src/app/views/application/show/admin/repository/application.repo.component.ts
- ui/src/app/views/application/show/application.component.ts
- ui/src/app/views/application/show/home/application.home.component.ts
- ui/src/app/views/application/show/keys/application.keys.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate application module to onPush strategy

- ui/src/app/views/broadcast/details/broadcast.details.component.ts
- ui/src/app/views/broadcast/list/broadcast.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate broadcast module to onpush strategy

- engine/api/workflow/process.go
- engine/api/workflow/repository.go
- engine/repositories/processor.go
- engine/repositories/processor_checkout.go
- go.mod
- go.sum
- sdk/repositories_operation.go
- vendor/github.com/fsamin/go-repo/repo.go
- vendor/modules.txt
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,repositories): use tag with as code workflow

- ui/src/app/shared/workflow/wnode/wnode.component.ts
- ui/src/app/views/workflow/add/workflow.add.component.ts
- ui/src/app/views/workflow/breadcrumb/workflow.breadcrumb.component.ts
- ui/src/app/views/workflow/graph/workflow.graph.component.ts
- ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts
- ui/src/app/views/workflow/run/node/history/history.component.ts
- ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
- ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/variables/job.variables.component.ts
- ui/src/app/views/workflow/run/node/summary/run.summary.component.ts
- ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
- ui/src/app/views/workflow/run/node/test/tests.component.ts
- ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
- ui/src/app/views/workflow/run/summary/workflow.run.summary.component.ts
- ui/src/app/views/workflow/run/summary/workflow.run.summary.html
- ui/src/app/views/workflow/run/workflow.run.component.ts
- ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
- ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts
- ui/src/app/views/workflow/show/notification/list/workflow.notification.list.component.ts
- ui/src/app/views/workflow/show/notification/list/workflow.notification.list.html
- ui/src/app/views/workflow/show/workflow.component.ts
- ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts
- ui/src/app/views/workflow/workflow.component.ts
- ui/src/app/views/workflow/workflow.module.ts
- ui/src/theme.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): add onPush strategy on workflow view

- engine/repositories/processor_push.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(repositories): migrate as code default branch

- ui/src/app/views/home/broadcast/home.broadcast.component.ts
- ui/src/app/views/home/favorite/home.favorite.component.ts
- ui/src/app/views/home/filter/home.filter.component.ts
- ui/src/app/views/home/heatmap/home.heatmap.component.ts
- ui/src/app/views/home/heatmap/toolbar/toolbar.component.ts
- ui/src/app/views/home/home.component.ts
- ui/src/app/views/home/timeline/home.timeline.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate home module to onPush strategy

- cli/cdsctl/admin_hooks.go
- cli/cdsctl/workflow_show.go
- tests/sc_workflow_edit_scheduler.yml
- tests/sc_workflow_git_clone_tag.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): update scheduler test case to filter by workflow id

- engine/api/workflow/execute_outgoing_hook_run.go
- engine/api/workflow/process_node.go
- engine/api/workflow/process_outgoinghook.go
- engine/api/workflow/run_workflow.go
- sdk/uuid.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): outgoinghook as code + parameters

- ui/src/app/shared/workflow/wizard/node-add/node.wizard.component.ts
- ui/src/app/views/navbar/navbar.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refacto(ui): migrate navbar module to onPush strategy

- ui/src/app/views/pipeline/add/pipeline.add.component.ts
- ui/src/app/views/pipeline/show/admin/pipeline.admin.component.ts
- ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.component.ts
- ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts
- ui/src/app/views/pipeline/show/pipeline.show.component.ts
- ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
- ui/src/app/views/pipeline/show/workflow/stage/form/pipeline.stage.form.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate pipeline module to onpush strategy

- contrib/grpcplugins/action/tmpl/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(plugin): bad usage of html/template instead of text for tmpl plugin

- engine/api/workflow/execute_outgoing_hook_run.go
- engine/api/workflow/process_outgoinghook.go
- engine/api/workflow/run_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): outgoing hook parameters

- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display logs

- ui/src/app/views/settings/action/add/action.add.component.ts
- ui/src/app/views/settings/action/edit/action.edit.component.ts
- ui/src/app/views/settings/action/form/action.form.component.ts
- ui/src/app/views/settings/action/help/action.help.component.ts
- ui/src/app/views/settings/action/list/action.list.component.ts
- ui/src/app/views/settings/action/show/action.show.component.ts
- ui/src/app/views/settings/action/usage/action.usage.component.ts
- ui/src/app/views/settings/cdsctl/cdsctl.component.ts
- ui/src/app/views/settings/download/download.component.ts
- ui/src/app/views/settings/group/edit/group.edit.component.ts
- ui/src/app/views/settings/group/list/group.list.component.ts
- ui/src/app/views/settings/queue/queue.component.ts
- ui/src/app/views/settings/settings.component.ts
- ui/src/app/views/settings/user/edit/user.edit.component.ts
- ui/src/app/views/settings/user/list/user.list.component.ts
- ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts
- ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts
- ui/src/app/views/settings/worker-model/form/worker-model.form.component.ts
- ui/src/app/views/settings/worker-model/help/worker-model.help.component.ts
- ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
- ui/src/app/views/settings/workflow-template/add/workflow-template.add.component.ts
- ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts
- ui/src/app/views/settings/workflow-template/editor/workflow-template.editor.component.ts
- ui/src/app/views/settings/workflow-template/form/workflow-template.form.component.ts
- ui/src/app/views/settings/workflow-template/help/workflow-template.help.component.ts
- ui/src/app/views/settings/workflow-template/list/workflow-template.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate settings module to onpush strategy

- ui/src/app/shared/input/autofocus/autofocus.input.component.ts
- ui/src/app/shared/input/autofocus/autofocus.input.html
- ui/src/app/shared/shared.module.ts
- ui/src/app/views/project/list/project.list.component.html
- ui/src/app/views/project/show/application/application.list.html
- ui/src/app/views/project/show/environment/environment.list.html
- ui/src/app/views/project/show/pipeline/pipeline.list.html
- ui/src/app/views/project/show/workflow/workflow.list.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(ui): add autofocus on input search

- engine/api/repositories_manager.go
- engine/api/workflow_import.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): send old workflow to update workflow method

- ui/src/app/views/project/add/project.add.component.ts
- ui/src/app/views/project/list/project.list.component.ts
- ui/src/app/views/project/show/admin/project.admin.component.ts
- ui/src/app/views/project/show/admin/repomanager/list/project.repomanager.list.component.ts
- ui/src/app/views/project/show/application/application.list.component.ts
- ui/src/app/views/project/show/environment/environment.list.component.ts
- ui/src/app/views/project/show/integrations/form/integration.form.component.ts
- ui/src/app/views/project/show/integrations/list/integration.list.component.ts
- ui/src/app/views/project/show/integrations/project.integrations.component.ts
- ui/src/app/views/project/show/keys/project.keys.component.ts
- ui/src/app/views/project/show/permission/permission.component.ts
- ui/src/app/views/project/show/pipeline/pipeline.list.component.ts
- ui/src/app/views/project/show/project.component.ts
- ui/src/app/views/project/show/variable/variable.list.component.ts
- ui/src/app/views/project/show/warnings/warnings.component.ts
- ui/src/app/views/project/show/workflow/blocs/workflow.list.blocs.component.ts
- ui/src/app/views/project/show/workflow/labels/workflow.list.labels.component.ts
- ui/src/app/views/project/show/workflow/lines/workflow.list.lines.component.ts
- ui/src/app/views/project/show/workflow/workflow.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): migrate project module to onpush strategy

- engine/vcs/bitbucketcloud/oauth_consumer.go
1. Description
#4416 
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): add state for bitbucket cloud to authorize redirect (#4416)

- engine/api/workflow/process_start.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): allow running auto a join if parent is failing

- ui/package.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore(ui): go to angular 8.2

- engine/config.go
1. Description
close #4501 
1. About tests
1. Mentions
@ovh/cds
> fix(engine): add configuration generation for bitbucketcloud

- ui/src/app/shared/workflow/wnode/wnode.component.ts
- ui/src/app/shared/workflow/wnode/workflow.node.html
1. Description
close #4502 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): add parent pipeline #4502

- ui/src/app/shared/workflow/node/run/node.run.param.component.ts
- ui/src/app/shared/workflow/node/run/node.run.param.html
1. Description
close #4503 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fix payload autocompletion #4503

- engine/api/workflow/dao.go
- engine/api/workflow/workflow_importer.go
- engine/api/workflow/workflow_parser.go
> fix(api): rename workflow as code & import

- engine/api/stage.go
1. Description
close #4487 
1. About tests
1. Mentions
@ovh/cds
> fix(api): given variable name for pipeline parameters in suggest #4487

- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fix json translations

- ui/src/app/shared/conditions/conditions.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display cds.manual correctly in UI

- ui/src/app/service/project/project.store.ts
- ui/src/app/shared/parameter/value/parameter.value.component.ts
- ui/src/app/shared/variable/value/variable.value.component.ts
- ui/src/app/store/applications.state.spec.ts
- ui/src/app/store/pipelines.state.spec.ts
- ui/src/app/store/project.state.spec.ts
- ui/src/app/store/project.state.ts
- ui/src/app/store/workflow.state.spec.ts
- ui/src/app/views/workflow/add/workflow.add.html
1. Description
close #4519 
close #4520 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): few bugs about project and workflow creation

- ui/src/app/shared/usage/environments/usage.environments.html
- ui/src/app/shared/workflow/wnode/pipeline/node.pipeline.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): change link to environment

- sdk/event.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk): save event integrations id in json

- engine/hatchery/openstack/openstack.go
> fix(hatchery/openstack): 10min max spawn time worker

- engine/api/workflow/process_start.go
before plan a wf migration for whole existing workflows on a cds instance
> fix(api): default behaviour on join

- sdk/exportentities/pipeline.go
- sdk/exportentities/pipeline_test.go
> fix(api): import / export os-architecture

- engine/api/project_integration_test.go
- engine/api/workflow/dao.go
- engine/api/workflow/dao_test.go
- engine/api/workflow/hook.go
- engine/api/workflow/process_node_test.go
- engine/api/workflow/workflow_parser.go
- engine/api/workflow/workflow_parser_test.go
- engine/api/workflow_ascode.go
- engine/api/workflow_ascode_test.go
- engine/api/workflow_test.go
> fix(api): init wf without repowebhook on existing workflow

- engine/api/environment.go
- engine/sql/174_fix_environment_name.sql
- ui/src/app/views/environment/show/advanced/environment.advanced.html
- Display err on ui
- Existing environment with '/' are not reachable, we replace / by _ on them.
> fix(api,ui): environment with wrong character

- engine/api/workflow_import.go
- ui/src/app/views/workflow/show/workflow.component.ts
- ui/src/app/views/workflow/show/workflow.html
> fix(api,ui): prevent user to edit yml and save if ascode

- ui/src/app/app.service.ts
> fix(ui): update node run if needed

- sdk/messages.go
> feat(api): icon on spawn info

- go.mod
- vendor/modules.txt
> chore(sdk): fix izanami dep sha1

- contrib/helm/cds/templates/ui-deployment.yaml
- docker-compose.yml
- docs/content/hosting/ready-to-run/from-binaries.md
- ui/Caddyfile
> chore(hooks): add hooks proxy-pass on ui

- sdk/hook.go
> fix(api): eventFilter configurable

- engine/worker/builtin_artifact_download.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): bad regex inside artifact download doesn't panic

- engine/hooks/kafka.go
- engine/hooks/rabbitmq.go
this will avoid to delete unprocessed tasks on func deleteTaskExecutionsRoutine
> fix(hooks): init kafka / rabbitmq task

- docs/content/docs/concepts/permissions.md
- docs/content/docs/concepts/pipeline.md
- docs/content/docs/concepts/project.md
- docs/content/docs/concepts/variables.md
- docs/content/docs/concepts/workflow/_index.md
- docs/content/docs/concepts/workflow/hooks/git-repo-poller.md
- docs/content/docs/concepts/workflow/hooks/git-repo-webhook.md
- docs/content/docs/concepts/workflow/hooks/kafka-hook.md
- docs/content/docs/concepts/workflow/payload.md
1. Description
1. About tests
1. Mentions
@ovh/cds
> Documentation improvements

- sdk/exportentities/workflow.go
- sdk/exportentities/workflow_test.go
> fix(api): mutex as-code

- ui/src/app/views/workflow/show/admin/workflow.admin.component.html
- ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
- ui/src/app/views/workflow/show/admin/workflow.admin.scss
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
1. Description
close #4568 
1. About tests
1. Mentions
@ovh/cds
> feat(ui): reorder tag #4568

- engine/api/workflow/dao.go
- engine/sql/175_resynchooks.sql
- engine/sql/176_remove_old_model.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sql): resync hook without ID + remove old workflow tables

- engine/vcs/bitbucketcloud/client_repos.go
- engine/vcs/bitbucketcloud/client_user.go
- engine/vcs/bitbucketcloud/types.go
- engine/vcs/types.go
1. Description
close #4581 
1. About tests
1. Mentions
@ovh/cds
> feat(vcs): add team repository support for bitbucketcloud #4581

- engine/api/workflow/process_outgoinghook.go
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.html
- ui/src/app/shared/workflow/wnode/hook/hook.html
- ui/src/app/store/workflow.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(ui): enable all nodes

- ui/src/app/views/home/broadcast/home.broadcast.component.ts
- ui/src/app/views/home/home.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): mark as read on home for broadcasts

- engine/api/workflowtemplate/execute.go
- tests/fixtures/template/simple/workflow/First-pipeline.pip.yml
- ui/src/app/store/project.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): preserve comments in template's generated files

- engine/api/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): update icon do not need to load all workflow

- tools/debpacker/debpacker_test.go
- tools/debpacker/writer_test.go
> fix(tools/debpacker): fix unit-test

- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow/process_node.go
- engine/api/workflow/process_parameters.go
- engine/api/workflow/process_requirements.go
- engine/api/workflow/run_workflow_test.go
- engine/hatchery/local/local.go
- engine/sql/177_project_integration_cascade.sql
- sdk/error.go
- sdk/hatchery/hatchery.go
- tests/clictl_admin_plugin_and_integrations.yml
- tests/fixtures/plugins/hello-it-plugin-binary.yml
and add a check on network requirement
> fix(api): context for further stages

- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow/execute_node_job_run_log.go
> fix(api): concat logs

- cli/cdsctl/monitoring.go
> fix(cdsctl): remove counter wmodel / queue count

- ui/src/app/app.service.ts
- ui/src/app/service/navbar/navbar.service.ts
- ui/src/app/views/navbar/navbar.component.ts
> fix(ui): refresh search

- cli/cdsctl/encrypt.go
- docs/content/docs/concepts/requirement/requirement_service.md
1. Description
1. About tests
1. Mentions
@ovh/cds
> doc: fix typo

- sdk/cdsclient/client_queue.go
- sdk/cdsclient/client_workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk): wait before retry on temp URL

- engine/api/status.go
- engine/service/metrics.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): expose mem stats as metrics

- engine/api/api.go
- engine/service/metrics.go
- go.mod
- sdk/signal_darwin.go
- sdk/signal_linux.go
- sdk/signal_windows.go
1. Description
set CDS_MAX_HEAP_SIZE in bytes
1. About tests
1. Mentions
@ovh/cds
> feat(api): dump heap profile

- engine/api/router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): force context cancellation

- contrib/integrations/kubernetes/kubernetes.yml
- contrib/integrations/kubernetes/plugin-kubernetes/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(contrib): fix kubernetes integration

- engine/api/router_permission.go
- sdk/user.go
- sdk/user_easyjson.go
> fix(api): clone perm

- README.md
Hello 👋 
Just a little PR to add an anchor (for the stages link in the Readme).
Keep the good work 👍
> docs(readme): edit link of stages to direct anchor

- engine/api/router.go
> fix(api): avoid potential leak on muxcontext

- engine/vcs/bitbucketserver/types.go
> fix(vcs): author stored in cache

- engine/api/repositoriesmanager/events.go
- engine/api/workflow/dao_notification.go
- engine/api/workflow/workflow_run_event.go
- engine/vcs/bitbucketserver/client_pull_request.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): send all pr comment for each nodes

- engine/api/cache/cache.go
- engine/api/cache/redis.go
- engine/hooks/branch_deletion.go
- engine/hooks/dao.go
- engine/hooks/tasks_test.go
- engine/hooks/test.go
- engine/hooks/webhook.go
1. Description
close #4553 
1. About tests
1. Mentions
@ovh/cds
> fix(hooks): delete the branch deletion when this branch is pushed again #4553

- engine/api/repositoriesmanager/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): fix vcs event on master for now

- engine/api/workflow/workflow_run_event.go
- ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts
- ui/src/app/views/workflow/show/notification/form/workflow.notifications.form.html
- ui/src/app/views/workflow/show/notification/form/workflow.notifications.form.scss
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
1. Description
close #4635 
1. About tests
1. Mentions
@ovh/cds
> feat(api): add option always send vcs notification #4635

- engine/api/router.go
> refactor(api): muxcontext is not used

- ui/src/app/views/workflow/run/node/test/tests.component.ts
> fix(ui): refresh junit results

- ui/src/app/app.service.ts
- ui/src/app/service/navbar/navbar.service.ts
- ui/src/app/service/project/project.store.ts
- ui/src/app/store/project.state.ts
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/admin/broadcast/add/broadcast.add.component.ts
- ui/src/app/views/admin/broadcast/edit/broadcast.edit.component.ts
- ui/src/app/views/favorite/favorite.component.ts
- ui/src/app/views/home/home.component.ts
- ui/src/app/views/navbar/navbar.component.ts
And use subscription instead of hard cleanCache on navbar
> fix(ui): load recents prj from localStorage

- ui/src/app/app.component.ts
- ui/src/assets/worker/web/version.js
1. Description
Temporary fix for version webworker.
TODO:  use angular proxy on branch . refactor/authentification.
1. About tests
1. Mentions
@ovh/cds
> fix(ui): get version worker

- ui/proxy.conf.json
- ui/src/app/app.component.ts
- ui/src/assets/worker/web/version.js
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): get version must use angular proxy

- .golangci.yml
- engine/api/workflow/dao_run_test.go
- engine/api/workflow/process_node.go
- engine/api/workflow/process_node_test.go
1. Description
#4201
1. About tests
1. Mentions
@ovh/cds
> fix(api): git info are not valid when running a fork

- engine/api/workflow_test.go
> fix(api): fix delete worfklow unittest

- sdk/action.go
- sdk/workflow.go
- sdk/workflow_hook.go
- sdk/workflow_template.go
> fix(api): avoid scan nil

- engine/api/workflow/dao_data_hook.go
- sdk/workflow_conditions.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load only one node hook by its uuid

- engine/api/api.go
- engine/api/artifact.go
- engine/api/artifact_test.go
- engine/api/cache.go
- engine/api/objectstore/awss3.go
- engine/api/objectstore/fs.go
- engine/api/objectstore/objectstore.go
- engine/api/objectstore/ssh.go
- engine/api/objectstore/swift.go
- engine/api/purge/purge.go
- engine/api/purge/purge_test.go
- engine/api/workflow_queue_storage.go
- engine/api/workflow_queue_test.go
- engine/api/workflow_run.go
> fix(api): purge artifacts data

- engine/worker/builtin_gitclone.go
- engine/worker/builtin_gitclone_test.go
> fix(worker): compute cds.semver with tag 1.6.2-1

- ui/src/app/shared/action/action.html
- ui/src/app/shared/requirements/form/requirements.form.component.ts
- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
> fix(ui): refresh tag in sidebar

- docker-compose.yml
- docs/content/docs/components/hatchery/local.md
- engine/Dockerfile
- engine/hatchery/local/local.go
- engine/hatchery/local/types.go
- engine/worker/cmd_update.go
- sdk/download.go
> feat(hatchery/local): download worker from CDS API

- engine/api/workflow/execute_node_run.go
> fix(api): possible panic on refNode/Context nil

- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): delete old workflow data tables

- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
> fix(ui): display default tags

- engine/hatchery/openstack/openstack.go
> feat(hatchery/openstack): delete vm not created

- engine/hooks/webhook.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hooks): do not split empty event filter

- engine/api/workflow/dao.go
- engine/vcs/github/client_hook.go
- engine/vcs/github/client_repos.go
- engine/vcs/github/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): github update hook uses patch method

- ui/src/app/shared/requirements/list/requirements.list.html
> fix(ui): display requirements opt for read access

- engine/hatchery/swarm/swarm_util_kill.go
> fix(hatchery/swarm): remove volume

- engine/api/environment.go
- engine/api/environment_test.go
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
> fix(api): clone env with type password

- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
- ui/src/app/store/workflow.action.ts
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/workflow/workflow.component.ts
> fix(ui): sidebar refresh

- engine/api/pipeline/pipeline_importer.go
- engine/api/pipeline/pipeline_importer_test.go
- engine/api/pipeline_job.go
- engine/api/pipeline_job_test.go
- engine/api/workflow_import_test.go
- sdk/common.go
> feat(api): stage name could not be empty

- sdk/error.go
- sdk/worker_model.go
> fix(api): avoid worker model name with space

- cli/cdsctl/application.go
- cli/cdsctl/environment.go
- cli/cdsctl/pipeline.go
- cli/cdsctl/workflow_export.go
- cli/cdsctl/workflow_import.go
- engine/api/application_import.go
- engine/api/environment_import.go
- engine/api/pipeline_import.go
- engine/api/workflow_import.go
- sdk/cdsclient/client_import.go
> fix(cdsctl,api): return msg error wf import

- engine/hatchery/swarm/swarm_util_kill.go
> fix(hatchery/swarm): remove volume only

- engine/api/workflow/execute_node_run.go
- engine/sql/178_clean_db.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): fix stop workflow run + clean db

- ui/src/app/app.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fix loosing event

- engine/hooks/github.go
- engine/hooks/webhook.go
1. Description
1. About tests
1. Mentions
cc @jleveugle @antleblanc 
@ovh/cds
> fix(hooks): delete branch on gitlab/github

- engine/api/workflow/dao.go
- engine/api/workflow/process_node.go
- engine/api/workflow/process_start.go
- engine/api/workflow/repository.go
- engine/api/workflow/run_workflow.go
- engine/api/workflow_run_test.go
- engine/hooks/outgoing_hooks.go
and various fixes on some log
close #4715
> fix(api): run wf with mutex, from a hook

- ui/src/app/shared/table/data-table.html
- ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts
- ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
- ui/src/app/views/workflow/run/node/test/table/test.table.html
- ui/src/styles.scss
> fix(ui): unit tests display

- ui/src/app/views/workflow/graph/workflow.graph.component.ts
- ui/src/app/views/workflow/run/summary/workflow.run.summary.component.ts
- ui/src/app/views/workflow/run/summary/workflow.run.summary.html
- ui/src/app/views/workflow/run/workflow.run.component.ts
- ui/src/app/views/workflow/run/workflow.run.html
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(ui): avoid refreshing workflow for nothing

- engine/api/workflow/process_node.go
- engine/api/workflow/process_outgoinghook.go
- engine/api/workflow/run_workflow.go
- engine/api/workflow_run_test.go
> fix(api): mutex & conditions on manual run

- engine/api/pipeline/pipeline_stage.go
- engine/api/pipeline_stage_test.go
- ui/src/app/shared/conditions/conditions.component.ts
- ui/src/app/shared/conditions/conditions.html
- ui/src/app/shared/select/select.component.ts
- ui/src/app/shared/select/select.filter.html
- ui/src/app/shared/shared.module.ts
- ui/src/app/shared/workflow/node/run/node.run.param.html
- ui/src/app/shared/workflow/wizard/conditions/wizard.conditions.component.ts
- ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
- ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
- ui/src/app/views/workflow/show/notification/form/workflow.notifications.form.html
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
- ui/src/styles.scss
> fix(ui): stage conditions update

- contrib/grpcplugins/action/venom/main.go
- ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
- ui/src/app/views/workflow/show/workflow.component.ts
close #4700
and various ui fixes
> fix(plugin/venom): files with coma

- ui/src/app/views/workflow/run/node/test/tests.component.ts
- ui/src/app/views/workflow/run/node/test/tests.result.html
> fix(ui): coverage title nan

- cli/cdsctl/main.go
- cli/cdsctl/user.go
FYI this will break integration tests, i will fix after the merge
> feat(cli): testability of user confirm command

- engine/api/repositories_manager.go
- ui/src/app/app.component.ts
- ui/src/assets/worker/web/version.js
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,ui): load integration + fix base url

- engine/hooks/type_github.go
1. Description
close #4733
1. About tests
1. Mentions
cc @jleveugle 
@ovh/cds
> fix(hooks): Createdat can be int or time.Time

- engine/vcs/bitbucketcloud/client_status.go
- engine/vcs/bitbucketserver/client_status.go
- engine/vcs/gerrit/client_status.go
> fix(vcs): skipped pipeline status

- engine/api/pipeline/audit.go
- engine/api/workflow/audit.go
> fix(api): purge audit pipeline/workflow

- contrib/integrations/arsenal/plugin-arsenal/main.go
> fix(plugin): increase timeout

- docker-compose.yml
- docs/content/development/contribute/development.md
- docs/content/hosting/ready-to-run/docker-compose.md
- docs/content/hosting/ready-to-run/from-binaries.md
- engine/Dockerfile
- engine/ui/ui_router.go
> chore: dockerfile engine ui

- sdk/cdsclient/http.go
> fix(sdk): check add header

- cli/cdsctl/workflow_run.go
1. Description
close #4753 
1. About tests
1. Mentions
@ovh/cds
> fix(cdsctl): workflow run only send git.branch when needed #4753

- engine/api/workflow/dao_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> test(api): fix TestUpdateWorkflowWithJoins

- go.mod
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/forward_requirements.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require.go.tmpl
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- vendor/github.com/stretchr/testify/require/requirements.go
- vendor/modules.txt
1. Description
1. About tests
1. Mentions
@ovh/cds
> test(api): fix dependencies

- engine/api/workermodel/registration.go
- engine/hatchery/marathon/marathon.go
- engine/hatchery/swarm/swarm.go
- engine/hatchery/swarm/swarm_test.go
- engine/hatchery/swarm/swarm_util_create_test.go
- engine/hatchery/swarm/swarm_util_get.go
- engine/hatchery/swarm/swarm_util_get_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> test: add unit test on swarm hatchery

- cli/cdsctl/workflow_run.go
if triggered from a directory that is not a directory
> fix(cdsctl): workflow run command failure

- sdk/exportentities/workflow.go
- sdk/exportentities/workflow_test.go
1. Description
close #4751 
1. About tests
1. Mentions
@ovh/cds
> fix(api): display hook's conditions in as code

- engine/api/workflow/dao_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> test(api): fix TestUpdateSimpleWorkflowWithApplication

- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): delete node trigger before all nodes

- engine/sql/tests.sh
1. Description
1. About tests
1. Mentions
@ovh/cds
> test(sql): check missing primary keys

- tools/debpacker/debpacker.go
- tools/debpacker/main.go
- tools/debpacker/writer.go
- tools/debpacker/writer_test.go
> feat(tools/debpacker): variables interpolation, extracts files

- .debpacker.yml
- .gitignore
- Makefile
- engine/Makefile
- engine/worker/Makefile
- ui/Makefile
> chore: ui makefile, global makefile, add ui.tar.gz in debian package

- engine/ui/ui.go
- engine/ui/ui_router.go
- go.sum
1. Description
Related to https://github.com/golang/go/issues/28168
1. About tests
1. Mentions
@ovh/cds
> fix(engine): force host to update for reverse proxy

- ui/src/app/model/pipeline.model.ts
- ui/src/app/views/workflow/run/workflow.run.component.ts
- ui/src/app/views/workflow/run/workflow.run.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display workflow error message correctly

- engine/api/pipeline_import_test.go
- sdk/exportentities/pipeline.go
- sdk/exportentities/pipeline_test.go
- ui/src/app/shared/duration/duration.service.ts
- ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
- ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk,ui): export pipeline with only 1 stage + duration on ui

- engine/main.go
example:
./engine config edit ~/.cds/dev.toml log.level=error hatchery.swarm.commonConfiguration.name=hatchery-swarm-name > new.file.toml
> feat(engine): engine config edit command

- engine/main.go
> fix(engine): uncomment key if edit

- engine/main.go
> fix(engine): no float on configuration file

- contrib/grpcplugins/action/examples/nodejs/package-lock.json
- contrib/grpcplugins/action/examples/nodejs/package.json
- go.sum
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(contrib): delete the vulnerability in our dependencies

- Makefile
- cli/cdsctl/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdsctl): makefiles

- engine/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(engine): add output flag to config edit cmd

- CONTRIBUTING.md
> docs: ensure dco

- ui/src/app/shared/permission/form/permission.form.html
- ui/src/app/shared/permission/list/permission.list.html
- ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): translation about permission and size changes

- ui/src/app/shared/workflow/node/run/node.run.param.html
1. Description
close #4806 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): not allow to resynchronize pipeline on as code workflow #4806

- contrib/grpcplugins/action/Makefile
- contrib/integrations/arsenal/plugin-arsenal/Makefile
- contrib/integrations/kubernetes/plugin-kubernetes/Makefile
- engine/worker/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore(worker): build with CGO_ENABLED=0

- ui/src/app/views/workflow/graph/workflow.graph.component.ts
- ui/src/app/views/workflow/run/workflow.run.component.ts
- ui/src/app/views/workflow/run/workflow.run.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): refresh workflow view when launching new workflow run

- engine/api/workflow_test.go
> test(api): fix panic in Test_deleteWorkflowHandler

- engine/api/workflow/process_outgoinghook.go
- engine/hooks/outgoing_hooks.go
1. Description
close #4815 
1. About tests
1. Mentions
@ovh/cds
> fix(api): interpolate outgoing hook payload properly #4815

- Makefile
> chore: generate FILES by Makefile

- engine/worker/builtin_checkout_application.go
- engine/worker/builtin_gitclone.go
- sdk/vcs/git/git_clone.go
- sdk/vcs/git/git_clone_test.go
- sdk/vcs/git/git_info.go
> fix(worker): force compute git.describe on checkoutApplication

- cli/cdsctl/configstore.go
> chore(cdsctl): build arm/arm64

- engine/worker/Makefile
> chore(worker): no clean before build

- engine/api/migrate/migration.go
- engine/api/migrate/refactor_authentication_auth.go
- engine/api/migrate/refactor_authentication_user.go
- engine/api/user/dao.go
- engine/api/user/dao_deprecated.go
- engine/cmd_start.go
- engine/migrateservice/service.go
- engine/service/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(migrate,api): bad interface impl for mig service and fix user mig

- README.md
- docs/content/_index.html
- docs/content/about/matrix.md
1. Description
Noticed some grammatical mistakes on the website whilst browsing the product. The linter has also picked up extra whitespace at the end of some sentences, resulting in a slightly larger diff.
N/A
1. About tests
N/A
1. Mentions
N/A
@ovh/cds
> Public website spelling fixes

- cli/cdsctl/config.go
- cli/cdsctl/login.go
- cli/cdsctl/main.go
> fix(cdsctl): env token usage

- cli/cdsctl/internal/keychain.go
> chore(cdsctl): let ppc64

- engine/api/workflow_trigger.go
- ui/src/app/shared/workflow/wizard/conditions/wizard.conditions.component.ts
1. Description
close #4846 
1. About tests
1. Mentions
@ovh/cds
> fix(ui,api): do not load condition names when it's not needed #4846

- docker-compose.yml
- docs/content/development/contribute/development.md
- engine/api/api_test.go
- engine/api/authentication/local/driver_test.go
- engine/api/migrate/refactor_authentication_auth_test.go
- tests/.gitignore
- tests/01_signup.yml
- tests/02_smoke_test_services.yml
- tests/Makefile
- tests/test.sh
- ui/README.md
- ui/angular.json
- ui/e2e/config/index.ts
- ui/proxy.conf.json
> chore(docker-compose): make test-docker-compose

- engine/vcs/gerrit/gerrit.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): fix gerrit link

- engine/hooks/gerrit.go
- engine/hooks/tasks.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hooks): avoid to send same gerrit event twice or more

- engine/api/workflow/dao_data_hook.go
- engine/hooks/gerrit.go
- engine/hooks/hooks_handlers.go
- engine/hooks/tasks.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> Merge fix 1

- engine/api/authentication/local/dao_registration.go
- engine/api/authentication/local/driver.go
- engine/api/migrate/refactor_authentication_user.go
- engine/api/user/dao.go
- engine/api/workflow/dao_node_run_job.go
- engine/sql/180_user.sql
- sdk/user.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> Fix user migration

- engine/api/workflow/dao_node_run_job.go
- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow/heartbeat.go
- engine/api/workflow/init.go
- engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): stop workflow

- engine/worker/internal/action/builtin_coverage.go
- engine/worker/internal/action/builtin_coverage_test.go
- engine/worker/internal/action/builtin_gitclone_test.go
- engine/worker/internal/action/builtin_junit.go
- engine/worker/internal/action/builtin_junit_test.go
- engine/worker/internal/action/builtin_script.go
- engine/worker/internal/action/builtin_script_test.go
- engine/worker/internal/run.go
- tests/fixtures/ITSCWRKFLW6/clone.pip.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> Fix worker windows

- engine/hatchery/local/local.go
- engine/worker/internal/logger.go
- engine/worker/internal/take.go
- tools/smtpmock/.gitignore
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): stop the worker

- ui/src/app/shared/table/data-table.html
- ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): datatable button display correctly

- cli/cdsctl/project.go
- engine/api/ascode_test.go
- engine/api/router_middleware_auth_permission.go
- engine/hatchery/marathon/helper_test.go
- engine/hatchery/marathon/marathon.go
- engine/hatchery/marathon/marathon_test.go
- engine/hatchery/marathon/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): return not found if project not readable, marathon cpu in conf

- engine/worker/cmd_upload.go
- engine/worker/internal/action/builtin_artifact_upload.go
- engine/worker/internal/action/builtin_coverage.go
- engine/worker/internal/action/builtin_junit.go
- engine/worker/internal/handler_upload.go
- sdk/cache.go
- sdk/common.go
- sdk/common_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): path.IsAbs is not working on windows

- engine/worker/internal/run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): overwrite value each time

- engine/api/workflow/dao_node_run_job.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow/heartbeat.go
- tests/fixtures/04SCWorkflowRunWorkerCmd/pipeline.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): remove only dead job

- engine/api/templates.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing members on group for template perm check

- engine/hatchery/kubernetes/kubernetes.go
- engine/hatchery/local/local.go
- engine/hatchery/marathon/marathon.go
- engine/hatchery/openstack/openstack.go
- engine/hatchery/swarm/swarm.go
- engine/hatchery/vsphere/vsphere.go
> fix(hatchery): check hostname prerequisite

- engine/worker/internal/action/builtin_artifact_download.go
- engine/worker/internal/action/builtin_artifact_download_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): download artifact outside of workspace

- engine/worker/internal/action/builtin_artifact_upload_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> test(worker): unit tests artifact upload

- engine/api/migrate/migration.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): take care of not executed for migration status

- engine/api/api_helper.go
- engine/api/cache.go
- engine/api/navbar/navbar.go
- engine/api/router_middleware_auth.go
- engine/api/router_middleware_auth_permission.go
- engine/api/services.go
- engine/api/services_test.go
- engine/api/ui.go
- engine/api/worker.go
- engine/api/worker_model.go
- engine/api/worker_model_hatchery.go
- engine/api/workflow/dao_hook_model.go
- engine/api/workflow_hook.go
- engine/api/workflow_queue.go
- engine/api/workflow_queue_storage.go
- engine/api/workflow_run.go
- sdk/token.go
- sdk/user.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): use consumer name instead of username if service or worker

- engine/api/action.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load members on group to import action

- engine/worker/internal/action/builtin_artifact_download_test.go
- engine/worker/internal/action/builtin_artifact_upload_test.go
- engine/worker/internal/action/builtin_checkout_application_test.go
- engine/worker/internal/action/builtin_coverage_test.go
- engine/worker/internal/action/builtin_gitclone.go
- engine/worker/internal/action/builtin_gitclone_test.go
- engine/worker/internal/action/builtin_junit_test.go
- engine/worker/internal/action/builtin_key_install.go
- engine/worker/internal/action/builtin_key_install_test.go
- engine/worker/internal/action/builtin_release_test.go
- engine/worker/internal/action/builtin_script_test.go
- engine/worker/internal/action/test_helper.go
- engine/worker/internal/action/vcs_strategy.go
- engine/worker/internal/handler_key.go
- engine/worker/internal/handler_key_test.go
- engine/worker/internal/keys.go
- engine/worker/internal/keys_test.go
- engine/worker/internal/logger.go
- engine/worker/internal/types.go
- engine/worker/pkg/workerruntime/types.go
- tests/04_sc_workflow_run_worker_cmd.yml
- tests/fixtures/04SCWorkflowRunWorkerCmd/pipeline.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): cmd key install with absolute file

- engine/api/api.go
- engine/ui/ui.go
- engine/vcs/types.go
- ui/src/app/app.component.ts
> fix(ui): display refresh banner on new ui deployed

- ui/Makefile
> chore(ui): do not write cds_version on ngbuild

- engine/api/project.go
- engine/api/project_test.go
- sdk/cdsclient/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): get projects from provider with username

- engine/api/services.go
- sdk/services.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): register service check if already exists based on consumer

- ui/src/app/model/pipeline.model.ts
- ui/src/app/shared/table/data-table.component.ts
- ui/src/app/shared/table/data-table.html
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/workflow/run/node/test/table/test.table.component.ts
- ui/src/app/views/workflow/run/node/test/table/test.table.html
- ui/src/app/views/workflow/run/node/test/tests.component.ts
- ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fix displayed data + toggle button

- engine/hooks/outgoing_hooks.go
> fix(api): outgoing webhook

- engine/api/project_integration.go
- engine/worker/internal/action/builtin_artifact_download.go
- engine/worker/internal/action/builtin_artifact_upload.go
- sdk/cdsclient/client_queue.go
it should not erase password it not set
> fix(api): edit project integration

- engine/api/user_schema.go
- ui/resources/cds-hint.js
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): get line using builtin function

- contrib/workflow-templates/demo-workflow-hello-world/1.pipeline.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(contrib): add a step to hello world template

- cli/cdsctl/template.go
- engine/api/workflow/process_parameters.go
- engine/api/workflow_run.go
- tests/04_sc_workflow_template_run.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): add cds.template.version var for current template version

- ui/src/app/views/settings/worker-model/form/worker-model.form.component.ts
- ui/src/app/views/settings/worker-model/form/worker-model.form.html
1. Description
close #4816 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): cannot add a worker model without required info #4816

- contrib/grpcplugins/action/kafka-publish/go.sum
- contrib/grpcplugins/action/kafka-publish/kafkapublisher/chunks.go
- engine/api/test/test.go
- engine/worker/cmd_key.go
- sdk/doc/generate.go
- sdk/hatchery/types.go
> chore(engine): remove some deprecated attributes

- ui/src/app/shared/parameter/value/parameter.value.html
1. Description
close #4935 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): edit custom action with key parameter display input correctly

- engine/api/application.go
- engine/api/application/dao.go
- engine/api/application_test.go
- engine/api/ascode.go
- engine/api/pipeline.go
- ui/src/app/service/application/application.service.ts
- ui/src/app/views/pipeline/show/pipeline.show.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: can have pultiple application as code on the same repository

- engine/api/group/workflow_group.go
- engine/api/workflow_group.go
1. Description
close #4918
1. About tests
1. Mentions
@ovh/cds
> fix(api): return right error on add workflow group

- sdk/exportentities/workflow_tar.go
- ui/src/app/service/ascode/ascode.service.ts
- ui/src/app/shared/ascode/events/ascode.event.component.ts
- ui/src/app/shared/ascode/events/ascode.event.html
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/pipeline/show/pipeline.show.html
- ui/src/app/views/workflow/workflow.component.ts
- ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: do not insert an empty workflow if there is no one

- engine/api/permission/permission.go
- engine/api/test/assets/assets.go
- engine/api/timeline.go
- engine/api/timeline_test.go
- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor(api): permissions for timeline events endpoint

- ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): check if application exist on workflow component

- engine/api/pipeline/audit.go
- engine/api/pipeline/pipeline_parser.go
- ui/src/app/shared/diff/diff.ts
- ui/src/app/shared/workflow-template/apply-form/workflow-template.apply-form.html
- ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,ui): audit on pipeline with template is now correct

- engine/api/events.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): sends all events to hatcheries only if wildcard even if maintainer

- sdk/cdsclient/client_workflow_as_code.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cli): add missing query parameter

- engine/api/workflow/dao.go
- sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): duplication of same node name is now forbidden

- engine/api/workflow/process_node.go
- engine/api/workflow_run_test.go
- engine/hooks/outgoing_hooks.go
- engine/hooks/tasks_test.go
- engine/hooks/webhook.go
1. Description
close #4948 
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not duplicate payload in build params for hooks

- ui/src/app/app.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): navbar hide only for route that starts by /auth

- sdk/exportentities/workflow.go
- sdk/exportentities/workflow_test.go
- tests/fixtures/ITSCWRKFLW6/ITSCWRKFLW6.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: use specific struct for ascode conditions

- engine/api/workflow/process_node.go
> fix(api): inconsistent git.hash

- docker-compose.yml
- docs/content/hosting/ready-to-run/docker-compose.md
> docs: review docker-compose tutorial

- engine/api/worker.go
> fix(api): avoid create worker consumer if the registration failed

- ui/src/app/shared/workflow-template/apply-form/workflow-template.apply-form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): allow to apply template even if latest version already applied

- engine/api/workflow/audit.go
> fix(api): workflow deletion audits do not work

- engine/api/migrate/refactor_group.go
> fix(api): migrate project_group for signature

- engine/api/authentication/dao_session.go
- engine/api/authentication/dao_session_test.go
- engine/api/authentication/session.go
> fix(api): delete corrupted sessions

- ui/src/app/views/project/show/project.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: display menu

- engine/api/notification/permission.go
> fix(api): filter default group on notif

- ui/src/app/views/broadcast/list/broadcast.list.component.ts
- ui/src/app/views/home/home.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): list of broadcast was not render

- engine/hooks/gerrit.go
- ui/src/app/model/workflow.hook.model.ts
- ui/src/app/shared/workflow/node/hook/details/hook.details.component.html
- ui/src/app/shared/workflow/node/hook/details/hook.details.component.scss
- ui/src/app/shared/workflow/node/hook/details/hook.details.component.ts
- ui/src/app/store/workflow.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hooks,ui): display payload from gerrit + fix hook edit

- engine/api/notification/permission_test.go
> fix(api): ut for usernames selected to send notifications

- ui/src/assets/worker/common.js
1. Description
Quick with before websocket
1. About tests
1. Mentions
@ovh/cds
> fix(ui): remove fibonacci retry to not trigger interval each second

- engine/api/workflow/workflow_run_event.go
- engine/vcs/gerrit/client_status.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: do not try to set status if gerrit event does not contain change id

- cli/cdsctl/config.go
> fix(cdsctl): avoid panic

- engine/api/workflow_import.go
- engine/vcs/bitbucketcloud/client_branch.go
- engine/vcs/bitbucketcloud/client_commit.go
- engine/vcs/bitbucketcloud/client_forks.go
- engine/vcs/bitbucketcloud/client_hook.go
- engine/vcs/bitbucketcloud/client_pull_request.go
- engine/vcs/bitbucketcloud/client_repos.go
- engine/vcs/bitbucketserver/client_branch.go
- engine/vcs/bitbucketserver/client_commit.go
- engine/vcs/bitbucketserver/client_forks.go
- engine/vcs/bitbucketserver/client_pull_request.go
- engine/vcs/bitbucketserver/client_repos.go
- engine/vcs/bitbucketserver/client_status.go
- engine/vcs/bitbucketserver/client_tags.go
- engine/vcs/github/client_branch.go
- engine/vcs/github/client_commit.go
- engine/vcs/github/client_forks.go
- engine/vcs/github/client_hook.go
- engine/vcs/github/client_pull_request.go
- engine/vcs/github/client_repos.go
- engine/vcs/github/client_tag.go
- engine/vcs/gitlab/client_forks.go
- engine/vcs/gitlab/client_repos.go
- sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): get commit status for bitbucket, missing pagination params

- ui/src/app/model/keys.model.ts
- ui/src/app/service/keys/keys.service.ts
- ui/src/app/shared/vcs/vcs.strategy.component.ts
> fix(ui): vcs strategy component

- sdk/cdsclient/client_workflow.go
> fix(sdk): dont try to run workflow from hook if the hook doesn't exist

- engine/api/workflow/node_run.go
- engine/api/workflow/node_run_test.go
- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): list artifact when restart failed jobs

- engine/api/action.go
- engine/api/action/usage.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): filter action usage in pipeline

- cli/cdsctl/application.go
- cli/cdsctl/pipeline.go
- engine/api/pipeline.go
- sdk/cdsclient/client_pipeline.go
- sdk/cdsclient/interface.go
- sdk/cdsclient/mock_cdsclient/interface_mock.go
added :
- cdsctl pipeline usage
- cdsctl application usage
- sdk interface for pipeline get
- RequestModifiers for pipeline usages
changed :
- sdk pipeline get
1. Description
1. About tests
1. Mentions
@ovh/cds
> Add pipeline and application usage in cli

- docker-compose.yml
- docs/content/docs/integrations/github/github_repository_manager.md
- docs/content/hosting/ready-to-run/docker-compose.md
> docs(docker-compose): add socat in docker-compose

- engine/api/workflow/execute_node_run.go
> fix(api): add some logs on random 401

- sdk/action/coverage.go
> docs(builtin/cobertura): fix example

- engine/api/bookmark_test.go
- engine/api/objectstore/fs.go
- engine/api/router_middleware_auth_permission_test.go
- engine/api/test/assets/assets.go
- engine/api/user_bookmark.go
- engine/api/workflow.go
- engine/api/workflow/dao.go
- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow/run_workflow_test.go
- engine/api/workflow_queue.go
- engine/api/workflow_queue_test.go
- engine/api/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): return workflow favorite flag

- ui/src/app/app.service.ts
- ui/src/app/service/application/application.resolver.ts
- ui/src/app/shared/workflow/node/run/node.run.param.component.ts
- ui/src/app/shared/workflow/wizard/context/wizard.context.component.ts
- ui/src/app/shared/workflow/wizard/node-add/node.wizard.component.ts
- ui/src/app/store/applications.action.ts
- ui/src/app/store/applications.state.spec.ts
- ui/src/app/store/applications.state.ts
- ui/src/app/views/application/add/application.add.component.ts
- ui/src/app/views/application/show/application.component.spec.ts
- ui/src/app/views/application/show/application.component.ts
- ui/src/app/views/application/show/home/application.home.component.ts
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> refactor: application state

- engine/api/workflow/node_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): bad condition to download artifact of re-runned pipeline

- contrib/helm/cds/README.md
- contrib/worker-models/README.md
- contrib/worker-models/go-official-1.13.yml
- contrib/worker-models/maven3-jdk10-official.yml
- contrib/worker-models/maven3-jdk9-official.yml
- contrib/worker-models/python-official-2.7.15-stretch.yml
- contrib/worker-models/python-official-3.4.9-stretch.yml
- contrib/worker-models/python-official-3.5.6-stretch.yml
- contrib/worker-models/python-official-3.6.5-jessie.yml
- contrib/worker-models/python-official-3.6.7-stretch.yml
- contrib/worker-models/python-official-3.7.1-stretch.yml
- contrib/worker-models/ruby-official-2.5.0-stretch.yml
- docker-compose.yml
- docs/content/docs/concepts/files/worker_model-syntax.md
- docs/content/hosting/ready-to-run/docker-compose.md
- ui/src/app/views/settings/worker-model/form/worker-model.form.component.ts
> fix(worker-model): communication attr removed

- Dockerfile
- docker-compose.yml
- engine/elasticsearch/elasticsearch_handlers.go
type_event already contains the value of _type
close #4528
> fix(elasticsearch): type ES

- ui/src/styles.scss
1. Description
close #5012 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): remove codemirror z-index on lines

- ui/src/app/shared/workflow/wnode/pipeline/node.pipeline.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): missing workflow components cause rendering errors

- engine/hatchery/kubernetes/kubernetes.go
- sdk/build.go
- sdk/hatchery/starter.go
- sdk/hatchery/starter_test.go
> fix(hatchery): fix worker model name for all hatcheries

- ui/src/styles.scss
- ui/src/theme.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): make right bottom buttons wrapper to be over codemirror

- docker-compose.yml
- docs/content/docs/integrations/github/github_authentication.md
- docs/content/docs/integrations/gitlab/gitlab_authentication.md
- docs/content/docs/integrations/ldap.md
- docs/content/hosting/cds_services.md
- docs/content/hosting/user_authentication.md
> docs: some reviews

- engine/api/router.go
- engine/service/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(engine): log http error as info if status < 500

- docker-compose.yml
> fix(docker-compose): index metrics name

- sdk/hatchery/starter.go
- sdk/hatchery/starter_test.go
> fix(hatcheries): fix generated name

- cli/cdsctl/action.go
Signed-off-by: Gaultier HUBERT <gaultier.hubert@corp.ovh.com>
1. Description
1. About tests
1. Mentions
@ovh/cds
> Fixe key of Fullname,Key in actionDisplay struct

- ui/src/app/views/workflow/show/notification/form/workflow.notifications.form.html
> fix(ui): edit conditions on notifications

- cli/cdsctl/project_key.go
- cli/cobra_test.go
- engine/api/api.go
- engine/api/migrate/refactor_proj_keys.go
- engine/api/project.go
- engine/api/project/dao.go
- engine/api/project/dao_key.go
- engine/api/project/gorp_model.go
- engine/api/project/key.go
- engine/api/project/loader.go
- engine/api/project_key.go
- engine/api/project_key_test.go
- engine/sql/187_project_key.sql
- go.mod
- sdk/key.go
- sdk/rust/sdk-cds/src/models.rs
> refactor(api): project keys crypto

- ui/src/app/shared/status/status.icon.html
> fix(ui): loader path

- engine/sql/188_project_builtin_key.sql
> fix(sql): project builtin key

- engine/api/project/dao_key.go
> fix(api): project.loadBuiltinKey

- engine/hatchery/kubernetes/kubernetes.go
- engine/hatchery/local/local.go
- engine/hatchery/marathon/marathon.go
- engine/hatchery/openstack/openstack.go
- engine/hatchery/swarm/swarm_conf.go
- engine/hatchery/vsphere/vsphere.go
- engine/service/types.go
- sdk/hatchery/starter.go
this will avoid to start many workers (in the same time) if maxProv >
maxWorker in the configuration
> fix(hatchery): check maxWorker with MaxProv

- engine/api/event/publish.go
- engine/api/workflow/workflow_run_event.go
- engine/api/workflow/workflow_run_event_test.go
- engine/api/workflow_event.go
- engine/api/workflow_hook.go
- engine/api/workflow_queue.go
- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: do not send setStatut + add memory cache on commit status list

- sdk/exportentities/v1/workflow.go
- sdk/exportentities/v2/workflow.go
- sdk/exportentities/v2/workflow_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): workflow import link nodes to existing joins

- sdk/requirement.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): add a global timeout when checking network requirement

- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display sidebar tags

- engine/api/secret/secret.go
- engine/config.go
- engine/config_vault.go
> refactor(engine): move vault config to the engine package

- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
- ui/src/app/shared/workflow/wnode/wnode.component.ts
- ui/src/app/store/workflow.action.ts
- ui/src/app/store/workflow.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): run workflow in the middle

- engine/api/workflow/workflow_run_event.go
- engine/api/workflow/workflow_run_event_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
>  fix(api): do not send pr comment if status is not terminated

- engine/api/notification/mail.go
- engine/api/notification/user.go
- engine/api/repositoriesmanager/dao.go
- engine/api/workermodel/status.go
- engine/api/workflow_event.go
> fix(api): interpolate notif event

- engine/api/workflow/process_start.go
- engine/api/workflow/process_start_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: allow run condition on joins

- engine/api/workflow_queue.go
> fix(api): getWorkflowJobQueueHandler filter by group for all hatcheries

- engine/api/workflow.go
- engine/api/workflow_test.go
> fix(api): unit test log

- ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.scss
1. Description
Close #5040 
1. About tests
1. Mentions
@ovh/cds
> fix(ui): z-index edit pipeline ascode section

- cli/cdsctl/template_bulk.go
- sdk/exportentities/common.go
- ui/src/app/shared/workflow-template/bulk-modal/workflow-template.bulk-modal.component.ts
- ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui,cdsctl): take care of not imported workflow for instance

- cli/cdsctl/workflow_delete.go
- engine/api/pipeline_test.go
- engine/api/router_middleware_auth_permission.go
- engine/api/templates.go
- engine/api/workflow.go
- engine/api/workflow/dao.go
- engine/api/workflow/dao_run.go
- engine/api/workflow_run_test.go
- engine/api/workflow_trigger.go
- sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): check if workflow exists found before permission

- sdk/exportentities/workflow_tar.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing json tag to init template from workflow

- ui/src/app/store/pipelines.state.ts
- ui/src/app/store/workflow.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): clean selected node when returning on workflow main page

- engine/api/api.go
- engine/api/migrate/clean_duplicate_hooks.go
- engine/api/workflow/dao.go
> fix(api): clean duplicate hooks

- engine/api/ascode.go
- engine/api/ascode_test.go
- engine/api/workflow/dao.go
- ui/src/app/shared/diff/diff.ts
- ui/src/app/store/pipelines.state.ts
- ui/src/app/views/pipeline/show/pipeline.show.html
- ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,ui): resync as code when application is not ascode

- engine/sql/193_hooks_uuid.sql
> fix(sql): add unique constraint on hook uuid

- engine/api/notification/user.go
- engine/api/workflow_event.go
- engine/api/workflow_queue.go
- engine/api/workflow_run.go
- ui/src/app/views/workflow/run/workflow.run.component.ts
Renaming an ascode workflow:
* navigation between the run and other runs is broken
* wrong url in vcs notification
@ovh/cds
> fix: navigation when renaming workflow + user notifications

- engine/hatchery/swarm/swarm_conf.go
- sdk/status.go
> fix(hatchery): don't send status alert for only 1 dockerengine failure

- engine/api/workflow/dao.go
- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): remove addSpawnInfo from loop

- ui/src/app/shared/action/action.html
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): get failed step log

- ui/src/app/shared/repomanager/from/repomanager.form.spec.ts
- ui/src/app/store/applications.state.spec.ts
- ui/src/app/store/pipelines.state.spec.ts
- ui/src/app/store/project.state.spec.ts
- ui/src/app/store/workflow.state.spec.ts
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/application/show/admin/application.admin.component.spec.ts
- ui/src/app/views/application/show/admin/repository/application.repo.component.spec.ts
- ui/src/app/views/application/show/application.component.spec.ts
- ui/src/app/views/pipeline/add/pipeline.add.component.spec.ts
- ui/src/app/views/pipeline/show/admin/pipeline.admin.spec.ts
- ui/src/app/views/pipeline/show/pipeline.show.component.spec.ts
- ui/src/app/views/project/add/project.add.component.spec.ts
- ui/src/app/views/project/show/admin/repomanager/list/project.repomanager.list.spec.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): do not refresh state if route changed before api response

- engine/api/database/gorpmapping/dao.go
- engine/api/database/gorpmapping/encryption.go
- engine/api/database/gorpmapping/gorpmapping.go
- engine/api/database/gorpmapping/signature.go
- engine/api/test/gorp.go
- go.mod
- go.sum
> fix(api): crypto layer now supports complex types

- ui/src/app/views/workflow/run/node/pipeline/pipeline.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): no jobs in runjobs

- ui/src/app/shared/commit/commit.list.component.ts
- ui/src/app/views/workflow/run/node/history/history.component.ts
- ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): commit list during manual run + navigation into subnum

- ui/src/app/shared/parameter/list/parameter.component.ts
- ui/src/app/shared/workflow/node/run/node.run.param.html
- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
- ui/src/app/views/workflow/workflow.component.ts
- ui/src/app/views/workflow/workflow.html
> fix(ui): disabled buttons, displaytag

- engine/sql/197_drop_user_key.sql
> refactor(sql): drop user_key table

- engine/api/api_routes.go
- engine/api/router_middleware_auth.go
- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow/run_workflow_test.go
- engine/api/workflow_queue.go
- engine/api/workflow_queue_test.go
- engine/worker/internal/action/test_helper.go
- engine/worker/internal/run.go
- engine/worker/internal/take.go
- engine/worker/pkg/workerruntime/types.go
- go.mod
- go.sum
- sdk/interpolate/go.mod
- sdk/interpolate/go.sum
- sdk/interpolate/interpolate.go
> fix(api,worker): send spawn infos when job is failed to show the reason

- ui/src/app/shared/parameter/list/parameter.component.ts
- ui/src/app/shared/workflow/node/run/node.run.param.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): do not send default value when running pipeline

- ui/src/app/store/workflow.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): refresh workflowrun in sidebar

- engine/api/pipeline.go
- engine/api/pipeline/pipeline_importer.go
- engine/api/pipeline/pipeline_importer_test.go
- engine/api/pipeline/pipeline_parser.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): remove all pipeline parameters before inserting new ones

- ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.scss
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): logs not displayed when count of lines too long

- engine/api/workflowtemplate/instance.go
- sdk/workflow_template.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing check template request for ascode

- ui/src/app/shared/workflow/wnode/pipeline/wnode.pipeline.component.ts
- ui/src/app/shared/workflow/wnode/wnode.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): link to noderun: missing name query params

- engine/api/project.go
- engine/api/project_test.go
> fix(api): getProjectsHandler_FilterByRepo

- ui/src/app/shared/shared.module.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: ngui autocomplete fix

- engine/api/workflow.go
> feat(api): load workflow without its base64 icon

- sdk/cdsclient/http.go
> feat(sdk): add WithQueryParameter request modifier

- ui/package.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): upgrade ng2-semantic-ui

- engine/api/event/event.go
- engine/api/integration/dao_project_integration.go
- engine/api/migrate/refactor_integration_cryto.go
- engine/api/purge/purge.go
- engine/api/workflow/execute_node_job_run.go
- engine/api/workflow_run.go
> fix(api): integration crypto migration

- engine/api/mail/mail.go
> fix(api): send mail with rfc2392

- engine/worker/internal/start_test.go
- engine/worker/internal/types.go
> fix(worker): CDS_API_URL available from job

- engine/api/websocket_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): websocket unit test

- engine/cmd_start.go
- engine/repositories/repositories.go
> fix(repositories): service name

- engine/api/integration/dao_model_test.go
- engine/api/websocket_test.go
- engine/sql/200_fix_w_node_context_constraint.sql
> fix(sql): w_node_context constraint

- engine/api/event/publish_workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): add node run ID on workflowNodeRunEvent

- ui/src/app/views/workflow/show/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): calculate readonly with null workflow

- engine/worker/cmd_run.go
> fix(worker): log before exit error

- engine/api/mail/mail.go
> fix(api): header date in mail

- ui/src/app/shared/workflow/wnode/hook/hook.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): deletion of hook

- sdk/hatchery/register.go
even if it's for a worker model registration
> fix(hatchery): check canSpawn

- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_test.go
- engine/worker/internal/logger.go
- engine/worker/internal/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: move some function + add level in log

- engine/hatchery/serve.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): service logs: do not send struct

- engine/api/pipeline.go
- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): loading pipeline workflow holder

- engine/api/action/dao.go
- engine/api/pipeline/pipeline.go
- engine/api/pipeline/pipeline_test.go
- engine/api/workermodel/crud_test.go
> fix(api): rename worker model

- engine/api/pipeline.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): ignore error if wkf holder not found when loading pipeline

- engine/api/worker.go
- engine/worker/cmd_run.go
> fix(api): more info about LoadNodeJobRun

- ui/src/app/shared/ascode/events/ascode.event.html
- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.component.ts
- ui/src/app/shared/workflow/modal/node-edit/node.edit.modal.component.ts
- ui/src/app/shared/workflow/wnode/hook/hook.component.ts
- ui/src/app/views/pipeline/show/pipeline.show.html
- ui/src/app/views/workflow/show/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): allow to edit a non ascode workflow from template

- docs/content/docs/tutorials/worker_model-vsphere.md
- engine/api/workermodel/init.go
- engine/hatchery/kubernetes/kubernetes.go
- engine/hatchery/marathon/marathon.go
- engine/hatchery/swarm/swarm.go
> fix(hatchery/marathon): let hatchery remove worker

- engine/api/ascode.go
- engine/api/operation/operation.go
- engine/api/workflow/repository.go
- engine/repositories/processor_loadfiles.go
- engine/repositories/repositories_handlers.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,repositories): hide operation secrets, improve load files errors

- engine/api/workflow/dao_node_run.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow_ascode_test.go
- sdk/workflow.go
> fix(api): notification as code duplicates

- cli/cdsctl/template_bulk.go
- engine/api/templates.go
- sdk/workflow_template.go
- ui/.gitignore
- ui/src/app/model/workflow-template.model.ts
- ui/src/app/shared/workflow-template/apply-modal/workflow-template.apply-modal.component.ts
- ui/src/app/views/settings/worker-model/list/worker-model.list.component.ts
- ui/src/app/views/settings/workflow-template/list/workflow-template.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui,cdsctl): merge args tmpl bulk, ui load instance with no workflow

- engine/api/workermodel/crud.go
- engine/api/workermodel/crud_test.go
- engine/api/workermodel/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): worker model migration should not set need registration

- engine/api/workflow/process_requirements.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load capabilities on worker model load fallback

- engine/api/environment/environment.go
- engine/api/environment/environment_exporter.go
- sdk/environment.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing data when loading environments

- engine/api/project/gorp_model.go
> refactor(api): fix deprecated vcs_server dao

- engine/api/websocket.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): send workflow run event to be able to refresh sidebar

- engine/api/environment/environment.go
- engine/sql/205_environment_created.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing column in environment

- ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fix link with log line

- sdk/environment.go
- sdk/environment_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): unmarshal env last modified date

- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): allow to stop a workflow run marked as to delete

- engine/api/workflow/execute_node_job_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load to delete run when updating node run job status

- docs/content/development/contribute/development.md
> docs(dev): start hatchery after init token

- engine/api/workflow/dao_node_run.go
- engine/api/workflow_event.go
> fix(api): don't  warn and skip if no previous run was found

- ui/src/app/shared/workflow/menu/edit-node/menu.edit.node.component.ts
- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
- ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): add subscription on workflowRun event

- engine/api/workflow/process_node.go
- engine/api/workflow/process_node_test.go
> fix(api): load vcsInfos on a run without a root app

- ui/src/app/shared/workflow-template/bulk-modal/workflow-template.bulk-modal.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): bulk modal validation

- cli/cdsctl/workflow_transform_as_code.go
- engine/api/workflow_ascode.go
- engine/api/workflow_ascode_test.go
- sdk/cdsclient/client_workflow_as_code.go
- sdk/cdsclient/interface.go
- sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdsctl): ask for branch and message when migrate workflow ascode

- cli/cdsctl/admin_database.go
> fix(cdsctl): display list-encrypted-data

- cli/cdsctl/application_variable.go
- cli/cdsctl/workflow_log.go
- cli/cdsctl/workflow_run_history.go
- cli/cdsctl/workflow_stop.go
- cli/cobra.go
- cli/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdsctl): bad sort of arg when mixed with ctx arg, remove weight

- engine/api/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> test: fix compilation after merge

- engine/api/workflow.go
- engine/api/workflow_test.go
- sdk/workflow_run.go
> feat(api): return workflow runs URLs

- Makefile
- engine/Makefile
- engine/worker/Makefile
> chore(engine): add parallel jobs in makefile

- ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
> fix(ui): display spawn info for waiting job

- sdk/services.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): change json tag

- engine/api/websocket.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): remove client when close message was send

- engine/Makefile
- engine/api/authentication/dao_session_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore(test): print human readable test report

- engine/api/api.go
- engine/api/workflow/gorp_model.go
- engine/api/workflow/init.go
- engine/api/workflow_queue_test.go
> feat(api): remove default region

- engine/service/types.go
- sdk/hatchery/hatchery.go
- sdk/hatchery/types.go
Ignore job without a region prerequisite if ignoreJobWithNoRegion=true
> feat(hatcheries): ignoreJobWithNoRegion conf

- cli/Makefile
- cli/cdsctl/Makefile
- cli/cdsctl/action.go
- cli/cdsctl/admin_metadata.go
- cli/cdsctl/consumer.go
- engine/Makefile
- engine/worker/Makefile
- sdk/Makefile
- tools/debpacker/Makefile
- ui/src/app/service/authentication/error.interceptor.ts
- ui/src/app/shared/table/data-table.component.ts
- ui/src/app/shared/workflow/wizard/context/wizard.context.html
- ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore: update makefile xunit generation and fix sonar issues

- docs/content/hosting/ready-to-run/from-binaries.md
> docs(ready-to-run): signup before start ui

- engine/api/application_import_test.go
- engine/api/database/gorpmapping/dao.go
- engine/api/environment.go
- engine/api/environment/environment_parser.go
- engine/api/environment_import_test.go
- engine/api/integration.go
- engine/api/pipeline.go
- engine/api/project.go
- engine/api/workflow/dao_label.go
- engine/api/workflow/workflow_importer.go
- sdk/cdsclient/http.go
- sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,sdk): allow to retry request when conflict due to database lock

- engine/api/timeline.go
- engine/api/ui.go
- sdk/overview.go
- ui/src/app/views/application/show/home/application.home.component.ts
- ui/src/app/views/application/show/home/application.home.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,ui): return empty app stats and timeline if no elastic service

- docs/content/development/contribute/development.md
- docs/content/hosting/ready-to-run/from-binaries.md
- docs/content/hosting/requirements.md
> docs(ready-to-run): min version is 9.6

- ui/src/app/views/workflow/graph/workflow.graph.component.ts
- ui/src/app/views/workflow/sidebar/code/sidebar.code.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): nodes not displayed and exception to get dimensions

- cli/cdsctl/config.go
- cli/cdsctl/main.go
- cli/cdsctl/version.go
> fix(cdsctl): avoid potential panic

- engine/api/application.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load application no-ascode

- engine/hatchery/openstack/spawn.go
- engine/hatchery/openstack/spawn_test.go
- engine/vcs/gerrit/client_pull_request.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery): count CPUs using flavor list instead of data from server

- engine/api/workflow/resync_workflow.go
- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): resync workflow run status when stopping a job

- engine/api/workflow/dao.go
- engine/api/workflowtemplate/instance.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing group for template when loaded from audit

- cli/cdsctl/workflow_init.go
- engine/api/router_middleware_auth.go
- engine/api/workflowtemplate/instance.go
1. Description
Contains a fix for #5262.
1. About tests
1. Mentions
@ovh/cds
> fix(api): resync repo managers to compute template default params

- engine/hatchery/vsphere/init.go
close #5281
initial commit https://github.com/ovh/cds/commit/c389564867fa7be76441c13d302c311dd42a94f8
> fix(hatchery/vsphere): init endpoint

- ui/src/app/views/workflow/run/workflow.run.component.ts
- ui/src/app/views/workflow/run/workflow.run.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display workflow run

- sdk/exportentities/v2/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): jsonschema wrong tag

- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not load all components of project when running workflow

- sdk/cdsclient/client_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk): subscribe to queue

- engine/api/workflow/dao.go
> feat(api): improve error msg on workflow import

- engine/api/workermodel/dao.go
- engine/api/workermodel/dao_test.go
- engine/api/workermodel/utils.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): default env vars should always be merged for docker model

- engine/api/router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(api): improve router logs fields

- sdk/cdsclient/client_queue.go
> fix(hatchery): avoid panic on queuePolling

- ui/src/app/shared/workflow/wnode/outgoinghook/node.outgoing.html
- ui/src/common.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): display outgoing hook when fails without child run

- engine/api/services.go
- engine/api/services/dao.go
- engine/api/worker.go
- engine/api/worker/attach.go
- engine/api/worker/attach_test.go
- engine/api/worker/dao.go
- engine/api/worker/heartbeat.go
- engine/api/worker/registration.go
- engine/api/worker/worker_test.go
- engine/cdn/cdn_log.go
- engine/sql/209_worker_hatchery_info.sql
- sdk/worker.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): worker should not be removed when hatchery is lost

- engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): lock noderun before updating it

- engine/api/cache/redis.go
- engine/cdn/cdn_log.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: add stop ticker + time.sleep

- engine/sql/210_worker_fix_hatchery_name.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): set hatchery_name default value for worker

- contrib/integrations/arsenal/plugin-arsenal/main.go
> fix(plugin/arsenal): use custom http client

- engine/api/migrate/migration.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: min version

- engine/api/workflow/process_parameters.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: do not erase vars slice

- engine/api/workflow/workflow_secrets.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: ignore non password integration variable

- engine/hooks/tasks_github_test.go
- engine/hooks/type_github.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hook): manage two type for pushed_at field in github event

- Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore: include not annoted tag to get git describe

- engine/api/environment/environment_parser.go
- engine/api/workflow/dao.go
- engine/api/workflow/workflow_secrets.go
- engine/api/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: load secret on non as code entity in as code workflow

- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.scss
- ui/src/app/shared/workflow/wizard/hook/hook.form.component.ts
- ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
- ui/src/common.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): unsubscribe log polling and log scroll x

- engine/worker/internal/keys.go
- engine/worker/internal/run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): limit workdir path length using a hash

- engine/hatchery/openstack/openstack.go
- engine/hatchery/openstack/spawn.go
- engine/hatchery/vsphere/client.go
- engine/hatchery/vsphere/spawn.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery:openstack): snapshot based on model path

- engine/api/purge/purge.go
- engine/api/status.go
- engine/api/workflow/dao_run.go
- engine/api/workflow/dao_run_test.go
- engine/api/workflow_run.go
even if they don't have new runs
> fix(api): new goroutine to mark as delete workflow

- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): step order not found and step status undefined

- engine/hooks/gerrit.go
- engine/hooks/gerrit_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hook): create unique changeID from repo branch and changeId

- engine/hatchery/openstack/openstack.go
- engine/hatchery/openstack/spawn.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery:openstack): spawn worker using old snapshot with model name

- engine/api/repositories_manager.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow/process_node.go
- engine/hatchery/swarm/swarm_util_create.go
- sdk/error.go
- sdk/error_test.go
- sdk/hatchery/starter.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk,api): some error where not displayed when creating job

- engine/api/websocket.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): remove websocket client when read failed

- engine/worker/internal/action/builtin_script.go
- engine/worker/internal/action/builtin_script_test.go
- sdk/cdsclient/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): return error when script action failed

- engine/ui/types.go
- engine/ui/ui_router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): add distinct deploy url param for ui service

- engine/api/admin.go
- engine/featureflipping/dao.go
- engine/featureflipping/dao_test.go
- engine/featureflipping/featureflipping_test.go
- engine/vcs/vcs_router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): do not use middleware from api

- ui/src/app/store/project.state.ts
- ui/src/app/views/application/show/admin/application.admin.component.ts
- ui/src/app/views/project/show/integrations/project.integrations.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): fetch project integration for application admin section

- engine/cdn/cdn_log_cds_api.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): import

- ui/src/app/app.component.ts
sse removed on https://github.com/ovh/cds/releases/tag/0.47.0
close #4809
> fix(ui): remove _sseSubscription support

- engine/api/api.go
- engine/api/authentication/xsrf.go
- engine/api/router_middleware_auth.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): xsrf session lifetime

- engine/cdn/cdn_log.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): print job logs only for debug purpose

- docs/content/docs/concepts/workflow/hooks/kafka-hook.md
- docs/content/docs/integrations/kafka/kafka_events.md
- docs/content/docs/integrations/kafka/kafka_hooks.md
> docs: kafka uses SASL and TLS

- engine/api/router_middleware_auth.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): xsrf renew only if not in cache or not in cookie

- engine/cache/cache.go
- engine/cache/redis.go
- engine/cache/redis_test.go
- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_cds_api.go
- engine/cdn/cdn_log_test.go
> feat(cdn): cache dequeue bulk

- contrib/uservices/hubot-xmpp/scripts/xmpp.coffee
if REPLACE_DOMAINS="@aa.net;@bb.net" -> will be replaced by defaultDomain
> feat(uservices/hubot-xmpp): replaced domains var

- tests/04_sc_workflow_run_notif.yml
> test: rename some duplicate venom yml steps

- cli/cdsctl/action.go
- cli/cdsctl/admin_broadcasts.go
- cli/cdsctl/admin_feature.go
- cli/cdsctl/admin_migrations.go
- cli/cdsctl/admin_plugin.go
- cli/cdsctl/application.go
- cli/cdsctl/application_key.go
- cli/cdsctl/application_variable.go
- cli/cdsctl/consumer.go
- cli/cdsctl/environment.go
- cli/cdsctl/environment_key.go
- cli/cdsctl/environment_variable.go
- cli/cdsctl/events.go
- cli/cdsctl/group.go
- cli/cdsctl/group_user.go
- cli/cdsctl/pipeline.go
- cli/cdsctl/project.go
- cli/cdsctl/project_favorite.go
- cli/cdsctl/project_group.go
- cli/cdsctl/project_integration.go
- cli/cdsctl/project_key.go
- cli/cdsctl/project_variable.go
- cli/cdsctl/template.go
- cli/cdsctl/tools.go
- cli/cdsctl/user.go
- cli/cdsctl/worker_model.go
- cli/cdsctl/workflow.go
- cli/cdsctl/workflow_artifact.go
> feat(cdsctl): aliases cmd

- contrib/integrations/kubernetes/plugin-kubernetes/plugin-kubernetes-deployment.yml
- engine/api/grpc_plugin.go
- sdk/plugin.go
> feat(api): validate yml plugin before import it

- tests/04_sc_workflow_run_notif.yml
- tests/04_sc_workflow_run_worker_cmd_cache.yml
- tests/04_sc_workflow_update_run.yml
> test: add some retries on async log check

- ui/src/app/shared/action/action.html
- ui/src/app/shared/action/step/form/step.form.html
- ui/src/app/views/settings/action/form/action.form.html
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
> feat(ui): title on delete buttons

- cli/cdsctl/template.go
- cli/cdsctl/template_instances.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdsctl): export template instances in yaml

- sdk/vcs/git/git.go
- sdk/vcs/git/git_clone.go
- sdk/vcs/git/git_clone_test.go
- sdk/vcs/git/git_tag.go
- tests/04_sc_workflow_run_simple_plugin.yml
- tests/04_sc_workflow_run_worker_cmd.yml
- tests/04_sc_workflow_template_run.yml
> fix(worker): git clone on windows over ssh

- cli/cdsctl/config.go
- cli/cdsctl/shell.go
- cli/cdsctl/template_apply.go
- cli/cdsctl/workflow.go
- cli/cdsctl/workflow_init.go
- cli/cdsctl/workflow_run.go
- cli/cdsctl/workflow_status.go
- engine/repositories/processor_checkout.go
- engine/repositories/processor_common.go
- engine/repositories/processor_loadfiles.go
- engine/repositories/processor_push.go
- go.mod
- go.sum
> chore: bump go-repo 1.8.0

- tests/06_sc_workflow_with_marathon.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
> test: decrease retry delay to catch run status

- engine/hooks/gerrit.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix: display error logs

- ui/src/app/service/queue/queue.service.ts
- ui/src/app/views/settings/queue/queue.component.ts
> fix(ui): queue filter

- engine/api/api.go
- engine/api/api_routes.go
- engine/api/help.go
- ui/src/app/app.component.ts
- ui/src/app/model/help.model.ts
- ui/src/app/service/help/help.service.ts
- ui/src/app/service/services.module.ts
- ui/src/app/shared/repomanager/from/repomanager.form.spec.ts
- ui/src/app/shared/toast/ToastService.ts
- ui/src/app/shared/toast/toast-http-error.component.ts
- ui/src/app/shared/toast/toast-http-error.html
- ui/src/app/store/help.action.ts
- ui/src/app/store/help.state.ts
- ui/src/app/store/store.module.ts
- ui/src/app/views/navbar/navbar.component.ts
- ui/src/app/views/navbar/navbar.html
- ui/src/app/views/navbar/navbar.scss
- ui/src/app/views/project/add/project.add.component.spec.ts
- ui/src/app/views/project/show/admin/repomanager/list/project.repomanager.list.spec.ts
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
> feat(api,ui): help text

- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): load minimal workflow when updating it to prevent load error

- engine/cdn/storage/webdav/webdav_test.go
> test(cdn): webdav ut

- engine/hatchery/kubernetes/kubernetes.go
as marathon / swarm hatcheries
> feat(hatchery/k8s): force pull if latest

- tests/test.sh
> test: workflow_with_third_parties

- engine/api/router.go
- engine/cmd_start.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): safely stop engine

- engine/hooks/gerrit.go
- engine/hooks/tasks.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hook): gerrit reconnection

- engine/database/database.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): ignore db connection default search path value

- engine/api/services.go
- engine/api/services/dao.go
- engine/api/services/external.go
- engine/api/services_test.go
- engine/sql/api/215_service_constraints.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): check if external service already exists before save

- engine/api/objectstore/swift.go
- engine/cache/cache.go
- engine/cache/redis.go
- engine/cdn/cdn.go
- engine/cdn/status_handler.go
- engine/cdn/storage/cds/cds.go
- engine/cdn/storage/dao.go
- engine/cdn/storage/local/local.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/swift/swift.go
- engine/cdn/storage/swift/swift_test.go
- engine/cdn/storage/webdav/webdav.go
- engine/cdn/storage/webdav/webdav_test.go
- engine/sql/cdn/001_create_index.sql
- tests/06_sc_workflow_with_marathon.yml
> feat(cdn): general status

- engine/worker/cmd.go
> fix(worker): remove unused flag from-github

- engine/cdn/cdn_gc.go
- engine/cdn/cdn_item.go
- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_cds_api.go
- engine/cdn/cdn_log_dequeue.go
- engine/cdn/cdn_sync.go
- engine/cdn/status_handler.go
- engine/cdn/storage/cds/cds.go
- engine/cdn/storage/local/local.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_run.go
- engine/cdn/storage/storageunit_test.go
- engine/cdn/storage/swift/swift.go
- engine/cdn/storage/swift/swift_test.go
- engine/cdn/storage/webdav/webdav.go
- engine/cdn/storage/webdav/webdav_test.go
- sdk/telemetry/stats.go
> feat(cdn): metrics

- engine/api/workflow/dao.go
- engine/api/workflow/workflow_parser.go
- engine/api/workflow_import.go
- sdk/cdsclient/client_import.go
- sdk/exportentities/v2/workflow_notif_test.go
- sdk/exportentities/v2/workflow_notification.go
- sdk/notif.go
- sdk/workflow.go
and fix cdsctl msg displayed in case of error on cdsctl worklow import
> fix(api,cdsctl): eventIntegration import/export

- engine/cdn/cdn.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn): enable swift driver

- docs/content/docs/integrations/bitbucket.md
- engine/migrateservice/service.go
> fix(migrate): goroutines init

- ui/src/app/views/pipeline/show/workflow/pipeline.workflow.component.ts
- ui/src/app/views/pipeline/show/workflow/stage/form/pipeline.stage.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): stringify pipeline stage conditions

- engine/api/websocket.go
- sdk/error.go
> fix(api): handle websocket upgrade error

- engine/cdn/cdn_log.go
- engine/hooks/scheduler.go
- go.mod
- go.sum
- sdk/jws/jws.go
> fix(hooks, cdn): logs + short write

- engine/cdn/storage/encryption/encryption.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): improve logs

- go.mod
- go.sum
> chore: update symmecrypt version

- engine/cdn/cdn_item.go
- engine/cdn/storage/storageunit_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): closing reader/writer

- engine/cdn/cdn_sync.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): sync node run cache

- engine/api/status.go
- tests/03_clictl_admin_services.yml
> fix(api): loadAll status

- engine/cdn/storage/dao.go
- engine/cdn/storage/dao_test.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_run.go
- engine/cdn/storage/storageunit_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn): sync item from buffer first

- engine/api/workflow_run.go
> fix(api): handle postWorkflowRunHandler check condition error

- engine/worker/internal/action/builtin_script.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(worker): panic step script when no content

- engine/api/workflow/workflow_importer.go
- engine/api/workflow_import_test.go
> fix(api): import workflow with perms on node

- engine/api/ascode.go
- engine/api/ascode/pull_request.go
- engine/api/operation/operation.go
- engine/api/workflow/repository.go
- engine/repositories/processor.go
- engine/repositories/processor_checkout.go
- engine/repositories/processor_common.go
- ui/src/app/model/operation.model.ts
- ui/src/app/views/workflow/add/workflow.add.html
> fix(api,ui): display ascode error messages

- engine/cdn/cdn_sync.go
- engine/cdn/item/dao.go
- engine/worker/internal/action/builtin_script.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): avoid to resync noderun

- engine/worker/internal/handler_tmpl.go
- engine/worker/internal/handler_tmpl_test.go
> fix(worker): support secrets in worker tmpl command

- engine/cdn/storage/storageunit_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn):  conflict during backend synchronization

- ui/src/app/model/pipeline.model.ts
- ui/src/app/store/pipelines.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): avoid duplicate of ref jobs

- engine/api/worker/registration.go
- engine/api/workermodel/registration.go
even if there is no capabilities
close #5411
> fix(api): update worker model registration

- engine/api/workflow/dao_node_run.go
- engine/api/workflow/dao_run.go
- engine/api/workflow/execute_node_run.go
- engine/api/workflow/process_parameters.go
- engine/api/workflow/resync_workflow.go
- engine/api/workflow/run_workflow.go
- engine/api/workflow_run.go
- sdk/luascript/luascript_test.go
- sdk/project.go
- sdk/workflow.go
- sdk/workflow_run.go
> refactor(api): dao workflow_run improvements

- ui/package.json
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): update d3 types

- engine/api/router_middleware_auth.go
- ui/src/app/store/feature.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): skip xsrf check for when not authenticated

- engine/api/mail/mail.go
- sdk/common.go
- sdk/common_test.go
> fix(api): support utf8 in mail subject

- docs/content/docs/concepts/variables.md
- engine/api/worker/init.go
- engine/cmd_start.go
- engine/service/service.go
- engine/service/types.go
- sdk/cdsclient/http_websocket.go
> fix(engine): manage signout

- ui/src/app/shared/workflow/modal/delete/workflow.node.delete.component.ts
- ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts
> fix(ui): edit notifications

- engine/ui/types.go
- engine/ui/ui.go
- ui/src/app/app.component.html
- ui/src/app/app.component.scss
- ui/src/app/app.component.ts
- ui/src/assets/i18n/en.json
- ui/src/assets/i18n/fr.json
> fix(ui): start ui service even if not registered

- engine/api/suggest.go
> fix(api): do not try to load env from appname

- engine/Makefile
> chore(engine): add kafka for testing purpose

- engine/cdn/cdn_log.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): adding log

- engine/cdn/cdn.go
- engine/cdn/cdn_gc.go
- engine/cdn/cdn_gc_test.go
- engine/cdn/cdn_item.go
- engine/cdn/cdn_item_test.go
- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_dequeue_test.go
- engine/cdn/cdn_metrics.go
- engine/cdn/cdn_test.go
- engine/cdn/item/dao.go
- engine/cdn/item_logs_handler_test.go
- engine/cdn/status_handler.go
- engine/cdn/storage/cds/cds.go
- engine/cdn/storage/dao.go
- engine/cdn/storage/dao_test.go
- engine/cdn/storage/local/local.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storage_unit_io.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_run.go
- engine/cdn/storage/swift/swift.go
- engine/cdn/storage/swift/swift_test.go
- engine/cdn/storage/types.go
- engine/cdn/storage/webdav/webdav.go
- engine/cdn/storage/webdav/webdav_test.go
- engine/cdn/types.go
- engine/config.go
- sdk/telemetry/stats.go
- sdk/telemetry/telemetry.go
> feat(cdn): add more metrics

- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_dequeue.go
- engine/cdn/cdn_log_dequeue_test.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storageunit.go
- engine/hatchery/kubernetes/kill_workers.go
- engine/hatchery/kubernetes/services.go
- engine/hatchery/serve.go
- engine/hatchery/swarm/swarm.go
- engine/hatchery/swarm/swarm_util_kill.go
- engine/hatchery/swarm/swarm_util_logs.go
- engine/worker/internal/handler_download.go
- engine/worker/internal/run.go
- engine/worker/internal/types.go
- engine/worker/pkg/workerruntime/types.go
- sdk/log/log.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn,hatchery): send and save service logs splitted

- go.mod
- go.sum
> chore(engine): upgrade mail lib to manage tls dial

- engine/cdn/cdn_item.go
- engine/cdn/cdn_metrics.go
- engine/cdn/cdn_sync.go
- engine/cdn/storage/storageunit_run.go
- engine/cdn/storage/types.go
- engine/cdn/types.go
> feat(cdn): remove sync mutex and fix metrics

- engine/api/workflow/execute_node_run.go
- engine/api/workflow/process.go
- engine/api/workflow/process_node.go
- engine/api/workflow/process_start.go
- engine/api/workflow/run_workflow.go
- engine/api/workflow_run.go
- sdk/build.go
- sdk/cdsclient/http.go
- sdk/error.go
- sdk/messages.go
> refactor(api): new SpawnMsg constructor

- engine/api/mail/mail.go
- go.mod
- go.sum
> fix(engine): wrap err on sendmail

- contrib/uservices/cds2http/README.md
- contrib/uservices/cds2http/service/main.go
- contrib/uservices/cds2http/service/process.go
- docs/content/docs/integrations/kafka/kafka_events.md
- docs/content/docs/integrations/kafka/kafka_hooks.md
- engine/hooks/kafka.go
- sdk/event/kafka_listener.go
- tests/05_sc_workflow_event_kafka.yml
- tests/fixtures/ITSCWRKFLW18/input-kafka.json
- tests/fixtures/ITSCWRKFLW18/workflow.yml
- tests/fixtures/integrations/kafka-hook.yml
> fix(engine): remove deprecated kafka-cluster lib

- engine/cache/cache.go
- engine/cache/redis.go
- engine/cdn/cdn_gc_test.go
- engine/cdn/cdn_item.go
- engine/cdn/cdn_item_test.go
- engine/cdn/item_logs_handler.go
- engine/cdn/item_logs_handler_test.go
- engine/cdn/lru/redis.go
- engine/cdn/lru/redis_test.go
- engine/cdn/redis/reader.go
- engine/cdn/redis/readwrite.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn): add sort options to /lines and /download handlers

- engine/api/event/publish_workflow_run.go
- engine/api/workflow_run.go
- sdk/event.go
- ui/src/app/app.service.ts
- ui/src/app/store/workflow.action.ts
- ui/src/app/store/workflow.state.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,ui): publish event when people delete a run from UI

- engine/cdn/lru/redis.go
- engine/cdn/status_handler.go
- engine/cdn/storage/dao.go
- engine/cdn/types.go
> feat(cdn): lag in status

- sdk/exportentities/v2/workflow.go
- sdk/exportentities/v2/workflow_test.go
> fix(sdk): workflow as code parser raise error if 2 roots are detected

- tests/05_sc_workflow_event_kafka.yml
- ui/src/app/views/application/show/application.component.ts
> fix(ui): display integrations list on app

- engine/api/workflow.go
- ui/src/app/views/workflow/show/admin/workflow.admin.component.html
- ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): fixing load project on dryrun routes

- engine/hatchery/openstack/get.go
> fix(hatchery/openstack): add retry on server list

- engine/worker/cmd_tmpl.go
- engine/worker/internal/handler_tmpl.go
- engine/worker/internal/handler_tmpl_test.go
> fix(worker): tmpl command returned error

- engine/featureflipping/featureflipping.go
- engine/vcs/gerrit/client_status.go
- tests/05_sc_workflow_event_kafka.yml
- ui/src/app/shared/repomanager/from/repomanager.form.html
> fix(vcs): building status with gerrit

- engine/api/api.go
- engine/api/purge/purge.go
- engine/api/purge/purge_test.go
- engine/api/workflow/dao_run.go
- engine/api/workflow/dao_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): separate workflow purge in 3 goroutines

- cli/cdsctl/workflow_log.go
- cli/cdsctl/workflow_run_interactive.go
- engine/api/workflow_run_log.go
- engine/api/workflow_run_log_test.go
- engine/cdn/cdn_router.go
- engine/cdn/item_logs_handler.go
- sdk/cdn.go
- ui/src/app/model/pipeline.model.ts
- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.html
- ui/src/app/shared/workflow/sidebar/run-node/workflow.sidebar.run.node.component.ts
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
- ui/src/app/views/workflow/run/node/pipeline/pipeline.html
- ui/src/app/views/workflow/run/node/pipeline/service/service.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
- ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
- ui/src/app/views/workflow/workflow.component.ts
- ui/src/app/views/workflow/workflow.module.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): log polling unsusbscribe, improve log refresh

- engine/repositories/fs.go
- engine/repositories/processor_push.go
> fix(repositories): clean repo basedir if any operation occurs in push operation

- engine/api/application.go
- engine/api/ascode.go
- engine/api/purge/purge_run.go
- engine/api/repositoriesmanager/repositories_manager.go
- engine/api/workflow/dao_coverage.go
- engine/api/workflow/hook.go
- engine/api/workflow/workflow_parser.go
> fix(api): avoid returning resource not found without informations for users

- engine/api/workflow.go
- engine/api/workflow/dao.go
> fix(api): clean node context when mark workflow as delete

- engine/cdn/storage/encryption/encryption.go
> fix(cdn): protect the encryption keys map with a mutex

- tests/05_sc_workflow_event_kafka.yml
> test(it): check if kafka consumer is started

- ui/src/app/views/workflow/show/workflow.component.ts
- ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): do not check feature is there is no project

- engine/api/api.go
- engine/api/application_test.go
- engine/api/environment_ascode_test.go
- engine/api/event/publish.go
- engine/api/pipeline_test.go
- engine/api/websocket.go
- engine/api/websocket_test.go
- engine/api/workflow_ascode_test.go
- engine/api/workflow_purge_test.go
- engine/cache/redis.go
- engine/cdn/websocket.go
- engine/websocket/client.go
- sdk/event.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): websocket event lost when many clients

- docs/content/docs/concepts/workflow/retention.md
- engine/api/ascode/sync.go
- engine/api/purge/purge_run.go
- engine/api/purge/purge_test.go
- engine/api/repositoriesmanager/repositories_manager.go
- engine/api/workflow.go
- engine/api/workflow/dao.go
- engine/vcs/bitbucketcloud/client_pull_request.go
- engine/vcs/bitbucketserver/client_pull_request.go
- engine/vcs/gerrit/client_pull_request.go
- engine/vcs/github/client_pull_request.go
- engine/vcs/gitlab/client_pull_request.go
- engine/vcs/vcs_handlers.go
- sdk/repositories_manager.go
- sdk/vcs.go
- ui/resources/cds-hint.js
- ui/src/app/store/workflow.state.ts
- ui/src/app/views/workflow/show/admin/workflow.admin.component.html
- ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(ui,api): add gerrit variable for workflow run retention

- ui/src/app/model/workflow.model.ts
> fix(ui): clean notification by searching by node names

- engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not update workflow with empty retention policy

- engine/service/service.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(sdk): print date with timezone in service status

- engine/vcs/bitbucketserver/client_pull_request.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(vcs): date is in millisecond

- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
> fix(ui): sidebar refresh when switching workflows

- engine/api/api_routes.go
- engine/api/workflow_run.go
- engine/worker/internal/handler_download.go
- sdk/cdsclient/interface.go
- sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,worker): missing code to load runs for a project

- ui/src/app/app.service.ts
- ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts
- ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): clean sidebar runs when switch workflow

- engine/api/keys/keys_pgp.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): generate pgp key using keyname for address

- engine/cdn/cdn.go
- engine/cdn/cdn_router.go
- engine/service/debug.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn): add pprof debug routes

- ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): refresh node status and logs

- engine/cdn/storage/storageunit.go
> fix(cdn): rollback tx on error

- engine/api/purge/purge.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): lock run when an api is trying to delete it

- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(ui): display loader when getting logs from cdn

- engine/api/purge/purge.go
- engine/api/purge/purge_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): purge add check on context

- engine/cdn/cdn_log.go
- ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html
- ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): job spawninfo duplicated subscription

- engine/api/workflow/logs.go
- engine/cdn/cdn.go
- engine/cdn/types.go
- engine/worker/internal/run.go
- sdk/cdn.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn,worker): worker can send only one terminated line to cdn

- engine/cache/cache.go
- engine/cache/redis.go
- engine/cache/redis_test.go
- engine/cdn/cdn.go
- engine/cdn/cdn_gc_test.go
- engine/cdn/cdn_item_test.go
- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_cds_api.go
- engine/cdn/cdn_log_dequeue.go
- engine/cdn/cdn_log_dequeue_test.go
- engine/cdn/cdn_log_test.go
- engine/cdn/cdn_sync_test.go
- engine/cdn/cdn_test.go
- engine/cdn/item_handler_test.go
- engine/cdn/item_logs_handler_test.go
- engine/cdn/storage/dao_test.go
- engine/cdn/storage/local/local.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_test.go
- engine/cdn/storage/types.go
- engine/cdn/types.go
- go.mod
- sdk/config.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): add rate limit + check buffer size before adding line

- engine/cdn/cdn.go
- engine/cdn/cdn_gc_test.go
- engine/cdn/cdn_log.go
- engine/cdn/cdn_log_dequeue.go
- engine/cdn/cdn_log_test.go
- engine/cdn/cdn_sync_test.go
- engine/cdn/cdn_test.go
- engine/cdn/storage/dao_test.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_test.go
- engine/cdn/storage/types.go
- sdk/config.go
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn): init default conf if values are missing

- engine/Makefile
- tools/smtpmock/Dockerfile
1. Description
1. About tests
1. Mentions
@ovh/cds
> chore: fix version for some docker deps

- cli/cdsctl/workflow_init.go
- engine/api/workflow/workflow_parser.go
- engine/api/workflowtemplate/instance.go
- sdk/vcs.go
- sdk/workflow_hook.go
- sdk/workflow_hook_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
>  fix(api,cli): allow ascode on event you want + fix hook.Equal

- engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not run old purge system if new purge is enabled

- engine/hatchery/swarm/swarm_util_kill.go
- sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(hatchery): error on registration are not sent on cds api

- cli/cdsctl/admin_cdn.go
- docs/content/docs/components/cdn/migration.md
- engine/cdn/cdn.go
- engine/cdn/cdn_sync.go
- engine/cdn/sync_handler.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> feat(cdn): run cds migration to cdn from cli

- engine/api/application.go
- engine/repositories/processor_common.go
- ui/src/app/shared/ascode/save-modal/ascode.save-modal.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,ui): allow to change sshkey on edit as code

- engine/api/workflowtemplate/execute.go
- ui/src/app/views/navbar/navbar.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): return more details on template apply error

- engine/vcs/github/client_status.go
- engine/vcs/github/http.go
> feat: display gh response

- sdk/workflow_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): missing workflow context fields for audits

- engine/cdn/storage/dao.go
> fix(cdn): item.LoadByIDs with a lot of empty ids

- cli/cdsctl/pipeline.go
- engine/api/pipeline.go
- engine/api/pipeline/pipeline_importer.go
- engine/api/pipeline/pipeline_importer_test.go
- engine/api/pipeline/pipeline_parser.go
> feat(cdsctl): pipeline import --force to detach from repo

- engine/cdn/cdn_gc.go
- engine/cdn/cdn_item.go
- engine/cdn/item_handler.go
- engine/cdn/storage/dao.go
- engine/cdn/storage/storage_unit_io.go
- engine/cdn/storage/storageunit_purge.go
- engine/cdn/storage/storageunit_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): remove slow queries

- cli/cdsctl/application.go
- cli/cdsctl/environment.go
- cli/cdsctl/workflow_import.go
- docker-compose.yml
- docs/content/hosting/ready-to-run/docker-compose/full-example.md
- engine/api/application/application_parser.go
- engine/api/application/application_parser_test.go
- engine/api/application/dao.go
- engine/api/ascode/dao.go
- engine/api/auth_local.go
- engine/api/environment/environment.go
- engine/api/environment/environment_parser.go
- engine/api/environment/environment_parser_test.go
- engine/api/environment_import.go
- engine/api/pipeline/pipeline.go
- engine/api/pipeline/pipeline_importer.go
- engine/api/pipeline/pipeline_parser_test.go
- engine/api/test/assets/assets.go
- engine/api/workflow/dao.go
- engine/api/workflow/workflow_importer.go
- engine/api/workflow_application.go
- engine/repositories/fs.go
- sdk/messages.go
- ui/src/app/views/workflow/add/workflow.add.html
> feat: detach fromRepository with force import

- engine/cdn/redis/reader.go
- engine/cdn/redis/reader_test.go
- engine/cdn/redis/writer.go
- engine/cdn/redis/writer_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> test(cdn): add tests for redis reader and writer

- engine/api/api_routes.go
- engine/api/workflow/dao_node_run.go
- engine/api/workflow_run.go
- engine/api/workflow_run_log.go
- engine/cdn/cdn_gc_test.go
- engine/cdn/cdn_item.go
- engine/cdn/cdn_item_test.go
- engine/cdn/cdn_log_engine.go
- engine/cdn/cdn_log_store_test.go
- engine/cdn/cdn_log_tcp_test.go
- engine/cdn/cdn_router.go
- engine/cdn/cdn_test.go
- engine/cdn/item_handler_test.go
- engine/cdn/item_logs_handler.go
- engine/cdn/item_logs_handler_test.go
- sdk/cdn.go
- ui/src/app/model/pipeline.model.ts
- ui/src/app/service/workflow/workflow.service.ts
- ui/src/app/service/workflow/workflow.store.ts
- ui/src/app/views/workflow/graph/workflow.graph.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api,cdn,ui): load all steps (lines count) at once

- engine/api/purge/purge_run.go
- engine/api/worker/dao.go
- engine/api/worker/dao_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(api): do not erase worker private key

- ui/src/app/shared/workflow/modal/hook-add/hook.modal.component.ts
- ui/src/app/shared/workflow/modal/node-add/workflow.trigger.component.ts
- ui/src/app/shared/workflow/modal/node-add/workflow.trigger.html
- ui/src/app/shared/workflow/wizard/node-add/node.wizard.component.ts
- ui/src/app/shared/workflow/wizard/node-add/node.wizard.html
- ui/src/app/shared/workflow/wizard/outgoinghook/wizard.outgoinghook.component.ts
- ui/src/app/shared/workflow/wizard/outgoinghook/wizard.outgoinghook.html
- ui/src/app/views/workflow/graph/workflow.graph.component.ts
- ui/src/app/views/workflow/workflow.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): remove deprecated parentInjector + fix viewChild on modal

- engine/api/application.go
- engine/api/application_test.go
- engine/api/environment.go
- engine/api/environment_ascode_test.go
- engine/api/pipeline.go
- engine/api/pipeline_test.go
- engine/api/workflow_ascode.go
- engine/api/workflow_ascode_test.go
- engine/vcs/bitbucketcloud/client_branch.go
- engine/vcs/bitbucketserver/client_branch.go
- engine/vcs/github/client_branch.go
- engine/vcs/gitlab/client_branch.go
- ui/src/app/shared/ascode/save-form/ascode.save-form.component.ts
- ui/src/app/shared/ascode/save-modal/ascode.save-modal.html
- ui/src/assets/i18n/en.json
> feat: do not let to push ascode on default branch

- engine/api/workflow_run_log.go
- sdk/cdn.go
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui,api): open last step when ok, or first failed step

- ui/src/app/shared/workflow/modal/node-edit/node.edit.modal.html
- ui/src/app/views/workflow/add/workflow.add.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): load pipeline/outgoinghook wizard component

- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
> fix(ui): new log view - check tab

- ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): load last step after getting links

- tests/Makefile
> fix(it): install nc

- ui/extra-webpack.config.js
- ui/src/app/app.component.ts
- ui/src/app/app.module.ts
- ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.component.ts
- ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.html
- ui/src/app/views/navbar/navbar.component.ts
- ui/src/app/views/navbar/navbar.html
- ui/src/app/views/settings/workflow-template/form/workflow-template.form.component.ts
- ui/src/app/views/settings/workflow-template/form/workflow-template.form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): replace sm-checkbox via sui-checkbox

- engine/api/api_test.go
- engine/api/repositories_manager_test.go
- engine/api/workflow/dao_node_run.go
- engine/api/workflow_application.go
- engine/api/workflow_application_test.go
- engine/api/workflow_queue_test.go
- engine/worker/internal/action/builtin_release.go
- engine/worker/internal/action/builtin_release_test.go
- sdk/error.go
> fix(worker): builtin release action

- engine/cache/cache.go
- engine/cache/redis.go
- engine/cdn/lru/redis.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): wrong way to check if item exist in lru

- engine/api/api.go
- engine/api/api_helper.go
- engine/api/auth.go
- engine/api/auth_builtin.go
- engine/api/auth_local.go
- engine/api/auth_test.go
- engine/api/authentication/builtin/builtin.go
- engine/api/authentication/corpsso/corpsso.go
- engine/api/authentication/dao_consumer.go
- engine/api/authentication/github/github.go
- engine/api/authentication/gitlab/gitlab.go
- engine/api/authentication/ldap/ldap.go
- engine/api/authentication/local/driver.go
- engine/api/authentication/oidc/openid.go
- engine/api/authentication/session.go
- engine/api/authentication/test/auth_driver.go
- engine/api/router_middleware_auth.go
- sdk/token.go
- ui/src/app/model/authentication.model.ts
- ui/src/app/store/authentication.state.ts
- ui/src/app/views/navbar/navbar.component.ts
- ui/src/app/views/navbar/navbar.html
- ui/src/assets/i18n/en.json
> feat(api): support MFA with corpsso auth driver

- engine/cdn/storage/cds/cds.go
- engine/cdn/storage/dao.go
- engine/cdn/storage/dao_test.go
- engine/cdn/storage/local/local.go
- engine/cdn/storage/redis/redis.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_run.go
- engine/cdn/storage/storageunit_test.go
- engine/cdn/storage/swift/swift.go
- engine/cdn/storage/types.go
- engine/cdn/storage/webdav/webdav.go
- engine/sql/cdn/003_item_lastmodified.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): workaround do not order by unitID

- engine/cdn/storage/dao.go
- engine/sql/cdn/003_item_lastmodified.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): change index column

- engine/cdn/storage/storageunit.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): slow sync

- engine/sql/cdn/004_storage_unit_item_index.sql
> fix(sql/cdn): add idx_storage_unit_item_unit_id missing index

- engine/cdn/item_logs_handler_test.go
- engine/cdn/storage/cds/cds.go
- engine/cdn/storage/storageunit_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): unit test + enable sync on cds backend

- ui/src/app/shared/vcs/vcs.strategy.component.ts
- ui/src/app/shared/vcs/vcs.strategy.html
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(ui): copy ssh key failed on load

- engine/cdn/storage/dao.go
from Execution time: 4097.985 ms
to Execution time: 909.439 ms
> fix(cdn): optim sync

- engine/cdn/storage/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): improve perf load items to sync using dynamic limit

- engine/vcs/bitbucketserver/client_pull_request.go
> fix(vcs/bitbucket): pull request comment must be less than 32768 chars

- engine/cdn/cdn_item_test.go
- engine/cdn/item_logs_handler_test.go
- engine/cdn/storage/dao.go
- engine/cdn/storage/dao_test.go
- engine/cdn/storage/storageunit.go
- engine/cdn/storage/storageunit_run.go
- engine/cdn/storage/storageunit_test.go
- engine/cdn/storage/types.go
- engine/cdn/types.go
> feat(cdn): sync settings in conf

- engine/cdn/item/dao.go
- engine/sql/cdn/005_percentil.sql
Do we really need to compute all percentil? Is it enough with these ?
@ovh/cds
> fix(cdn): do not compute all percentil + add index

- engine/cdn/cdn_gc.go
- engine/cdn/storage/dao.go
1. Description
Before: 1.6s
After : < 1ms
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): preselect item from buffer before counting

- docs/content/docs/concepts/files/environment-syntax.md
- engine/cdn/item/dao.go
- engine/cmd_start.go
- sdk/error.go
> fix(cdn): percentil compute stats

- engine/cdn/storage/local/local.go
- engine/cdn/storage/storageunit_purge.go
- engine/cdn/storage/swift/swift.go
1. Description
1. About tests
1. Mentions
@ovh/cds
> fix(cdn): manage 404 when deleting from storage

- engine/cdn/cdn_log_tcp.go
> refactor: refreshHatcheriesPK is called by handleServiceLog
