engine/cdn/cdn_log_store.go
engine/cdn/cdn_log_tcp.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): add logs

---

engine/hooks/hooks_handlers.go
engine/migrateservice/service.go

feat(hooks): remove todo status

---

cli/cdsctl/admin_cdn.go
engine/cache/cache.go
engine/cdn/cdn_router.go
engine/cdn/cdn_sync.go
engine/cdn/storage/cds/cds.go
engine/cdn/storage/local/local.go
engine/cdn/storage/redis/redis.go
engine/cdn/storage/storageunit.go
engine/cdn/storage/storageunit_purge.go
engine/cdn/storage/swift/swift.go
engine/cdn/storage/types.go
engine/cdn/storage/webdav/webdav.go
engine/cdn/sync_handler.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): do not use locator research on storage without locator

---

engine/cdn/cdn_sync.go
engine/cdn/cdn_sync_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): err was not available

---

engine/api/workermodel/dao.go
engine/api/workermodel/dao_secret.go
engine/api/workermodel/utils.go
engine/hatchery/openstack/openstack.go
engine/hatchery/vsphere/client.go
engine/hatchery/vsphere/init.go
engine/hatchery/vsphere/ip.go
engine/hatchery/vsphere/spawn.go
engine/hatchery/vsphere/types.go
engine/hatchery/vsphere/vsphere.go
go.mod
go.sum
sdk/hatchery/model.go
sdk/ip.go
sdk/worker_model.go
ui/src/app/model/worker-model.model.ts
ui/src/app/views/settings/worker-model/form/worker-model.form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery:vsphere): update vmware deps + fix auth secrets

---

engine/cdn/cdn_gc_test.go
engine/cdn/cdn_metrics.go
engine/cdn/item/dao.go
engine/cdn/storage/dao.go
engine/cdn/storage/dao_test.go
engine/cdn/storage/storageunit_run.go
engine/sql/cdn/006_add_type_column.sql
sdk/cdn.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): add type in storage_unit_item to avoid join with item

---

engine/cdn/cdn_gc.go
engine/cdn/cdn_gc_test.go
engine/cdn/cdn_item.go
engine/cdn/cdn_item_test.go
engine/cdn/cdn_log_store.go
engine/cdn/cdn_log_store_test.go
engine/cdn/cdn_log_tcp_test.go
engine/cdn/cdn_metrics.go
engine/cdn/cdn_sync.go
engine/cdn/cdn_sync_test.go
engine/cdn/cdn_test.go
engine/cdn/item_handler.go
engine/cdn/item_logs_handler.go
engine/cdn/storage/dao_test.go
engine/cdn/storage/redis/redis.go
engine/cdn/storage/storage_unit_io.go
engine/cdn/storage/storageunit.go
engine/cdn/storage/storageunit_test.go
engine/cdn/storage/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cdn): can have multiple buffer

---

engine/api/workflow.go
engine/api/workflow_run.go

fix(api): return workflow run URLs data

---

sdk/interpolate/interpolate_helper.go
sdk/interpolate/interpolate_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): add func in interpolate helper

---

ui/src/app/shared/workflow/node/run/node.run.param.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): reset format json button for workflow payload

---

ui/src/app/views/workflow/graph/workflow.graph.component.ts
ui/src/app/views/workflow/graph/workflow.graph.html
ui/src/app/views/workflow/run/workflow.run.component.ts
ui/src/app/views/workflow/show/workflow.component.ts
ui/src/app/views/workflow/show/workflow.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): workflow graph no render navigate from run to show

---

ui/angular.json
ui/src/app/service/authentication/logout.interceptor.ts
ui/src/app/shared/workflow-template/apply-modal/workflow-template.apply-modal.component.ts
ui/src/app/shared/workflow-template/bulk-modal/workflow-template.bulk-modal.component.ts
ui/src/app/views/admin/worker-model-pattern/form/worker-model.pattern.form.component.ts
ui/src/app/views/auth/signin/signin.ts
ui/src/app/views/settings/action/add/action.add.component.ts
ui/src/app/views/settings/action/list/action.list.component.ts
ui/src/app/views/settings/group/list/group.list.component.ts
ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.component.ts
ui/src/app/views/settings/user/edit/user.edit.component.ts
ui/src/app/views/settings/user/list/user.list.component.ts
ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts
ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts
ui/src/app/views/settings/worker-model/form/worker-model.form.component.ts
ui/src/app/views/settings/workflow-template/add/workflow-template.add.component.ts
ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts
ui/src/app/views/settings/workflow-template/list/workflow-template.list.component.ts
ui/src/app/views/workflow/graph/workflow.graph.scss
ui/src/app/views/workflow/run/workflow.run.html
ui/src/app/views/workflow/run/workflow.run.scss
ui/src/app/views/workflow/show/workflow.html
ui/src/app/views/workflow/show/workflow.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): errors and warning after dependencies upgrade

---

engine/hooks/kafka.go
sdk/event/kafka_listener.go

fix(hooks): listen with many kafka brokers

---

engine/cache/cache.go
engine/cache/redis.go
engine/cdn/cdn.go
engine/cdn/cdn_gc.go
engine/cdn/cdn_gc_test.go
engine/cdn/cdn_item_test.go
engine/cdn/cdn_log_store.go
engine/cdn/cdn_log_store_test.go
engine/cdn/cdn_log_tcp_test.go
engine/cdn/cdn_sync.go
engine/cdn/cdn_sync_test.go
engine/cdn/cdn_test.go
engine/cdn/item_handler_test.go
engine/cdn/item_logs_handler_test.go
engine/cdn/storage/dao.go
engine/cdn/storage/dao_test.go
engine/cdn/storage/storageunit.go
engine/cdn/storage/storageunit_run.go
engine/cdn/storage/storageunit_test.go
engine/cdn/storage/types.go
engine/cdn/test/test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): use redis to sync item from buffer

---

engine/api/application.go
engine/api/environment.go
engine/api/pipeline.go
engine/elasticsearch/elasticsearch.go
engine/vcs/vcs.go

perf(api): getPipeline / env / app

---

engine/api/api_helper.go
engine/api/router_middleware_auth_permission.go
engine/api/services/cache.go
sdk/error.go
ui/src/app/service/authentication/error.interceptor.ts

feat(api, ui): support 'required_mfa' to access project

---

engine/cdn/cdn_metrics.go
engine/cdn/storage/dao.go
engine/cdn/storage/storage_unit_io.go
engine/cdn/storage/storageunit_purge.go
engine/cdn/storage/storageunit_run.go
engine/sql/cdn/007_index_hash_locator.sql

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): remove slow query on deduplication check + change metric frequence

---

engine/api/application.go
engine/api/environment.go
engine/api/pipeline.go
engine/api/workflow_ascode.go
ui/src/app/app.service.ts
ui/src/app/store/authentication.action.ts
ui/src/app/store/authentication.state.ts
ui/src/app/views/admin/broadcast/add/broadcast.add.component.ts
ui/src/app/views/admin/worker-model-pattern/form/worker-model.pattern.form.component.ts
ui/src/app/views/application/show/admin/application.admin.component.ts
ui/src/app/views/application/show/application.component.ts
ui/src/app/views/environment/show/advanced/environment.advanced.component.ts
ui/src/app/views/environment/show/environment.show.component.ts
ui/src/app/views/home/home.component.ts
ui/src/app/views/pipeline/show/pipeline.show.component.ts
ui/src/app/views/project/show/admin/project.admin.component.ts
ui/src/app/views/project/show/project.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,ui): wrong error check

---

ui/src/app/views/workflow/add/workflow.add.component.ts
ui/src/app/views/workflow/add/workflow.add.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): limit results in repo list

---

sdk/cdsclient/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): stream should return original error

---

engine/worker/internal/handler_cache.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): fix cache push error and retry

---

engine/cdn/storage/dao.go
engine/sql/cdn/008_index_item_status.sql

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cdn): optim for monitoring queries

---

sdk/cdsclient/client_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): worker cache http client

---

docs/content/hosting/ready-to-run/docker-compose/full-example.md
engine/cdn/cdn_metrics.go
engine/cdn/item/dao.go
engine/cdn/status_handler.go
engine/cdn/storage/dao.go
engine/cdn/types.go
engine/gorpmapper/table_mapping.go
engine/sql/cdn/010_index_item_status.sql
sdk/telemetry/telemetry.go
sdk/telemetry/types.go

fix(cdn): compute cdn_items_sync metrics

---

engine/hatchery/hatchery_helper_test.go
engine/hatchery/local/local.go
engine/worker/internal/action/builtin_artifact_download_test.go
engine/worker/internal/action/builtin_artifact_upload_test.go
engine/worker/internal/action/builtin_coverage_test.go
engine/worker/internal/action/builtin_junit_test.go
engine/worker/internal/action/builtin_release_test.go
engine/worker/internal/start_test.go
sdk/cdsclient/client.go
sdk/cdsclient/client_cdn.go
sdk/cdsclient/client_plugins.go
sdk/cdsclient/client_workflow.go
sdk/cdsclient/http.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

fix(hatchery/local): download worker without timeout

---

engine/worker/internal/handler_artifacts.go
engine/worker/internal/handler_cache.go
engine/worker/internal/handler_check_secret.go
engine/worker/internal/handler_download.go
engine/worker/internal/handler_exit.go
engine/worker/internal/handler_export.go
engine/worker/internal/handler_key.go
engine/worker/internal/handler_service.go
engine/worker/internal/handler_tag.go
engine/worker/internal/handler_tmpl.go
engine/worker/internal/handler_tmpl_test.go
engine/worker/internal/handler_upload.go
engine/worker/internal/handler_vulnerability.go
engine/worker/internal/run.go
engine/worker/internal/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): set step data in context in worker handler

---

engine/cdn/cdn.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): start units and lru in service start func

---

engine/api/workflow/dao_node_run.go
engine/api/workflow/dao_node_run_test.go
engine/api/workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): do not load pipeline without logs for CDN migration

---

ui/src/app/views/auth/signin/signin.html

fix(ui): password signup

---

engine/cdn/cdn.go
engine/cdn/cdn_metrics.go
engine/cdn/storage/storageunit.go
engine/cdn/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): add metric generation frequency in cdn configuration

---

engine/sql/cdn/011_index_item_status.sql

fix(cdn): add missing index

---

engine/cdn/cdn_gc.go
engine/cdn/cdn_gc_test.go
engine/cdn/storage/storageunit.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): item can be removed before sync

---

engine/cdn/cdn_sync.go
engine/cdn/status_handler.go

fix(cdn): remove some unused status

---

engine/cdn/cdn.go
engine/cmd_start.go
engine/hatchery/hatchery_local_test.go
engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/local/local.go
engine/hatchery/marathon/marathon.go
engine/hatchery/openstack/openstack.go
engine/hatchery/serve.go
engine/hatchery/swarm/swarm.go
engine/hatchery/vsphere/vsphere.go
engine/service/service.go
engine/service/types.go
sdk/hatchery/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(services): heartbeat when the service was fully started

---

engine/api/workflow/hook.go
engine/api/workflow_run_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): fix git hook update + reset uuid

---

engine/worker/internal/run.go
engine/worker/internal/start_test.go
sdk/log/hook/hook.go
ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html
ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): send terminated step log only for root job actions

---

engine/api/project.go
engine/api/workflow_run_log.go

fix(api): getWorkflowAccessHandler for admin

---

engine/api/workflowtemplate/execute.go

fix(api): improve display err on wf template apply to user

---

engine/cdn/storage/dao.go
engine/cdn/storage/storageunit_purge.go
tests/test.sh

fix(cdn): avoid panic on purge

---

engine/hatchery/vsphere/init.go
sdk/hatchery/hatchery.go

fix(hatchery/vsphere): login with context, add logs

---

docs/content/docs/components/cdn/_index.md
engine/cdn/cdn.go
engine/cdn/item_handler.go
engine/cdn/storage/s3/s3.go
engine/cdn/storage/s3/s3_test.go
engine/cdn/storage/storageunit.go
engine/cdn/storage/types.go
sdk/cdn.go

feat(cdn): support AWS s3 as storage driver

---

engine/cdn/cdn_gc.go

fix(cdn): add some log on gc

---

engine/hatchery/kubernetes/helper_test.go
engine/hatchery/kubernetes/kill_workers.go
engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/kubernetes/kubernetes_client.go
engine/hatchery/kubernetes/secrets.go
engine/hatchery/kubernetes/services.go
engine/hatchery/kubernetes/types.go

* new interface to have a cleaner interface to k8s API
* don't get the namespace at startup (to reduce the expected roles in k8s RBAC)
* don't try to create the namespace (to reduce the expected roles in k8s RBAC)

feat(hatchery/kubernetes): various improvement

---

engine/cdn/cdn_gc.go

fix(cdn): id log

---

engine/hatchery/vsphere/client.go
engine/hatchery/vsphere/init.go
engine/hatchery/vsphere/ip.go
engine/hatchery/vsphere/spawn.go
engine/hatchery/vsphere/vsphere.go
sdk/hatchery/starter.go

fix(hatchery/vsphere): add logs, context and stacktrace

---

engine/cdn/cdn_gc.go
engine/cdn/storage/dao.go
engine/cdn/storage/storageunit_run.go
engine/gorpmapper/encryption.go

fix(cdn): fix some logs

---

engine/hatchery/vsphere/spawn.go

feat(hatchery/vsphere): add logs in createVMModel function

---

engine/cdn/storage/dao.go
engine/cdn/storage/storageunit_purge.go

fix(cdn): continue purge if err

---

engine/hatchery/vsphere/client.go
engine/hatchery/vsphere/spawn.go
engine/hatchery/vsphere/vsphere.go

feat(hatchery/vsphere): add logs in launchClientOp

---

tests/test.sh

fix(it): check result it

---

engine/hatchery/vsphere/client.go
engine/hatchery/vsphere/spawn.go

feat(hatchery/vshpere): add result logs of launchClientOp

---

engine/api/purge/purge.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): remove old workflow run code purge

---

engine/Makefile
engine/hatchery/vsphere/client.go

chore(test): fix find warning in Makefile

---

engine/Makefile
engine/api/admin_test.go
engine/api/api.go
engine/api/api_test.go
engine/api/workflow/dao.go
engine/api/workflow/init.go
engine/api/workflowtemplate/execute_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

test: fix for go 1.16

---

ui/src/common.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): add border to avoid invisible input

---

engine/cdn/cdn.go
engine/hooks/hooks.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks,cdn): remove log.Fatal to properly stop services

---

Makefile
docs/config.toml
docs/content/development/contribute/documentation.md
docs/content/development/contribute/hatchery.md
docs/content/development/contribute/plugin.md
docs/content/docs/concepts/variables.md
docs/content/docs/concepts/workflow/notifications.md
docs/content/docs/integrations/kafka/kafka_events.md
docs/content/hosting/database.md
docs/content/hosting/ready-to-run/docker-compose/docker-compose.md
docs/layouts/shortcodes/children.html
docs/layouts/shortcodes/expand.html
docs/layouts/shortcodes/feature.html
docs/layouts/shortcodes/matrix.html
docs/layouts/shortcodes/note.html
docs/layouts/shortcodes/notice.html
docs/layouts/shortcodes/param.html
docs/layouts/shortcodes/section.html

1. Description
1. About tests
1. Mentions
@ovh/cds

docs: allow to overrides GH links version

---

engine/api/status.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): change metric values for workflow run count

---

engine/hatchery/kubernetes/services.go
engine/hatchery/kubernetes/services_test.go
engine/hatchery/swarm/swarm_util_logs.go
engine/hatchery/swarm/swarm_util_logs_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): wait for worker registered before sending service logs

---

contrib/grpcplugins/action/plugin-archive/go.sum
contrib/grpcplugins/action/plugin-clair/go.sum
contrib/grpcplugins/action/plugin-download/go.sum
contrib/grpcplugins/action/plugin-group-tmpl/go.sum
contrib/grpcplugins/action/plugin-kafka-publish/go.sum
contrib/grpcplugins/action/plugin-marathon/go.sum
contrib/grpcplugins/action/plugin-npm-audit-parser/go.sum
contrib/grpcplugins/action/plugin-ssh-cmd/go.sum
contrib/grpcplugins/action/plugin-tmpl/go.sum
contrib/grpcplugins/action/plugin-venom/go.sum
engine/Makefile
engine/cmd_start.go
engine/main_test.go
go.mod
go.sum
tests/args.file

1. Description
1. About tests
1. Mentions
@ovh/cds

test: build test binary

---

sdk/cdsclient/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): stream func should use httpclient from its args

---

engine/worker/internal/action/builtin_checkout_application_test.go
engine/worker/internal/action/builtin_gitclone.go
engine/worker/internal/action/builtin_gitclone_test.go
engine/worker/internal/start_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): compute cds semver var from cds run number

---

ui/src/app/views/workflow/show/workflow.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): wrong pipeline parameters displayed

---

engine/api/workflow/process_requirements.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): error when no worker model can be loaded

---

engine/api/admin.go
engine/api/cdn/item.go
engine/api/repositoriesmanager/repositories_manager.go
engine/api/services/external.go
engine/api/services/http.go
engine/api/workflow_application.go
engine/vcs/bitbucketcloud/client_release.go
engine/vcs/bitbucketserver/client_release.go
engine/vcs/gerrit/client_release.go
engine/vcs/github/client_hook.go
engine/vcs/github/client_pull_request.go
engine/vcs/github/client_release.go
engine/vcs/github/client_status.go
engine/vcs/github/http.go
engine/vcs/gitlab/client_release.go
engine/vcs/vcs_handlers.go
go.mod
sdk/vcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): upload artifact for vcs release

---

engine/worker/cmd_tag.go
engine/worker/internal/action/builtin_script.go
engine/worker/internal/handler_tag.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: change error to have more details

---

engine/api/workflow/workflow_run_results.go
engine/api/workflow_queue.go
engine/cdn/cdn_item.go

fix(api): missing errors checking

---

engine/hooks/gerrit.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: error condition

---

engine/cmd_download.go

fix(engine): download - check config

---

engine/cdn/cdn_gc.go
engine/cdn/cdn_gc_test.go
engine/cdn/cdn_test.go
engine/cdn/item_upload_test.go
engine/cdn/storage/dao.go
engine/cdn/storage/storageunit.go
engine/cdn/storage/storageunit_purge.go
engine/cdn/storage/types.go
engine/cdn/unit_handler_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): do not select all database for item unit purge

---

engine/hooks/tasks.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks): add log on from hook

---

engine/api/repositories_manager.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): improve error for callback repo manager

---

cli/cdsctl/Makefile
cli/cdsctl/main_test.go
cli/cobra.go
tests/.gitignore
tests/04_sc_workflow_simple_serve.yml
tests/Makefile
tests/cdsctl_wrapper.sh

1. Description
1. About tests
1. Mentions
@ovh/cds

test: allow to wrap cdsctl calls in it tests to compute coverage

---

engine/cdn/cdn_gc.go
engine/cdn/cdn_item.go
engine/cdn/item_handler.go
engine/cdn/storage/cds/cds.go
engine/cdn/storage/local/buffer.go
engine/cdn/storage/local/local.go
engine/cdn/storage/nfs/nfs.go
engine/cdn/storage/redis/redis.go
engine/cdn/storage/s3/s3.go
engine/cdn/storage/storage_unit_io.go
engine/cdn/storage/swift/swift.go
engine/cdn/storage/types.go
engine/cdn/storage/webdav/webdav.go
ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn,ui): fix download run-result + clean buffer

---

docs/content/docs/integrations/github/github_authentication.md
docs/content/docs/integrations/github/github_repository_manager.md
docs/content/hosting/ready-to-run/docker-compose/docker-compose.md
docs/content/hosting/ready-to-run/from-binaries.md
engine/api/api.go
engine/vcs/types.go

doc: fix page ref to configure github vcs

---

engine/hatchery/kubernetes/kill_workers.go
engine/hatchery/marathon/marathon.go
engine/hatchery/openstack/openstack.go
engine/hatchery/swarm/swarm_util_kill.go
engine/hatchery/vsphere/client.go
sdk/hatchery/register.go

fix(hatchery): double check flag need registration

---

cli/cdsctl/workflow_status.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cli): search by commit instead of run number

---

ui/package.json

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): update prismjs

---

engine/cdn/cdn_sync_test.go
engine/cdn/storage/storageunit.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cdn): requires at least one storage that is not cds

---

engine/api/purge/purge_run.go
engine/api/purge/purge_test.go
sdk/luascript/luascript.go
sdk/luascript/luascript_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): strict variable usage for lua, check result is bool

---

go.mod
go.sum

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): update nfs client

---

sdk/cdsclient/client_workflow.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

feat(sdk): add WorkflowNodeRunJobStepLinks func

---

engine/worker/internal/action/builtin_coverage.go
sdk/action/coverage.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(worker): allow all coverage reports to be uploaded in CDN

---

docs/content/docs/concepts/workflow/retention.md
engine/api/purge/purge_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add has_git_branch variable to purge

---

sdk/cdsclient/client_workflow.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

fix(sdk): WorkflowNodeRunJobStepLinks

---

engine/api/workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: build is failing due to conflict

---

engine/worker/cmd_register.go
engine/worker/cmd_run.go
engine/worker/internal/register.go
sdk/log/log.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): flush graylog hook logs when run or register ends

---

engine/hatchery/vsphere/hatchery.go
engine/hatchery/vsphere/hatchery_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery:vsphere): kill awol already used provisioned workers

---

ui/src/app/shared/workflow/node/run/node.run.param.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): use node pipeline parameters from run's workflow data

---

engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/local/worker_spawn.go
engine/hatchery/marathon/marathon.go
engine/hatchery/openstack/spawn.go
engine/hatchery/serve.go
engine/hatchery/swarm/swarm.go
engine/hatchery/vsphere/spawn.go
engine/service/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery): allow to set specific api url for workers

---

cli/cdsctl/Makefile
engine/Makefile

1. Description
1. About tests
1. Mentions
@ovh/cds

chore: all go package in coverage

---

engine/service/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): bad toml key for workerApiHttp

---

ui/src/app/shared/workflow/wnode/outgoinghook/node.outgoinghook.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): add outgoing ui in ascode workflow

---

tests/test.sh

test: xunit venom output

---

ui/src/app/views/auth/callback/callback.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): handle fragment auth callback

---

engine/ui/ui_router.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): check proxy empty config

---

engine/api/workflowtemplate/instance.go
engine/vcs/types.go
ui/package.json
ui/src/app/shared/pipes/safeHtml.pipe.spec.ts
ui/src/app/shared/pipes/safeHtml.pipe.ts
ui/src/app/views/workflow/run/node/pipeline/step/step.log.component.ts
ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.html

chore(ui): ansi_up bump

---

sdk/cdsclient/client_cdn.go
sdk/cdsclient/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): improve error log on seek error

---

engine/api/api_routes.go
engine/api/status.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: /mon/status returns details only for maintainer

---

sdk/workflow_run_result.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): do not check empty size for artifact

---

engine/api/status.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): return public status with maintenance flag

---

engine/api/router.go

fix(api): set the stacktrace as a field

---

ui/src/app/views/auth/callback/callback.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): signin callback redirect only on other pages

---

engine/config.go
engine/hatchery/hatchery_local_test.go
engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/kubernetes/kubernetes_test.go
engine/hatchery/local/worker_spawn.go
engine/hatchery/marathon/marathon.go
engine/hatchery/openstack/spawn.go
engine/hatchery/serve.go
engine/hatchery/swarm/swarm.go
engine/hatchery/vsphere/spawn.go
engine/service/types.go
sdk/worker.go

feat(hatchery): inject env variables into workers from hatchery config

---

engine/hatchery/kubernetes/kubernetes_test.go

test(hatchery): fix TestHatcheryKubernetes_Status

---

ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): artifact download links

---

engine/cdn/storage/nfs/nfs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): finfo.Name is always empty

---

engine/cdn/unit_handler.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): resync backend use wrong unit

---

engine/cdn/cdn_item.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: increase time for read an item

---

engine/api/environment/environment_parser.go

fix(engine): env ascode with many secrets

---

engine/api/workflow_run.go
sdk/parameter.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): missing app secret for git checkout with https

---

engine/cdn/cdn_gc_test.go
engine/cdn/storage/dao.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): select item inside at least n storage_unit

---

engine/api/api.go
engine/api/status.go
engine/cdn/cdn_metrics.go

fix(api,cdn): restart some goroutines

---

engine/main.go
engine/worker/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker,engine): return 1 when command not found

---

contrib/grpcplugins/action/plugin-archive/go.mod
contrib/grpcplugins/action/plugin-archive/go.sum
contrib/grpcplugins/action/plugin-archive/main.go
contrib/grpcplugins/action/plugin-archive/plugin-archive.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib): Updated plugin-archive

---

docs/content/hosting/upgrade/migrate_0.49.md

1. Description
1. About tests
1. Mentions
@ovh/cds

docs: disable and remove cdn unit

---

ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): spawninfo polling wait for request end

---

contrib/integrations/Makefile

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: build all artifactory integration plugins

---

engine/api/workflow/dao.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(engine): set model on workflow integration

---

engine/worker/internal/http_server.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): remove srv timeout

---

engine/cdn/cdn_gc.go
engine/cdn/cdn_gc_test.go
engine/cdn/item/dao.go
engine/cdn/storage/storageunit.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): do not stack purge goroutine

---

engine/api/api_routes.go
engine/api/group.go
engine/api/group/crud.go
engine/api/group_test.go
engine/gorpmapper/dao.go
ui/src/app/service/group/group.service.ts
ui/src/app/shared/variable/list/variable.component.ts
ui/src/app/views/settings/group/edit/group.edit.component.ts
ui/src/app/views/settings/group/edit/group.edit.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): fix variable audit + group project usage

---

engine/api/purge/purge_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(engine): add debug log on purge

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): do not add same pattern twice

---

contrib/integrations/artifactory/plugin-artifactory-build-info/main.go
engine/worker/cmd_run_result.go
sdk/integration.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib,engine): add artifact manager project key

---

engine/api/purge/purge_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): load application when loading workflow

---

engine/sql/cdn/014_cdn_type_index.sql

Fix migration file cdn 014
@ovh/cds

fix(migration) add missed ; on cdn 014

---

ui/.eslintrc.json
ui/src/app/views/project/show/project.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): allow to edit new integration parameters

---

engine/api/purge/purge_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(engine): do not load all applications with workflow

---

engine/cdn/item/dao.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): update query to use index

---

ui/src/app/app.component.ts
ui/src/app/app.service.ts
ui/src/app/event.service.ts
ui/src/app/store/cds.state.ts
ui/src/app/store/workflow.state.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): handle events sequentially

---

engine/api/pipeline/pipeline_importer.go
engine/config.go

fix(hatchery/swarm): default value docker.sock

---

engine/worker/internal/action/builtin_coverage.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): upload coverage in artifactory

---

engine/api/purge/purge_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(engine): app is already define above

---

engine/cdn/storage/storageunit.go
engine/cdn/storage/storageunit_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): reduce transaction duration

---

docs/content/docs/integrations/_index.md
docs/content/docs/integrations/artifact-manager.md

1. Description
1. About tests
1. Mentions
@ovh/cds

docs: add doc on artifactory integration

---

engine/cdn/storage/nfs/nfs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): do not compute size from hidden directory

---

engine/sql/cdn/015_cdn_idx_clean.sql

refactor(cdn): clean some unused idx

---

engine/vcs/bitbucketserver/oauth_consumer.go

refactor(vcs): remove useless cache vcs consumer

---

engine/vcs/bitbucketserver/http.go
engine/vcs/vcs_handlers.go

fix(vcs): renew token logs

---

engine/api/api.go
engine/api/purge/purge.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(engine): add parameter to disable workflow run purge

---

engine/vcs/bitbucketserver/http.go
engine/vcs/vcs_handlers.go

fix(vcs): getBranches logs

---

docs/content/docs/concepts/requirement/requirement_os_arch.md
engine/api/api.go
engine/vcs/bitbucketserver/oauth_consumer_helper.go

fix(vcs): nonce

---

ui/src/app/shared/workflow/wnode/wnode.component.ts

fix(ui): link to the outoing hook wf on another prj

---

engine/worker/cmd_upload.go
engine/worker/internal/action/builtin_artifact_upload.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): tag is no more required with CDN artifact management

---

cli/cdsctl/queue.go
engine/api/workflow/dao_node_job_run_info.go
engine/api/workflow/dao_node_run_job.go
engine/api/workflow/execute_node_job_run.go
engine/api/workflow/execute_node_run.go
engine/api/workflow/gorp_model.go
engine/api/workflow_queue.go
engine/api/workflow_queue_test.go
engine/api/workflow_run.go
engine/sql/api/228_workflow_node_job_run_region.sql
sdk/cdsclient/client_queue.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/hatchery/hatchery.go
sdk/workflow_run.go
ui/src/app/model/workflow.run.model.ts
ui/src/app/views/settings/queue/queue.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,hatchery): add region filter for job list handler

---

engine/sql/api/228_workflow_node_job_run_region.sql
engine/sql/api/229_workflow_node_job_run_region_index.sql

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sql): job run region index should not be unique

---

sdk/hatchery/hatchery_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

test(hatchery): fix unit test hatchery.TestCreate

---

engine/api/workflow/dao.go
engine/api/workflow/execute_outgoing_hook_run.go
engine/api/workflow_hook.go
engine/api/workflow_queue.go
engine/api/workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): recursively stop parent run using workflow hook

---

engine/hatchery/marathon/marathon.go
engine/hatchery/marathon/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery:marathon): allow to set uris for new applications

---

contrib/integrations/artifactory/plugin-artifactory-build-info/main.go
contrib/integrations/artifactory/plugin-artifactory-release/main.go

* PushBuildInfo can be re run if release has not been run
* Release can be re run
* Distribution is sync with a 10mn timeout
@ovh/cds

feat(artifactory): allow to re run actions

---

contrib/integrations/artifactory/plugin-artifactory-build-info/main.go
contrib/integrations/artifactory/plugin-artifactory-release/main.go
contrib/integrations/artifactory/plugin-artifactory-upload-artifact/main.go
sdk/integration.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: start moving build.info.path inside project integration configuration

---

engine/hatchery/swarm/swarm.go
engine/hatchery/swarm/swarm_util_create.go
engine/hatchery/swarm/swarm_util_pull.go
go.mod

fix(hatchery/swarm): improve spawn error message on docker pull

---

.build/core.mk
.build/go.mk
cli/cdsctl/Makefile
contrib/grpcplugins/action/examples/nodejs/Makefile
contrib/integrations/arsenal/plugin-arsenal/Makefile
contrib/integrations/artifactory/plugin-artifactory-build-info/Makefile
contrib/integrations/artifactory/plugin-artifactory-download-artifact/Makefile
contrib/integrations/artifactory/plugin-artifactory-release/Makefile
contrib/integrations/artifactory/plugin-artifactory-upload-artifact/Makefile
contrib/integrations/hello/plugin-hello-deployment/Makefile
contrib/integrations/kubernetes/plugin-kubernetes/Makefile
engine/Makefile
engine/api/download/download.go
engine/worker/Makefile
tests/test.sh
tools/debpacker/Makefile
tools/os-ansible-inventory/Makefile
ui/Makefile

1. Description
1. About tests
1. Mentions
@ovh/cds

chore: use cds.version everywhere 

---

docs/actions/builtin-pushBuildInfo.part.md
docs/actions/builtin-release.part.md

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(doc): add missing builtin actions

---

sdk/interpolate/interpolate.go

When using [venom](https://github.com/ovh/venom) I found the performance to be not as good as I hoped and used [pprof](https://go.dev/blog/pprof) to try to find some places where it can be improved. Venom seems to use `interpolate.Do` a lot, so I looked if there's anything to improve and found something that seems safe and doesn't make the code more complex:
Instead of allocating new maps, the existing ones can be reused. Deleting the keys while ranging over a map is safe in Go, see the section in [Effective Go](https://golang.org/doc/effective_go#for):
> ```go
> for key := range m {
>     if key.expired() {
>         delete(m, key)
>     }
> }
> ```
Previous benchmark:
```
$ go test -run=XXX -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: github.com/ovh/cds/sdk/interpolate
cpu: …
```

Reduce memory allocations in interpolation

---

engine/api/download/download.go
sdk/download.go

fix: overwrite binary if already exists

---

engine/vcs/bitbucketcloud/client_branch.go
engine/vcs/gerrit/client_branch.go
engine/vcs/gitlab/client_branch.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): add get default branch for each vcs manager

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go
sdk/action/release.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib): allow to add suffix on release name

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: update release action, do not move artifacts

---

sdk/exportentities/pipeline_test.go
sdk/exportentities/step.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): manage release action as code

---

contrib/integrations/Makefile
contrib/integrations/artifactory/artifactory.go
contrib/integrations/artifactory/plugin-artifactory-build-info/main.go
contrib/integrations/artifactory/plugin-artifactory-promote/Makefile
contrib/integrations/artifactory/plugin-artifactory-promote/main.go
contrib/integrations/artifactory/plugin-artifactory-promote/plugin-artifactory-promote.yml
contrib/integrations/artifactory/plugin-artifactory-release/main.go
docs/actions/builtin-promote.part.md
docs/content/docs/integrations/artifact-manager.md
engine/worker/internal/action/builtin_promote.go
engine/worker/internal/builtin.go
sdk/action.go
sdk/action/action.go
sdk/action/promote.go
sdk/exportentities/pipeline_test.go
sdk/exportentities/step.go
sdk/integration.go
sdk/plugin.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib,sdk): add promotion action

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): add new line

---

cli/cdsctl/encrypt.go
engine/api/api_routes.go
engine/api/project/key.go
engine/api/project_variable.go
engine/api/project_variable_test.go
sdk/cdsclient/client_project_variable.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

feat(api,cli): delete secret from commandline

---

cli/cdsctl/config.go
cli/cdsctl/main.go

feat(cli): max number of retries for HTTP calls from env variable

---

cli/cdsctl/workflow_artifact.go
cli/cdsctl/workflow_log.go
cli/cdsctl/workflow_run_result.go
sdk/cdsclient/client.go
sdk/cdsclient/http.go

fix(cli): various fixes about errors

---

engine/vcs/types.go
engine/vcs/vcs.go

fix(vcs): remove UI URL from config, get it by API call

---

engine/api/workflow/execute_node_run.go
engine/api/workflow/process_requirements.go
sdk/integration.go
ui/src/app/views/project/show/integrations/list/project.integration.list.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(engine): add region requirement on integration

---

sdk/hatchery/hatchery.go
sdk/hatchery/starter.go
sdk/telemetry/telemetry.go
sdk/telemetry/types.go

feat(service): ability to set jaeger servicename

---

contrib/integrations/artifactory/plugin-artifactory-upload-artifact/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): do not use old param anymore

---

engine/api/notification/user.go
tests/04_sc_workflow_run_notif.yml
tests/fixtures/04SCWorkflowRunNotif/workflow.yml

feat(api): allow variable interpolation in notification recipients

---

engine/api/workflow/execute_node_run.go
engine/api/workflow_queue.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): add debug log for constraint error on worker table

---

engine/api/authentication/corpsso/corpsso.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): create username from user fullname

---

contrib/grpcplugins/action/plugin-archive/go.sum
contrib/grpcplugins/action/plugin-clair/go.sum
contrib/grpcplugins/action/plugin-download/go.sum
contrib/grpcplugins/action/plugin-group-tmpl/go.sum
contrib/grpcplugins/action/plugin-kafka-publish/go.sum
contrib/grpcplugins/action/plugin-marathon/go.sum
contrib/grpcplugins/action/plugin-npm-audit-parser/go.sum
contrib/grpcplugins/action/plugin-ssh-cmd/go.sum
contrib/grpcplugins/action/plugin-tmpl/go.sum
contrib/grpcplugins/action/plugin-venom/go.sum
go.mod
go.sum

1. Description
1. About tests
1. Mentions
@ovh/cds

chore: upgrade to go-repo v0.1.10

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): remove default suffix

---

ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): refresh on notification

---

engine/sql/api/230_vulnerability_title.sql

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sql): increase column size

---

engine/hatchery/local/worker_spawn.go

fix(hatchery:local): unable to run worker cmd: context cancelled

---

engine/repositories/processor_push.go

fix(repositories): error management when push fails

---

contrib/grpcplugins/action/plugin-archive/go.sum
contrib/grpcplugins/action/plugin-clair/go.sum
contrib/grpcplugins/action/plugin-download/go.sum
contrib/grpcplugins/action/plugin-group-tmpl/go.sum
contrib/grpcplugins/action/plugin-kafka-publish/go.sum
contrib/grpcplugins/action/plugin-marathon/go.sum
contrib/grpcplugins/action/plugin-npm-audit-parser/go.sum
contrib/grpcplugins/action/plugin-ssh-cmd/go.sum
contrib/grpcplugins/action/plugin-tmpl/go.sum
contrib/grpcplugins/action/plugin-venom/go.sum
engine/cdn/cdn_item_test.go
engine/cdn/cdn_log_store.go
engine/cdn/redis/reader.go
engine/cdn/redis/writer.go
engine/cdn/storage/redis/redis.go
engine/cdn/storage/storageunit_test.go
engine/cdn/storage/types.go
go.mod
go.sum
sdk/common.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): move log 'since' value from score to data in Redis

---

engine/hooks/bitbucket_cloud.go
engine/hooks/bitbucket_server.go
engine/hooks/github.go
engine/hooks/gitlab.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks): skip branch deletion events

---

.gitignore
ui/Makefile
ui/angular.json
ui/karma.conf.js
ui/package.json
ui/semantic/src/site/globals/site.variables
ui/src/styles.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): use local fonts

---

sdk/doc/generate.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(doc): see also link to root command

---

ui/src/app/views/settings/action/add/action.add.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): cast in string during action creation

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib):  use markdown as default release note format

---

cli/cdsctl/project_integration.go
engine/worker/internal/run.go
engine/worker/internal/start_test.go
engine/worker/internal/types.go
sdk/cdsclient/client_project_integration.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

feat(worker): execute worker hooks

---

engine/worker/cmd_run_result.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): remove null logs

---

ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): display job variables is empty

---

engine/worker/internal/action/builtin_junit.go

fix(worker): warn for invalid junit file

---

engine/worker/internal/run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): init worker hooks directory

---

contrib/integrations/arsenal/plugin-arsenal/main.go
contrib/integrations/hello/hello.yml
contrib/integrations/hello/plugin-hello-deployment/Makefile
contrib/integrations/hello/plugin-hello-deployment/main.go
contrib/integrations/kubernetes/kubernetes.yml
engine/api/grpc_plugin.go
engine/api/plugin/dao.go
engine/api/plugin/dao_test.go
engine/api/plugin/gorp_model.go
engine/api/plugin/loader.go
engine/api/plugin/plugin.go
engine/api/project_integration.go
engine/api/workflow/execute_node_run.go
engine/api/workflow/gorp_model.go
engine/api/workflow/process_requirements.go
sdk/plugin.go
tests/fixtures/ITSCWRKFLW15/simple-integ.yml
tests/fixtures/integrations/hello-it.yml
tests/fixtures/integrations/marathon.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): select requirements from plugin binary depending os/arch

---

engine/api/purge/purge_run.go

fix(api): check vcsclient

---

engine/worker/internal/run.go

fix(worker): skip hooks on worker

---

engine/hatchery/swarm/swarm.go
engine/hatchery/swarm/swarm_conf.go
engine/hatchery/swarm/swarm_test.go
engine/hatchery/swarm/swarm_util_create_test.go
engine/hatchery/swarm/swarm_util_get.go
engine/hatchery/swarm/swarm_util_get_test.go
engine/hatchery/swarm/swarm_util_kill.go
engine/hatchery/swarm/swarm_util_logs.go
engine/hatchery/swarm/swarm_util_logs_test.go
engine/hatchery/swarm/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(harchery:swarm): improve stability when sharing host

---

sdk/workflowv3/convert.go
sdk/workflowv3/convert_run.go
sdk/workflowv3/job.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): simplify job name in workflow v3 export

---

engine/worker/internal/run.go
engine/worker/internal/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): base dir + env variable

---

ui/package.json
ui/src/app/shared/permission/list/permission.list.html
ui/src/app/views/project/show/project.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): display permissions tabs

---

engine/api/workflow/execute_node_run.go
engine/api/workflow/run_workflow.go
engine/api/workflow_run.go
engine/api/workflow_run_test.go
sdk/messages.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add more info on region check

---

engine/api/api_routes.go
engine/api/auth.go
sdk/workflowv3/convert.go
ui/src/app/shared/workflow/node/hook/details/hook.details.component.html
ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): workflow v3 job name generate

---

engine/hooks/gerrit.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: add more logs on gerrit stream event

---

sdk/workflowv3/artifact_manager.go
sdk/workflowv3/convert.go
sdk/workflowv3/convert_run.go
sdk/workflowv3/workflow.go
sdk/workflowv3/workflow_run.go
ui/src/app/model/workflow.run.model.ts
ui/src/app/service/workflow/run/workflow.run.service.ts
ui/src/app/service/workflow/workflow.helper.ts
ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts
ui/src/app/views/workflowv3/graph/workflowv3-stages-graph.component.ts
ui/src/app/views/workflowv3/run/workflowv3-run-job.component.ts
ui/src/app/views/workflowv3/run/workflowv3-run.component.ts
ui/src/app/views/workflowv3/run/workflowv3-run.html
ui/src/app/views/workflowv3/run/workflowv3-run.scss
ui/src/app/views/workflowv3/workflowv3.model.ts
ui/src/app/views/workflowv3/workflowv3.module.ts
ui/src/app/views/workflowv3/workflowv3.run.service.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui,api): display run results in workflow v3 preview

---

engine/worker/cmd_artifacts.go
engine/worker/cmd_cache.go
engine/worker/cmd_cds_version_set.go
engine/worker/cmd_check_secret.go
engine/worker/cmd_download.go
engine/worker/cmd_exit.go
engine/worker/cmd_export.go
engine/worker/cmd_key.go
engine/worker/cmd_run_result.go
engine/worker/cmd_tag.go
engine/worker/cmd_tmpl.go
engine/worker/cmd_upload.go
engine/worker/internal/handler_tmpl_test.go
engine/worker/internal/http_server.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): error management on worker cmd

---

engine/api/auth.go
engine/api/auth_test.go
engine/api/authentication/corpsso/corpsso.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): store user organization on signup

---

engine/api/api_routes.go
engine/api/router_middleware_auth_permission.go
engine/api/router_middleware_auth_permission_test.go
engine/api/workflow_queue_test.go
engine/api/workflow_run.go
engine/api/workflow_run_artifact.go
engine/api/workflow_run_log.go
engine/api/workflow_run_result_test.go
sdk/doc/route.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): worker download cross workflow for same project

---

engine/api/workflow_hook.go
engine/api/workflow_queue.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): loading organization on project to check region usage

---

engine/api/workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): check region load organization after workflow outgoing hook

---

contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/main.go
contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/plugin-artifactory-release-bundle-distribute.yml
contrib/integrations/artifactory/plugin-artifactory-release/edge/edge.go
contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): distribute on all edges to avoid deleting artifacts linked to a release bundle from master

---

engine/worker/internal/run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): add log on teardown error

---

ui/src/assets/i18n/en.json

1. Description
A simple english typo
@ovh/cds

fix(ui): typo in pipeline wizard

---

contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/main.go
contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/main.go
contrib/integrations/artifactory/artifactory.go
contrib/integrations/artifactory/plugin-artifactory-release/edge/edge.go
contrib/integrations/artifactory/plugin-artifactory-release/main.go
sdk/integration.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib): allow to specify a distribution url + manage full access token

---

docs/content/hosting/ready-to-run/from-binaries.md

Signed-off-by: Jean-Louis QUEGUINER jlqueguiner@gladia.io
Fix typo in install from binaries docs
@ovh/cds

[FIX][DOC] Fix typo in install from binaries

---

engine/api/status.go

fix(api): set now 'field' in /mon/status

---

engine/sql/api/223_rename_release_action.sql
engine/sql/api/231_workflow_delete_dependencies.sql

1. Description
Semilicons missed, i fix it
@ovh/cds

fix(migrations): fix missed semilicon

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): fail if there is no artifacts on a release

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

fix(contrib): typo in artifactory log

---

engine/api/workflow_group.go
engine/api/workflow_group_test.go
engine/service/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add checks for workflow groups

---

sdk/integration.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib): add repo prefix in artifactory integration

---

contrib/integrations/arsenal/arsenal.yml
contrib/integrations/arsenal/plugin-arsenal/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(contrib): support for alternative in plugin-arsenal

---

engine/api/group/group_permission.go
engine/api/group/workflow_group_test.go
engine/api/project_group.go
engine/api/workflow_group.go
ui/src/app/shared/permission/form/permission.form.component.ts
ui/src/app/shared/permission/form/permission.form.html
ui/src/app/shared/permission/form/permission.form.scss
ui/src/app/shared/permission/form/workflow-permission.form.component.ts
ui/src/app/shared/permission/form/workflow-permission.form.html
ui/src/app/shared/permission/form/workflow-permission.form.scss
ui/src/app/shared/shared.module.ts
ui/src/app/shared/workflow/modal/node-edit/node.edit.modal.html
ui/src/app/views/workflow/show/workflow.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): allow to enter group name manually for project

---

contrib/grpcplugins/action/plugin-archive/go.sum
contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/go.sum
contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/go.sum
contrib/grpcplugins/action/plugin-download/go.sum
contrib/grpcplugins/action/plugin-group-tmpl/go.sum
contrib/grpcplugins/action/plugin-kafka-publish/go.sum
contrib/grpcplugins/action/plugin-marathon/go.sum
contrib/grpcplugins/action/plugin-npm-audit-parser/go.sum
contrib/grpcplugins/action/plugin-ssh-cmd/go.sum
contrib/grpcplugins/action/plugin-tmpl/go.sum
contrib/grpcplugins/action/plugin-venom/go.sum
go.mod
go.sum
tests/fixtures/04SCWorkflowRunSimplePlugin/go.sum

chore: bump github.com/docker/distribution

---

engine/api/workflow_event.go
sdk/event.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add pipeline name to event job summary

---

engine/hatchery/vsphere/init.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): remove log

---

ui/src/app/views/workflow/show/notification/form/workflow.notification.form.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): allow to edit notifications without pipelines

---

contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/main.go
contrib/integrations/artifactory/artifactory.go
contrib/integrations/artifactory/plugin-artifactory-build-info/main.go
contrib/integrations/artifactory/plugin-artifactory-download-artifact/main.go
contrib/integrations/artifactory/plugin-artifactory-promote/main.go
contrib/integrations/artifactory/plugin-artifactory-release/main.go
contrib/integrations/artifactory/plugin-artifactory-upload-artifact/main.go
engine/vcs/bitbucketserver/bitbucketserver_test.go

feat(contrib/artifactory): enable xray build scan through project variable

---

engine/api/workflowtemplate/instance.go

fix(api): allow hooks to apply template

---

sdk/luascript/luascript.go

feat(sdk): improve luascript performance

---

engine/api/download.go
engine/api/user.go
engine/api/user_test.go
sdk/common.go
sdk/common_test.go
sdk/download.go
ui/src/app/views/settings/user/edit/user.edit.html

fix(api,ui): download worker route + user profile form

---

engine/api/router_middleware_auth_permission.go

fix(api): getWorkerModelSecretHandler permission

---

engine/api/api_routes.go
engine/api/workflow_hook.go

fix(api): let hooks call getWorkflowJobHookDetailsHandler

---

engine/hatchery/openstack/types.go

feat(hatchery:openstack): default api is v3

---

engine/api/application.go
engine/api/ascode.go
engine/api/ascode/pull_request.go
engine/api/ascode/sync.go
engine/api/environment.go
engine/api/hook.go
engine/api/operation/operation.go
engine/api/pipeline.go
engine/api/purge/purge_run.go
engine/api/repositories_manager.go
engine/api/repositoriesmanager/events.go
engine/api/repositoriesmanager/repositories_manager.go
engine/api/ui.go
engine/api/workflow/dao_coverage.go
engine/api/workflow/dao_node_run.go
engine/api/workflow/dao_node_run_vulnerability.go
engine/api/workflow/execute_node_run.go
engine/api/workflow/hook.go
engine/api/workflow/process_node.go
engine/api/workflow/workflow_run_event.go
engine/api/workflow_application.go
engine/api/workflow_ascode.go
engine/api/workflow_hook.go
engine/api/workflow_queue.go

refactor(api): prepare new AuthorizedClient()

---

ui/src/app/views/project/show/project.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): project tab initialization done before getting project

---

engine/api/auth.go

chore(api): log new session with mfa

---

engine/api/worker/registration.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): compare hatchery and job region for register

---

contrib/integrations/artifactory/plugin-artifactory-build-info/main.go

fix(contrib/artifactory): push build info retry

---

ui/src/app/views/navbar/navbar.html
ui/src/app/views/navbar/navbar.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): dropdown height + bookmark trigger

---

engine/api/router_middleware.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): maintenance allow worker and service calls

---

engine/api/workflow/process_parameters.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): use final status for pipeline parent parameter

---

ui/src/app/views/navbar/navbar.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): update to have same button width

---

README.md

1. Description
1. About tests
1. Mentions
@ovh/cds

doc: rm gitter

---

engine/api/auth.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): new session with mfa log info

---

engine/api/ascode/pull_request.go
engine/vcs/github/client_branch.go
engine/vcs/github/http.go

fix(vcs): github call oauth2

---

sdk/vcs.go

fix(vcs): notif resync

---

engine/api/repositoriesmanager/repositories_manager.go
engine/api/workflow/workflow_run_event.go
engine/vcs/bitbucketcloud/client_status.go
sdk/vcs.go

fix(vcs): notif bitbucket cloud

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go
engine/api/workflow/workflow_run_results.go
engine/api/workflow/workflow_run_results_test.go
engine/api/workflow_purge_test.go
engine/api/workflow_queue_test.go
engine/api/workflow_run.go
engine/api/workflow_run_result_test.go
engine/cdn/cdn_file.go
engine/worker/cmd_run_result.go
engine/worker/internal/action/builtin_artifact_upload.go
engine/worker/internal/handler_run_result_test.go
sdk/workflow_run_result.go
sdk/workflow_run_result_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): include repo type for run result unicity

---

engine/ui/ui_router.go

fix(engine/ui): disable directory listing

---

ui/src/app/shared/action/step/step.html
ui/src/ngzorro.dark.less

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): increase input size

---

ui/src/app/shared/variable/value/variable.value.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): input style in for variable password

---

ui/src/app/model/pipeline.model.ts

fix(ui): nil pointer

---

engine/api/application/application_importer.go
ui/src/app/model/pipeline.model.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,ui): load as code pipeline + ascode application

---

tools/os-ansible-inventory/.gitignore
tools/os-ansible-inventory/Makefile
tools/os-ansible-inventory/main.go
tools/os-ansible-inventory/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): add os-ansible-inventory

---

ui/src/app/views/navbar/navbar.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): listen change on authenticationState

---

engine/api/api.go
engine/cdn/cdn.go
engine/cdn/types.go
engine/cmd_database.go
engine/config.go
engine/database/database.go
engine/database/types.go
engine/migrateservice/migrate.go
engine/test/database.go

refactor: db settings

---

engine/worker/cmd_exit.go

1. Description
explicit exit code in worker exit doc
@ovh/cds

doc: explicit exit code in worker exit doc

---

engine/vcs/vcs_auth.go

fix(vcs): check auth on vcsType and not url

---

ui/src/app/service/authentication/error.interceptor.ts
ui/src/app/views/navbar/navbar.component.ts
ui/src/app/views/navbar/navbar.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): set redirect uri when navigate on protected project

---

ui/src/app/service/authentication/error.interceptor.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): redirect mfa on home page

---

ui/src/app/service/authentication/error.interceptor.ts
ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts
ui/src/app/views/settings/worker-model/form/worker-model.form.component.ts
ui/src/app/views/settings/worker-model/form/worker-model.form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): worker model edit with pattern

---

engine/api/ui.go
engine/vcs/bitbucketcloud/oauth_consumer.go
engine/vcs/bitbucketserver/oauth_consumer.go
engine/vcs/github/oauth_consumer.go
engine/vcs/gitlab/oauth_consumer.go
engine/vcs/vcs.go
engine/vcs/vcs_auth.go

fix(vcs): compute default url for github

---

sdk/action/promote.go
sdk/action/release.go
tests/test.sh

test: fix venom output

---

engine/api/repositoriesmanager/repositories_manager.go
engine/vcs/github/client_status.go
engine/vcs/vcs_handlers.go

fix(api): disableStatusDetails flag

---

sdk/exportentities/pipeline_test.go
sdk/exportentities/step.go

fix(sdk): promote action export entities

---

ui/src/app/shared/requirements/value/requirements.value.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): service opts was not saved

---

engine/api/purge/purge.go

fix(api): delete workflow run with artifact manager

---

engine/worker/internal/handler_cache.go
engine/worker/internal/handler_cache_test.go
engine/worker/internal/start_test.go
engine/worker/internal/take.go
engine/worker/internal/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(worker): read CDN info from config

---

ui/src/app/shared/workflow/node/run/node.run.param.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): avoid button infinite spinner

---

sdk/exportentities/v2/workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): improve the error msg returned to UI

---

sdk/messages.go
sdk/notif.go
sdk/workflow_run_result.go

fix: json annotation

---

ui/src/app/views/workflow/show/notification/form/workflow.notifications.form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): notification switch binding

---

tests/03_clictl_admin_integration_model.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(test): wrong yaml format

---

tests/03_clictl_admin_integration_model.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(test): bad format

---

engine/types.go
engine/worker/cmd.go

fix: log level doc

---

engine/vcs/bitbucketcloud/client_hook.go

fix(vcs): missing data when getting hook by its ID. #6292

---

cli/cdsctl/admin.go
cli/cdsctl/admin_repositories.go
engine/repositories/fs.go
engine/repositories/repositories.go
engine/repositories/repositories_handlers.go
engine/repositories/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(repositories): add cache size in mon/status

---

engine/repositories/processor.go

1. Description
1. About tests
1. Mentions
@ovh/cds

debug(repositories): add log

---

cli/cdsctl/workflow_push.go
engine/api/workflow/dao.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): push a workflow and remove ascode link

---

LICENSE

doc: update copyright date

---

cli/cdsctl/user_gpg.go
contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/plugin_test.go
contrib/integrations/arsenal/arsenal.go
engine/api/workflow_test.go
engine/hooks/hooks_router.go

refactor: remove ioutil deprecated package

---

contrib/grpcplugins/action/plugin-archive/go.mod
contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/go.mod
contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/go.mod
contrib/grpcplugins/action/plugin-download/go.mod
contrib/grpcplugins/action/plugin-group-tmpl/go.mod
contrib/grpcplugins/action/plugin-kafka-publish/go.mod
contrib/grpcplugins/action/plugin-npm-audit-parser/go.mod
contrib/grpcplugins/action/plugin-ssh-cmd/go.mod
contrib/grpcplugins/action/plugin-tmpl/go.mod
docs/content/development/contribute/development.md
go.mod
sdk/interpolate/go.mod
tests/fixtures/04SCWorkflowRunSimplePlugin/go.mod
tools/smtpmock/go.mod

chore: go 1.19

---

cli/cdsctl/config.go
cli/cdsctl/main.go
cli/cdsctl/workflow_artifact.go
cli/cdsctl/workflow_log.go
cli/cdsctl/workflow_run_interactive.go
cli/cdsctl/workflow_run_result.go
engine/api/workflow_run_log.go
engine/api/workflow_run_log_test.go
engine/cdn/cdn_log_engine.go
engine/worker/internal/types.go
sdk/cdn.go
sdk/cdsclient/client.go
sdk/cdsclient/client_workflow.go
sdk/cdsclient/config.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/featureflipping.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cdsctl): allow to set CDN url as env variable

---

engine/api/workflow/dao.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): workflow push from repository

---

README.md

1. Description
Fixed some typos in README file.
@ovh/cds

📝 README typos fix

---

ui/src/app/views/home/filter/home.filter.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): filter can be null

---

Dockerfile

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(repositories): allow cloning with rsa key

---

sdk/cdsclient/client.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): set value for http response header timeout

---

engine/api/application/application_parser.go
engine/api/application_import_test.go
sdk/application.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): allow description in application import and cli

---

engine/api/workflow/workflow_run_results.go
engine/worker/internal/types.go

feat: add some trace on release action

---

ui/src/app/app.component.html
ui/src/app/shared/shared.module.ts
ui/src/app/shared/vulnerability/list/vulnerabilities.list.html
ui/src/app/shared/vulnerability/list/vulnerabilities.list.scss
ui/src/app/views/workflowv3/edit/workflowv3-edit.html
ui/src/app/views/workflowv3/graph/workflowv3-jobs-graph.html
ui/src/app/views/workflowv3/graph/workflowv3-stages-graph.html
ui/src/app/views/workflowv3/graph/workflowv3-stages-graph.scss
ui/src/app/views/workflowv3/run/workflowv3-run.html
ui/src/app/views/workflowv3/run/workflowv3-run.scss
ui/src/assets/i18n/en.json
ui/src/index.html
ui/src/styles.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): remove semantic from workflow v3

---

engine/hatchery/vsphere/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): wrong token set

---

engine/api/api_helper.go
engine/api/api_routes.go
engine/api/authentication/dao_consumer.go
engine/api/authentication/dao_hatchery_consumer.go
engine/api/hatchery/dao_status.go
engine/api/router_middleware_auth.go
engine/api/router_rbac_rule_hatchery.go
engine/api/v2_hatchery.go
engine/api/v2_hatchery_test.go
engine/hatchery/serve.go
sdk/cdsclient/client_hatchery_service.go
sdk/cdsclient/interface.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery): add hatchery heartbeat

---

engine/api/api.go
engine/api/workflow/workflow_run_results.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add lock to resync workflow run results

---

engine/api/workflow/execute_node_run.go
sdk/messages.go
ui/src/app/shared/action/step/form/step.form.html
ui/src/app/shared/action/step/form/step.form.scss
ui/src/app/shared/action/step/step.html
ui/src/app/shared/action/step/step.scss
ui/src/app/shared/breadcrumb/breadcrumb.component.ts
ui/src/app/shared/breadcrumb/breadcrumb.html
ui/src/app/shared/icons/bitbucket.icon.component.ts
ui/src/app/shared/icons/bitbucket.icon.success.component.ts
ui/src/app/shared/requirements/form/requirements.form.html
ui/src/app/shared/requirements/form/requirements.form.scss
ui/src/app/shared/shared.module.ts
ui/src/app/shared/status/status.icon.html
ui/src/app/shared/status/status.icon.scss
ui/src/app/shared/status/status.spec.ts
ui/src/app/shared/usage/applications/usage.applications.html
ui/src/app/shared/usage/environments/usage.environments.html
ui/src/app/shared/usage/pipelines/usage.pipelines.html
ui/src/app/shared/usage/workflows/usage.workflows.html
ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.html
ui/src/app/shared/workflow/wizard/context/wizard.context.html
ui/src/app/shared/workflow/wnode/hook/hook.component.ts
ui/src/app/shared/workflow/wnode/hook/hook.html
ui/src/app/shared/workflow/wnode/hook/hook.scss
ui/src/app/shared/workflow/wnode/outgoinghook/node.outgoing.html
ui/src/app/shared/workflow/wnode/outgoinghook/node.outgoinghook.component.ts
ui/src/app/views/project/show/project.component.ts
ui/src/app/views/workflow/breadcrumb/workflow.breadcrumb.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): remove last icon

---

ui/angular.json
ui/package-lock.json
ui/package.json
ui/semantic/src/site/globals/site.variables
ui/src/app/views/admin/worker-model-pattern/form/worker-model-pattern.form.html
ui/src/app/views/auth/signin/signin.html
ui/src/app/views/auth/signin/signin.scss
ui/src/app/views/pipeline/show/workflow/pipeline.workflow.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): remove fomanticUI

---

engine/api/api_routes.go
engine/api/entity/dao.go
engine/api/v2_entities.go
sdk/entity.go
sdk/featureflipping.go
sdk/namesgenerator/namesgenerator.go
ui/src/app/app.routing.ts
ui/src/app/guard/feature.guard.ts
ui/src/app/model/project.model.ts
ui/src/app/service/feature/feature.service.ts
ui/src/app/service/project/project.service.ts
ui/src/app/shared/directives/auto-height-collapse-panel.directive.ts
ui/src/app/shared/shared.module.ts
ui/src/app/shared/tabs/tabs.component.ts
ui/src/app/shared/tree/tree.component.ts
ui/src/app/shared/tree/tree.html
ui/src/app/shared/tree/tree.scss
ui/src/app/views/project/show/project.component.ts
ui/src/app/views/projectv2/project.component.ts
ui/src/app/views/projectv2/project.html
ui/src/app/views/projectv2/project.module.ts
ui/src/app/views/projectv2/project.routing.ts
ui/src/app/views/projectv2/project.scss
ui/src/app/views/projectv2/sidebar/project.sidebar.html
ui/src/app/views/projectv2/sidebar/project.sidebar.scss
ui/src/app/views/projectv2/sidebar/sidebar.component.ts
ui/src/app/views/projectv2/top-menu/project.top.menu.component.ts
ui/src/app/views/projectv2/top-menu/project.top.menu.html
ui/src/app/views/projectv2/top-menu/project.top.menu.scss
ui/src/styles.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): add ascode project view

---

sdk/error.go

feat: err msg - add name integration not found

---

contrib/integrations/arsenal/arsenal.go

Signed-off-by: Alexandre Jin <1076513+Inozuma@users.noreply.github.com>
1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): espace alternative name when deleting alternative

---

Dockerfile

Need to be able to import gpg key for repositories

feat(docker): add gpg agent

---

engine/api/purge/purge.go
engine/api/purge/purge_run.go
sdk/artifact_manager/interface.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: clean some error logs

---

engine/hatchery/openstack/openstack.go
engine/hatchery/openstack/openstack_test.go
engine/hatchery/openstack/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery:openstack): default flavor

---

cli/cdsctl/template_bulk.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdsctl): clean ouput for template bulk track no-interactive

---

cli/cdsctl/template_bulk.go
engine/api/api.go
engine/api/environment/environment.go
engine/api/environment/environment_importer.go
engine/api/templates.go
engine/api/workflow_run_craft.go
engine/api/workflow_template_bulk.go
engine/api/workflowtemplate/dao_bulk.go
engine/api/workflowtemplate/instance.go
engine/sql/api/261_template_bulk_parallel.sql
sdk/error.go
sdk/error_test.go
sdk/workflow_template.go
tests/03_clictl_template_bulk_parallel.yml
tests/fixtures/template/bulk_request_parallel.yml
tests/fixtures/template/simple-safe/1.environment.yml
tests/fixtures/template/simple-safe/1.pipeline.yml
tests/fixtures/template/simple-safe/2.pipeline.yml
tests/fixtures/template/simple-safe/example-simple.yml
tests/fixtures/template/simple-safe/workflow.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): template bulk update parallel

---

engine/api/workflow_template_bulk.go
sdk/workflow_template.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): template bulk add logs

---

ui/src/app/shared/action/step/form/step.form.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): width of select action must be 100%

---

engine/api/event/publish_project.go
engine/api/v2_project_repository.go
engine/api/v2_project_repository_test.go
engine/api/v2_repository_analyze.go
sdk/event_project.go
sdk/hooks.go
tests/08_v2_analyze.yml
ui/src/app/app.component.spec.ts
ui/src/app/app.service.ts
ui/src/app/model/analysis.model.ts
ui/src/app/model/event.model.ts
ui/src/app/service/analysis/analysis.service.ts
ui/src/app/service/project/project.service.ts
ui/src/app/service/services.module.ts
ui/src/app/shared/tree/tree.component.ts
ui/src/app/views/projectv2/project.scss
ui/src/app/views/projectv2/sidebar/sidebar.component.ts
ui/src/app/views/projectv2/vcs/repository/show/project.repository.show.component.ts
ui/src/app/views/projectv2/vcs/repository/show/project.repository.show.html
ui/src/app/views/projectv2/vcs/repository/show/project.repository.show.scss

Auto refresh when analyses event received
Repository sidebar loader when there is a analysis in progress

feat(ui): display analyses in repository view

---

engine/api/api_routes.go
engine/api/v2_entities.go
engine/api/v2_entities_test.go
engine/api/v2_jsonschema.go
sdk/doc/route.go
ui/angular.json
ui/package-lock.json
ui/package.json
ui/src/app/app.component.ts
ui/src/app/app.service.ts
ui/src/app/model/editor.model.ts
ui/src/app/model/jsonschema.model.ts
ui/src/app/model/project.model.ts
ui/src/app/model/schema.model.ts
ui/src/app/service/project/project.service.ts
ui/src/app/service/sidebar/sidebar.service.ts
ui/src/app/shared/entity/entity.form.component.html
ui/src/app/shared/entity/entity.form.component.scss
ui/src/app/shared/entity/entity.form.component.ts
ui/src/app/shared/shared.module.ts
ui/src/app/shared/tree/tree.component.ts
ui/src/app/shared/tree/tree.html
ui/src/app/shared/tree/tree.scss
ui/src/app/views/projectv2/project.module.ts
ui/src/app/views/projectv2/project.routing.ts
ui/src/app/views/projectv2/sidebar/sidebar.component.ts
ui/src/app/views/projectv2/vcs/repository/show/project.repository.show.component.ts
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.component.ts
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.html
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.scss

Add ascode editor with yaml key autocompletion

feat(api,ui): first iteration on worker model view

---

engine/api/user.go
engine/api/user_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): check groups on user deletion

---

sdk/goroutine.go

fix(sdk): goroutine display stack

---

engine/api/api.go
engine/api/config.go
engine/api/project.go
sdk/config.go
ui/src/app/model/config.service.ts
ui/src/app/views/navbar/navbar.component.ts
ui/src/app/views/navbar/navbar.html
ui/src/app/views/navbar/navbar.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): allow to disable project creation

---

docs/content/docs/concepts/files/workflow-syntax.md
docs/content/docs/concepts/variables.md

It was hard to find how to add a pipeline parameters and modify it inside a workflow and to use a cds vars as a value inside the workflow. I added element to explain how to do it.
@ovh/cds

Improve documentation for variables/params

---

engine/api/application.go
engine/api/environment.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): load project with integration to be able to load ascode workflow

---

ui/src/app/app.component.spec.ts
ui/src/app/app.routing.ts
ui/src/app/guard/api-config.guard.ts
ui/src/app/shared/action/action.component.spec.ts
ui/src/app/shared/shared.module.ts
ui/src/app/store/authentication.state.ts
ui/src/app/store/config.action.ts
ui/src/app/store/config.state.ts
ui/src/app/store/store.module.ts
ui/src/app/views/admin/admin.routing.ts
ui/src/app/views/application/application.routing.ts
ui/src/app/views/application/show/admin/application.admin.component.spec.ts
ui/src/app/views/application/show/admin/repository/application.repo.component.spec.ts
ui/src/app/views/application/show/application.component.spec.ts
ui/src/app/views/environment/environment.routing.ts
ui/src/app/views/favorite/favorite.routing.ts
ui/src/app/views/home/home.routing.ts
ui/src/app/views/navbar/navbar.component.ts
ui/src/app/views/navbar/navbar.html
ui/src/app/views/pipeline/add/pipeline.add.component.spec.ts
ui/src/app/views/pipeline/pipeline.routing.ts
ui/src/app/views/pipeline/show/pipeline.show.component.spec.ts
ui/src/app/views/project/add/project.add.component.spec.ts
ui/src/app/views/project/project.routing.ts
ui/src/app/views/projectv2/project.routing.ts
ui/src/app/views/settings/settings.routing.ts
ui/src/app/views/workflow/show/admin/workflow.admin.component.ts
ui/src/app/views/workflow/workflow.routing.ts
ui/src/app/views/workflowv3/workflowv3.routing.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): load api config only if authenticated

---

sdk/v2_worker_model.go
ui/extra-webpack.config.js
ui/src/app/model/schema.model.ts
ui/src/app/shared/entity/entity.form.component.html
ui/src/app/shared/entity/entity.form.component.scss
ui/src/app/shared/entity/entity.form.component.ts
ui/src/app/shared/entity/form/form-item-conditional/json-form-field-conditional.html
ui/src/app/shared/entity/form/form-item-conditional/json.form.item.conditional.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/entity/form/json-form.component.ts
ui/src/app/shared/shared.module.ts
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): add entity form generate from jsonschema

---

sdk/v2_worker_model.go
sdk/v2_worker_model_test.go
ui/src/app/model/schema.model.ts
ui/src/app/shared/entity/entity.form.component.html
ui/src/app/shared/entity/form/form-item-conditional/json-form-field-conditional.html
ui/src/app/shared/entity/form/form-item-conditional/json.form.item.conditional.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/entity/form/form-item/json-form-field.scss
ui/src/app/shared/entity/form/json-form.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: handle required field and description

---

engine/api/repository/dao_vcs_project_repository.go
engine/api/workflow/execute_node_run.go
engine/api/workflow/process_requirements.go
engine/api/workflow/process_requirements_test.go
sdk/hatchery/hatchery.go
tests/08_v2_analyze.yml
tests/fixtures/ITCLIPRJVCS/application.app.yml
tests/fixtures/ITCLIPRJVCS/pipeline.pip.yml
tests/fixtures/ITCLIPRJVCS/workflow.yml
ui/src/app/shared/entity/form/form-item/json-form-field.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/entity/form/form-item/json-form-field.scss
ui/src/app/shared/tree/tree.component.ts
ui/src/app/views/pipeline/show/ascode-editor/pipeline.ascode.editor.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): simplify usage of worker model v2 requirement

---

sdk/hatchery/register.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): priority for models registration

---

ui/src/app/shared/breadcrumb/breadcrumb.html
ui/src/app/shared/breadcrumb/breadcrumb.scss
ui/src/app/shared/favorite-button/favorite-button.component.html
ui/src/app/shared/favorite-button/favorite-button.component.scss
ui/src/app/shared/favorite-button/favorite-button.component.ts
ui/src/app/shared/project-breadcrumb/project-breadcrumb.html
ui/src/app/shared/project-breadcrumb/project-breadcrumb.scss
ui/src/app/shared/shared.module.ts
ui/src/app/views/application/show/application.html
ui/src/app/views/application/show/application.scss
ui/src/app/views/environment/show/environment.show.html
ui/src/app/views/environment/show/environment.show.scss
ui/src/app/views/pipeline/show/pipeline.show.html
ui/src/app/views/pipeline/show/pipeline.show.scss
ui/src/app/views/project/show/project.html
ui/src/app/views/project/show/project.scss
ui/src/app/views/workflow/breadcrumb/workflow.breadcrumb.component.ts
ui/src/app/views/workflow/workflow.component.ts
ui/src/app/views/workflow/workflow.html
ui/src/app/views/workflow/workflow.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): breadcrumb style

---

cli/cdsctl/experimental.go
docs/content/docs/concepts/_index.md
docs/content/docs/concepts/organization.md
docs/content/docs/concepts/rbac/_index.md
docs/content/docs/concepts/rbac/global.md
docs/content/docs/concepts/rbac/project.md
ui/src/app/shared/workflow/wnode/wnode.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

docs: add rbac and organization

---

contrib/integrations/artifactory/plugin-artifactory-build-info/main.go
contrib/integrations/artifactory/plugin-artifactory-promote/main.go
contrib/integrations/artifactory/plugin-artifactory-release/main.go
sdk/artifact_manager/interface.go
sdk/artifactory.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): fix log on artifactory plugins

---

ui/src/app/service/authentication/error.interceptor.ts
ui/src/app/shared/entity/entity.form.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/resizable-panel/resizable-panel.component.ts
ui/src/app/views/projectv2/project.component.ts
ui/src/app/views/projectv2/sidebar/sidebar.component.ts
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.component.ts
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.html
ui/src/app/views/projectv2/vcs/repository/workermodel/show/project.workermodel.show.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): project v2 panels default size

---

sdk/error.go

fix(sdk): msg if auth error on git repo

---

docs/content/docs/concepts/files/pipeline-syntax.md

I could not find documentation about optional args on a step so I amend the documentation.

Add optional information for steps

---

ui/src/app/views/workflow/add/workflow.add.component.ts
ui/src/app/views/workflow/add/workflow.add.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): remove connect button if vcs disabled

---

engine/api/workflow/repository.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix:(api) do not look into sub directories

---

engine/api/application.go
engine/api/event/publish_workflow.go
engine/api/purge/purge_run.go
engine/api/workflow.go
sdk/event_workflow.go
ui/src/app/model/purge.model.ts
ui/src/app/store/workflow.state.ts
ui/src/app/views/workflow/show/admin/workflow.admin.component.html
ui/src/app/views/workflow/show/admin/workflow.admin.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): display error on dryrun

---

engine/api/workflow/execute_node_run.go
engine/api/workflow/process_requirements.go
engine/api/workflow/process_requirements_test.go
engine/worker/internal/requirement.go
sdk/exportentities/pipeline.go
sdk/hatchery/hatchery.go
sdk/requirement.go
tests/fixtures/ITCLIPRJVCS/pipeline.pip.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(api,hatchery): remove requirement modelv2

---

engine/api/v2_repository_analyze_test.go
sdk/hatchery/hatchery.go
sdk/jsonschema.go
sdk/requirement.go
sdk/v2_worker_model.go
sdk/v2_worker_model_test.go
tests/08_v2_analyze.yml
tests/fixtures/worker-model-template/tmpl-docker.yml
tests/fixtures/worker-model/docker-debian9.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): add os/arch on worker model v2

---

engine/cmd_start.go
engine/hatchery/kubernetes/kubernetes.go
sdk/hatchery/hatchery.go
sdk/hatchery/starter.go
sdk/hatchery/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): improve hatchery log

---

sdk/hatchery/hatchery.go
sdk/hatchery/starter.go
sdk/hatchery/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): hatchery step log delay millisecond

---

ui/src/app/shared/workflow/wizard/context/wizard.context.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): binding on pipeline mutex

---

engine/api/workflow/process_requirements.go
sdk/hatchery/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,hatchery): fix detection of modelv2

---

ui/src/app/shared/workflow/wizard/hook/hook.form.html
ui/src/app/shared/workflow/wizard/node-add/node.wizard.html
ui/src/app/shared/workflow/wizard/outgoinghook/wizard.outgoinghook.html

Workflow docs URL needs the concepts card by adding "/concepts" to it.
@ovh/cds

fix(ui): add /concepts in workflow docs URL

---

engine/worker/internal/requirement.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): remove memory requirement check

---

engine/hatchery/swarm/monitoring.go
engine/hatchery/swarm/swarm.go
engine/hatchery/swarm/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery:swarm): compute worker cpu/memory metrics

---

docs/content/docs/concepts/worker-model/ascode.md

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(doc): remove old fields

---

engine/hatchery/swarm/monitoring.go
engine/hatchery/swarm/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery:swarm): unregister worker cpu/memory metrics

---

cli/cdsctl/consumer.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdsctl): do not ask service question if there is no service name

---

engine/api/entity/dao.go
engine/api/rbac/dao_rbac_project_key.go
engine/api/rbac/dao_rbac_test.go
engine/api/repository/dao_vcs_project_repository.go
engine/api/v2_entities.go
engine/api/vcs/dao_vcs_project.go
sdk/entity.go
ui/src/app/model/project.model.ts
ui/src/app/service/entity/entity.service.ts
ui/src/app/service/services.module.ts
ui/src/app/shared/action/action.component.spec.ts
ui/src/app/shared/action/action.component.ts
ui/src/app/shared/action/action.html
ui/src/app/shared/requirements/form/requirements.form.component.ts
ui/src/app/shared/requirements/form/requirements.form.html
ui/src/app/shared/requirements/list/requirements.list.component.ts
ui/src/app/shared/requirements/list/requirements.list.html
ui/src/app/views/settings/action/form/action.form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): add ascode worker model in requirement modal

---

engine/api/api_routes.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): add missing route

---

engine/api/action/ascode.go
engine/api/action/children.go
engine/api/action/dao.go
engine/api/action/loader.go
engine/api/api_routes.go
engine/api/bootstrap/bootstrap.go
engine/api/pipeline/pipeline_action.go
engine/api/pipeline_job.go
engine/api/v2_action.go
engine/api/v2_action_test.go
sdk/action.go
sdk/doc/route.go
ui/src/app/model/action.ascode.model.ts
ui/src/app/service/action/actionAscode.service.ts
ui/src/app/service/services.module.ts
ui/src/app/shared/action/action.component.spec.ts
ui/src/app/shared/action/action.component.ts
ui/src/app/shared/action/action.html
ui/src/app/shared/action/step/step.component.ts
ui/src/app/shared/action/step/step.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): add ascode action in existing pipeline

---

ui/src/app/shared/action/action.component.ts
ui/src/app/shared/action/step/step.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): fix display action and step management

---

engine/api/entity/dao.go
engine/api/pipeline/pipeline_action.go
engine/api/v2_action.go
engine/api/v2_repository_analyze.go
engine/api/v2_worker_model.go
engine/api/workflow/execute_node_run.go
engine/api/workflow/factory_dao.go
engine/api/workflow_queue.go
engine/worker/internal/run.go
engine/worker/internal/run_ascode.go
engine/worker/internal/take.go
engine/worker/internal/types.go
sdk/action.go
sdk/entity.go
sdk/exportentities/step.go
sdk/worker.go
sdk/workflow.go
sdk/workflowv3/job.go
sdk/workflowv3/step.go
tests/08_v2_analyze.yml
tests/fixtures/ITCLIPRJVCS/my-action.yml
tests/fixtures/ITCLIPRJVCS/pipeline.pip.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): execute ascode action

---

engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/kubernetes/types.go

feat(hatchery/k8s): add option to disable pod limit

---

engine/api/actionplugin/plugin.go
engine/api/grpc_plugin.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): remove action plugin when deleting grpc plugin aciton

---

Makefile
engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/kubernetes/kubernetes_client.go

feat(hatchery/k8s): log pod events

---

engine/api/worker.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: resync job outside tx

---

engine/hatchery/kubernetes/kubernetes.go
engine/worker/cmd_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery:k8s): watch events routine auto restart

---

sdk/workflow_template.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): workflow template check params typos

---

engine/worker/internal/plugin/plugin.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): do not limit inputs for now

---

engine/api/workflow/execute_node_run.go
engine/api/workflow/process_requirements.go
engine/api/workflow/process_requirements_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): if local workermodel, get current branch

---

engine/api/plugin/dao.go
engine/api/v2_jsonschema.go
sdk/jsonschema.go
sdk/v2_action.go
ui/src/app/model/plugin.model.ts
ui/src/app/model/schema.model.ts
ui/src/app/service/plugin.service.ts
ui/src/app/service/services.module.ts
ui/src/app/shared/entity/form/form-item/json-form-field.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/entity/form/json-form.component.ts
ui/src/app/views/projectv2/vcs/repository/action/show/project.action.show.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): get all plugins in action list and get plugin from UI

---

README.md

doc(readme): blog post links

---

engine/api/worker/registration.go
engine/api/workflow_queue.go
engine/sql/api/267_plugin.sql
sdk/hatchery/types.go
sdk/hatchery/worker_token.go
sdk/worker.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): add ascode worker model name on worker and runjob

---

engine/api/workflow/dao_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): workflow search sort runs

---

sdk/v2_action.go
ui/src/app/model/schema.model.ts
ui/src/app/shared/entity/entity.form.component.html
ui/src/app/shared/entity/entity.form.component.scss
ui/src/app/shared/entity/form/form-item/json-form-field.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/entity/form/form-item/json-form-field.scss
ui/src/app/shared/entity/form/json-form.component.ts
ui/src/app/shared/entity/form/json-form.scss
ui/src/app/shared/input/editor/editor.input.component.ts
ui/src/app/shared/input/editor/editor.input.html
ui/src/app/shared/input/editor/editor.input.scss
ui/src/app/shared/resizable-panel/resizable-panel.component.ts
ui/src/app/shared/shared.module.ts
ui/src/app/views/projectv2/project.scss
ui/src/app/views/projectv2/vcs/repository/action/show/project.action.show.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): style for action v2

---

engine/cdn/storage/nfs/nfs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): add debug log

---

ui/src/app/shared/action/action.component.ts
ui/src/app/shared/action/step/form/step.form.component.ts
ui/src/app/shared/action/step/form/step.form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): display list of steps, manage async

---

ui/src/app/shared/action/action.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): wrong concat of array

---

engine/hatchery/openstack/spawn.go
engine/hatchery/openstack/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery:openstack): set security groups

---

engine/service/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): go build

---

engine/hatchery/openstack/spawn.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery:openstack): set security groups

---

docs/content/docs/concepts/variables.md

doc: typo + complete pipeline parameters doc

---

sdk/workflow_run.go
tests/08_v2_analyze.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: unmarshal cds job context

---

engine/api/api.go
engine/api/workflow/execute_node_job_run.go
engine/api/workflow/run_workflow_test.go
engine/api/workflow_queue.go
engine/config.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): allow to customize book delay for an hatchery

---

sdk/hatchery/starter.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery): release book in case of error

---

engine/config.go
engine/hatchery/vsphere/client.go
engine/hatchery/vsphere/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery:vsphere): set guest credentials from config

---

ui/src/app/views/pipeline/show/audit/pipeline.audit.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): add better check to avoid undefined

---

contrib/integrations/artifactory/plugin-artifactory-release/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

plugin(artifactory): increase distribution timeout

---

ui/src/app/shared/ascode/events/ascode.event.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): put a clearer description on the button

---

engine/api/v2_jsonschema.go
sdk/jsonschema.go
sdk/v2_workflow.go
ui/src/app/model/editor.model.ts
ui/src/app/model/schema.model.ts
ui/src/app/shared/entity/form/form-item/json-form-field.component.ts
ui/src/app/shared/entity/form/form-item/json-form-field.html
ui/src/app/shared/entity/form/form-item/json-form-field.scss
ui/src/app/shared/entity/form/json-form.component.ts
ui/src/app/views/projectv2/vcs/repository/workflow/show/entity/project.workflow.entity.component.ts
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/stages-graph.component.ts

- Region / WorkerModel form: use a select
- Needs from: use select with tags mode (+ auto update schema enum when adding job from editor)
- yaml autocomplete value with enum ( region and worker model )
- fix black zone on graph when resizin editor during form view
@ovh/cds

feat(ui): improve form list field + autocomplete with enum

---

docker-compose.yml
docs/content/hosting/upgrade/migrate_0.53.md

1. Description
1. About tests
1. Mentions
@ovh/cds

doc: update migration to 0.53.0

---

engine/api/objectstore/swift.go
engine/cdn/storage/swift/swift.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,cdn): set timeout for swift client

---

engine/api/api.go
engine/api/entity/dao.go
engine/api/entity/gorp_model.go
engine/api/migrate/migrate_entity_sign.go
engine/api/workflow_v2/dao_run.go
engine/gorpmapper/table_mapping.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): hash signature

---

engine/hatchery/openstack/cache.go
engine/hatchery/openstack/cache_test.go
engine/hatchery/openstack/get.go
engine/hatchery/openstack/init.go
engine/hatchery/openstack/init_test.go
engine/hatchery/openstack/openstack.go
engine/hatchery/openstack/openstack_test.go
engine/hatchery/openstack/spawn_test.go
engine/hatchery/openstack/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(hatchery:openstack): servers and images cache

---

engine/api/repositoriesmanager/repositories_manager.go
engine/api/workflow/execute_node_run.go
engine/api/workflow/process_node_test.go
engine/vcs/bitbucketcloud/client_tag.go
engine/vcs/bitbucketserver/client_tags.go
engine/vcs/gerrit/client_tag.go
engine/vcs/gitea/client_tags.go
engine/vcs/github/client_tag.go
engine/vcs/gitlab/client_tag.go
engine/vcs/vcs_handlers.go
engine/vcs/vcs_router.go
sdk/vcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): get right commit id when running on a branch

---

engine/api/workflow/workflow_run_results.go

fix(api): run result sync goroutine empties promotion data

---

engine/api/workflow/workflow_run_results.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): FindOldestWorkflowRunsWithResultToSync

---

ui/src/app/model/workflow.model.ts
ui/src/app/shared/workflow/wizard/context/wizard.context.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): edit pipeline context

---

cli/cdsctl/admin_hooks.go
cli/cdsctl/admin_hooks_repository.go
cli/cdsctl/admin_hooks_repository_event.go
engine/cache/redis.go
engine/hooks/dao_repository.go
engine/hooks/dao_repository_event.go
engine/hooks/hooks.go
engine/hooks/hooks_handlers.go
engine/hooks/hooks_repositories_handlers.go
engine/hooks/hooks_router.go
engine/hooks/scheduler_clean_old_repository_event.go
engine/hooks/scheduler_clean_old_repository_event_test.go
engine/hooks/scheduler_repository_event.go
engine/hooks/scheduler_repository_event_callback.go
engine/hooks/scheduler_repository_event_retry.go
engine/hooks/scheduler_repository_event_test.go
engine/hooks/types.go
sdk/hooks_repository_event.go
tests/08_v2_analyze.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cli,hooks): add hook cli

---

contrib/grpcplugins/action/plugin-checkout/Makefile
engine/api/api.go
engine/api/api_routes.go
engine/api/v2_project_repository.go
engine/api/v2_project_repository_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go
engine/api/v2_workflow_run_test.go
engine/api/workflow_v2/gorp_model.go
engine/sql/api/279_workflow_run_job_matrix.sql
engine/worker/internal/runV2.go
sdk/doc/route.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
ui/src/app/model/pipeline.model.ts
ui/src/app/model/v2.workflow.run.model.ts
ui/src/app/service/workflowv2/workflow.service.ts
ui/src/app/views/projectv2/run/project.run.component.ts
ui/src/app/views/projectv2/run/run-job-logs.component.ts
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/graph.lib.ts
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/node/fork-join-node.scss
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/node/job-node.html
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/node/job-node.scss
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/stages-graph.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add stage, multi job and matrix job

---

contrib/integrations/artifactory/artifactory.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(integration:artifactory): increase upload timeout

---

engine/hatchery/local/local.go
engine/hatchery/openstack/get.go
engine/hatchery/openstack/openstack.go
engine/hatchery/openstack/spawn.go
engine/hatchery/openstack/spawn_test.go
engine/hatchery/vsphere/hatchery.go
engine/worker/internal/requirement.go
sdk/exportentities/pipeline.go
sdk/hatchery.go
sdk/hatchery/hatchery.go
sdk/requirement.go
sdk/v2_worker_model.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: spawn openstack v2 model with custom flavor

---

Makefile
engine/worker/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): use doc command in CI mode

---

engine/api/v2_queue_worker.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go
engine/worker/internal/runV2.go
sdk/v2_action.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
tests/08_v2_analyze.yml
tests/fixtures/ITCLIPRJVCS/my-workflow.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add vars and env contexts

---

ui/src/app/event.service.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): base href

---

ui/src/app/views/projectv2/run/project.run.component.ts
ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts
ui/src/app/views/workflowv3/run/workflowv3-run.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): websocket baseHref

---

ui/src/app/views/workflow/show/admin/workflow.admin.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): refresh codemirror

---

contrib/grpcplugins/grpcplugins.go
engine/worker/internal/runtime_v2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): uploadArtifact error message

---

cli/cdsctl/admin_hooks_repository_event.go
engine/api/v2_hooks.go
engine/hooks/scheduler_repository_event.go
engine/hooks/trigger_workflow_hook.go
sdk/hooks.go
sdk/log/fields.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,hooks): add hook event id as a log field + fix log

---

engine/api/v2_hooks.go
sdk/log/fields.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): use the right VCS to check permission

---

cli/cdsctl/admin_hooks_repository_event.go
engine/api/v2_repository_analyze.go
engine/hooks/scheduler_repository_event.go
sdk/vcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks,cli): add mising error status + refact cli get hook event

---

engine/api/v2_workflow_run_engine.go
engine/sql/api/283_run_attempt_default.sql
sdk/vcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): set runAttempt for matrix job

---

cli/cdsctl/admin_hooks_repository_event.go
engine/api/v2_hooks.go
engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go
engine/api/v2_workflow_run_engine.go
engine/hooks/scheduler_repository_event_callback.go
engine/hooks/trigger_signingkey.go
engine/hooks/trigger_workflow.go
engine/vcs/github/client_commit.go
sdk/hooks_repository_event.go
sdk/log/fields.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,hooks): fix error status + logs

---

engine/hatchery/openstack/get.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery/openstack): log openstack server info

---

cli/cdsctl/admin_hooks_repository_event.go
contrib/grpcplugins/action/checkout/checkout.yml
contrib/grpcplugins/action/checkout/main.go
engine/api/v2_hooks.go
engine/api/v2_workflow_run.go
engine/hooks/trigger_workflow.go
sdk/v2_workflow_run.go
ui/src/app/views/projectv2/vcs/repository/workflow/show/graph/jobs-graph.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,hooks): load private project key + improve logs

---

engine/api/event/publish_workflow_run.go
engine/api/websocket.go
sdk/cdsclient/client_events.go
sdk/cdsclient/client_queue.go
sdk/cdsclient/client_queue_V2.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/event.go
sdk/hatchery/hatchery.go
sdk/hatchery/hatchery_test.go
sdk/websocket.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): end queuepolling when ws ends

---

engine/api/api.go
engine/api/event/publish.go
engine/api/event/publish_project.go
engine/api/event_v2/event.go
engine/api/event_v2/event_analysis.go
engine/api/event_v2/event_run.go
engine/api/v2_hatchery_ws.go
engine/api/v2_project_repository.go
engine/api/v2_queue.go
engine/api/v2_queue_worker.go
engine/api/v2_repository_analyze.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_job_routines.go
engine/elasticsearch/elasticsearch_handlers.go
engine/elasticsearch/elasticsearch_router.go
engine/elasticsearch/types.go
sdk/cdsclient/client_queue_V2.go
sdk/event_v2.go
sdk/websocket.go

Manage analysis event and RunJob event
@ovh/cds

feat(api): manage cds event v2

---

ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): template apply form params

---

sdk/interpolate/interpolate_helper.go
sdk/interpolate/interpolate_test.go

1. Description
3. About tests
4. Mentions
@ovh/cds

feat(sdk/interpolate) Add new math interpolations

---

ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.component.ts
ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): template apply form with repo param

---

engine/elasticsearch/elasticsearch_handlers.go
engine/elasticsearch/mock_elasticsearch/esclient_mock.go
engine/elasticsearch/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: change how we index doc in es

---

engine/api/event_v2/event.go
engine/api/notification_v2/dao.go
engine/api/v2_project_notification_test.go
engine/sql/api/287_v2_project_notification_id_type.sql

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): change notification primary key type

---

engine/api/event_v2/event.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): missing notif body

---

engine/api/v2_workflow_run.go
engine/api/workflow_v2/dao_run.go
ui/src/app/shared/shared.module.ts
ui/src/app/views/projectv2/run-list/run-list.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui,api): workflow run v2 list without filters

---

engine/api/v2_queue_worker.go
engine/api/v2_queue_worker_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
engine/worker/internal/runV2.go
engine/worker/internal/takeV2.go
engine/worker/internal/types.go
sdk/action_parser.go
sdk/blur.go
sdk/blur_test.go
sdk/v2_worker.go
tests/08_v2_env_context.yml
tests/08_v2_workflow_generic_artifacts_with_artifactory.yml
ui/proxy.conf.json

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add variableset in workflows

---

cli/cdsctl/experimental_project_repository_analyze.go
cli/cdsctl/experimental_rbac.go
engine/api/api_routes.go
engine/api/rbac/dao_rbac.go
engine/api/router_rbac_rule_project.go
engine/api/v2_project_repository.go
engine/api/v2_rbac.go
engine/api/v2_repository_analyze.go
sdk/cdsclient/client_project_repository.go
sdk/cdsclient/client_rbac.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/hooks_repository_event.go
sdk/rbac.go
tests/08_v2_checkout.yml
tests/08_v2_cli_rbac.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,cli): manual analysis trigger + list rbac

---

engine/api/v2_queue_worker.go
engine/api/v2_queue_worker_test.go
engine/hatchery/swarm/swarm_util_kill.go
engine/worker/internal/runV2.go
engine/worker/internal/types.go
tests/08_v2_env_context.yml
ui/src/app/shared/requirements/list/requirements.list.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,ui): hide secret, avoid sending stacktrace to job, fix requirement

---

engine/api/v2_repository_analyze.go
engine/worker/internal/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): avoid using admin user

---

engine/api/v2_rbac.go
engine/api/v2_rbac_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): load workflow part

---

contrib/grpcplugins/action/deployArsenal/main.go
contrib/integrations/arsenal/arsenal-deployment-plugin/main.go
contrib/integrations/arsenal/arsenal.go
sdk/v2_workflow_run.go
ui/src/app/views/projectv2/run/project.run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk,contrib): add deployment run result

---

engine/worker/internal/runV2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): worker hook execution

---

contrib/integrations/arsenal/arsenal-deployment-plugin/main.go
engine/worker/internal/runV2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): do not add integration env variable in result

---

tests/08_v2_workflow_on_pullrequest.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(tests): workflow v2 notifications

---

contrib/grpcplugins/action/artifactory-promote/Makefile
contrib/grpcplugins/action/artifactory-promote/artifactory-promote.yml
contrib/grpcplugins/action/artifactory-promote/main.go
contrib/grpcplugins/action/docker-push/main.go
contrib/grpcplugins/action/uploadArtifact/main.go
contrib/grpcplugins/grpcplugins.go
contrib/integrations/artifactory/artifactory-promote-plugin/main.go
contrib/integrations/artifactory/artifactory-release-plugin/main.go
contrib/integrations/artifactory/artifactory.go
engine/api/v2_queue.go
engine/api/workflow_v2/dao_run.go
engine/api/workflow_v2/dao_run_job.go
engine/worker/internal/runtime_v2.go
engine/worker/pkg/workerruntime/handlers_v2.go
sdk/glob/glob_test.go
sdk/v2_worker.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(workflowv2/plugin): artifactory promote

---

engine/api/v2_workflow_run_craft.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: the vcs name in different project are differents

---

engine/api/v2_queue.go
engine/api/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): add job ended date + fix restart job with runresult

---

cli/cdsctl/experimental_hatchery.go
engine/api/api.go
engine/api/api_routes.go
engine/api/auth_hatchery.go
engine/api/authentication/consumer.go
engine/api/authentication/dao_hatchery_consumer.go
engine/api/clean_worker.go
engine/api/clean_worker_test.go
engine/api/router_middleware_auth.go
engine/api/router_rbac_rule_hatchery.go
engine/api/v2_hatchery.go
engine/api/v2_hatchery_test.go
engine/api/v2_worker_model_test.go
engine/api/worker_v2/dao.go
sdk/cdsclient/client_hatchery.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/event_v2.go
sdk/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): clean worker consumer + regen hatchery consumer

---

contrib/vscode-cds/.vscodeignore
contrib/vscode-cds/src/extension.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): do not ignore nodemodules

---

engine/api/project.go
sdk/project.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): favorites in projects list

---

sdk/hatchery/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vsphere): run cmd with worker model v2

---

contrib/grpcplugins/action/downloadArtifact/main.go
contrib/grpcplugins/action/uploadArtifact/main.go
contrib/grpcplugins/action/uploadArtifact/uploadArtifact.yml
engine/worker/internal/runtime_v2.go
engine/worker/pkg/workerruntime/types.go
sdk/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add run result of type coverage

---

engine/api/v2_workflow_run.go
engine/api/workflow_v2/dao_run.go
sdk/luascript/luascript_test.go
ui/src/app/store/navigation.action.ts
ui/src/app/store/navigation.state.ts
ui/src/app/views/projectv2/activity-bar/activity-bar.component.ts
ui/src/app/views/projectv2/run-list/run-list-sidebar.component.ts
ui/src/app/views/projectv2/run/project.run.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui,api): project v2 improve activity navigation

---

sdk/hatchery/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): fix precmd

---

engine/api/v2_jsonschema.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(jsonschema): fix job validation

---

contrib/grpcplugins/action/downloadArtifact/main.go
contrib/grpcplugins/action/junit/main.go
contrib/grpcplugins/grpcplugins.go
engine/api/v2_queue.go
engine/api/v2_workflow_run_engine.go
engine/api/workflow_v2/dao_run.go
engine/api/workflow_v2/dao_run_result.go
engine/worker/internal/runtime_v2.go
engine/worker/pkg/workerruntime/types.go
sdk/cdsclient/client_queue_V2.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,contrib): get run result without type filter

---

engine/worker/internal/runtime_v2_test.go
sdk/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): cast helm run result

---

contrib/grpcplugins/action/artifactory-plugins-lib/artifactory-plugins-lib.go
contrib/grpcplugins/grpcplugins.go
contrib/integrations/artifactory/artifactory.go
engine/worker/internal/runtime_v2_test.go
sdk/artifact_manager/artifactory/http/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): release plugin

---

contrib/vscode-cds/Makefile
contrib/vscode-cds/package.json
contrib/vscode-cds/webviews/workflow-preview/angular.json

1. Description
1. About tests
1. Mentions
@ovh/cds

chore: go build use cache

---

engine/api/api.go
engine/api/api_routes.go
engine/api/entity/dao.go
engine/api/migrate/migrate_entity_sign.go
engine/api/v2_action.go
engine/api/v2_action_test.go
engine/api/v2_entities.go
engine/api/v2_entities_test.go
engine/api/v2_project_clean_ascode_test.go
engine/api/v2_queue.go
engine/api/v2_queue_test.go
engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go
engine/api/v2_worker_model.go
engine/api/v2_worker_model_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_test.go
engine/api/workflow/factory_dao.go
engine/api/workflow/process_requirements.go
engine/sql/api/294_v2_entity_unique_index.sql
engine/vcs/gitea/client_tags.go
engine/worker/internal/takeV2.go
sdk/cdsclient/client_queue_V2.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/hatchery/hatchery.go
sdk/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): manage multiple commit on branch entity

---

tests/Makefile

1. Description
1. About tests
1. Mentions
@ovh/cds

chore: fix makefile to generate coverage

---

ui/libs/workflow-graph/src/lib/stages-graph.html
ui/package-lock.json
ui/package.json
ui/src/app/views/projectv2/project.module.ts
ui/src/app/views/projectv2/run/gate/gate.component.ts
ui/src/app/views/projectv2/run/gate/gate.html
ui/src/app/views/projectv2/run/gate/gate.scss
ui/src/app/views/projectv2/run/project.run.component.ts
ui/src/app/views/projectv2/run/project.run.html
ui/src/app/views/projectv2/run/project.run.scss
ui/src/app/views/projectv2/run/run-job-logs.scss
ui/src/app/views/projectv2/run/run-job.component.ts
ui/src/app/views/projectv2/run/run-job.scss
ui/src/app/views/projectv2/run/run-result.component.ts
ui/src/app/views/projectv2/run/run-workflow.component.ts
ui/src/app/views/projectv2/run/run-workflow.html
ui/src/app/views/projectv2/run/run-workflow.scss
ui/src/app/views/projectv2/vcs/repository/workflow/show/entity/project.workflow.entity.component.ts
ui/src/app/views/projectv2/vcs/repository/workflow/show/project.workflow.show.component.ts
ui/src/app/views/workflow/run/node/pipeline/workflow-run-job/workflow-run-job.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): workflow run v2 show sources

---

engine/api/api_routes.go
engine/api/v2_queue.go
engine/api/v2_queue_worker.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_context.go
engine/api/workflow_v2/dao_run.go
engine/api/workflow_v2/dao_run_job.go
engine/api/workflow_v2/dao_run_result.go
sdk/v2_workflow_run.go
sdk/v2_workflow_test.go
ui/src/app/model/v2.workflow.run.model.ts
ui/src/app/service/workflowv2/workflow.service.ts
ui/src/app/views/projectv2/run/project.run.component.ts
ui/src/app/views/projectv2/run/project.run.html
ui/src/app/views/projectv2/run/project.run.scss
ui/src/app/views/projectv2/run/run-result.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): workflow run v2 switch attempt

---

engine/api/test/assets/assets.go
engine/api/v2_queue.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
engine/hatchery/swarm/swarm.go
sdk/hatchery.go
sdk/hatchery/hatchery.go
sdk/v2_workflow.go
sdk/v2_workflow_test.go
tests/08_v2_checkout.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery): add flavor and memory

---

engine/cdn/storage/local/buffer.go

1. Description
1. About tests
1. Mentions
@ovh/cds

Rebase external contributions

---

contrib/grpcplugins/action/dockerPush/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): docker push tag list

---

cli/cdsctl/experimental_workflow.go
cli/cdsctl/experimental_workflow_results.go
contrib/grpcplugins/action/pythonPush/main.go
engine/api/api_routes.go
engine/api/router_rbac_rule_cdn.go
engine/api/v2_project.go
engine/api/v2_workflow_run.go
engine/cdn/auth.go
sdk/cdsclient/client_project.go
sdk/cdsclient/client_workflowv2.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
tests/08_v2_workflow_generic_artifacts.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cli): search workflow run + download runResult from cli

---

tests/08_v2_workflow_generic_artifacts_with_artifactory.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(test): it artifactory integration

---

engine/api/download/download.go
engine/cmd_database.go
engine/cmd_download.go
sdk/download.go
sdk/file.go

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor: remove mholt/archiver usage

---

ui/src/app/views/navbar/navbar.html
ui/src/app/views/navbar/navbar.scss
ui/src/app/views/project/activity-bar/activity-bar.component.ts
ui/src/app/views/project/project.component.ts
ui/src/app/views/project/project.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): display project v2 banner

---

ui/libs/workflow-graph/src/lib/graph.lib.ts
ui/libs/workflow-graph/src/lib/graph.model.ts
ui/libs/workflow-graph/src/lib/jobs-graph.component.ts
ui/libs/workflow-graph/src/lib/node/fork-join-node.components.ts
ui/libs/workflow-graph/src/lib/node/job-node.component.ts
ui/libs/workflow-graph/src/lib/node/matrix-node.component.ts
ui/libs/workflow-graph/src/lib/stages-graph.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): navigate workflow v2 graph with keyboard

---

ui/src/app/views/projectv2/run/run-job-logs.component.ts
ui/src/app/views/projectv2/run/run-job-logs.html
ui/src/app/views/projectv2/run/run-job-logs.scss
ui/src/app/views/projectv2/run/run-job.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): run v2 improve logs view

---

engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go
sdk/entity.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): remove entity on HEAD

---

engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): gate condition

---

ui/libs/workflow-graph/src/lib/graph.model.ts
ui/libs/workflow-graph/src/lib/stages-graph.component.ts
ui/src/app/views/projectv2/run/project.run.html
ui/src/app/views/projectv2/run/run-contexts.html
ui/src/app/views/projectv2/run/run-hook.html
ui/src/app/views/projectv2/run/run-job-logs.component.ts
ui/src/app/views/projectv2/run/run-job-logs.html
ui/src/app/views/projectv2/run/run-job-logs.scss
ui/src/app/views/projectv2/run/run-job.component.ts
ui/src/app/views/projectv2/run/run-job.html
ui/src/app/views/projectv2/run/run-job.scss
ui/src/app/views/projectv2/run/run-result.html
ui/src/app/views/projectv2/run/run-test.html
ui/src/app/views/projectv2/run/run-workflow.html
ui/src/app/views/projectv2/vcs/repository/workflow/show/entity/project.workflow.entity.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): workflow run v2 view shortcuts

---

engine/api/router_rbac_rule_admin.go
engine/api/v2_workflow_run.go
engine/api/workflow_v2/dao_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): workflow run v2 search lower repositories

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/vcs/bitbucketcloud/client_forks.go
engine/vcs/bitbucketcloud/client_repos.go
engine/vcs/bitbucketserver/client_forks.go
engine/vcs/bitbucketserver/client_repos.go
engine/vcs/bitbucketserver/types.go
engine/vcs/gitea/client_forks.go
engine/vcs/gitea/client_repos.go
engine/vcs/github/client_forks.go
engine/vcs/github/client_repos.go
engine/vcs/gitlab/client_forks.go
engine/vcs/gitlab/client_repos.go
engine/worker/internal/start_test.go
sdk/contexts.go
sdk/repositories_manager.go
ui/libs/workflow-graph/src/lib/graph.model.ts
ui/src/app/shared/tree/tree.component.ts
ui/src/app/shared/tree/tree.html
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss
ui/src/app/views/projectv2/run/project.run.html
ui/src/app/views/projectv2/run/project.run.scss
ui/src/app/views/projectv2/sidebar/workspace/sidebar.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): workflow run v2 link to vcs resources

---

engine/api/project/dao_variable_set.go
ui/src/app/model/project.model.ts
ui/src/app/model/variablesets.model.ts
ui/src/app/service/project/project.service.ts
ui/src/app/shared/shared.module.ts
ui/src/app/store/project.action.ts
ui/src/app/store/project.state.ts
ui/src/app/views/project/project.module.ts
ui/src/app/views/project/settings/settings.html
ui/src/app/views/project/show/variablesets/items/variableset.item.component.ts
ui/src/app/views/project/show/variablesets/items/variableset.item.html
ui/src/app/views/project/show/variablesets/items/variableset.item.scss
ui/src/app/views/project/show/variablesets/variablesets.component.ts
ui/src/app/views/project/show/variablesets/variablesets.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): add variableset components

---

engine/api/application/dao.go
engine/api/application/dao_application_integration.go
engine/api/application/dao_key.go
engine/api/application/dao_variable.go
engine/api/authentication/gorp_model.go
engine/api/entity/gorp_model.go
engine/api/environment/gorp_model.go
engine/api/group/gorp_model.go
engine/api/integration/gorp_model.go
engine/api/notification_v2/gorp_model.go
engine/api/project/gorp_model.go
engine/api/user/gorp_model.go
engine/api/worker/gorp_model.go
engine/api/workflow/gorp_model.go
engine/api/workflow_v2/gorp_model.go
engine/gorpmapper/table_mapping.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,cdn): new signatures

---

engine/api/v2_workflow_run_engine.go
engine/hooks/hook_repository_event.go
engine/hooks/scheduler_clean_old_repository_event.go
engine/repositories/repositories.go
engine/repositories/repositories_router.go
sdk/vcs.go

feat: artifactory properties workflow v2

---

engine/api/v2_rbac_check.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): allow maintainer to see workflow logs

---

engine/api/api_routes.go
engine/api/router_rbac_rule_queue.go
engine/api/test/assets/assets.go
engine/api/v2_queue.go
engine/api/v2_queue_test.go
engine/api/v2_workflow_run_engine.go
engine/api/workflow_v2/dao_run_job.go
sdk/v2_workflow_run.go
ui/src/app/service/queue/queue.service.ts
ui/src/app/service/workflowv2/workflow.service.ts
ui/src/app/views/navbar/navbar.html
ui/src/app/views/settings/queue/queuev2.component.html
ui/src/app/views/settings/queue/queuev2.component.scss
ui/src/app/views/settings/queue/queuev2.component.ts
ui/src/app/views/settings/settings.module.ts
ui/src/app/views/settings/settings.routing.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): display job queue v2

---

ui/src/app/store/preferences.state.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): explore sidebar cache

---

contrib/grpcplugins/action/keyInstall/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): allow to install key everywhere

---

docs/content/docs/concepts/cds_as_code/entities/_index.md
docs/content/docs/concepts/cds_as_code/entities/workflow.md
docs/content/docs/concepts/cds_as_code/entities/workflow_template.md
docs/content/docs/concepts/cds_as_code/rbac/project.md
engine/api/v2_entities.go
engine/api/v2_jsonschema.go
engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go
engine/api/v2_workflow_run_craft.go
sdk/contexts.go
sdk/entity.go
sdk/jsonschema.go
sdk/rbac.go
sdk/rbac_project.go
sdk/telemetry/telemetry.go
sdk/v2_workflow.go
sdk/v2_workflow_template.go
tests/08_v2_workflow_template.yml
tests/Makefile
tests/lib/v2_create_project.yml
tests/lib/v2_push_cds_files_on_repo.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,sdk): new workflow template v2

---

ui/src/app/store/preferences.action.ts
ui/src/app/store/preferences.state.ts
ui/src/app/views/projectv2/explore/explore-sidebar.component.ts
ui/src/app/views/projectv2/explore/explore-sidebar.html
ui/src/app/views/projectv2/explore/vcs/repository/workflow/show/entity/project.workflow.entity.html
ui/src/app/views/projectv2/explore/vcs/repository/workflow/show/project.workflow.show.html

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): explore select repo branch

---

ui/src/app/views/projectv2/explore/explore-sidebar.component.ts
ui/src/app/views/projectv2/explore/explore-sidebar.html
ui/src/app/views/projectv2/explore/explore-sidebar.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): improve project explore tree

---

engine/api/api.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_test.go
engine/api/workflow_v2/dao_run.go
engine/api/workflow_v2/purge_run.go
engine/sql/api/297_v2_project_workflow_retention.sql
sdk/project.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
ui/src/app/model/project.model.ts
ui/src/app/views/project/show/admin/project.admin.component.ts
ui/src/app/views/project/show/admin/project.admin.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): addv2 run purge

---

docs/content/docs/concepts/cds_as_code/contexts.md
docs/content/docs/concepts/cds_as_code/entities/action.md
docs/content/docs/concepts/cds_as_code/entities/workflow.md
docs/content/docs/concepts/cds_as_code/entities/workflow_template.md
docs/content/docs/concepts/cds_as_code/project/_index.md
docs/content/docs/concepts/cds_as_code/project/repository.md
docs/content/docs/integrations/github/github_repository_manager.md

1. Fix typos in doc using [typos](https://github.com/crate-ci/typos)
1. About tests
1. Mentions
@ovh/cds

Fix typos doc

---

ui/src/app/shared/workflow/wnode/wnode.component.ts
ui/src/app/views/project/add/project.add.html

1. Description
1. About tests
1. Mentions
@ovh/cds

Fix typos (ui)

---

docs/content/docs/concepts/cds_as_code/entities/workflow.md
docs/content/docs/concepts/cds_as_code/entities/workflow_template.md

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(doc): update template parameters + add workflow example

---

engine/vcs/bitbucketserver/client_branch.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): limit branch + order by last modification

---

engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft.go
engine/api/workflow_v2/dao_run.go
engine/sql/api/298_v2_run_index_workflow_template.sql
sdk/contexts.go
sdk/jsonschema.go
sdk/v2_workflow.go
ui/src/app/shared/tabs/tabs.component.ts
ui/src/app/views/project/activity-bar/activity-bar.component.ts
ui/src/app/views/project/project.routing.ts
ui/src/app/views/projectv2/explore/entity/entity-json-form-field.component.ts
ui/src/app/views/projectv2/explore/entity/entity-json-form-field.html
ui/src/app/views/projectv2/explore/entity/entity-json-form-field.scss
ui/src/app/views/projectv2/project.module.ts
ui/src/app/views/projectv2/run-list/run-list-sidebar.component.ts
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run/run-contexts.component.ts
ui/src/app/views/projectv2/run/run-contexts.html
ui/src/app/views/projectv2/run/run-hook.component.ts
ui/src/app/views/projectv2/run/run-hook.html
ui/src/app/views/projectv2/run/run-job.component.ts
ui/src/app/views/projectv2/run/run-result.component.ts
ui/src/app/views/projectv2/run/run-result.html
ui/src/app/views/projectv2/run/run-test.component.ts
ui/src/app/views/projectv2/run/run-test.html
ui/src/app/views/projectv2/run/run-workflow.component.ts
ui/src/app/views/projectv2/run/run-workflow.html
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): display template info in run v2

---

ui/src/app/views/project/show/admin/project.admin.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): input retention name

---

contrib/grpcplugins/action/debianPush/main.go
contrib/grpcplugins/grpcplugins.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib, api): info typo

---

engine/api/v2_project_clean_ascode.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: add log on entities deletion

---

engine/api/api.go
engine/api/v2_project_clean_ascode.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): move purge delay in conf

---

sdk/glob/main_test.go
sdk/glob/pattern_parser.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): glob

---

engine/api/api_helper.go
engine/api/auth.go
engine/api/auth_builtin.go
engine/api/auth_hatchery.go
engine/api/router.go
engine/api/router_middleware_auth.go
engine/api/router_middleware_auth_permission_test.go
engine/api/v2_hatchery.go
engine/api/v2_queue.go
engine/api/v2_queue_worker.go
engine/service/http.go
engine/service/router_response_tracker.go
sdk/application.go
sdk/hatchery.go
sdk/pipeline.go
sdk/project.go
sdk/project_variable.go
sdk/repository.go
sdk/v2_workflow_run.go
sdk/worker_model.go
sdk/workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add log field from body

---

engine/api/cdn/item.go
engine/api/services/http.go

fix(api): 404 error from CDN raised 500 from API

---

engine/api/entity/dao.go
engine/api/entity_search.go
engine/api/v2_repository_analyze.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
sdk/entity.go
sdk/hatchery/hatchery.go
tests/08_v2_worker_model_templated.yml
tests/08_v2_workflow_template.yml
tests/lib/v2_push_cds_files_on_repo.yml
ui/libs/workflow-graph/src/lib/node/job-node.html
ui/libs/workflow-graph/src/lib/node/job-node.scss
ui/libs/workflow-graph/src/lib/node/matrix-node.html
ui/libs/workflow-graph/src/lib/node/matrix-node.scss
ui/src/app/model/entity.model.ts
ui/src/app/service/action/actionAscode.service.ts
ui/src/app/shared/action/action.component.ts
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: interpolate wm v2 image name

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): invalid worker v2 model type

---

engine/api/api.go
engine/api/migrate/migrate_hook.go
engine/api/workflow_v2/gorp_model.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): upadte hook signature

---

engine/api/api.go
engine/api/migrate/migrate_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): migrate run v2 non blocker

---

engine/api/v2_repository_analyze.go
engine/api/workflow_v2/dao_workflow_hook.go
engine/hooks/trigger_workflow_hook.go
tests/08_v2_manual_run.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks,api): fix manual run + head hook

---

engine/api/v2_queue_worker.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): send matrix context to job

---

engine/api/v2_workflow_run.go
engine/cache/cache.go
engine/cache/redis.go
engine/cdn/item_duplicate.go
engine/cdn/storage/redis/redis.go
engine/cdn/storage/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): duplicate logs + fix gate.if syntax

---

engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/workflow_v2/dao_run.go
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/model/project.model.ts
ui/src/app/service/project/project.service.ts
ui/src/app/service/workflowv2/workflow.service.ts
ui/src/app/shared/shared.module.ts
ui/src/app/views/navbar/navbar.html
ui/src/app/views/projectv2/explore/explore-repository.component.ts
ui/src/app/views/projectv2/explore/explore-sidebar.component.ts
ui/src/app/views/projectv2/explore/explore-sidebar.html
ui/src/app/views/projectv2/explore/explore-sidebar.scss
ui/src/app/views/projectv2/project.module.ts
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-start/run-start.component.ts
ui/src/app/views/projectv2/run-start/run-start.html
ui/src/app/views/projectv2/run-start/run-start.scss
ui/src/app/views/projectv2/run/run.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): start workflow run v2

---

engine/api/v2_workflow_run_engine.go
engine/api/workflow/dao_node_run.go
engine/api/workflow/workflow_run_results.go
sdk/workflow_run.go

feat(api): add job metadata in CDS signature

---

engine/api/v2_repository_analyze.go
sdk/common.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): clean analysis error display

---

contrib/grpcplugins/action/checkout/checkout.yml
contrib/grpcplugins/action/checkout/main.go
contrib/grpcplugins/action/keyInstall/main.go
contrib/grpcplugins/action/pythonPush/main.go
contrib/grpcplugins/grpcplugins_keys.go
engine/api/v2_queue_worker.go
engine/worker/internal/runV2.go
sdk/contexts.go
tests/08_v2_key_install.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: install sskkey on worker during checkout

---

contrib/grpcplugins/action/checkout/main.go
contrib/grpcplugins/action/keyInstall/main.go
contrib/grpcplugins/grpcplugins_keys.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): use user.HomeDir instead of /home/sguiheux

---

tests/08_v2_checkout.yml
tests/08_v2_cli_hatchery.yml
tests/08_v2_distant_workflow.yml
tests/08_v2_env_context.yml
tests/08_v2_key_install.yml
tests/08_v2_manual_run.yml
tests/08_v2_manualjob.yml
tests/08_v2_rerun.yml
tests/08_v2_step_job_conditions.yml
tests/08_v2_sub_action.yml
tests/08_v2_worker_model_templated.yml
tests/08_v2_workflow_artifactory_plugins.yml
tests/08_v2_workflow_generic_artifacts.yml
tests/08_v2_workflow_generic_artifacts_with_artifactory.yml
tests/08_v2_workflow_integration.yml
tests/08_v2_workflow_on_pullrequest.yml
tests/08_v2_workflow_service.yml
tests/08_v2_workflow_template.yml
tests/cdsctl_wrapper.sh
tests/lib/v2_create_project.yml
tests/lib/v2_install_gpg_key.yml
tests/test.sh

1. Description
1. About tests
1. Mentions
@ovh/cds

test: refactor it v2 startup

---

tests/00_smoke_test_api.yml
tests/01_signup.yml
tests/02_smoke_test_services.yml
tests/03_clictl_admin_database.yml
tests/03_clictl_admin_integration_model.yml
tests/03_clictl_admin_services.yml
tests/03_clictl_template_bulk.yml
tests/03_clictl_template_bulk_parallel.yml
tests/04_sc_workflow_create_run_join.yml
tests/04_sc_workflow_git_clone_tag.yml
tests/04_sc_workflow_integration_deploy_plugin_req.yml
tests/04_sc_workflow_run_check_payload.yml
tests/04_sc_workflow_run_notif.yml
tests/04_sc_workflow_run_simple_plugin.yml
tests/04_sc_workflow_run_simple_service.yml
tests/04_sc_workflow_run_worker_cmd.yml
tests/04_sc_workflow_run_worker_cmd_cache.yml
tests/04_sc_workflow_template_run.yml
tests/04_sc_workflow_update_run.yml
tests/05_sc_workflow_event_kafka.yml
tests/06_sc_workflow_with_artifactory.yml
tests/08_v2_workflow_artifactory_plugins.yml
tests/08_v2_workflow_generic_artifacts_with_artifactory.yml
tests/08_v2_workflow_integration.yml
tests/fixtures/04SCWorkflowRunSimplePlugin/.gitignore
tests/fixtures/04SCWorkflowRunSimplePlugin/Makefile
tests/fixtures/ITSCWRKFLW15/.gitignore
tests/fixtures/ITSCWRKFLW15/Makefile
tests/lib/v2_create_project.yml
tests/test.sh

1. Description
1. About tests
1. Mentions
@ovh/cds

test: refactor it v1 startup

---

cli/cdsctl/experimental_project_variableset.go
engine/api/api_routes.go
engine/api/v2_project_variable_migrate.go
sdk/cdsclient/client_project_variable_set.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/project_variable.go
tests/08_v2_cli_variableset_migrate.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,cli): migrate environment to variableset

---

engine/api/v2_project_repository.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): do not load repository from db if we receive the name

---

tests/01_init_model.yml
tests/04_sc_workflow_create_run_join.yml
tests/04_sc_workflow_create_simple.yml
tests/04_sc_workflow_edit_scheduler.yml
tests/04_sc_workflow_git_clone_tag.yml
tests/04_sc_workflow_integration_deploy_plugin_req.yml
tests/04_sc_workflow_run_check_payload.yml
tests/04_sc_workflow_run_simple_plugin.yml
tests/04_sc_workflow_run_simple_service.yml
tests/04_sc_workflow_update_run.yml
tests/test.sh

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: workflow it tests init model

---

engine/api/v2_project_variable_migrate.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): migrate env and app to vars set remove dots in names

---

engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss
ui/src/app/views/projectv2/run-start/run-start.component.ts
ui/src/app/views/projectv2/run-start/run-start.html
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): display annotations for run v2

---

engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/swarm/swarm.go
engine/service/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery): check model os/arch for docker hatcheries

---

ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): run v2 show annotation value

---

engine/api/v2_queue.go
engine/api/workflow_v2/dao_run_job.go
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/settings/queue/queuev2.component.html
ui/src/app/views/settings/queue/queuev2.component.scss
ui/src/app/views/settings/queue/queuev2.component.ts
ui/src/theme.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): queue job v2 page

---

sdk/entity.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): remove dot from entity name

---

cli/cdsctl/admin_hooks_scheduler.go
engine/api/api_routes.go
engine/api/repositoriesmanager/repositories_manager.go
engine/api/v2_hooks.go
engine/hooks/hook_repository_event.go
engine/hooks/hooks.go
engine/hooks/scheduler_repository_event.go
engine/hooks/scheduler_repository_event_test.go
engine/hooks/types.go
engine/vcs/bitbucketcloud/client_status.go
engine/vcs/bitbucketserver/client_insight.go
engine/vcs/bitbucketserver/http.go
engine/vcs/bitbucketserver/types.go
engine/vcs/gerrit/client_status.go
engine/vcs/gitea/client_status.go
engine/vcs/github/client_status.go
engine/vcs/gitlab/client_status.go
engine/vcs/vcs_handlers.go
engine/vcs/vcs_router.go
sdk/cdsclient/client_hook.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/doc/route.go
sdk/hooks_repository_event.go
sdk/repositories_manager.go
sdk/vcs.go
tests/08_v2_scheduler.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hooks,api): send insight report

---

engine/repositories/processor_checkout.go
engine/worker/internal/runV2.go
tests/08_v2_workflow_artifactory_plugins.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(repositories): add fallback on get changeset 

---

engine/api/entity_search.go
engine/api/v2_project_repository.go
engine/api/v2_queue.go
engine/api/v2_repository_analyze.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go
engine/api/v2_workflow_run_job_routines.go
engine/api/v2_workflow_run_test.go
engine/hooks/hooks_handlers.go
engine/hooks/trigger_analyses.go
engine/hooks/trigger_workflow.go
engine/sql/api/301_v2_mfa_manual_run.sql
sdk/hooks_repository_event.go
sdk/repository.go
sdk/v2_workflow_run.go
tests/08_v2_env_context.yml
tests/fixtures/rbac/ITV2ENVCONTEXT.yml
tests/lib/v2_create_project.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,hook): refact behaviour when admin triggered a workflow

---

engine/api/v2_workflow_run_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): unit test

---

sdk/log/formatter.go
tests/04_sc_workflow_create_run_join.yml
tests/05_sc_workflow_event_kafka.yml
tests/08_v2_cli_hatchery.yml
tests/08_v2_worker_model_templated.yml
tests/08_v2_workflow_integration.yml
ui/libs/workflow-graph/src/lib/node/job-node.component.ts
ui/libs/workflow-graph/src/lib/node/matrix-node.component.ts
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/shared/searchable/searchable.component.ts
ui/src/app/shared/searchable/searchable.html
ui/src/app/shared/searchable/searchable.scss
ui/src/app/shared/shared.module.ts
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): searchable fields in run list

---

engine/api/v2_queue_worker.go
engine/api/v2_queue_worker_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_context.go
engine/worker/internal/runV2.go
engine/worker/internal/runtime_v2.go
sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go
sdk/contexts.go
sdk/v2_workflow_run.go
tests/08_v2_sub_action.yml
tests/08_v2_workflow_generic_artifacts_with_artifactory.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): run results in context 

---

cli/cdsctl/experimental_workflow_logs.go
engine/api/v2_workflow_run.go
engine/cdn/cdn_log_store.go
engine/cdn/cdn_log_store_test.go
engine/worker/internal/plugin/plugin.go
engine/worker/internal/runV2.go
engine/worker/internal/types.go
sdk/grpcplugin/grpcplugin.go
sdk/v2_action.go
tests/08_v2_sub_action.yml
ui/src/app/views/projectv2/run/run-job-logs.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(worker): add post action

---

contrib/grpcplugins/action/cacheSave/main.go
contrib/grpcplugins/action/downloadArtifact/main.go
contrib/grpcplugins/grpcplugins.go
contrib/grpcplugins/grpcplugins_cache.go
engine/api/api_routes.go
engine/api/v2_queue.go
engine/cdn/auth.go
engine/cdn/cdn_file.go
engine/cdn/cdn_item.go
engine/cdn/item/dao.go
engine/cdn/item/gorp_model.go
engine/cdn/item_handler.go
engine/worker/internal/action/test_helper.go
engine/worker/internal/http_server.go
engine/worker/internal/runtime_v2.go
engine/worker/internal/types.go
engine/worker/pkg/workerruntime/handlers_v2.go
engine/worker/pkg/workerruntime/mock_workerruntime/runtime_mock.go
engine/worker/pkg/workerruntime/types.go
sdk/cdn.go
sdk/cdsclient/client_queue_V2.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/doc/route.go
tests/08_v2_cache.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: enable cache v2 on CDN

---

engine/api/v2_project_repository.go
engine/api/v2_project_repository_test.go
engine/hooks/hooks_repositories_handlers.go
engine/hooks/hooks_router.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): remove repository event when adding it

---

contrib/grpcplugins/action/artifactory-plugins-lib/artifactory-plugins-lib.go
contrib/grpcplugins/action/debianPush/main.go
contrib/integrations/artifactory/artifactory.go
engine/api/v2_workflow_run_engine.go
engine/api/workflow_v2/dao_run_result.go
tests/08_v2_workflow_artifactory_plugins.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): rename buildinfo and release name

---

sdk/action_parser_funcs.go
tests/08_v2_step_job_conditions.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): as success(), we must use needs context for failure()

---

ui/src/app/views/projectv2/run/run-job-logs.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): display post action step logs

---

contrib/vscode-cds/webviews/workflow-preview/angular.json
contrib/vscode-cds/webviews/workflow-preview/src/app/app.module.ts
ui/angular.json
ui/libs/workflow-graph/src/lib/node/job-node.html
ui/libs/workflow-graph/src/lib/node/job-node.scss
ui/libs/workflow-graph/src/lib/node/matrix-node.component.ts
ui/libs/workflow-graph/src/lib/node/matrix-node.html
ui/libs/workflow-graph/src/lib/node/matrix-node.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): restart job icons

---

engine/elasticsearch/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(elasticsearch): index document without id

---

engine/worker/v2_cmd_output.go
tests/08_v2_sub_action.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(worker): use worker export from stdin

---

engine/hooks/dao_repository_event.go
engine/hooks/hooks_handlers.go
engine/hooks/hooks_repositories_handlers.go
engine/hooks/scheduler_v2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hook): balance

---

engine/api/v2_project_clean_ascode.go
engine/api/v2_repository_analyze.go
tests/08_v2_checkout.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): do not delete scheduler on non head entities

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): fill job region from integration

---

engine/api/repository/dao_vcs_project_repository.go
ui/libs/workflow-graph/src/lib/graph.model.ts
ui/libs/workflow-graph/src/lib/node/job-node.component.ts
ui/libs/workflow-graph/src/lib/node/matrix-node.component.ts
ui/libs/workflow-graph/src/lib/stages-graph.component.ts
ui/src/app/app.component.spec.ts
ui/src/app/app.component.ts
ui/src/app/event-v2.service.ts
ui/src/app/views/projectv2/explore/entity/entity-json-form.component.ts
ui/src/app/views/projectv2/explore/explore-entity-workflow.component.ts
ui/src/app/views/projectv2/explore/explore-entity.component.ts
ui/src/app/views/projectv2/explore/explore-entity.html
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss
ui/src/app/views/projectv2/run/run-job.scss
ui/src/app/views/projectv2/run/run.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): various fixes for v2 view

---

engine/api/v2_project_variable_migrate.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(jsonschema): from and jobs cannot be set together

---

contrib/grpcplugins/action/junit/main.go
engine/repositories/processor_checkout.go
go.mod
go.sum

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(repository): improve compute changeset

---

contrib/grpcplugins/action/dockerPush/main.go
engine/api/v2_repository_analyze.go
sdk/v2_action.go
sdk/v2_worker_model.go
sdk/v2_workflow_template.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,contrib): docker push (image list) + analysis error not returned

---

engine/api/api.go
engine/api/status.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): workflow v2 metrics

---

cli/cdsctl/admin_hooks_repository_event.go
engine/api/auth_local.go
engine/api/v2_hooks.go
engine/api/v2_hooks_test.go
engine/api/v2_repository_analyze.go
engine/api/v2_workflow_run_craft_test.go
engine/api/workflow_v2/dao_workflow_hook.go
engine/hooks/hook_repository_event.go
engine/hooks/hooks_handlers.go
engine/hooks/scheduler_repository_event.go
engine/hooks/scheduler_repository_event_test.go
engine/hooks/scheduler_v2.go
engine/hooks/trigger_analyses.go
engine/hooks/trigger_signingkey.go
engine/hooks/trigger_workflow_hook.go
sdk/contexts.go
sdk/hooks.go
sdk/hooks_repository_event.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/model/project.model.ts
ui/src/app/shared/date-from-now/date-from-now.ts
ui/src/app/shared/shared.module.ts
ui/src/app/views/projectv2/explore/explore-repository.component.ts
ui/src/app/views/projectv2/explore/explore-repository.html
ui/src/app/views/projectv2/explore/explore-repository.scss
ui/src/app/views/projectv2/explore/trigger-analysis/trigger-analysis.component.ts
ui/src/app/views/projectv2/run-list/run-list.html

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): project v2 repository view

---

contrib/grpcplugins/action/cache/cache.yml
contrib/grpcplugins/action/cache/main.go
contrib/grpcplugins/action/checkout/main.go
tests/08_v2_cache.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): create directory to checkout if needed

---

engine/api/v2_repository_analyze.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): update existing entity when def is not the same 

---

sdk/action_parser_funcs.go
sdk/action_parser_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): consider skipped as success for step

---

ui/src/app/views/projectv2/explore/trigger-analysis/trigger-analysis.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): skipped analysis

---

contrib/grpcplugins/action/cache/cache.yml
engine/worker/internal/runV2.go
engine/worker/internal/types.go
sdk/plugin.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): add continue on error on post

---

contrib/grpcplugins/action/cacheSave/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): save cache

---

engine/api/v2_workflow_run_craft.go
sdk/contexts.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add run url in context

---

engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): interpolate region

---

engine/api/v2_workflow_run_engine.go
ui/libs/workflow-graph/src/lib/node/job-node.html
ui/libs/workflow-graph/src/lib/node/matrix-node.component.ts
ui/libs/workflow-graph/src/lib/node/matrix-node.html
ui/src/app/model/project.model.ts
ui/src/app/views/projectv2/explore/explore-repository.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): interpolate and display job name

---

go.mod
go.sum
ui/src/app/shared/repository-ref-selector/repository-ref-select.html
ui/src/app/shared/repository-ref-selector/repository-ref-select.scss
ui/src/app/views/projectv2/explore/explore-repository.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): ref selector scroll

---

engine/api/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): add missing perm

---

engine/worker/internal/runV2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): only apply post action on success

---

ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): improve run v2 filter input

---

contrib/grpcplugins/action/cacheSave/main.go
engine/worker/internal/runV2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): create post action

---

cli/cdsctl/workflow_status.go

Description
Remove the code that has no practical effect
@ovh/cds

Remove the code that has no practical effect

---

contrib/grpcplugins/action/cacheSave/main.go
engine/api/action.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): manage absolute path

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): use gate inputs for job interpolation

---

cli/cdsctl/experimental_worker_model.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(cli): add migrate worker model

---

engine/worker/internal/runV2.go
sdk/action_parser_funcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): manage multiple absolute path

---

contrib/integrations/arsenal/arsenal.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): arsenal deployment

---

contrib/grpcplugins/action/debianPush/main.go
contrib/grpcplugins/action/junit/main.go
contrib/grpcplugins/action/uploadArtifact/main.go
contrib/grpcplugins/grpcplugins.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(junit): manage absolute path

---

sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): hashfiles, sort files

---

contrib/grpcplugins/action/cacheSave/main.go
contrib/grpcplugins/action/junit/main.go
sdk/action_parser_funcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: use filepath.join

---

ui/src/app/views/projectv2/run-start/run-start.component.ts
ui/src/app/views/projectv2/run-start/run-start.html
ui/src/app/views/projectv2/run-start/run-start.scss
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): start workflow run v2 form

---

engine/vcs/gitea/client_tags.go
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-start/run-start.component.ts
ui/src/app/views/projectv2/run-start/run-start.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui,api): add loaders for workflow run start form

---

engine/api/v2_workflow_run_engine.go
ui/src/app/shared/repository-ref-selector/repository-ref-select.component.ts
ui/src/app/shared/repository-ref-selector/repository-ref-select.html
ui/src/app/views/projectv2/explore/trigger-analysis/trigger-analysis.html
ui/src/app/views/projectv2/run-start/run-start.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui,api): place holder for ref selector

---

contrib/grpcplugins/action/artifactory-plugins-lib/artifactory-plugins-lib.go
contrib/integrations/artifactory/artifactory-promote-plugin/main.go
contrib/integrations/artifactory/artifactory-release-plugin/main.go
contrib/integrations/artifactory/artifactory.go
engine/worker/internal/runV2.go
engine/worker/internal/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): check is runresult is part of a release

---

engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): create head entity when user have no right

---

sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go

Add `b64enc`/`b64dec`/`b32enc`/`b32dec` to the default SDK funcs.
cc/ @fsamin

feat(sdk): add base64/32 encoding/decoding functions

---

sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go

Add `trimAll`, `trimPrefix` and `trimSuffix` SDK funcs.
Note that the order of parameters expected is the inverse of the underlying `strings` functions that are used, i.e `trim* <prefix/suffix/cutset> <value>`.

feat(sdk): add trim functions

---

contrib/integrations/artifactory/artifactory.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(plugin): move flag to the right place

---

engine/api/v2_repository_analyze.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): fix entities list to use

---

sdk/glob/glob.go
sdk/glob/glob_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): manage relative path starting with ./

---

ui/src/app/views/projectv2/project.module.ts
ui/src/app/views/projectv2/run/run-info.component.ts
ui/src/app/views/projectv2/run/run-info.html
ui/src/app/views/projectv2/run/run-info.scss
ui/src/app/views/projectv2/run/run-results.html
ui/src/app/views/projectv2/run/run-results.scss
ui/src/app/views/projectv2/run/run-tests.component.ts
ui/src/app/views/projectv2/run/run-tests.html
ui/src/app/views/projectv2/run/run-tests.scss
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(ui): run v2 tests list

---

cli/cdsctl/tools.go
sdk/v2_workflow_template.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vscode): add missing jsonschema

---

engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go
sdk/v2_workflow.go
tests/08_v2_manualjob.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): allow gate and if together

---

engine/worker/internal/runV2.go
engine/worker/internal/types.go
sdk/action_parser_funcs.go
sdk/v2_workflow_run.go
tests/08_v2_sub_action.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): only export path if needed

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: implement custom semver for debian package based on changelog

---

engine/hatchery/openstack/get.go
engine/hatchery/openstack/spawn.go
engine/hatchery/openstack/spawn_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): do not ignore error when flavor doesn't exist

---

ui/src/app/views/project/project.component.ts
ui/src/app/views/project/project.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): remove v2 banner

---

engine/api/v2_repository_analyze.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): allow hooks to list analysis

---

contrib/grpcplugins/grpcplugins_script.go
engine/worker/internal/plugin/socket.go
engine/worker/internal/runV2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): merge worker and context PATH

---

engine/hooks/scheduler_repository_event.go
engine/worker/internal/runV2.go
sdk/v2_workflow_run.go
tests/08_v2_sub_action.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): action step now inherits from previous exported path

---

ui/src/app/shared/searchable/searchable.component.ts
ui/src/app/shared/searchable/searchable.html
ui/src/app/shared/searchable/searchable.scss
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): start new run from run view

---

engine/api/v2_workflow_run_craft.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(engine): compute the right semver

---

engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): manage matrix with 0 permutation

---

sdk/v2_workflow_template.go
sdk/v2_workflow_template_test.go

feat: add annotations to workflow template

---

ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): filter run by annotation value with space

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
sdk/contexts.go
sdk/v2_workflow.go
sdk/v2_workflow_template.go
sdk/v2_workflow_template_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): allow to use on on workflow template

---

engine/api/v2_repository_analyze.go
sdk/v2_workflow_template_test.go
tests/08_v2_workflow_template.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): manage hook from template

---

engine/api/event_v2/event.go
engine/api/v2_workflow_run_craft.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): allow func in pr comment

---

contrib/grpcplugins/grpcplugins.go
tests/08_v2_cache.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): remove invalid utf8 before log

---

ui/src/app/views/projectv2/run/run-results.html
ui/src/app/views/projectv2/run/run-tests.component.ts
ui/src/app/views/projectv2/run/run-tests.html
ui/src/app/views/projectv2/run/run-tests.scss
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): improve v2 run tests view

---

cli/cdsctl/experimental_project_variableset_item.go
engine/api/api_routes.go
engine/api/v2_project_variable_migrate.go
sdk/cdsclient/client_project_variable_set.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/project_variable.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): allow to migrate deployment token to variableset

---

engine/api/v2_queue_worker.go
sdk/event_v2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): attach output to the right job

---

engine/hooks/dao_repository_event.go
engine/hooks/scheduler_repository_event.go
engine/hooks/scheduler_repository_event_callback.go
engine/hooks/scheduler_repository_event_retry.go
engine/hooks/trigger_analyses.go
engine/hooks/trigger_git_info.go
engine/hooks/trigger_signingkey.go
engine/hooks/trigger_workflow.go
engine/hooks/trigger_workflow_hook.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks): use the right data to remove old repository event

---

engine/hooks/dao_repository_event.go
engine/hooks/scheduler_repository_event_retry.go
sdk/v2_workflow.go
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/views/projectv2/run/gate/gate.html
ui/src/app/views/projectv2/run/gate/gate.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui,hooks): hook remove from progress queue + gate description

---

docs/content/docs/tutorials/worker_model-docker/_index.md
engine/hatchery/swarm/helper_test.go
engine/hatchery/swarm/swarm.go
engine/hatchery/swarm/swarm_util_create.go
engine/hatchery/swarm/swarm_util_create_test.go
engine/hatchery/swarm/types.go

1. Description
#4594 
1. About tests
1. Mentions
@ovh/cds

refactor: remove docker opts support

---

sdk/entity.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(entity): add commit sha in templating context

---

sdk/hooks.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): hook check pattern

---

sdk/artifact_manager/artifactory/http/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): manage zip header

---

sdk/hatchery.go
sdk/v2_worker_model.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(hatchery): add default flavor on worker model

---

sdk/v2_workflow_template.go
sdk/v2_workflow_template_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): manage default value for workflow template

---

engine/cdn/cdn_log_tcp.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(cdn): use the right job identifier

---

ui/src/app/views/settings/queue/queuev2.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): init status filter

---

engine/api/event_v2/event_run.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go
sdk/event_v2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): add match function

---

sdk/event_v2.go
ui/src/app/views/projectv2/explore/explore-repository-add.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): url to repository

---

engine/api/v2_queue_worker.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_test.go
engine/api/workflow_v2/dao_run_job.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): load jobs with run attempts

---

engine/api/workflow/dao_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): crafting only load different workflows

---

engine/api/v2_repository_analyze.go
ui/src/app/views/projectv2/run/run.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,ui): improve template error and ui run view style

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/hooks/dao_repository_event.go
engine/hooks/hooks_repositories_handlers.go
engine/hooks/scheduler_clean_old_repository_event.go
engine/hooks/scheduler_repository_event_retry.go
sdk/v2_workflow.go
tests/08_v2_workflow_job_template.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add job templated

---

contrib/vscode-cds/webviews/workflow-preview/package.json
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): integration can be interpolated

---

engine/api/v2_workflow_run_craft.go
tests/08_v2_workflow_template.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): init plugin list before workflow template check

---

sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): add func to get a value from job available contexts

---

go.mod
go.sum

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: update docker dependency

---

contrib/grpcplugins/action/uploadArtifact/main_test.go
engine/api/v2_workflow_run_engine.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): implement a copy function for job definition

---

engine/api/project_key.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): avoid deleting sshkey used by vcs

---

contrib/grpcplugins/action/addRunResult/main.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
sdk/v2_workflow.go
sdk/v2_workflow_run_detail.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): manage npm run result

---

engine/api/v2_workflow_run_craft.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): insert gate/integ/vars into templatesworkflow to lint it

---

engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): matrix job data conflict

---

ui/src/app/views/navbar/navbar.component.ts
ui/src/app/views/project/list/project.list.component.ts
ui/src/app/views/projectv2/explore/entity/entity-json-form-field.component.ts
ui/src/app/views/projectv2/explore/explore-repository-add.component.ts
ui/src/app/views/projectv2/explore/explore-repository.component.ts
ui/src/app/views/projectv2/explore/trigger-analysis/trigger-analysis.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): use project v2 store

---

engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_test.go
sdk/v2_workflow.go
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/views/projectv2/run/gate/gate.component.ts
ui/src/app/views/projectv2/run/gate/gate.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): manage gate array

---

ui/src/app/shared/shared.module.ts
ui/src/app/views/project/project.guard.ts
ui/src/app/views/project/project.module.ts
ui/src/app/views/project/project.routing.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): load project with guard

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_context.go
engine/api/v2_workflow_run_engine_test.go
sdk/error.go
sdk/v2_workflow.go
sdk/v2_workflow_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): avoid templating if job is skipped

---

engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): only avoid evaluating job if there is a template

---

ui/src/app/service/project/project.resolver.ts
ui/src/app/views/projectv2/explore/trigger-analysis/trigger-analysis.html
ui/src/app/views/projectv2/explore/trigger-analysis/trigger-analysis.scss
ui/src/app/views/workflow/show/admin/workflow.admin.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: workflow v1 edit load integrations

---

engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): gate with no job.if

---

cli/cdsctl/experimental_workflow.go
engine/api/search.go
engine/api/search/dao.go
engine/api/v2_queue.go
engine/api/v2_workflow_run.go
engine/api/workflow_run.go
engine/api/workflow_v2/dao_run.go
sdk/cdsclient/client_workflow.go
sdk/cdsclient/client_workflowv2.go
ui/src/app/views/search/search.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): global search sort and limit

---

engine/api/project/dao.go
engine/api/search.go
engine/api/search/dao.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): improve global search delay

---

engine/api/api_routes.go
engine/api/search.go
engine/api/search/dao.go
engine/api/v2_workflow_run.go
sdk/search.go
sdk/v2_workflow_run.go
ui/src/app/model/search.model.ts
ui/src/app/service/search.service.ts
ui/src/app/shared/input/input-filter.component.ts
ui/src/app/shared/input/input-filter.html
ui/src/app/shared/shared.module.ts
ui/src/app/views/navbar/navbar.html
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/search/search.component.ts
ui/src/app/views/search/search.html
ui/src/app/views/search/search.scss
ui/src/assets/i18n/en.json

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,ui): improve global search filters

---

cli/cdsctl/admin_hooks_repository_event.go
engine/api/v2_workflow_run.go
engine/hooks/trigger_workflow.go
tests/08_v2_commit.yml
tests/08_v2_distant_workflow.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks,api): do not try to get user if there is no gpgkey

---

ui/src/app/shared/input/input-filter.component.ts
ui/src/app/views/navbar/navbar.component.ts
ui/src/app/views/navbar/navbar.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): navbar load filters only if authenticated

---

engine/api/v2_project_clean_ascode.go
engine/api/v2_repository_analyze.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): update entityID when updating workflow hook on HEAD commit

---

engine/api/event_v2/event_run.go
engine/api/v2_hatchery_ws.go
engine/api/v2_queue.go
engine/api/v2_queue_test.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
engine/api/workflow_v2/dao_run_job.go
engine/sql/api/307_v2_workflow_run_job_osarch.sql
sdk/cdsclient/client_queue_V2.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/event_v2.go
sdk/hatchery/hatchery.go
sdk/v2_workflow_run.go
sdk/websocket.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,hatchery): manage osarch on job queued

---

engine/api/v2_workflow_run_craft.go
tests/08_v2_workflow_job_template_distant.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): use the right ref

---

sdk/action_parser_funcs.go
sdk/action_parser_funcs_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(sdk): add replace function

---

engine/api/workflow_v2/dao_run.go
sdk/v2_workflow_run.go
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/app.module.ts
ui/src/app/shared/repository-ref-selector/repository-ref-select.html
ui/src/app/views/navbar/navbar.component.ts
ui/src/app/views/navbar/navbar.html
ui/src/app/views/projectv2/run-list/run-list.component.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html
ui/src/app/views/projectv2/run/run.scss
ui/src/app/views/search/search-bar.component.ts
ui/src/app/views/search/search-bar.html
ui/src/app/views/search/search-bar.scss
ui/src/app/views/search/search.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: prevent job selection change on run refresh

---

engine/api/event_v2/event_analysis.go
engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
sdk/hooks_repository_event.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): interpolate region + analysis error message

---

engine/api/v2_project_vcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): udpate the vcs server, but keep the existing token

---

contrib/grpcplugins/action/checkout/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(action:checkout): lookup for gpg

---

engine/api/v2_queue.go
engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_concurrency.go
engine/api/v2_workflow_run_engine_concurrency_test.go
engine/api/v2_workflow_run_job_routines.go
engine/api/workflow_v2/dao_run_job_concurrency.go
engine/sql/api/308_v2_workflow_concurrency.sql
sdk/build.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
tests/08_v2_workflow_job_concurrency.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add workflow job concurrency

---

contrib/grpcplugins/action/checkout/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib/checkout): git config log

---

engine/hatchery/kubernetes/kubernetes.go
engine/hatchery/kubernetes/kubernetes_test.go
engine/hatchery/kubernetes/types.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery:k8s): remove wm path label

---

.build/plugin.mk

1. Description
1. About tests
1. Mentions
@ovh/cds

chore: fix windows plugin config

---

contrib/grpcplugins/action/helmPush/main.go
contrib/grpcplugins/action/pythonPush/main.go
contrib/grpcplugins/grpcplugins_script.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(actions): compatibility for windows worker

---

ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): loaders on run v2 page

---

engine/api/router_rbac_rule_variableset.go
engine/api/router_rbac_rule_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): mfa_required check for v2 run routes

---

engine/api/event_v2/event_run.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_concurrency.go
engine/api/v2_workflow_run_engine_concurrency_test.go
engine/api/v2_workflow_run_engine_test.go
engine/api/v2_workflow_run_job_routines.go
engine/api/workflow_v2/dao_run_job_concurrency.go
sdk/build.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
tests/08_v2_workflow_job_concurrency_cancel.yml
ui/libs/workflow-graph/src/lib/node/job-node.html
ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add cancel-in-progress on job concurrency

---

engine/vcs/bitbucketserver/client_status.go
engine/vcs/bitbucketserver/types.go

https://developer.atlassian.com/server/bitbucket/rest/v819/api-group-builds-and-deployments/#api-api-latest-projects-projectkey-repos-repositoryslug-commits-commitid-builds-post

fix(vcs): send parent field to bitbucket setStatus in order to use feature required builds

---

contrib/grpcplugins/action/checkout/main.go
engine/api/rbac/dao_rbac_region.go
engine/api/router_rbac_rule_region.go
engine/api/router_rbac_rule_region_test.go
engine/api/v2_workflow_run_engine.go
sdk/rbac_region.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): improve region

---

engine/vcs/bitbucketserver/client_status.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): use the new url for build status

---

engine/api/router_rbac_rule_workflow.go
engine/api/router_rbac_rule_workflow_test.go
engine/api/test/assets/assets.go
engine/api/v2_workflow_run_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): workflow perm

---

engine/api/entity_search.go
engine/api/rbac/dao_rbac_project.go
engine/api/rbac/dao_rbac_project_key.go
engine/api/rbac/dao_rbac_region.go
engine/api/v2_repository_analyze_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go
engine/sql/api/310_v2_rbac_region_all_vcs_users.sql
sdk/rbac_project.go
sdk/rbac_region.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): grant all vcs_users at once

---

engine/vcs/github/client_branch.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): fill branch.id with git refs

---

contrib/grpcplugins/grpcplugins.go
engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker,api): check error on get key + fix region on restart

---

cli/cdsctl/experimental_project_concurrency.go
engine/api/api_routes.go
engine/api/v2_project_concurrency.go
engine/api/v2_project_concurrency_test.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_concurrency.go
engine/api/v2_workflow_run_engine_test.go
engine/api/workflow_v2/dao_run_job_concurrency.go
engine/sql/api/313_v2_workflow_concurrency_if.sql
sdk/cdsclient/client_project_concurrency.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go
sdk/v2_project_concurrency.go
sdk/v2_workflow.go
tests/08_v2_workflow_concurrency.yml
tests/08_v2_workflow_job_concurrency.yml
ui/src/app/model/project.concurrency.model.ts
ui/src/app/service/projectv2/project.service.ts
ui/src/app/views/project/settings/concurrency/concurrencies.components.ts
ui/src/app/views/project/settings/concurrency/concurrencies.html
ui/src/app/views/project/settings/concurrency/concurrencies.scss
ui/src/app/views/project/settings/concurrency/concurrency.form.component.html
ui/src/app/views/project/settings/concurrency/concurrency.form.component.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): add concurrency condition + usage in UI

---

tests/08_v2_workflow_concurrency_cancel_with_job.yml
tests/08_v2_workflow_concurrency_cancel_with_workflow.yml
tests/08_v2_workflow_concurrency_with_jobs.yml
tests/08_v2_workflow_concurrency_with_workflow.yml
tests/08_v2_workflow_job_concurrency_cancel_with_job.yml
tests/08_v2_workflow_job_concurrency_cancel_with_workflow.yml
tests/08_v2_workflow_job_concurrency_with_workflow.yml

1. Description
1. About tests
1. Mentions
@ovh/cds

refactor(tests): split concurrency it

---

engine/api/user.go

1. Description
1. About tests
1. Mentions
@ovh/cds

chore(api): specific audit log for admin updates

---

engine/api/router_rbac_rule_project.go
engine/api/v2_project_repository_hook.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): allow hooks to retrieve project hook

---

engine/vcs/github/client_tag.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): set hash on tag object

---

engine/hatchery/kubernetes/kubernetes.go
sdk/cdsclient/client_queue_V2.go
ui/src/app/shared/searchable/searchable.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix: hatchery k8s osarch filter

---

engine/api/rbac/dao_rbac_variableset.go
engine/api/v2_workflow_run_engine.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): manage vcsuser and variableset

---

engine/api/v2_workflow_run_engine.go
engine/vcs/bitbucketcloud/client_status.go
engine/vcs/bitbucketserver/client_status.go
engine/vcs/github/client_status.go
engine/vcs/gitlab/client_status.go
ui/src/app/views/projectv2/run-list/run-list.html
ui/src/app/views/projectv2/run-list/run-list.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api,vcs): manage skipped status

---

cli/cdsctl/admin_database.go
sdk/cdsclient/client_admin.go
sdk/cdsclient/interface.go
sdk/cdsclient/mock_cdsclient/interface_mock.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat: improve cli utils to manage encrypted tuples

---

engine/api/repositoriesmanager/events.go
engine/api/workflow/workflow_run_event.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): send success for skipped pipeline

---

engine/api/user.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): admin update logs

---

engine/api/purge/purge_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): ApplyRetentionPolicyOnWorkflow with empty git.repository

---

contrib/grpcplugins/grpcplugins.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): use filename instead of filepath

---

engine/api/api.go
engine/api/v2_repository_analyze.go
engine/api/v2_repository_analyze_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): increase analysis retention

---

engine/worker/internal/runtime_v2.go
engine/worker/internal/runtime_v2_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(worker): upload generic artifacts

---

sdk/jsonschema.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): allows local path

---

contrib/grpcplugins/grpcplugins.go
contrib/integrations/artifactory/artifactory.go
engine/api/v2_workflow_run_engine.go
engine/worker/internal/runtime_v2.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api,worker): fix multiple buildinfo

---

engine/api/api.go
engine/api/project.go
engine/api/v2_project.go
engine/api/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): add max workflow retention

---

sdk/v2_action.go
sdk/v2_worker_model.go
sdk/v2_workflow.go
sdk/v2_workflow_template.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): improve error displayed

---

ui/src/app/views/projectv2/run/run-test.component.ts
ui/src/app/views/projectv2/run/run-test.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): add dedicated tabs for junit logs

---

sdk/hatchery/hatchery.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hatchery): remove queueJobResult as hatchery as not already booked the job

---

engine/api/v2_workflow_run_craft_test.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): add g letter before commit to have a valid semver

---

sdk/action_parser.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): error message on expression

---

engine/api/v2_hooks.go
engine/api/workflow_v2/dao_workflow_hook.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): fallback on pr event hook

---

engine/api/v2_repository_analyze.go
engine/api/v2_workflow_run_craft_test.go
engine/api/v2_workflow_run_engine_concurrency.go
sdk/v2_workflow.go

Simple fix to a common typo in the codebase.
This is very minor but displays very easily when analyzing CDSv2 repository metadata.
1. Mentions
@ovh/cds

fix(typo): workfow -> workflow

---

contrib/grpcplugins/action/artifactoryPromote/artifactoryPromote.yml
contrib/grpcplugins/action/downloadArtifact/downloadArtifact.yml

fix: correct typos in downloadArtifact and artifactoryPromote actions

---

ui/libs/workflow-graph/src/lib/graph.component.ts
ui/libs/workflow-graph/src/lib/graph.lib.ts
ui/src/app/views/projectv2/explore/explore-sidebar.scss

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): workflow run v2 graph refresh

---

cli/cdsctl/experimental_workflow.go
engine/hooks/hooks_handlers.go
sdk/v2_workflow.go
ui/src/app/views/projectv2/run-start/run-start.component.ts
ui/src/app/views/projectv2/run-start/run-start.html

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): remove manual payload

---

contrib/grpcplugins/action/addRunResult/main.go
contrib/grpcplugins/action/dockerPush/main.go
contrib/grpcplugins/grpcplugins.go
contrib/grpcplugins/grpcplugins_runresult.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib): addRunResult for docker images

---

contrib/grpcplugins/action/plugin-archive/go.mod
contrib/grpcplugins/action/plugin-archive/go.sum
contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/go.mod
contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/go.sum
contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/go.mod
contrib/grpcplugins/action/plugin-artifactory-release-bundle-distribute/go.sum
contrib/grpcplugins/action/plugin-tmpl/go.mod
contrib/grpcplugins/action/plugin-tmpl/go.sum
contrib/integrations/artifactory/artifactory-build-info-plugin/go.mod
contrib/integrations/artifactory/artifactory-build-info-plugin/go.sum
contrib/integrations/artifactory/artifactory-download-artifact-plugin/go.mod
contrib/integrations/artifactory/artifactory-download-artifact-plugin/go.sum
contrib/integrations/artifactory/artifactory-promote-plugin/go.mod
contrib/integrations/artifactory/artifactory-promote-plugin/go.sum
contrib/integrations/artifactory/artifactory-release-plugin/go.mod
contrib/integrations/artifactory/artifactory-release-plugin/go.sum
contrib/integrations/artifactory/artifactory-upload-artifact-plugin/go.mod
contrib/integrations/artifactory/artifactory-upload-artifact-plugin/go.sum
engine/gorpmapper/table_mapping.go
sdk/v2_workflow.go
sdk/v2_workflow_run.go
tests/fixtures/04SCWorkflowRunSimplePlugin/go.mod
tests/fixtures/04SCWorkflowRunSimplePlugin/go.sum

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): change yaml lib for db

---

engine/api/api.go
engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_engine.go
engine/cdn/cdn_router.go
engine/cdn/item_logs_handler.go
engine/cdn/item_logs_handler_test.go
engine/cdn/storage/dao.go
engine/cdn/websocket.go
ui/libs/workflow-graph/src/lib/graph.component.ts
ui/libs/workflow-graph/src/lib/graph.lib.ts
ui/libs/workflow-graph/src/lib/node/fork-join-node.components.ts
ui/libs/workflow-graph/src/lib/node/job-node.component.ts
ui/libs/workflow-graph/src/lib/node/job-node.html
ui/libs/workflow-graph/src/lib/node/matrix-node.component.ts
ui/libs/workflow-graph/src/lib/node/matrix-node.html
ui/libs/workflow-graph/src/lib/node/model.ts
ui/libs/workflow-graph/src/lib/node/stage-node.component.ts
ui/src/app/model/help.model.ts
ui/src/app/shared/favorite-button/favorite-button.component.ts
ui/src/app/views/home/home.html
ui/src/app/views/home/home.scss
ui/src/app/views/navbar/navbar.html
ui/src/app/views/project/project.routing.ts
ui/src/app/views/projectv2/run/run-job.component.ts
ui/src/app/views/projectv2/run/run-job.html
ui/src/app/views/projectv2/run/run-sources.component.ts
ui/src/app/views/projectv2/run/run.component.ts
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui,api): graph and logs views

---

engine/api/v2_workflow_run_engine.go
sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): manage default gate input

---

ui/libs/workflow-graph/src/lib/node/job-node.html
ui/libs/workflow-graph/src/lib/node/job-node.scss
ui/libs/workflow-graph/src/lib/node/matrix-node.html
ui/libs/workflow-graph/src/lib/node/matrix-node.scss
ui/src/app/views/projectv2/run/run-job.component.ts
ui/src/app/views/projectv2/run/run-job.html
ui/src/app/views/projectv2/run/run.html

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(ui): do not display popconfirm on explore view

---

contrib/grpcplugins/action/artifactory-plugins-lib/artifactory-plugins-lib.go
contrib/integrations/artifactory/artifactory-release-plugin/main.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(contrib/artifactoryRelease): x2 the value of timeout for release

---

engine/hooks/dao_v2_scheduler.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hook): update the member without deleting it

---

engine/api/workflow/resync_workflow.go
engine/vcs/gerrit/client_commit.go
engine/vcs/github/client_commit.go
engine/vcs/github/http.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(vcs): list commit only get first page for github like other vcs

---

engine/api/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): fork use the right repository

---

engine/api/v2_workflow_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): use the right VCS for fork

---

ui/src/app/service/projectv2/project.service.ts
ui/src/app/views/project/settings/variablesets/items/variableset.item.component.ts
ui/src/app/views/project/settings/variablesets/items/variableset.item.html
ui/src/app/views/projectv2/run/run.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(ui): allow to update variableset item + click on skipped job

---

engine/api/v2_hooks.go
engine/hooks/trigger_git_info.go
engine/hooks/trigger_signingkey.go
engine/repositories/processor_checkout.go
go.mod
go.sum
sdk/hooks_repository_event.go
sdk/repositories_operation.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks,api,repositories): pr event compute changeset with branch diff

---

engine/api/api.go
engine/api/purge/purge_v2.go
engine/api/purge/purge_v2_test.go
engine/api/v2_workflow_run.go
engine/api/v2_workflow_run_retention.go
ui/src/app/views/project/settings/retention/retention.component.ts

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): delete artifacts in parallel

---

engine/worker/internal/requirement.go

similar to https://github.com/ovh/cds/commit/579fc8f72061c42cb1ad9b0ec6c7cb4909fd1fd2

feat(worker): add retry to plugin download (wf v1)

---

engine/api/v2_workflow_run_craft.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): search previous workflow version

---

engine/api/purge/purge_v2_test.go
engine/api/workflow_v2/dao_run.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): purge must use git ref instead of workflow_ref

---

engine/api/v2_workflow_run.go
sdk/action_parser_funcs.go
sdk/action_parser_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): implement cancelled and stopped function

---

engine/api/v2_workflow_run_engine.go
engine/api/v2_workflow_run_engine_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

feat(api): refact skipped jobs

---

engine/api/v2_project_clean_ascode.go
engine/api/v2_repository_analyze.go
engine/api/workflow_v2/dao_run_job_info.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): manage non annotated tag + fix purge entities

---

engine/hooks/trigger_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hooks): do not check skip ci on manual run

---

engine/hooks/trigger_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(hook): test nil before using value

---

sdk/v2_workflow.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): check default hooks

---

sdk/v2_workflow_template.go
sdk/v2_workflow_template_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): manage workflow template default value for json type

---

engine/api/v2_workflow_run_craft.go
engine/api/v2_workflow_run_craft_test.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(api): auto assign stage on templated job

---

sdk/action_parser_funcs.go

1. Description
1. About tests
1. Mentions
@ovh/cds

fix(sdk): check input before executing actions
