sdk/worker.go
This have to be removed after sql migration script 4
=> fix (api): add OwnerID on model struct to be able to scan old fashioned database

engine/hatchery/docker/cmd.go, engine/hatchery/local/cmd.go, engine/hatchery/main.go, engine/hatchery/mesos/cmd.go, engine/hatchery/openstack/cmd.go, engine/hatchery/swarm/cmd.go, sdk/hatchery/register.go
This option explicitly allows hatchery to perform "insecure" SSL connections on CDS API.
=> feat(hatchery): add -k for insecure SSL

docker-compose.yml
This is a fix while waiting for a refactoring of the workers download from API and at hatchery local start.
This fix enable docker-compose up with hatchery local (full tested)
=> chore: docker-compose - hatchery local, fix:worker

ui/src/app/views/project/add/project.add.html
On project creation if no group added, the error not displayed.
I add a error `div` below "Add an existing group" which is displayed when no group added, and hide when there is groups.
=> fix (ui): error hide when no group added

contrib/actions/cds-perl-test.hcl
Allow to execute prove outside the tests directory, and so test
several ones at once. In case of classic hierarchy lib/, t/, xt/
proveOptions could be set to:
--timer -lr t xt
while testDirectory is the root directory of the module.
=> feat (contrib/actions): Add proveOptions parameter to CDS_PerlTest

contrib/plugins/plugin-venom/venom.go, engine/worker/builtin.go, vendor/github.com/runabove/venom/process.go, vendor/github.com/runabove/venom/process_files.go
This is used by plugin-venom
+ use io.writer on plugin-venom to see venom output on cds logs
=> feat (plugin): allow using cds.build.var in a plugin

cli/README.md
We cannot run `go get` with the root cds project URL.
```
go get github.com/ovh/cds
can't load package: package github.com/ovh/cds: no buildable Go source files in /Users/user/work/dev/go/src/github.com/ovh/cds
```
This is fixed with running `go get github.com/ovh/cds/cli` instead.
=> doc: fix go get command

cli/cds/login/login.go, cli/cds/user/verify.go, docker-compose.yml, tests/sc_join_action.yml
This PR:
- fix cds user verify to use same config file as cds signup (and use token instead of password). #796  to allow session mode only.
- Remove a go pre-requisite for a test -> no need to put go inside docker image hatchery-local to run test (go was not usefull for the test too)
- set default Provision to 1 on hatchery local
=> test: it tests on all branches

engine/api/database/cli.go
Sample output:
```
$ api database status --db-password cds
Record '001_gorp_migrations_lock.sql' not in migration list, manual migration needed
Record '002_template.sql' not in migration list, manual migration needed
Record '003_worker_model-permissions.sql' not in migration list, manual migration needed
Record '004_clean_worker_model.sql' not in migration list, manual migration needed
|              MIGRATION              | APPLIED |
|-------------------------------------|---------|
| 000_create_all.sql                  | no      |
| 001_event.sql                       | no      |
| 002_pipeline_build.sql              | no      |
| 003_build_log.sql                   | no      |
| 004_scheduler_timezone.sql          | no      |
| 005_pollers.sql                     | no      |
| …
```
=> fix (migration): avoid panic, display error when unwanted record present

ui/src/app/shared/button/delete/delete.button.ts, ui/src/app/shared/button/delete/delete.html
Use case: in admin of an application
Delete repository, add a new repository and the button is always in showConfirmation mode
=> fix(ui): reset button when you click on delete

engine/hatchery/openstack/spawn.go
usefull with -C - on spawn with snapshot
=> fix (hatchery/openstack): force get worker

engine/hatchery/local/local.go, engine/worker/builtin_script.go
this avoid that ->
fork/exec /bin/sh : invalid argument
exec: not started
=> fix (worker): env key

engine/worker/requirement.go
=> fix (worker): check grp only if worker is attached to a worker model

contrib/actions/cds-python-pylint.hcl
This pr fixes the empty default value of the xml_output_file parameter which causes
the junit step to search for a report using an empty string and fixes the
pylintrc content definition.
=> fix (contrib): CDS_PythonPylint

engine/api/application.go, engine/api/application_variable.go, engine/api/environment.go, engine/api/project_variable.go
Sanity are too slow, really too slow on project with many apps / env.
Compute Warnings need to be refacto to be more precise, fastest without force user (with > 30 apps) to wait more dans 30" en each action on UI.
This commit in only to make UI faster, especially since the new UI get warnings async now.
=> fix (api): goroutine on sanity

engine/api/pipeline/pipeline_importer.go, engine/api/pipeline_import.go, sdk/error.go, sdk/messages.go
remove all job before insert job from yml (if stage already exist)
use oldStage.ID to insertJob, this avoid create a new stage if the current stage already exists
close #923
=> fix (api): cds pipeline import existing stages

sdk/hatchery/hatchery.go
if requirement model/ network / hostname -> no need to check hatchery
Worker will be spawned and send spanInfos showing to users that binaries are not in path.
=> feat (hatchery): no need to check binary everytime

engine/api/cache/local.go
This avoid:
fatal error: concurrent map writes
goroutine 20 [running]:
runtime.throw(0x2419962, 0x15)
/.../go/src/runtime/panic.go:605 +0x95 fp=0xc420101828 sp=0xc420101808 pc=0x102d1a5
runtime.mapassign_faststr(0x2111e80, 0xc42019a330, 0x24000f4, 0x6, 0x3087120)
/.../go/src/runtime/hashmap_fast.go:607 +0x4f5 fp=0xc4201018a8 sp=0xc420101828 pc=0x100eb35
github.com/ovh/cds/engine/api/cache.(*LocalStore).Enqueue(0xc4201a0800, 0x24000f4, 0x6, 0x2316e40, 0xc420358a20)
/.../src/github.com/ovh/cds/engine/api/cache/local.go:92 +0x366 fp=0xc420101958 sp=0xc4201018a8 pc=0x1743766
github.com/ovh/cds/engine/api/event.Publish(0x2192180, 0xc4201ac150)
/.../src/github.com/ovh/cds/engine/api/event/publish.go:28 +0x23e fp=0xc420101ae8 sp=0xc420101958 pc=0x17dcb8e …
=> fix (api): panic cache local

sdk/exportentities/pipeline.go
enable, optional, always executed not exported if they are default values
close #1032
=> fix (sdk): export pipeline - default step options

engine/worker/cmd_upload.go, sdk/cdsclient/client_queue.go
SDK: if there is no Error AND code < 300 -> error.
With a 401, there was no error returns by SDK.
=> fix (worker, sdk): worker upload file with workflow

contrib/plugins/Makefile
without ";" -> it does not work at all, silently ...
=> chore: fix Makefile Plugins

engine/worker/cmd_main.go
this avoid this deadlock (with chan) on worker shutdown:
```
goroutine 10 [running]:
runtime/pprof.writeGoroutineStacks(0x4b02480, 0xc4201ba020, 0x0, 0x0)
/Users/yesnault/go/src/runtime/pprof/pprof.go:608 +0xa7
runtime/pprof.writeGoroutine(0x4b02480, 0xc4201ba020, 0x2, 0x0, 0x0)
/Users/yesnault/go/src/runtime/pprof/pprof.go:597 +0x44
runtime/pprof.(*Profile).WriteTo(0x4b54060, 0x4b02480, 0xc4201ba020, 0x2, 0x0, 0x0)
/Users/yesnault/go/src/runtime/pprof/pprof.go:310 +0x3ab
github.com/ovh/cds/vendor/github.com/google/gops/agent.handle(0x4b02480, 0xc4201ba020, 0xc4201be02d, 0x1, 0x1, 0x0, 0x0)
/Users/yesnault/src/github.com/ovh/cds/vendor/github.com/google/gops/agent/agent.go:171 +0x1a3
github.com/ovh/cds/vendor/github.com/google/gops/agent.listen() …
```
=> fix (worker): do not hang on close

sdk/hatchery/register.go
avoid this log at startup: "routine>  No model returned by CDS api"
=> fix (hatchery): avoid log at startup

engine/hatchery/marathon/marathon.go, engine/hatchery/marathon/types.go, engine/hatchery/openstack/types.go, engine/hatchery/swarm/types.go, engine/hatchery/vsphere/types.go
Default Values (with a cfg File) are not auto-injected if key is commented in toml.
Default values are injected only for a run with environment variables
see. https://github.com/ovh/cds/blob/master/engine/config.go#L62
On config.go, no defaults.SetDefaults(conf) after viper.Unmarshal (or all hatcheries will start with docker-compose otherwise).
=> fix (hatchery): load configuration & token

engine/api/api_routes.go
Since arch 386 isn't in TARGET_ARCH in the makefile it should be the amd64 file that is the default download
And x86_64 means 64bit processor so why download a 32bit binary since the automatic worker download is based on uname -m
=> Change file download for x86_64 route

engine/worker/cmd_main.go, engine/worker/take_workflow_node_run_job.go
Keep alive the worker if the job was already taken by another worker
This is the same behaviour avec PipelineBuildJob.
=> fix (worker): don't always kill the worker

tests/sc_git_hook.yml
/hook run a goroutine, after calling it, the pipeline history can show build few seconds after in IT. retry 1, delay 3 is not enough.
=> test (engine): git hook -> retry / delay 5

engine/api/pipeline/pipeline_build.go
=> fix(api): fix getRemoteName when project is already in the repo name

sdk/cdsclient/client_environment.go, sdk/cdsclient/client_template.go, sdk/cdsclient/interface.go
* `POST /project/{key}/environment` returns a `200` code on success, which is not properly handled by the new *cdsclient* sdk that used to expect a `201`.
* Initialize `/template` routes in the new *cdsclient* sdk.
=> feat (sdk) template routes

engine/worker/requirement.go
=> fix (worker): check service only if current worker is based on a model docker

sdk/interpolate.go, sdk/interpolate_test.go
two issues fixed:
- replace empty string with empty string, instead of {{.cds__env__foo}} if foo exists with empty value
- replace values for two keys starting with same string: .cds.env.foo and .cds.env.fooBar
go test -v -run TestInterpolate
=== RUN   TestInterpolate
=== RUN   TestInterpolate/simple
=== RUN   TestInterpolate/only_unknown
=== RUN   TestInterpolate/simple_with_unknown
=== RUN   TestInterpolate/upper
=== RUN   TestInterpolate/title_and_filter_on_unknow
=== RUN   TestInterpolate/many
=== RUN   TestInterpolate/two_same_unknown
=== RUN   TestInterpolate/empty_string
=== RUN   TestInterpolate/two_keys_with_same_first_characters
=== RUN   TestInterpolate/config
--- PASS: TestInterpolate (0.00s)
--- PASS: TestInterpolate/simple (0.00s)
--- PASS: TestInterpolate/only_unknown …
=> fix (engine): interpolate with empty string

engine/worker/cmd_main.go, engine/worker/take_pipeline_build_job.go, engine/worker/take_workflow_node_run_job.go
this will avoid to have logs as:
```
go-official-1.9.1-nostalgic-meninsky      | 2017-11-04 15:44:16 | info | checkQueue> Taking job 8717, this was my booked job
go-official-1.9.1-nostalgic-meninsky      | 2017-11-04 15:44:16 | info | checkQueue> Taking job 8714
go-official-1.9.1-nostalgic-meninsky      | 2017-11-04 15:44:16 | info | checkQueue> Taking job 8713
go-official-1.9.1-nostalgic-meninsky      | 2017-11-04 15:44:16 | info | checkQueue> Taking job 8712
```
and we don't know which job is taken.
=> feat (worker): logs: debug on try take, info on taken

sdk/log/log.go
this avoid having truncated log in graylog like:
```
| 2017-11-05 16:19:17 | err  | workflow.execute> Unable to add infos on run 588: loadRun> Unable to load workflow run. query:select workflow_run.*
```
this is better:
```
| 2017-11-05 17:20:56 | err  | workflow.execute> Unable to add infos on run 588: loadRun> Unable to load workflow run. query:select workflow_run.*     from workflow_run     where workflow_run.id = $1 for update nowait args:[588]: pq: current transaction is aborted, commands ignored until end of transaction block
```
=> feat (sdk): remove new line on all log

engine/api/workflow/dao_run.go, engine/api/workflow/execute_node_run.go
Worker take a job, send info and there's errors on API (see below). This PR is only to add more context on logs.
Theses errors explains why a worker take a Job (workflow) and does not work on job after.
```
2017-11-04 15:44:20 | warn | POST    | 500  | /queue/workflows/8717/spawn/infos      postSpawnInfosWorkflowJobHandler> Cannot save job 8717: AddSpawnInfosNodeJobRun> Cannot update node job run: workflow.execute> Unable to execute node: Unable to update node id=2611 at status Building
2017-11-04 15:44:20 | err  | workflow.execute> Unable to add infos on run 554: loadRun> Unable to load workflow run%!(EXTRA string=select workflow_run.*
```
=> fix (api): more details on logs

engine/hatchery/docker/docker.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go, engine/hatchery/vsphere/spawn.go, engine/hatchery/vsphere/utils.go, engine/worker/cmd_main.go, engine/worker/init.go, engine/worker/main.go, engine/worker/take_workflow_node_run_job.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go
A worker can be launch to run a Pipeline Build Job or a Workflow Job
Before this commit, we can see:
```
| 2017-11-05 11:33:40 | warn | GET     | 404  | /queue/8820/infos      getPipelineBuildJobHandler> Unable to load pipeline build job id: Pipeline build not found
| 2017-11-05 11:33:40 | warn | GET     | 404  | /queue/8821/infos      getPipelineBuildJobHandler> Unable to load pipeline build job id: Pipeline build not found
| 2017-11-05 11:33:40 | warn | GET     | 404  | /queue/8812/infos      getPipelineBuildJobHandler> Unable to load pipeline build job id: Pipeline build not found
| 2017-11-05 11:33:40 | warn | GET     | 404  | /queue/8811/infos      getPipelineBuildJobHandler> Unable to load pipeline build job id: Pipeline build not found
```
from Worker launched to work on workflow …
=> fix (hatcheries,worker): book & take care on workflow

engine/api/pipeline_import.go
no need to call pipeline.LoadPipelines, it's already done inside sanity.CheckProjectPipelines
=> fix (api): perf import pipeline

engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go
SpawnInfo can be send in same time by hatchery & worker
this avoid many err as:
```
| 2017-11-05 14:08:01 | warn | POST    | 500  | /queue/workflows/8831/spawn/infos      postSpawnInfosWorkflowJobHandler> Cannot save job 8831: AddSpawnInfosNodeJobRun> Cannot update node job run: workflow.execute> Unable to execute node: Unable to update node id=2664 at status Waiting. err:pq: canceling statement due to statement timeout
```
=> fix (api): LoadAndLockNodeJobRunWait on spawnInfo

engine/api/error.go, engine/api/pipeline/pipeline_build_job.go, engine/api/scheduler/dao.go, engine/api/scheduler/executer.go, engine/api/workflow/process.go, sdk/error.go
There is something strange,
```
Run> Unable to load to pipeline scheduler 150 pq: could not obtain lock on row in relation "pipeline_scheduler"
```
This error should be "55P03", so ignored from log.Error. This commit is to have the real pqerr.Code
=> fix (api): more precision in the log

engine/worker/cmd_exit.go, engine/worker/cmd_server.go, engine/worker/main.go, engine/worker/run.go
worker exit command lets job finish current step and disabled all further steps
=> feat (worker): worker exit

engine/api/workflow_run.go, engine/api/workflow_run_test.go
./workflow_run_test.go:671:35: api.resyncWorkflowRunPipelinesHandler undefined (type *API has no field or method resyncWorkflowRunPipelinesHandler)
=> fix (api): resyncWorkflowRunHandler UT

engine/api/worker/worker.go, engine/worker/builtin.go, engine/worker/cmd_main.go, engine/worker/run.go, engine/worker/take_pipeline_build_job.go, engine/worker/take_workflow_node_run_job.go
And add logs on start / end step & job
As it was done for Pipeline Build
and to avoid
An error has occured: Post ...//queue/workflows/11831/result: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
=> fix (worker): add retry on Sending build result

engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go
check status without FOR UPDATE
then if status is not waiting, select again with FOR UPDATE
this will avoid FOR UPDATE select for many existing workers who try to take the job
postTakeWorkflowJobHandler> Cannot take job 12043: TakeNodeJobRun> job 12043 is not waiting status. Current status:Building: This job is already taken by another worker
=> fix (api): quick check status on take

engine/api/api.go, engine/api/api_routes.go, engine/api/auth/auth.go, engine/api/auth/localclient.go, engine/api/debug.go
The API handles /admin/debug for admins. You just have to add your session token as a query param.
It is inspired by the net/http/pprof package, with a few custom things.
I hope we will be able to embbed the next pprof web ui from go 1.10 https://twitter.com/rakyll/status/887401222478602241?lang=fr
=> feat (api): pprof handlers

ui/src/app/app.component.ts
_translate.getBrowserLang(); always returns en
=> fix (ui): fix load locale fr

engine/vcs/bitbucket/types.go, engine/vcs/bitbucket/types_test.go
Example of GET (mix of string / bool in value)
```json
{
"version": "3",
"locationCount": "2",
"httpMethod": "POST",
"url": "https://foo",
"postContentType": "application/x-www-form-urlencoded",
"postData": "",
"branchFilter": "",
"tagFilter": "",
"userFilter": "",
"httpMethod2": "GET",
"url2": "http://foo.local",
"skipSsl2": true,
"postContentType2": "application/x-www-form-urlencoded",
"branchFilter2": "",
"tagFilter2": "",
"userFilter2": ""
}
```
=> fix (vcs): GET/PUT bitbucket /settings

contrib/plugins/plugin-venom/README.md
Simple doc cleanup.  Also added the `vars-from-file` while here.
=> Remove reference to the `parallel` option in the venom plugin.

contrib/uservices/cds2xmpp/service/bot.go
Send XMPP message as HTML to highlight notifications.
ref: https://github.com/mattn/go-xmpp/blob/master/xmpp.go#L644
=> send XMPP message in HTML

engine/api/hatchery.go
after a stop / start of hatchery, model ID was not set anymore on local hatchery
=> fix (api): update hatchery local

sdk/interpolate.go, sdk/interpolate_helper.go, sdk/interpolate_test.go
before
````
Running tool: /Applications/go/bin/go test -v -benchmem -run=^$ github.com/ovh/cds/sdk -bench ^BenchmarkInterpolate$
goos: darwin
goarch: amd64
pkg: github.com/ovh/cds/sdk
BenchmarkInterpolate-8   	    5000	    261920 ns/op	  109879 B/op	     682 allocs/op
PASS
ok  	github.com/ovh/cds/sdk	1.352s
Success: Benchmarks passed.
````
after 
````
Running tool: /Applications/go/bin/go test -v -benchmem -run=^$ github.com/ovh/cds/sdk -bench ^BenchmarkInterpolate$
goos: darwin
goarch: amd64
pkg: github.com/ovh/cds/sdk
BenchmarkInterpolate-8   	   10000	    152740 ns/op	   59311 B/op	     560 allocs/op
PASS
ok  	github.com/ovh/cds/sdk	1.558s
Success: Benchmarks passed.
````
=> fix (sdk): interpolate perf

cli/cdsctl/workflow.go
os.Stat(fname) returns nil if file exists
add quiet flag, default false. User can see that there are many files written by cmd.
=> fix (cdsctl): workflow pull & ask override files

vendor/github.com/docker/docker/pkg/archive/archive_unix.go, vendor/github.com/docker/docker/pkg/archive/changes_unix.go
it's a temporary patch, should be reviewed when we go on deps (and so, removing docker vendor, for using moby)
=> fix (engine): build freebsd

engine/api/workflow_hook_test.go, ui/src/app/shared/workflow/node/hook/form/node.hook.component.ts
The hook configuration was not editable anymore after creation. This commit fixes that behaviour
introduced here https://github.com/ovh/cds/pull/1772/files#diff-0f3bb1aa71e303bfc2caaf71e00493b4R53
=> fix (ui): edit existing hook

ui/src/app/views/project/show/project.component.ts
When workflows are enabled on a project, go on Worflows tab instead of Applications tab
When workflows are not enabled on a project, go on Applications tab, as before.
=> fix (ui): go to Workflows tab if wf are enabled

contrib/plugins/plugin-kafka-publish/kafka_ack.go, contrib/plugins/plugin-kafka-publish/kafka_consummer.go
With async :
calling MarkOffset does not necessarily commit the offset to the backend
store immediately for efficiency reasons, and it may never be committed if
your application crashes
This PR ensure that markOffset is done before stop the worker
=> fix (plugin/plugin-kafka-publish): no async close

engine/api/application/dao_test.go, engine/api/workflow/dao_node.go, engine/api/workflow/dao_node_run.go, engine/api/workflow/dao_test.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/gorp_model.go, engine/api/workflow/process.go, engine/sql/073_workflow_mutex.sql, sdk/messages.go, sdk/workflow.go, sdk/workflow_run.go
Adding a mutex on a workflow node will let the node run at status `waiting` if the node is already running somewhere else.
Major impacts:
* Persist mutex on workflow node in database
* Added workflow node name in the workflow run for conveniency
* If there is a mutex on a node, avoid call `workflow.execute` on the node run
* At the end of workflow node run, if there is a mutex, try to find other workflow node run for the same node and trigger `workflow.execute` on it
Next:
* We have to discuss about how to manage event channel on mutex release
* UI features will come in another PR
=> feat (api): workflow Mutex

engine/worker/cmd_main.go, engine/worker/cmd_register.go, engine/worker/cmd_run.go, engine/worker/cmd_update.go, engine/worker/main.go, engine/worker/register.go
New flag on the main cmd: --auto-update
the command ./worker [args] -> internally os.exec worker run [args]. If auto-update -> update the worker before launch the run cmd. If auto-update -> the run command check each 10min the version on api. If version is != "" : sdk.Exit and the main process will relaunch the worker.
No impact on user / hatchery.
close https://github.com/ovh/cds/issues/870
=> feat (worker): worker auto-update

engine/worker/builtin_artifact_upload.go
without waiting the end of append in globalError,
globalError could be empty after <-chanError: the test
of empty could be done before than the goroutine with sendLog + Append.
Add a waitGroup ensure that error in well append in globalError before checking
that globalError is empty or not.
=> fix (worker): artifact upload - check errors

engine/worker/builtin_artifact_upload.go
This will avoid this:
SwiftStore> Creating new session key for 1111-11111-%!B(MISSING)%!B(MISSING).git.branch%!D(MISSING)%!D(MISSING)trusty5
and error from switf after
=> fix (sdk): espace tag on Container Swift

tests/sc_artifact.yml
It could be happend when previous IT pipeline is stopped in the middle of this test case
=> tests: remove existing action

sdk/interpolate/interpolate.go, sdk/interpolate/interpolate_test.go
close #2046
before fix:
Running tool: /Users/yesnault/go/bin/go test -benchmem -run=^$ github.com/ovh/cds/sdk/interpolate -bench ^BenchmarkDo$
goos: darwin
goarch: amd64
pkg: github.com/ovh/cds/sdk/interpolate
BenchmarkDo-4   	   10000	    170029 ns/op	   53574 B/op	     546 allocs/op
PASS
ok  	github.com/ovh/cds/sdk/interpolate	1.732s
Success: Benchmarks passed.
Running tool: /Users/yesnault/go/bin/go test -benchmem -run=^$ github.com/ovh/cds/sdk/interpolate -bench ^BenchmarkDoNothing$
goos: darwin
goarch: amd64
pkg: github.com/ovh/cds/sdk/interpolate
BenchmarkDoNothing-4   	   50000	     30224 ns/op	   11906 B/op	     247 allocs/op
PASS
ok  	github.com/ovh/cds/sdk/interpolate	1.798s
Success: Benchmarks passed.
---
With fix:
goos: darwin
goarch: amd64
pkg: …
=> fix (sdk): interpolate, replace same var prefix

cli/cds/main.go, ui/README.md, ui/src/assets/i18n/fr.json
I can't login to an insecure (self-signed cert) CDS with the cli.
It looks like the code that overrides the http config was added after a check that returns immediately for login or signup (PR #173).
Is there a problem doing that also for login or signup command ?
=> fix (cli): allow insecure also for login and signup

ui/src/styles.scss
After searching an existing project in the top search navbar, the text color should be inverted too.
The `<sui-search>` component does not allow to override his `<input>` inner child with an 'inverted` class from semantic... 
https://github.com/edcarroll/ng2-semantic-ui/blob/master/src/modules/search/components/search.ts#L19
=> fix (ui): right text color on inverted sui-search

engine/worker/builtin_gitclone.go
extract .git.* only if we git clone the current application
=> fix (worker): extract .git.* only if git clone app

engine/api/api_routes.go, engine/api/hatchery.go, engine/api/hatchery/hatchery.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow_queue.go, engine/sql/080_workflow_node_run_job_spawn_attempts.sql, engine/worker/cmd_run.go, sdk/cdsclient/client_hatchery.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/hatchery/hatchery.go, sdk/hatchery/register.go, sdk/messages.go, sdk/workflow_run.go
Useful to inform user that no hatchery can spawn his worker.
The logic behind is that I count the number of hatchery, if each hatchery tried to spawn the worker but without success then I push a spawn info to inform user that we can't spawn his worker.
=> feat(hatchery): add spawn info when no hatchery can spawn a worker for this job

engine/api/worker/worker.go, sdk/hatchery/hatchery.go
and a shared.infra hatchery can't provision a worker model not shared.infra too
=> fix (api, hatchery): provision only for same group

engine/api/workflow_queue_artifact.go
for this kind of err:
postWorkflowJobArtifactWithTempURLCallbackHandler> Submitted artifact doesn't match: forbidden
=> fix (api): more logs on artifact upload err

cli/cdsctl/workflow_as_code.go, engine/api/application/application_parser.go, engine/api/application_import_test.go, engine/api/environment/environment_parser.go, engine/api/keys/parse.go, sdk/application.go, sdk/environment.go, sdk/exportentities/application.go, sdk/exportentities/environment.go, sdk/exportentities/types.go
close #2245
How to use:
```json
version: v1.0
name: myNewApp
keys:
myPGPkey:
type: pgp
regen: false
mySSHKey:
type: ssh
```
=> feat(api): import keys without values but avoid regen them

engine/api/workflow/dao.go, engine/api/workflow/dao_node_run_job.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_export_test.go, engine/api/workflow_group_test.go, engine/api/workflow_queue_test.go, engine/api/workflow_run_test.go
Refactor workflow queue sql statement, to only relies on "execGroups" and fixing the "empty jobs" bug
I guess we could optimize it to check execgroups on sql side to avoid to much.
Fixing the "count" function because it wasn't the same behavior than the queue.
Side effect... a regular can see all the queue... i think we can live with this - btw our users ask for it
and fixing a lot of tests
i hope all of this will fix the "invisible jobs" bugs
=> fix(api): workflow queue permissions

engine/worker/cmd_main.go, engine/worker/cmd_update.go, engine/worker/init.go
this will avoid this stack:
```
worker  --api http://localhost:8081 --token foo --auto-update
2018-03-13 23:48:18 [INFO] api=%!!(MISSING)(EXTRA string=http://localhost:8081)
CDS Worker version:snapshot os:darwin architecture:amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x46a06b5]
goroutine 1 [running]:
main.FlagBool(0xc4202426c0, 0x48846f8, 0xb, 0x3)
/Users/yesnault/src/github.com/ovh/cds/engine/worker/init.go:87 +0x195
main.updateCmd.func1(0xc4202426c0, 0xc4201e0780, 0x0, 0x5)
/Users/yesnault/src/github.com/ovh/cds/engine/worker/cmd_update.go:34 +0x122
main.mainCommandRun.func1(0xc4202426c0, 0xc4201e0780, 0x0, 0x5)
/Users/yesnault/src/github.com/ovh/cds/engine/worker/cmd_main.go:34 +0x229 …
```
=> fix (worker): auto-update

engine/worker/cmd_register.go, engine/worker/cmd_run.go
register cmd have to use same flags as run cmd. Without this, register command does not work:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x46a0599]
goroutine 1 [running]:
main.FlagString(0xc42027fb00, 0x487d6f9, 0x4, 0x0, 0x0)
/Users/yesnault/src/github.com/ovh/cds/engine/worker/init.go:106 +0x149
main.initFlags(0xc42027fb00, 0xc4202b7200)
/Users/yesnault/src/github.com/ovh/cds/engine/worker/init.go:150 +0x11b
main.cmdRegisterRun.func1(0xc42027fb00, 0x4d115e0, 0x0, 0x0)
/Users/yesnault/src/github.com/ovh/cds/engine/worker/cmd_register.go:23 +0x54
github.com/ovh/cds/vendor/github.com/spf13/cobra.(*Command).execute(0xc42027fb00, 0x4d115e0, 0x0, 0x0, 0xc42027fb00, 0x4d115e0) …
```
=> fix (worker): register

engine/api/migrate/default_payload.go, engine/api/worker_model.go, engine/api/worker_model_test.go, ui/src/app/views/settings/worker-model/add/worker-model.add.component.ts, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.component.ts, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html
1. Description
- user is allowed to set provision on a restricted worker model
- a default group can be a owner of a worker model
n/a
1. About tests
Manual done
1. Mentions
it's for you @henyxia
=> feat (engine,ui): allow provisioning for restricted wm 

ui/src/app/model/notification.model.ts
1. Description
cds.buildNumber does not exist anymore on workflow, use cds.version
none
1. About tests
manual
1. Mentions
@ovh/cds
=> fix (ui): default value notif for wf

engine/hooks/scheduler.go, engine/hooks/tasks.go, engine/hooks/types.go
1. Description
A new goroutine dedicated for enqueue scheduler, 30s
Existing goroutine (120s retry) works only on very old hooks or error
n/a
1. About tests
Manual done
1. Mentions
@ovh/cds
=> fix (engine): scheduler enqueue

engine/api/api.go, engine/api/grpc_server.go
1. Description
allow restrict listen addr for grpc
(cf. gitter)
close #2490
1. About tests
Manual start
1. Mentions
@ovh/cds
=> feat (engine): add addr grpc listen

engine/api/auth/auth.go
1. Description
to avoid search by non-existent uid
none
1. About tests
none
1. Mentions
@ovh/cds
=> feat (api): display name of invalid hatchery

engine/api/worker.go
1. Description
Disable the worker even it hasn't been created by a hatchery
```
/worker/1014b8d0eeebc8f9d522620b4f2a6396efed6f70cf209c6a27e9aaa8f52ce8fd/disable  disableWorkerHandler> Cannot disable a worker (workername) not started by an hatchery: forbidden
```
1. About tests
n/a
1. Mentions
@ovh/cds
=> fix(api): let me disable this worker

tools/debpacker/debpacker.go, tools/debpacker/tmpl.go
1. Description
The binary /usr/bin/<binary> has not the right permission
n/a
1. About tests
n/a
1. Mentions
@ovh/cds
=> fix(tools/debpacker): chmod +x the binary

tools/debpacker/tmpl.go
1. Description
On CDS, we need lot of manual configuration to be able to start the service. So don't try to start it after installation
n/a
1. About tests
n/a
1. Mentions
@ovh/cds
=> fix(tools/debpacker): do not start the service after installation

cli/cdsctl/login.go
```bash
cdsctl login -H https://foo/
CDS API URL: https://foo/
Username: qsf
Password:
Error: invalid character '<' looking for beginning of value
```
with this PR:
```bash
cdsctl login -H http://foo/
CDS API URL: http://foo/
Username: qsfd
Password:
Invalid URL. Remove trailing '/'
Error: Please check CDS API URL
```
Trailing '/' is a common user mistake
```bash
cdsctl login -H http://foo
CDS API URL: http://foo
Username: qsdf
Password:
Error: Please check CDS API URL
```
=> fix (cdsctl): error msg on cdsctl login

sdk/interpolate/interpolate.go, sdk/interpolate/interpolate_test.go
1. Description
interpolate should not be replaced git.branch as  git__branch
n/a
1. About tests
unit tests passed
1. Mentions
@ovh/cds
=> fix(api): interpolate should not be replaced git.branch as  git__branch

cli/cdsctl/monitoring.go, engine/api/status.go
=> feat (engine,cdsctl): improve global status compute

engine/worker/run.go
this increases the chances of having a lock on api side
=> feat (worker): retry only after 15s (max: 150s)

engine/api/auth/auth.go
1. Description
Typo on line 42
log.Info("Auth> Intializing driver (%s)", mode)
log.Info("Auth> Initializing driver (%s)", mode)
@ovh/cds
=> Fix Intializing driver

engine/api/api.go, engine/api/objectstore/objectstore.go
1. Description
Add DisableTempURL in config for the ability to disable temporary URL usage in Swift
If Swift does support temporary URL. You can disable usage in CDS
1. About tests
Nope
1. Mentions
Thanks to @yesnault for the track
@ovh/cds
=> Add DisableTempURL for the ability to disable temporary URL use in Swift

cli/cdsctl/workflow_artifact.go, engine/api/api_routes.go, engine/api/workflow_queue_test.go, engine/api/workflow_run.go, engine/worker/builtin_artifact_download.go, engine/worker/builtin_artifact_upload.go, engine/worker/cmd_download.go, engine/worker/cmd_upload.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go, sdk/workflow_run.go, sdk/workflow_run_test.go
1. Description
With CDS Workflows, the tag of an aritfact is now cds.run (399.0).
And to avoid download same artifact twice, we use a filter to keep
only one artifact per name, keep the latest (based on id filter)
none
1. About tests
ut + manual 
=> feat (engine, worker, sdk): artifact tag

ui/src/app/shared/action/step/step.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
This is temporary, tag field have to be removed
from action when old workflows will be removed from CDS Engine.
But this will avoid misunderstanding for users using old and new workflows.
=> feat (ui): info on tag field with cds workflows

engine/api/api.go, engine/api/auth/ldapclient.go
1. Description
If LDAP auth is enabled on LDAP need bind before the search, users are disconnected after API restart.
With their logs:
```
2018-05-03 15:30:23 [WARN] LDAP> Search error (uid=nico): LDAP Result Code 50 "Insufficient Access Rights": INSUFFICIENT_ACCESS_RIGHTS: failed for MessageType : SEARCH_REQUEST
Message ID : 3
SearchRequest
baseDn : 'dc=fr,dc=world,dc=company'
filter : '(uid=nico)'
scope : whole subtree
typesOnly : false
Size Limit : no limit
Time Limit : no limit
Deref Aliases : never Deref Aliases
attributes : 'uid', 'cn', 'ou', 'givenName', 'sn', 'mail', 'dn'
org.apache.directory.api.ldap.model.message.SearchRequestImpl@41843e7f: ERR_5 Attempted operation SEARCH_REQUEST by unauthenticated caller.
```
1. About tests
Use an LDAP need bind before the …
=> Add BindDN to ldap configuration & bind before search if needed

engine/worker/builtin_gitclone.go, engine/worker/builtin_gittag.go
on a tag: git.describe+cds.version
example: 0.13.0+cds.888, where 888 is the cds.version
on a non-tag: 0.31.1-1-g3dfdc2031+cds.888
notice that 0.31.1-1-g3dfdc2031 is considered as a valid semver
=> feat (worker): cds.semver review

ui/src/assets/i18n/fr.json
From 'Téléchargement' to 'Télécharger' which no longer exceeds the limits of the sidebar and match more (I think) the semantic of the panel (links to donwloads cds binaries)
=> fix(ui): change french translation for 'navbar_downloads'

cli/cdsctl/admin_grpc_plugin.go, engine/api/workflow/dao_hook.go, engine/api/workflow/hook.go, engine/api/workflow/hook_test.go, engine/sql/099_hook_ref.sql, sdk/exportentities/workflow.go, sdk/workflow_hook.go
1. Description
A new field named 'ref' is exported with workflow
This will let CDS to know if the hook have to be delete, update or create on import
close #2690
1. About tests
Unit test on impacted func
1. Mentions
@ovh/cds
=> fix (api): do not regenerate uuid on import hook

engine/api/application/application_importer.go, engine/api/application/application_platform.go, engine/api/application_deployment.go, engine/api/application_deployment_test.go, engine/api/application_import_test.go
1. Description
The problem was in a sql subquery while adding two platform deployment strategies on coming from the same platform model (which is totally legit)
#2703 
1. About tests
New unit test
1. Mentions
@ovh/cds
=> fix(api): add deployment strategy with same model

cli/cdsctl/config.go, sdk/cdsclient/client.go, sdk/cdsclient/config.go
this is useful for cdsctl, for a cds api behind a proxy
=> fix (sdk): take care of --insecure and http proxy from env

ui/src/app/views/admin/broadcast/add/broadcast.add.html, ui/src/app/views/admin/broadcast/edit/broadcast.edit.html, ui/src/app/views/admin/worker-model-pattern/add/worker-model-pattern.add.html, ui/src/app/views/admin/worker-model-pattern/edit/worker-model-pattern.edit.html, ui/src/app/views/broadcast/list/broadcast.list.component.html, ui/src/app/views/settings/action/add/action.add.html, ui/src/app/views/settings/action/edit/action.edit.html, ui/src/app/views/settings/group/edit/group.edit.html, ui/src/app/views/settings/user/edit/user.edit.html, ui/src/app/views/settings/worker-model/add/worker-model.add.html, ui/src/app/views/settings/worker-model/edit/worker-model.edit.html, ui/src/app/views/settings/worker-model/list/worker-model.list.html
- harmonize all helper to use <h2> and remove fa-3x on icons
- use borders on worker models table
- use a pointing menu instead of button group for information page
@ovh/cds
=> feat(ui): harmonize helpers + use menu instead of buttons for info

engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_util_create.go, engine/hatchery/swarm/swarm_util_create_test.go, engine/hatchery/swarm/types.go
1. Description
This option let user to add --add-host and --privileged on all containers started by the hatchery
For the add-host: unbound should be considered if the hatchery does not manage CDS Service, but using unbound for containers using a private network is much more tricky to configure than using this option.
1. About tests
UT and manual Tests done
1. Mentions
@ovh/cds
=> feat (hatchery/swarm): dockerOpts 

sdk/exportentities/workflow_test.go
with that: https://github.com/ovh/cds/pull/2816/files#diff-e62d6ddf5c536d7b3ed7418615c60916R111
ancestors are sorted.
The expected keys need to be sorted too in unit test
This will avoid this error:
```
Error Trace:
Error:		Not equal: "F" (expected)
!= "E" (actual)
Messages:	value Workflow.Joins.Joins0.Triggers.Triggers2.WorkflowDestNode.Name doesn't match. Got E but want F
assertions.go:213:
Error Trace:
Error:		Not equal: "E" (expected)
!= "F" (actual)
Messages:	value Workflow.Joins.Joins0.Triggers.Triggers1.WorkflowDestNode.Name doesn't match. Got F but want E
```
=> fix (api): unit test exportentities

engine/api/migrate/hatchery_cmd.go, engine/api/worker/pattern.go
as we want to always download the latest worker model.
use case: a snapshot openstack will contains a worker,
with -C -, the worker is not updated by the curl command
=> fix (api): do not use curl "-C -"

engine/api/project_group.go
1. Description
When we add a group on a project, it's added on app, pip, env... (recursively).
When we remove a group on a project, it should be deleted recursively
close #2829
1. About tests
manual done.
@ovh/cds
=> feat (api): project delete group recursively 

engine/api/event/publish.go, engine/api/repositoriesmanager/events.go, engine/api/workflow_queue.go
1. Description
It's not useful to sent waiting status to repo manager. For 0 stage/job pipeline, this will avoid concurrent status set on repo manager.
Fix another issue about sending event for the new UI.
1. About tests
Manual done ok.
=> fix (api): do not send waiting status to repomanager

engine/main.go
This will avoid to have a running service without a proper heartbeat on API
On a CDS base on docker deployment, this let user to put a healthcheck on a route (as /mon/status or /mon/version), if no heartbeat, the endpoint will not answer anymore, the container could restart.
=> fix (engine): heatbeat failed -> stopping serve

ui/src/app/views/broadcast/list/broadcast.list.component.scss, ui/src/common.scss
- delimit accordion content in broadcast list to wrap the markdown in order to make it look less messy
- fix glitch on CDSMenu when scrolling (the content partially pass through the menu)
@ovh/cds
=> feat(ui): modify css to delimit broadcast content  + fix glitch on CDSMenu on scroll

contrib/grpcplugins/deployment/arsenal/main.go
As a CDS user in order to access to my semver attribute i want to add CDS_SEMVER in my deployment metadata
1. Description
Just add a new metadata called CDS_SEMVER in deployment metadata
None
3. About tests
No test
4. Mentions
What is a mention ?
@ovh/cds
=> fix(plugin): add CDS_SEMVER metadata

.editorconfig, docs/.editorconfig
Signed-off-by: Joel Seguillon <joel.seguillon@gmail.com>
1. Add default .editorconfig file that helps to comply with coding style
1. https://github.com/ovh/cds/issues/2893
1. N/A
1. Should be reviewed by devs with IDE handling .editor 
@ovh/cds
=> Add default .editorconfig file

engine/api/api.go, engine/api/api_test.go, engine/api/event/event.go, engine/api/event/publish.go, engine/api/event/publish_environment.go, engine/api/event/publish_pipeline.go, engine/api/event/publish_workflow.go, engine/api/event/publish_workflow_run.go, engine/api/feature_test.go, engine/api/test/test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): lint

engine/api/workflow/workflow_run_event.go, sdk/workflow_run.go, sdk/workflow_run_test.go
1. Description
fixing this error: 
````
| err  | sendVCSEventStatus> unable to compute node run reporttemplate: :9:16: executing "" at <.Tests.TotalKO>: can't evaluate field TotalKO in type *venom.Tests
````
1. About tests
1. Mentions
@ovh/cds
=> fix(api): send pull request reports with tests

engine/api/api_routes.go, engine/api/hatchery/hatchery.go, engine/api/worker.go, engine/api/worker/worker.go, engine/api/worker/worker_test.go, engine/api/worker_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): load workers per hatcheries

sdk/cdsclient/client_queue.go, sdk/hatchery/hatchery.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): try to speedup

engine/worker/run.go
1. Description
close #3068 
1. About tests
1. Mentions
cc @pgaxatte 
@ovh/cds
=> fix(worker): add error line number #3068

sdk/hatchery/starter.go
1. Description
For example, on a swarm hatchery when an user want to spawn a model with a lot of service and lack of resources on swarm. It should not return an error on worker model. Only return error on worker model when you try to register
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery): do not put worker model in error when spawn a worker for job doesn't work

engine/api/application/application_platform.go, engine/api/application_deployment.go, engine/api/workflow/dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): delete application deployment strategies

contrib/plugins/plugin-venom/venom.go, contrib/plugins/plugin-venom/venom_test.go
Signed-off-by: Marc Audefroy <marc.audefroy@corp.ovh.com>
1. Description
Currently, plugin don't handle * into the path and excluded arguments. This PR add this behaviour.
1. About tests
1. Mentions
@ovh/cds
=> feat: handle * on plugin venom for pathfile andexcluded pathfile

engine/api/workflow/process_parameters.go
1. Description
exposes {{.git.server}} in CDS workflows
1. About tests
Tested manually. git.server appears in the build variables.
@ovh/cds
=> feat: expose git.vcs_server as a template variable

engine/api/suggest.go, engine/api/workflow/execute_node_run.go
usecase:
a workflow, 1 pipeline, 2 nodes. pipeline doing checkoutApplication only. Node A: app A, Node B: appB. If we launch the workflow with git.hash = aa, git.hash is no more propagated on Node B with this fix. This will avoid a checkoutApplication on a non-existent hash. Bug introduced from https://github.com/ovh/cds/commit/906aac70466855788c0ee01aae5934f35061fd31 on action checkoutApplication
=> fix(api): reset git.hash for child pipeline if diff repo

docs/content/hosting/monitoring.md, engine/api/api.go, engine/api/status.go
example (default min is 1 for everything):
```toml
[api.status]
[api.status.api]
minInstance = 1
[api.status.dbmigrate]
minInstance = 0
[api.status.elasticsearch]
minInstance = 0
[api.status.hatchery]
minInstance = 1
[api.status.hooks]
minInstance = 1
[api.status.repositories]
minInstance = 0
[api.status.vcs]
minInstance = 1
```
=> feat(api): avoid AL if it's not an AL on /mon/status

engine/api/action/builtin.go, engine/sql/122_git_clone_default_tag.sql, engine/worker/builtin_gitclone.go, sdk/action.go, sdk/exportentities/action.go, sdk/vcs/git/git_clone.go, tests/clictl_action.yml, tests/fixtures/action_git_clone_default.yml, ui/src/app/shared/action/action.component.ts, ui/src/app/shared/action/step/step.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api,worker): add default value to tag parameter in gitClone

engine/api/metrics/metrics.go
nbJobs can't be computed as previous code
we will add worker spawn metrics (with labels model) to be more precise
=> refactor(api): remove metrics nbJobs

cli/cdsctl/monitoring.go, engine/api/router_util.go, engine/api/workflow_queue.go, sdk/build.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, ui/src/app/model/job.model.ts, ui/src/app/views/settings/queue/queue.component.html, ui/src/app/views/settings/queue/queue.component.ts, ui/src/app/views/settings/status/status.component.ts, ui/src/app/views/settings/status/status.html, ui/src/assets/worker/web/queue.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui,api,cdsctl): Add filter to queue/workflows on status

engine/api/repositoriesmanager/repositories_manager.go, engine/api/ui.go
=> fix(api): Return no err if app is not linked to a repo

ui/src/app/shared/labels/edit/labels.edit.component.html, ui/src/app/shared/labels/edit/labels.edit.component.scss, ui/src/app/shared/labels/edit/labels.edit.component.ts, ui/src/app/views/project/show/workflow/labels/workflow.list.labels.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
close #3286
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): better label modals

docs/content/workflows/pipelines/actions/builtin/gittag.md, engine/api/action/builtin.go, engine/sql/127_git_tag.sql, engine/worker/builtin_gitclone.go, engine/worker/builtin_gittag.go, sdk/exportentities/action.go
if git.describe return a tag with a 'v', keep it to compute cds.semver
New advanced parameter on gitTag action, prefix 'v' is disabled by default
If false, this field is not exported
This will be usefull for go 1.11 and allow using the default value
of tag-version-prefix for node users:
https://docs.npmjs.com/misc/config#tag-version-prefix
=> feat(action/gitTag): advanced parameter bool vprefix

engine/api/build_test.go, engine/api/event/event.go, engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/spawn.go, engine/hatchery/swarm/swarm.go, engine/hatchery/vsphere/spawn.go, sdk/namesgenerator/namesgenerator.go, sdk/namesgenerator/namesgenerator_test.go
There is too many collisions with namegenerator.
This explains the non-detecting worker timeout and the running jobs
since many days in workflow node run jobs.
=> fix(sdk): name generator - add random

docker-compose.yml, engine/hatchery/swarm/swarm.go
CDS_HATCHERY_SWARM_MAXCONTAINERS = 4 -> the hatchery can't spawn workers
(as max containers is reached with cds-ui, cds-cache, cds-api, cds-hatchery-swarm, cds-db...).
=> chore(docker-compose): maxcontainers is too small

engine/api/action/action.go, engine/api/api_routes.go, engine/api/user.go, engine/service/http.go, tests/clictl_action.yml, tests/fixtures/action_disabled_expected.yml, ui/src/app/app.component.ts, ui/src/app/service/logout.interceptor.service.ts, ui/src/assets/worker/sharedWorker.js, ui/src/assets/worker/webWorker.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix sse when 401 occured

engine/worker/cmd_run.go, engine/worker/take_workflow_node_run_job.go
don't allow worker to work on another job if it was created to work on one specified job
this will fix a bunch of issue on worker using pre-requisite service & model options
=> fix(worker): work with booked job

cli/cdsctl/admin.go, cli/cdsctl/admin_errors.go, cli/cobra.go, engine/api/api.go, engine/api/api_routes.go, engine/api/application_import.go, engine/api/ascode_test.go, engine/api/error.go, engine/api/services/dao.go, engine/api/status.go, engine/api/workflow/dao.go, engine/service/http.go, engine/worker/cmd_cache.go, engine/worker/cmd_server.go, sdk/cdsclient/client_mon.go, sdk/cdsclient/http.go, sdk/cdsclient/interface.go, sdk/error.go, sdk/error_test.go, sdk/log/log.go, sdk/request.go
1. Description
- Printing call stack and stack trace automatically in wrapped errors.
- Add UUID on error returned from API.
- Show error uuid in ctl when an error occured.
- Create admin endpoint to get error from Graylog by uuid.
- Create ctl command to get error by uuid.
2. Log strategy
- For a simple error: catched by the router and associated with a unknown sdk.Error, then logged with a UUID.
- For a sdk.Error: catched by the router the logged with a UUID.
- For a wrapped simple error: same as simple error but logged with stack trace and call stack.
- For a wrapped sdk.Error: same as sdk.Error but logged with stack trace and call stack.
3. Err return strategy
- All error from lib should be wrapped like sdk.WithStack(err) or sdk.WrapError(err, format, values...), WithStack and …
=> Generate call stack for sdk error and preserve stack trace

sdk/cdsclient/http_sse.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): no more ctx.Err() in queue polling

cli/cdsctl/workflow_export.go, cli/cdsctl/workflow_pull.go, engine/api/workflow/audit.go, engine/api/workflow/dao.go, engine/api/workflow/dao_node_run_vulnerability.go, engine/api/workflow/dao_test.go, engine/api/workflow/hook.go, engine/api/workflow/workflow_exporter.go, engine/api/workflow/workflow_exporter_test.go, engine/api/workflow/workflow_importer.go, engine/api/workflow_export.go, engine/api/workflow_test.go, sdk/cdsclient/client_export.go, sdk/cdsclient/client_import.go, sdk/cdsclient/interface.go, sdk/exportentities/workflow.go, sdk/workflow.go
1. Description
* Since a hook is mandatory for workflow as code, do not export it
* Do not export default VCS payload
* closes #3239
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow as code improvements

engine/api/api_routes.go, engine/api/events.go, engine/api/router.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add SSE metrics

engine/hatchery/swarm/swarm.go, sdk/cdsclient/client.go, sdk/cdsclient/http.go, sdk/hatchery/register.go
=> fix(hatchery/swarm): adjust http client keepAlive

engine/api/api.go, engine/api/error.go
conf toml:
```toml
###########################
#$ cdsctl admin errors get <error-id>
###########################
[api.graylog]
accessToken = ""
stream = ""
url = ""
```
=> fix(api): search err in graylog with cdsctl

engine/api/purge/purge.go, go.sum
example:
```
2018-10-24 21:24:41 [WARN] unable to load workflow 486 due to error GoRoutine>Serve>Initialize>workflows>LoadByID>load: internal server error (caused by: Unable to load workflow 486: Unable to load workflow: sql: Scan error on column index 5, name "root_node_id": converting driver.Value type <nil> ("<nil>") to a int64: invalid syntax), we try to delete it
2018-10-24 21:24:41 [WARN] workflow_node with workflow_id 486 are deleted
2018-10-24 21:24:41 [WARN] workflow with id 486 is deleted
```
=> fix(api): purge workflow with node_root_id=null

engine/api/router_middleware.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/resync_workflow.go, engine/api/workflow/workflow_run_event.go, engine/api/workflow_queue.go
this will avoid this stack:
```
[PANIC_RECOVERY] Stacktrace of 4096 bytes
goroutine 331321 [running]:
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1.1(0xc42b27da28, 0xc42018bf00, 0xc4200d1a00, 0x28ca880, 0xc43203a370)
/go/src/github.com/ovh/cds/engine/api/router.go:130 +0x502
panic(0x2150f80, 0x3a0b7a0)
/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/ovh/cds/engine/api/workflow.(*ProcessorReport).WorkflowRuns(...)
/go/src/github.com/ovh/cds/engine/api/workflow/execute_node_job_run.go:37
github.com/ovh/cds/engine/api.postJobResult(0x28d7ec0, 0xc432581500, 0xc423d70c10, 0x28fba60, 0xc420385c90, 0xc4211650e0, 0xc4277322d0, 0xc43203a410, 0x0, 0x0, ...)
/go/src/github.com/ovh/cds/engine/api/workflow_queue.go:499 +0x82e …
```
=> fix(api): report could be nil

engine/hatchery/swarm/swarm_util_create.go, engine/hatchery/swarm/types.go
It's an option, as it's not enable per default on docker engine.
=> feat(hatchery/swarm): enable ipv6

cli/cdsctl/template.go, engine/api/templates.go, engine/api/workflow/workflow_importer.go, engine/api/workflowtemplate/dao.go, engine/sql/143_template_instance_workflow_name.sql, sdk/workflow_template.go, ui/src/app/views/settings/workflow-template/add/workflow-template.add.component.ts, ui/src/app/views/settings/workflow-template/form/workflow-template.form.component.ts, ui/src/app/views/settings/workflow-template/form/workflow-template.form.html
1. Description
Take care of the workflow name value from generated workflow after template execution.
Allow admin to apply a template on all projects.
Remove template instance duplicates (not already linked to a workflow with same workflow name).
1. About tests
1. Mentions
@ovh/cds
=> fix(api): Take care of workflow name value after template generation

engine/Makefile, engine/api/ascode_test.go
1. Description
go2xunit failed to generated xunit report because of some non utf8 character
1. About tests
1. Mentions
@ovh/cds
=> tests: fix unit test report

engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/workflow_importer.go, engine/api/workflow/workflow_importer_test.go, engine/api/workflow/workflow_parser.go, engine/api/workflow/workflow_parser_test.go, engine/api/workflow_import.go, engine/api/workflow_import_test.go
1. Description
Extract workflow loading out of import func and load the workflow before using workflow ParseAndImport.
This will avoid problems to load the workflow when its components were already updated (ex: workflow.Push make changes on application before loading the workflow, this will generate an error if you remove a deployment strategy on an application).
#3763 
1. About tests
Create the workflow before updating it for put workflow endpoint. The put workflow will not create the workflow anymore.
1. Mentions
@ovh/cds
=> fix(api): load old workflow before changing anything in database

engine/Makefile, engine/api/database/cli.go, engine/api/database/cli_test.go, engine/update.go, sdk/version.go
downloads sql.tar.gz from github release corresponding to the current engine version
close #1899
=> feat(engine): engine database upgrade improvement

engine/worker/run.go
Why : some makefile can try to interprete '=' in path.
ex : OBJS = $(SRCS:$(SRCS_DIR)/%.c=$(OBJDIR)/%.o)
if SRCS_DIR contains '=' this fail to create the list of objs
Even if it should be up to the build script to manage this.
This commit will prevent this kind of tricky issue.
How : use RawStdEncoding instead of StdEncoding
RawStdEncoding is the standard raw, unpadded base64 encod
=> fix(worker): remove trailing '=' from working dir

engine/hatchery/serve.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(engine): stop warning about missing panic_dumps directories

contrib/helm/cds/templates/repositories-deployment.yaml
1. Description
Just found an issue when doing kubectl apply -f repositories-deployment.yaml
It's just indentation issues, so here is my fix proposal
error: error validating "repositories-deployment.yaml": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): unknown field "volumeMounts" in io.k8s.api.core.v1.ContainerPort, ValidationError(Deployment.spec.template.spec): unknown field "mountPath" in io.k8s.api.core.v1.PodSpec, ValidationError(Deployment.spec): unknown field "volumes" in io.k8s.api.extensions.v1beta1.DeploymentSpec]; if you choose to ignore these errors, turn validation off with --validate=false
3. About tests
Tested on my kubernetes cluster
4. Mentions
@ovh/cds
=> fix(contrib): fix indentation errors in repositories deployment template file

engine/api/workflow/audit.go, engine/api/workflow/audit_test.go
=> fix(api): purge workflow audits

README.md
1. Description
Comparison matrix uses wrong anchors.
**Note**: other parts of the readme file has been updated as well due to the `.editorconfig` rules.
none.
1. About tests
none.
1. Mentions
none.
@ovh/cds
=> docs(readme): specify the right anchor on the comparison matrix

engine/hatchery/kubernetes/kubernetes.go
Adds the auth parsing to the k8s go-client so user's who are using hosted solutions can use the `kubeconfig.yaml` files!
NOTE: I haven't actually tested this, just added this in from lots and lots of reading! :)
1. Description
1. About tests
1. Mentions
@ovh/cds
=> Add auth parsing to hatchery-k8s

cli/cdsctl/template_bulk.go, docs/static/images/workflow_template_bulk.cast, tests/clictl_template_bulk.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): rename duplicated file arg for template bulk cmd

contrib/helm/cds/templates/elasticsearch-deployment.yaml
The bad indentation breakes the elasticsearch-deployment.yaml deployment in the Helm chart
@ovh/cds
=> (fix)Helm chart : bad indenting in persistent volumes of elasticsearch-deployment.yaml

ui/src/app/model/application.model.ts, ui/src/app/store/applications.state.spec.ts, ui/src/app/store/applications.state.ts, ui/src/app/views/application/show/home/application.home.component.ts, ui/src/app/views/application/show/home/application.home.html
1. Description
Also fix repository href.
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): overview empty first time opening app

engine/api/workflow/execute_node_run.go, engine/api/workflow/process_requirements.go, sdk/error.go, tests/fixtures/ITSCWRKFLW2/pipeline.yml, tests/fixtures/ITSCWRKFLW3/build_api.pip.yml, tests/fixtures/ITSCWRKFLW3/build_front.pip.yml
while computing the new job `addJobsToQueue`, the function `processNodeJobRunRequirements` now checks:
* the group of the worker model againt the `execGroups` computed on the node (close #4002)
* the binaries requirements against the worker model binary capabilitites
In case of error, the job is failed
Related issues:
#4002
About tests:
done manually
Mentions:
@ovh/cds
=> fix(api): check worker model requirements on job processing

cli/cdsctl/application_variable.go
1. Description
Arguments must have a weight to predict their order
close #2503
1. About tests
1. Mentions
@ovh/cds
=> fix(cli): application variable argument order

contrib/helm/cds/templates/vcs-deployment.yaml
1. Description
If an ingress is enabled the vcs deployment will use the ingress host as the api URL to have relevant url in the repository manager linking
#4050 
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): use external api endpoint for vcs deployment

contrib/helm/cds/requirements.yaml
1. Description
This change will prevent the embedded postgres to be deployed when the user want to use an external database.
#4057 
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): fix postgres dependency condition

engine/api/action/builtin.go, engine/api/api.go, engine/api/bootstrap/bootstrap.go, engine/api/migrate/pipeline.go, sdk/exportentities/action.go
1. Description
Clean builtin action on bootstap, by allowing the bootstrap to create or update the actions.
Add a 0.39 migration to remove all the useless parameters on all the pipelines
close #4020
1. About tests
Manually on dev and preprod env
1. Mentions
@ovh/cds
=> fix(api): clean builtin artifact actions

engine/hatchery/kubernetes/kubernetes.go
=> fix(hatchery/kubernetes): allow empty masterURL if a configFile is provided

engine/api/action/builtin.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): revert privateKey GitClone parameter to string

engine/vcs/github/client_rate_limit.go, engine/vcs/github/github.go, engine/vcs/github/http.go, engine/vcs/github/oauth_consumer.go, engine/vcs/types.go, engine/vcs/vcs.go, engine/vcs/vcs_handlers_test.go
1. Description: The existing GitHub VCS provider only allows functionality to public GitHub where the BitBucket and GitLab allow for custom URLs. This aims to fix this by using the URL config for GitHub as well as adding an APIURL config option so enterprises with custom endpoints can use this as well.
1. Related issues : None
1. About tests: Have not added additional tests, am open to suggestions about how to best test the changes.
1. Mentions
@ovh/cds
=> feat(vcs): update github vcs provider to use github enterprise

engine/api/workflow/workflow_run_event.go, engine/vcs/bitbucket/client_pull_request.go
1. Description
Refs were inverted when translating bitbucket PR to CDS PR.
Before this fix, comments on PR can't work for bitbucket.
Also if current node branch is the repo default branch this will create many comments on all PRs.
In addition because there should be only on PR for a given branch, we can stop to iterate over PRs when the PR was found.
1. About tests
1. Mentions
@ovh/cds
=> fix(vcs): inverted base and head refs for bitbucket pull requests

sdk/vcs/git/git_clone.go, sdk/vcs/git/git_test.go
1. Description
Fetching the hash is useless if branch info already given, the commit hash should be part of the branch history that was fetched on git clone.
Also because old git version don't support fetching a specific commit hash, this will remove the breaking change introduced with fetch.
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): fetch given hash only if branch or tag info not given

engine/api/workflow/as_code.go, engine/api/workflow_ascode.go, engine/api/workflow_run.go, engine/repositories/processor_common.go, ui/src/app/app.service.ts
* automatically add repository web hook on as-code migration
* publish workflow event on ascodeEventSync to update UI on ascodeEvent updates
* first gitclone failed on ascode migration
* update UI workflow cache
related to #4170
=> fix(api,ui,repositories): as-code migration

ui/src/app/shared/requirements/form/requirements.form.html
Signed-off-by: Nicolas Crocfer <nicolas.crocfer@corp.ovh.com>
1. Description
The documentation link is not good in the "Requirements" modal box.
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): change documentation link of requirements

engine/hatchery/kubernetes/types.go
1. Description
Avoiding duplicate configuration entry for KubernetesMasterURL.
I got an issue on the hatchery kubernetes component when updating CDS from 0.38.1 to 0.39.0.
`Unable to init service hatchery:kubernetes: ApplyConfiguration: internal server error (caused by: Cannot create namespace cds in kubernetes: Post https://1.1.1.1:8443/api/v1/namespaces?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers))`
It appears that I had to add CDS_HATCHERY_KUBERNETES_KUBERNETESMASTERURL to environment variable (or in config.toml).
To avoid duplicate information (Kubernetes Master URL already present in kubeconfig.yaml), @yesnault suggested me to remove default value.
1. About tests
I test this code in my dev …
=> fix(hatchery-kubernetes): remove default value for master-url

sdk/hatchery/register.go, sdk/hatchery/types.go
=> feat(hatchery): MaxConcurrentRegistering

contrib/helm/cds/templates/api-deployment.yaml, contrib/helm/cds/templates/elasticsearch-deployment.yaml, contrib/helm/cds/templates/hatchery-k8s-deployment.yaml, contrib/helm/cds/templates/hooks-deployment.yaml, contrib/helm/cds/templates/repositories-deployment.yaml, contrib/helm/cds/templates/ui-deployment.yaml, contrib/helm/cds/templates/vcs-deployment.yaml
1. Description
Update kubernetes deployment api from extension/v1beta2 to apps/v1 to allow rolling update (deployments without downtime, if numbers of replica greater than 1)
None
3. About tests
I didn't did tests, because I'm not using helm to deploy cds on ours environments, but my yaml k8s config file looks like this. 
4. Mentions
@bnjjj 
@ovh/cds
=> chore(contrib/helm): update deployment k8s api and enable rolling update

engine/worker/run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): change context timeout to be the same as in the api goroutine

engine/api/worker.go, engine/hatchery/swarm/swarm_util_kill.go
hatchery swarm: avoid error log if a container is already under deletion
=> fix(hatchery/swarm): improve some logs

docs/content/docs/components/worker/_index.md, engine/api/permission.go, engine/api/worker/worker.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, engine/worker/cmd_main.go, engine/worker/cmd_run.go, engine/worker/init.go, engine/worker/main.go, engine/worker/register.go, engine/worker/run.go, engine/worker/take_workflow_node_run_job.go
rm auto-update flag, worker will be launched only by hatchery, this flag is no need anymore
rm sub-process
kill process -> try to send result only 1 time
close #3963 (linked to cache worker on api side)
=> fix(api, worker): some fixes about cache & subprocess

engine/worker/cmd_main.go, engine/worker/cmd_run.go, engine/worker/init.go, engine/worker/main.go, engine/worker/register.go, engine/worker/run.go, engine/worker/take_workflow_node_run_job.go
rm auto-update flag, worker will be launched only by hatchery, this flag is no need anymore
rm sub-process
=> fix(worker): one process

contrib/uservices/badge/src/configuration.rs
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): fix separator for env variable in badge uservice

engine/api/worker/worker.go, engine/api/workermodel/registration.go
Theses two sequences can happen.
This fix allows to have more info about spawn register, as:
```
l2019-06-07T20:39:09.266904200Z  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
q2019-06-07T20:39:09.418793300Z  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
J2019-06-07T20:39:09.510410800Z  (1/4) Installing nghttp2-libs (1.35.1-r0)
D2019-06-07T20:39:09.523838000Z  (2/4) Installing libssh2 (1.8.2-r0)
E2019-06-07T20:39:09.538660200Z  (3/4) Installing libcurl (7.64.0-r2)
B2019-06-07T20:39:09.568090800Z  (4/4) Installing curl (7.64.0-r2)
E2019-06-07T20:39:09.594085800Z  Executing busybox-1.29.3-r10.trigger
92019-06-07T20:39:09.609865100Z  OK: 7 MiB in 19 packages
p2019-06-07T20:39:09.633641200Z    % Total    % Received % Xferd …
```
=> fix(api): 0x00/0xbf in spawnError

contrib/helm/cds/templates/api-deployment.yaml, contrib/helm/cds/templates/elasticsearch-deployment.yaml, contrib/helm/cds/templates/hooks-deployment.yaml, contrib/helm/cds/templates/repositories-deployment.yaml, contrib/helm/cds/templates/vcs-deployment.yaml
replace --decode by -d to be compatible with more distribs / os
1. Description
base64 --decode is not working on alpine, whereas base64 -d is working on alpine, debian, darwin ... 
None
3. About tests
tested on debian, macos, alpine
4. Mentions
@bnjjj 
@ovh/cds
=> fix(contrib/helm): replace --decode by -d to be compatible with more distribs / os

engine/hatchery/openstack/openstack.go, engine/hatchery/openstack/spawn.go
if multiple images (due to probably race-condition):
- use the real image on spawn
- delete all images with same name when uploading a new ones
=> fix(hatchery/openstack): manage multiple images with same name

engine/hatchery/local/local.go
This is must have if:
- osDefault != osHatchery
- provision 0 on hatchery local
=> fix(hatchery/local): check requirement os/arch

engine/api/workflow/workflow_importer.go, engine/api/workflow_import_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): when update workflow via ascode, keep the icon #4397

ui/src/app/views/home/heatmap/home.heatmap.component.ts
1. Description
Keep only one hour of finished builds (not building status) displayed into the heatmap view
@ovh/cds
=> fix(UI): Cleanup old builds on home heatmap prevents memory leak

cli/cdsctl/login.go
Signed-off-by: Raphael Westphal <westphal.raphael@gmail.com>
1. Description
During login, if the username/password is wrong, cdsctl returns "Please check CDS API URL" instead of "invalid user or password"
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): Add user/pass error check on login

ui/src/app/service/workflow/workflow.service.ts, ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #4513 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): allow set run number event if workflow is as-code

tools/debpacker/README.md, tools/debpacker/debpacker.go, tools/debpacker/tmpl.go, tools/debpacker/writer.go
* allow absolute paths in copy-files and mkdirs
* perform daemon-reload before starting service
* auto-start options to automatically start service
* "prerm" script to stop service before removing package files
* do not create a service if no binary specified
* documentation
=> fix(debPacker): allow absolute paths in copy-files and mkdirs

ui/commitlint.config.js, ui/package.json
Hello 👋 
As requested by @bnjjj , this PR does 2 things : 
- Upgrade Husky to new format, instead of using npm precommit
- Add Commitlint, to lint commit messages (based on conventional format type(scope): body)
=> chore(husky): upgrade to new format + add commitlint

engine/api/workflow_run.go, engine/api/workflow_run_test.go, sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): not allow to resynchronize pipeline on as code workflow #4806

docs/content/hosting/ready-to-run/from-binaries.md
The documentation mentions an `-f` switch, which doesn't exist. It appears that the --config argument is meant. Also since since a FreeBSD binary exists it could be mentioned.
@ovh/cds
=> fix commands, add freebsd as OS

go.mod, go.sum
close issue #4692
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(repositories): bufio.Scanner: token too long

engine/api/workflow/dao_data_hook.go, engine/hooks/hooks_handlers.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hooks): delete task handler

ui/src/app/shared/tabs/tabs.component.ts, ui/src/app/shared/tabs/tabs.html, ui/src/app/shared/workflow-template/bulk-modal/workflow-template.bulk-modal.html, ui/src/app/views/settings/workflow-template/edit/workflow-template.edit.component.ts, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
close #4824 
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): add more informations for template instances list #4824

ui/src/app/app.component.html
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>
1. Description
A banner is displayed with a the following helper class `pointing` but
the element isn't clickable.
That's why I suggest to remove this extra helper class.
None.
1. About tests
None.
1. Mentions
// @marie-j 
@ovh/cds
=> fix(ui): remove extra pointing class from the banner element

engine/worker/internal/run.go, engine/worker/internal/start_test.go
without cds.build if not worker export
=> fix(worker): use exported variables in further step

contrib/grpcplugins/action/marathon/go.sum, contrib/grpcplugins/action/marathon/main.go
Timeout is checked by WaitOnDeployment
this will avoid a panic like that:
[INFO] Stopping plugin...Error on deployment xxxxx-xxxxx-xxxxx-xxxxx: the operation has timed out
[INFO] panic: send on closed channel
[INFO]
[INFO] goroutine 50 [running]:
[INFO] main.(*marathonActionPlugin).Run.func2(0x78, 0xc4202da050, 0xc420370230, 0xc420373a20, 0xb68620, 0xc4202f80f0, 0xc4202bcc60, 0x24)
[INFO] /go/src/github.com/ovh/cds/contrib/grpcplugins/action/marathon/main.go:213 +0x1f2
[INFO] created by main.(*marathonActionPlugin).Run
[INFO] /go/src/github.com/ovh/cds/contrib/grpcplugins/action/marathon/main.go:202 +0x1159
=> fix(plugin/marathon): avoid panic on timeout

contrib/integrations/arsenal/plugin-arsenal/Makefile, contrib/integrations/hello/plugin-hello-deployment/main.go, docs/content/docs/integrations/kubernetes/kubernetes_deployment.md, docs/content/docs/integrations/rabbitmq.md, engine/api/workflow/process_requirements.go, engine/worker/internal/requirement.go, go.mod, go.sum, sdk/hatchery/hatchery.go, sdk/integration.go, sdk/requirement.go, sdk/requirement_test.go
=> fix(api): deduplicate req from plugin's integration

engine/api/ascode.go, sdk/workflow_run.go, ui/src/app/service/ascode/ascode.service.ts
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ovh/cds/engine/api.(*API).postResyncPRAsCodeHandler.func1(0x3110ce0, 0xc002caa1e0, 0x31055a0, 0xc002362440, 0xc001eece00, 0xc001358d90, 0x3110ce0)
/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/ascode.go:199 +0x5eb
=> fix(api): avoid panic if app does not exist

engine/api/authentication/gitlab/gitlab.go
Signed-off-by: Louis GOUNOT <louis-gounot@users.noreply.github.com>
1. Description
Force gitlab golang Client to use custom url from configuration when fecthing user info for User Authentication
ovh/cds#5005
1. About tests
1. Mentions
@ovh/cds
=> ovh/cds#5005 Fix gitlab user auth with custom endpoint

engine/api/workflow/dao_run.go
stacktrace was:
```
workflow.stopRunsBlocked> Error on stopRunsBlocked : GoRoutine>Serve>Initialize>
stopRunsBlocked: internal server error
(caused by: cannot get workflow node run infos: sql: Scan error on column index 2, name "stages": converting NULL to string is unsupported)
```
=> fix(api): scan error on stopRunsBlocked

cli/cdsctl/action.go, engine/api/action.go, engine/api/action/usage.go, sdk/action.go, sdk/cdsclient/client_action.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
Signed-off-by: Gaultier HUBERT <gaultier.hubert@corp.ovh.com>
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cdsctl): action usage command

contrib/integrations/kubernetes/kubernetes.yml, contrib/integrations/kubernetes/plugin-kubernetes/main.go, docs/content/docs/concepts/files/application-syntax.md, docs/content/docs/integrations/kubernetes/kubernetes_deployment.md
Signed-off-by: Axel Dumortier <axel.dumortier@ovhcloud.com>
1. Description
Allow support for Helm v3 in kubernetes deployement plugin
1. About tests
1. Mentions
@ovh/cds
=> feat(contrib): select helm version (#5058)

ui/src/app/shared/workflow/node/run/node.run.param.component.ts, ui/src/app/shared/workflow/node/run/node.run.param.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): display default payload

engine/api/workflow_queue.go, engine/vcs/bitbucketserver/client_pull_request.go, engine/vcs/bitbucketserver/client_repos.go, engine/vcs/bitbucketserver/types.go, engine/vcs/github/client_pull_request.go, engine/vcs/github/client_repos.go, engine/vcs/github/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): check and grant user before creating pullrequest or comment

engine/api/api_routes.go, engine/api/observability/http_exporter.go, engine/api/observability/init.go, engine/api/router.go, engine/service/metrics.go, go.sum
usage:
```
curl  http://localhost:8081/mon/metrics/detail/
```
returns the list of all metrics as a JSON array
```
curl -vv http://localhost:8081/mon/metrics/detail/cds/nb_users
```
Returns the detail of a metric.
Here the metric is named `cds/nb_users`
```
curl "http://localhost:8081/mon/metrics/detail/cds/queue?range=all&status=building"
```
Returns the detail of a tagged metric
You can add the query parameter `threshold=x`
to raised a 509 HTTP Error if the threshold is reached of exceeded
=> feat(engine, api): metrics through REST API

engine/api/migrate/clean_duplicate_hooks.go
=> fix(api): avoid error if project cannot be loaded

engine/api/workflow/process_node_test.go, engine/hooks/bitbucket_server.go, engine/hooks/tasks_bitbucket_test.go
This reverts commit 1db9d660e0ebf0e32d5607be3effc4fad8db3c42.
The fix should remove the set of git.author from the actor.name of bitbucket, which is not the git user.name of commit.
=> fix(hooks): revert use DisplayName as bitbucket cloud (#5064)

engine/api/api.go, engine/api/migrate/clean_duplicate_hooks.go
=> fix(api): fix hooks with empty UUID

engine/api/services/dao.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/gorp_model.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, engine/sql/194_workflow_node_job_run_infos.sql, sdk/workflow_run.go
=> feat(api): add hatchery and worker details in job run

engine/api/workflow/dao.go, engine/api/workflow_test.go
By adding a duplicate ref check in workflow.IsValid
I have to check If I need to write a migration to fix existing workflow with duplicate hooks in database
=> fix(api): forbid update workflow with duplicate hooks

engine/sql/196_sql_jobs_view.sql
=> feat(sql): add view on run nodes

docs/content/docs/concepts/files/workflow-syntax.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add doc on notification in yaml files

engine/api/workflow/dao.go, engine/api/workflow/process_node.go, ui/src/app/shared/workflow/modal/node-edit/node.edit.modal.html, ui/src/app/shared/workflow/wizard/node-add/node.wizard.component.ts, ui/src/app/shared/workflow/wizard/node-add/node.wizard.html, ui/src/app/views/workflow/add/workflow.add.html, ui/src/assets/i18n/en.json, ui/src/assets/i18n/fr.json
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: start workflow with a fork

ui/src/app/store/workflow.state.ts, ui/src/app/views/workflow/run/node/pipeline/node.pipeline.component.ts, ui/src/app/views/workflow/run/node/pipeline/spawninfo/spawninfo.component.ts
=> fix(ui): fix loading 1st job variables

engine/hooks/dao.go, engine/hooks/hooks.go, engine/hooks/hooks_handlers.go, engine/hooks/scheduler.go
=> feat(hooks): add logs and balance in/out in status

engine/api/websocket.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): allow cross origin for websocket

engine/api/websocket.go, engine/api/websocket_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): fix workflow run filter

engine/hatchery/openstack/openstack.go
we have to use the created field, and not the updated field
=> fix(openstack): killAwolServers BUILD NOSTATE

contrib/grpcplugins/action/clair/main.go, contrib/grpcplugins/grpcplugins.go, engine/api/api.go, engine/api/api_routes.go, engine/api/services.go, engine/api/services/dao.go, engine/api/services/external.go, engine/api/services_test.go, engine/config.go, engine/worker/internal/handler_service.go, sdk/cdsclient/client_services.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go, sdk/services.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): Allow to get every service through getServiceHandler

engine/api/api.go, engine/cdn/cdn_log.go, engine/cdn/status_handler.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: add metrics on cdn

engine/api/router_util.go, engine/api/timeline.go, engine/api/workflow.go, engine/api/workflow/dao_run.go, engine/api/workflow/factory_dao.go, engine/api/workflow/factory_dao_test.go, engine/api/workflow_test.go, engine/api/workflow_trigger.go, sdk/workflow.go
=> feat(api): load runs with searchWorkflows

engine/api/api.go, engine/api/workflow/gorp_model.go, engine/api/workflow/init.go, engine/api/workflow_queue_test.go
=> feat(api): defaultRegion

engine/api/workflow/dao_node_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): release mutex when stopping a node run

engine/api/services.go, engine/api/workflow_queue.go, engine/api/workflow_queue_test.go, engine/cdn/types.go, engine/hatchery/kubernetes/services_test.go, engine/hatchery/serve.go, engine/hatchery/swarm/swarm_util_logs_test.go, sdk/services.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: add public addresses for cdn

ui/src/app/shared/conditions/conditions.html, ui/src/app/shared/requirements/form/requirements.form.html, ui/src/app/shared/workflow/wizard/hook/hook.form.html, ui/src/app/shared/workflow/wizard/node-add/node.wizard.html, ui/src/app/shared/workflow/wizard/outgoinghook/wizard.outgoinghook.html, ui/src/app/views/admin/worker-model-pattern/form/worker-model-pattern.form.html, ui/src/app/views/application/show/application.html, ui/src/app/views/home/home.html, ui/src/app/views/navbar/navbar.html, ui/src/app/views/pipeline/show/pipeline.show.html, ui/src/app/views/settings/action/help/action.help.html, ui/src/app/views/settings/worker-model/form/worker-model.form.html, ui/src/app/views/settings/worker-model/help/worker-model.help.html, ui/src/app/views/settings/workflow-template/help/workflow-template.help.html, ui/src/app/views/workflow/show/notification/list/workflow.notification.list.html, ui/src/app/views/workflow/workflow.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor: fix sonar issues

engine/api/services/http.go, engine/repositories/repositories.go
=> fix(api): call services retries

engine/api/api.go, engine/api/authentication/ldap/ldap.go, engine/api/authentication/ldap/ldap_test.go, ui/src/app/service/authentication/authentication.service.ts, ui/src/app/views/auth/signin/signin.html, ui/src/app/views/auth/signin/signin.ts, ui/src/assets/i18n/en.json
1. Description
Make LDAP Auth login more generic. If config has a supplied `bindDN` value, it will use that to search the ldap server with the user search filter `userSearch`, grab the DN from the result and then try to bind using that DN and the user supplied password.
If no `bindDN` value was given, it will use the supplied login user value with the `UserDN` value and attempt to bind to the ldap server with the resulting DN and user supplied password.
Added configuration values to be able to change email, external id and full name values as well as what attributes the ldap search should request.
Added template string to modify ldap login username field.
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): generalize ldap

engine/hooks/gerrit.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hook): store md5 before sending event to channel

engine/api/notification/user.go, engine/hooks/scheduled_task.go, sdk/hook.go
=> fix(api): don't try to load cds.scheduler user

contrib/grpcplugins/action/plugin-clair/go.mod, contrib/grpcplugins/action/plugin-clair/go.sum, engine/api/test/test.go, engine/cmd_start.go, engine/hatchery/hatchery_helper_test.go, engine/hatchery/serve.go, engine/hatchery/swarm/helper_test.go, engine/hooks/tasks_github_test.go, engine/hooks/tasks_gitlab_test.go, engine/hooks/tasks_test.go, engine/repositories/repositories_test.go, engine/vcs/vcs_test.go, engine/worker/cmd.go, engine/worker/internal/action/builtin_script_test.go, engine/worker/internal/action/test_helper.go, engine/worker/internal/run.go, engine/worker/internal/start_test.go, engine/worker/internal/take.go, engine/worker/internal/types.go, go.mod, go.sum, sdk/log/log.go, ui/src/app/views/workflow/run/node/pipeline/step/step.log.html
=> fix(worker,ui): send and view all logs

engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/process.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go, engine/api/workflow_run.go, engine/worker/internal/start.go, engine/worker/internal/take.go, sdk/build.go, sdk/hatchery/hatchery.go, sdk/workflow_run.go
=> fix(api): avoid panic on err msg deleted

engine/api/router.go, engine/api/router_context.go, engine/repositories/processor_checkout.go
1. Description
Fix repo issue and show request id in panic recovery log.
1. About tests
1. Mentions
@ovh/cds
=> fix(api,repositories): clean not pushed branch when checkout

sdk/cdsclient/http_websocket.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): missing host path part on websocket request

engine/hooks/webhook.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hook): check error to avoid panic

engine/api/workflow_run.go, ui/Makefile, ui/src/app/views/workflow/run/workflow.run.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api, ui): synchronous ended child workflow + navigation parent/child

docs/content/hosting/ready-to-run/from-binaries.md
=> docs(ready-to-run): ensure cdsctl signup verify

cli/cdsctl/worker_model.go, engine/hatchery/swarm/swarm_util_create_test.go, engine/sql/208_worker_model.sql, sdk/exportentities/worker_model.go, sdk/worker_model.go
=> fix(cdsctl): worker model list - image field

contrib/README.md
1. Description
Browsing into the **contrib** section and found a broken URL.
None.
1. About tests
No test required.
1. Mentions
@ovh/cds
Signed-off-by: Antoine Leblanc <ant.leblanc@gmail.com>
=> docs(contrib): update worker models documentation URL

cli/cdsctl/workflow_artifact.go, engine/worker/cmd_artifacts.go, engine/worker/cmd_download.go, engine/worker/cmd_upload.go, engine/worker/internal/action/builtin_artifact_download_test.go, engine/worker/internal/action/builtin_artifact_upload.go, engine/worker/internal/handler_download.go, engine/worker/internal/handler_key.go, engine/worker/internal/handler_upload.go, engine/worker/internal/keys.go, sdk/error.go
=> fix(worker): improve display err on worker command

engine/api/observability/helper.go, engine/api/observability/tracing.go, engine/api/project/dao.go, engine/api/router.go, engine/api/services/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(engine): keep the main trace.span in context

engine/api/api.go, engine/api/worker.go, engine/api/workflow/execute_node_job_run.go, engine/api/workflow/execute_node_job_run_log.go, engine/api/workflow/heartbeat.go, engine/api/workflow/init.go, engine/api/workflow/run_workflow_test.go, engine/api/workflow_queue.go, engine/api/workflow_run_test.go, engine/cdn/cdn_log.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): append log when retry job

engine/api/cache/cache.go, engine/api/cache/redis.go, engine/api/event/event.go, engine/api/repositoriesmanager/events.go, engine/cdn/cdn_log.go, engine/cdn/cdn_log_test.go, engine/hooks/scheduler.go, engine/repositories/processor.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not loose logs when api restart

contrib/grpcplugins/action/plugin-venom/main.go, contrib/grpcplugins/action/plugin-venom/plugin-venom.yml
1. Description
stop-on-failure venom option was not available in venom plugin parameters
None
1. About tests
Have tested parameter behavior is OK on my CDS instance
1. Mentions
@ovh/cds
Signed-off-by: Francois Lesage francois.lesage@gmail.com
=> feat(venom plugin): add stop-on-failure parameter to venom plugin

engine/hatchery/kubernetes/kubernetes.go
=> fix(hatchery/k8s): enable service requirement

engine/api/ascode/pull_request.go, engine/api/worker.go, engine/cdn/cdn_log.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): permission on worker that are no more linked to an hatchery

ui/src/app/service/monitoring/monitoring.service.ts, ui/src/app/views/admin/service/list/service.list.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): take care of base href to get version

engine/api/websocket.go
1. Description
When looking at a workflow run, we need node run event to be able to refresh pipeline status on UI
1. About tests
1. Mentions
@ovh/cds
=> fix(api): send node run event on filter workflow run

cli/cdsctl/config.go, cli/cdsctl/login.go, cli/cdsctl/reset.go, cli/cdsctl/signup.go
Fixing cdsctl `--verbose` and `--insecure` flags not working all the time, especially during a login command
1. Description
`cdsctl --verbose --insecure login --api-url https://.....` fails when api endpoint uses TLS with an untrusted certificate. Insecure flag is not working as expected.  While fixing the use of `--insecure` flag for the login command, I also fixed it in other places, and fixed the `--verbose` flag which was not properly handled neither.
2. About tests
cdsctl commands now works on an api endpoint using a self signed certificate
3. Mentions
@ovh/cds
Signed-off-by: Pierre-Henri Symoneaux <pierre-henri.symoneaux@nokia.com>
=> fix(cdsctl):  verbose and insecure config from env or flags

cli/cdsctl/signup.go
1. Description
cdsctl verify now uses the api url provided in arguments instead of url advertised by CDS verify response. It will display a warning when provided and advertised URLs differ from each other.
This is useful when cdsctl verify is used where the advertised user facing URL is not reachable.
It also makes verify command consistent with login command behavior
1. About tests
1. Mentions
@ovh/cds
Signed-off-by: phsym <pierre-henri.symoneaux@nokia.com>
=> Fix "cdsctl verify" cmd: Do not use advertised API URL

docs/content/docs/integrations/openid-connect.md, engine/api/api.go, engine/api/authentication/oidc/openid.go, go.mod, go.sum, sdk/token.go, ui/src/app/views/auth/signin/signin.ts, ui/src/app/views/settings/user/edit/user.edit.component.ts, ui/src/app/views/settings/user/edit/user.edit.html
1. Description
This enables basic integration with openid-connect authentication providers like Keycloak or Hydra
2. About tests
Not sure yet how to automate the tests here, but for manual testing :
* Setup Keycloak ([more here](https://www.keycloak.org/getting-started/getting-started-docker))
* Start a keycloak server in Docker with `docker run -p 4040:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:11.0.1`
> Map internal port 8080 to 4040 to avoid conflict with CDS UI, in case you run everything locally
* Login to keycoak web UI as admin
* Create a realm named "cds"
* Create a user in this realm, add a password to it
* Create an openid-connect client named "cds_client", set the CDS urls, and change it from public to confidential. Save, and copy the …
=> feat(api): basic support for openid-connect authentication provider

cli/cdsctl/template_instances.go, tests/03_clictl_template_apply.yml
add version and status attributes
=> feat(cdsctl): cdsctl template instances

cli/cdsctl/queue.go, tests/01_queue_stopall.yml, tests/test.sh
=> feat(cdsctl): cdsctl queue stopall

cli/cdsctl/admin_cdn.go, engine/api/admin.go, engine/api/api.go, engine/api/services.go, engine/api/services/dao.go, engine/api/services/dao_test.go, engine/api/services/external.go, engine/api/services/gorp_model.go, engine/api/services/loader.go, engine/api/status.go, engine/api/test/assets/assets.go, engine/elasticsearch/elasticsearch_router.go, engine/repositories/repositories_router.go, engine/service/service.go, engine/sql/api/216_service_status.sql, sdk/services.go, sdk/status.go, ui/src/app/views/admin/service/list/service.list.html, ui/src/app/views/admin/service/show/service.show.html
=> feat: status for all instances

docs/content/development/contribute/documentation.md, docs/content/docs/concepts/files/workflow-syntax.md, docs/content/docs/concepts/workflow/mutex.md
1. Description
Following #4565 , the documentation has to mention the configuration as code keyword to define a mutex.
#4551 (closed by the implementation PR)
1. About tests
- Visual test done on a local Hugo Server
1. Mentions
@ovh/cds
=> Documents the configuration as code attribute for mutex

engine/api/mail/mail.go, go.mod, go.sum, tests/01_signup.yml, tests/04_sc_workflow_run_notif.yml, tools/smtpmock/message.go, tools/smtpmock/server/smtp.go
=> fix(api): sendmail utf-8

engine/api/api.go, engine/api/mail/mail.go
=> feat(engine): conf insecureSkipVerifyTLS on smtp

engine/api/pipeline_job_test.go, sdk/action.go
=> fix(api): do not clean requirements when job is disabled

engine/api/purge/purge_run.go, engine/vcs/gerrit/client_pull_request.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api):  manage change not found in gerrit

engine/cdn/cdn_log_tcp.go
If service log arrive before worker registering, worker in cdn cache doesn't have a private key
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): manage worker without private key in cache

contrib/integrations/kubernetes/plugin-kubernetes/main.go
Fix helm stable repository, as old one doesnt exist.
Related blog post:
https://helm.sh/blog/new-location-stable-incubator-charts/
@ovh/cds
=> Fix helm stable repository

engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_util_create.go, engine/hatchery/swarm/swarm_util_create_test.go, engine/hatchery/swarm/swarm_util_kill.go, engine/hatchery/swarm/types.go, engine/worker/internal/action/builtin_script.go, sdk/hatchery/register.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(harchery:swarm): improve compatibility with docker windows

ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.html, ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.scss, ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.ts, ui/src/app/views/admin/worker-model-pattern/form/worker-model.pattern.form.component.ts, ui/src/app/views/navbar/navbar.component.ts, ui/src/app/views/settings/cdsctl/cdsctl.component.ts, ui/src/app/views/settings/cdsctl/cdsctl.html, ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.component.ts, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): add button to copy run number

docs/layouts/index.json, docs/static/js/search.js
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(doc): search links

contrib/integrations/arsenal/plugin-arsenal/main.go
Arsenal can be temporarily unavailable while it redeploys itself. This
change introduce a new condition to allow follow up retries on 503 status
codes.
@ovh/cds
=> fix(contrib/integrations): arsenal deployment plugin retry on 503

engine/worker/internal/handler_cds_version_set.go, engine/worker/internal/handler_tag.go, engine/worker/internal/take.go, engine/worker/internal/types.go, sdk/cdsclient/client_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): reduce httpclient timeout and remove some context

engine/cdn/storage/storageunit.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): missing default config panic

docs/content/hosting/ready-to-run/docker-compose/docker-compose.md, docs/content/hosting/ready-to-run/docker-compose/full-example.md, docs/content/hosting/upgrade/migrate_0.48.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs: improve 0.48 migration doc

cli/cdsctl/workflow.go, cli/cdsctl/workflow_run_result.go, engine/api/workflow/workflow_run_results.go, engine/api/workflow_run.go, engine/cdn/cdn_file.go, engine/worker/internal/action/builtin_coverage.go, sdk/workflow_run_result.go
CLi Run result List:
```
+--------------------------------------+-------------+----------+
|                  ID                  |    NAME     |   TYPE   |
+--------------------------------------+-------------+----------+
| 692cb48e-577b-4f0a-8d47-d37a4874bb4f | lcov.info   | coverage |
| 161cc6d4-9563-40e2-bb5c-e7b23883f4c3 | workin.log  | artifact |
| 79a64549-0a36-411a-afd2-0fb3cb617b21 | workout.log | artifact |
| 2f6215c0-dc69-42b8-b426-3578a956310c | artin.log   | artifact |
| af98b219-7957-4353-8e74-edc08017a09e | artout.log  | artifact |
+--------------------------------------+-------------+----------+
```
=> feat(engine,cli): add coverage report in workflow run result

engine/Makefile, engine/api/api_routes.go, engine/api/workflow/dao.go, engine/api/workflow_run_log.go, engine/cdn/auth.go, engine/cdn/auth_test.go, engine/cdn/item_handler_test.go, engine/cdn/item_logs_handler_test.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn,api): check workflow access with id, use workflow name from run

engine/api/workflowtemplate/execute.go, engine/api/workflowtemplate/execute_test.go
1. Description
#5759 
1. About tests
1. Mentions
@ovh/cds
=> feat(api): template skip empty files

engine/api/workflow/dao.go, engine/api/workflow/workflow_importer.go, engine/api/workflow_export_test.go, sdk/exportentities/v1/workflow.go, sdk/exportentities/v1/workflow_test.go, sdk/exportentities/v2/workflow.go, sdk/exportentities/v2/workflow_test.go, sdk/workflow.go
1. Description
Exports purge info in workflow yaml files only if different than default values. This will hide retention_policy for project that are not using it.
When updating yaml, if purge values are removed, CDS API will preserve old values instead of reapplying default values. This will prevent from dropping legacy purge options when switching to retention policy.
1. About tests
1. Mentions
@ovh/cds
=> feat(api): export workflow purge info

engine/api/services/http.go, engine/worker/internal/handler_download.go
=> fix(api): update http client between services

engine/api/services/http.go, engine/vcs/bitbucketserver/client_branch.go
=> fix(api): for retry on timeout with service

docs/content/docs/concepts/files/pipeline-syntax.md
1. Description
1. About tests
1. Mentions
@ovh/cds
=> docs: add pipeline parameter in yaml

engine/api/event/publish_workflow.go, engine/api/event/publish_workflow_run.go, engine/api/workflow/dao.go, engine/api/workflow/factory_dao.go, engine/api/workflow/resync_workflow.go, engine/api/workflow_test.go, sdk/exportentities/v2/workflow_notification.go, sdk/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): rename EventIntegration

engine/api/api.go, engine/api/auth.go, engine/api/auth_builtin.go, engine/api/auth_local.go
=> fix(api): http cookies properties

docker-compose.yml, engine/api/router.go, engine/service/types.go, engine/ui/types.go, engine/ui/ui.go, engine/ui/ui_router.go, sdk/cdsclient/client_cdn.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): flag to enable service proxy, filter proxy routes

engine/cdn/storage/dao.go, engine/cdn/storage/storage_unit_io.go, engine/cdn/storage/storageunit_purge.go, engine/cdn/storage/storageunit_run.go, engine/cdn/storage/storageunit_test.go, ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): add deduplication by item type

engine/api/workflow/dao_run.go, engine/api/workflow_queue.go, sdk/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): return more info for error on worker set-version

cli/cdsctl/workflow_run_result.go, ui/src/app/model/workflow.run.model.ts, ui/src/app/shared/table/data-table.html, ui/src/app/views/workflow/run/node/artifact/artifact.list.component.ts, ui/src/app/views/workflow/run/node/artifact/artifact.list.html, ui/src/app/views/workflow/run/node/workflow.run.node.component.ts, ui/src/assets/i18n/en.json
1. Description
It removes the column tag on artifact list.
1. About tests
1. Mentions
@ovh/cds
=> feat(ui): display run result in artifacts list

engine/cdn/cdn_router.go, engine/cdn/storage/cds/cds.go, engine/cdn/storage/dao.go, engine/cdn/storage/local/buffer.go, engine/cdn/storage/local/local.go, engine/cdn/storage/nfs/nfs.go, engine/cdn/storage/redis/redis.go, engine/cdn/storage/s3/s3.go, engine/cdn/storage/swift/swift.go, engine/cdn/storage/types.go, engine/cdn/storage/webdav/webdav.go, engine/cdn/unit_handler.go, engine/cdn/unit_handler_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cdn): add route to be able to resync a backend with database

engine/cdn/cdn_gc.go, engine/cdn/cdn_gc_test.go, engine/cdn/cdn_item.go, engine/cdn/cdn_item_test.go, engine/cdn/storage/storageunit.go, engine/cdn/storage/storageunit_purge.go, engine/cdn/storage/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): get item unit from buffer while deleting it

engine/worker/cmd_cache.go, engine/worker/internal/handler_cache.go, engine/worker/internal/handler_tmpl_test.go, sdk/cdsclient/client_cdn.go, sdk/cdsclient/http.go, sdk/error.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): improve error message + fix retry on cdnDownloadItem

engine/cdn/cdn_sync_test.go, engine/cdn/storage/storageunit_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): random position

engine/cdn/item/dao.go, engine/cdn/item_handler.go, engine/cdn/item_handler_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): deduplicate run-result on getItems

engine/api/migrate/migrate_auth_consumer_token_expiration.go
=> fix(api): authentication consumer migration

engine/cdn/cdn_file.go, engine/cdn/item/dao.go, engine/cdn/item_handler.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): clean old worker cache items

engine/api/api_helper.go, engine/api/api_routes.go, engine/api/workflow/dao_node_run.go, engine/api/workflow_hook.go, engine/hooks/tasks.go, engine/hooks/tasks_test.go, sdk/cdsclient/client_workflow_hooks.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hooks): sync outgoing tasks

engine/api/workflow/dao_run.go, engine/sql/api/226_indexes.sql
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(engine): add missing index + improve query

engine/cdn/storage/storageunit_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdn): insert item unit on deduplication

cli/cdsctl/workflow_artifact.go, engine/cdn/cdn_file.go, engine/cdn/cdn_router.go, engine/cdn/item_handler_test.go, engine/cdn/item_upload.go, engine/cdn/migrate_handler.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cli,cdn): add command to migrate artifact into CDN

engine/api/api.go, engine/api/api_routes.go, engine/api/config.go, engine/api/purge/purge.go, engine/api/purge/purge_run.go, engine/api/workflow/dao.go, engine/sql/api/227_workflow_retention.sql, sdk/config.go, sdk/exportentities/v2/workflow.go, sdk/workflow.go, ui/angular.json, ui/src/app/model/config.service.ts, ui/src/app/service/config/config.service.ts, ui/src/app/views/workflow/show/admin/workflow.admin.component.html, ui/src/app/views/workflow/show/admin/workflow.admin.component.ts, ui/src/styles.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: move default purge on configuration

engine/api/workflow_run.go, engine/api/workflow_run_craft.go
=> fix(api): craft workflow run now locks repository

engine/api/workflow/dao_node_run.go, engine/api/workflow/resync_workflow.go
```
Process 29654 waits for ShareLock on transaction 317362823; blocked by process 41641.
Process 41641 waits for ShareLock on transaction 317362703; blocked by process 29654.
Process 29654: UPDATE workflow_node_run SET commits = $1 where id = $2
Process 41641: update "workflow_run" set "num"=$1, "version"=$2, "project_id"=$3, "workflow_id"=$4, "status"=$5, "workflow"=$6, "start"=$7, "last_modified"=$8, "infos"=$9, "last_sub_num"=$10, "last_execution"=$11, "to_delete"=$12, "join_triggers_run"=$13, "header"=$14, "read_only"=$15, "to_craft"=$16, "to_craft_opts"=$17 where "id"=$18;
```
=> fix(api): remove deacklock on database

engine/api/workflow/process_node.go
=> fix(api): protect api from bad interpolation sequences from git info

engine/api/api.go, engine/api/auth.go, engine/api/auth_local.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix: remove default group

engine/hatchery/openstack/spawn.go
=> fix(hatchery/openstack): allow usage of old worker args in user data

engine/api/environment_import.go, engine/api/project.go, engine/api/project/loader.go, engine/api/workflow/execute_node_run.go, engine/api/workflow/run_workflow.go, ui/src/app/service/project/project.service.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): take care of integration model requirements for region check

engine/api/authentication/local/dao_registration.go, engine/api/user/dao.go, sdk/user.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): validate username with regex

docker-compose.yml, docs/content/hosting/cds_services.md, docs/content/hosting/ready-to-run/docker-compose/docker-compose.md, engine/service/types.go
=> fix: docker-compose upgrade

engine/worker/internal/types.go, sdk/blur_test.go, sdk/variable.go, sdk/variable_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): multiline job variable to one line environment variable

sdk/interpolate/interpolate.go, sdk/interpolate/interpolate_helper.go, sdk/interpolate/interpolate_test.go
1. Description 
Add more helpers, will be useful for venom
1. About tests
1. Mentions
@ovh/cds
=> feat(sdk): ternary, urlencode, dirname, basename interpolate helper

engine/api/api_helper.go, engine/api/event/publish_project.go, engine/api/group.go, engine/api/group/group.go, engine/api/group/group_permission.go, engine/api/group/workflow_group.go, engine/api/group/workflow_group_test.go, engine/api/project_group.go, engine/api/project_group_test.go, engine/api/router_middleware_auth_permission_test.go, engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow/dao_test.go, engine/api/workflow/workflow_importer.go, engine/api/workflow/workflow_importer_test.go, engine/api/workflow/workflow_parser.go, engine/api/workflow/workflow_parser_test.go, engine/api/workflow_ascode_test.go, engine/api/workflow_group.go, engine/api/workflow_group_test.go, engine/api/workflow_import_test.go, engine/api/workflow_test.go, engine/api/workflowtemplate/instance.go, engine/api/workflowtemplate/instance_test.go, sdk/workflow_node.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(api): same checks for project and workflow permissions

engine/hatchery/kubernetes/helper_test.go, engine/hatchery/kubernetes/kill_workers.go, engine/hatchery/kubernetes/kill_workers_test.go, engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/kubernetes/kubernetes_test.go, engine/hatchery/kubernetes/secrets.go, engine/hatchery/kubernetes/services.go, engine/hatchery/kubernetes/services_test.go, engine/hatchery/kubernetes/types.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/marathon/marathon_test.go, engine/hatchery/openstack/openstack.go, engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_conf.go, engine/hatchery/swarm/swarm_test.go, engine/hatchery/vsphere/client.go, engine/hatchery/vsphere/hatchery.go, sdk/hatchery/hatchery_test.go, sdk/hatchery/mock_hatchery/interface_mock.go, sdk/hatchery/pool.go, sdk/hatchery/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery:k8s): worker config as secret

engine/hatchery/kubernetes/kill_workers.go, engine/hatchery/kubernetes/kill_workers_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(hatchery:k8s): add delay before pending workers cleanup

sdk/exportentities/v2/workflow.go
Typo: the version number in the json schema was incorrect.
Signed-off-by: Stéphane Roy <stephane.roy@ovhcloud.com>
@ovh/cds
=> fix(contrib): typo in workflow.go

engine/api/workflow/process_node.go
=> fix(api): raise error if git.branch and git.tag are set

cli/cdsctl/consumer.go, engine/api/auth_consumer.go, engine/api/authentication/builtin/builtin.go, ui/src/app/model/authentication.model.ts, ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.component.ts, ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.html, ui/src/app/views/settings/user/consumer-details-modal/consumer-details-modal.html
=> feat(ui,cli): set service (name, type, region) on new consumer

engine/api/api_routes.go, engine/api/workflow.go, engine/api/workflow_queue_test.go, engine/api/workflow_run.go, engine/api/workflow_run_test.go
=> fix(api): hooks uservice calls getWorkflowRunHandler

engine/api/application/dao.go, engine/api/application/dao_application_integration.go, engine/api/application/dao_application_integration_test.go, engine/api/application/dao_dependencies.go, engine/api/application_deployment_test.go, engine/api/project/loader.go
=> fix(api): load missing fields from app deployment strategies

docs/content/docs/concepts/workflow/hooks/_index.md
There are two broken links on the hooks documentation.
https://ovh.github.io/cds/docs/concepts/workflow/hooks/
This PR should fix that issue.
=> doc: Fix broken links on hooks page

engine/api/workflow/workflow_parser.go, sdk/exportentities/v1/workflow_test.go, sdk/exportentities/v2/workflow.go, sdk/exportentities/v2/workflow_notif_test.go, sdk/exportentities/v2/workflow_notification.go, sdk/exportentities/v2/workflow_test.go, sdk/exportentities/workflow.go
=> fix(sdk): ignore invalid notif type

cli/cdsctl/workflow_transform_as_code.go, engine/api/application/application_vunerability.go, engine/api/application_import.go, engine/api/environment_import.go, engine/api/keys/parse.go, engine/api/pipeline/pipeline_parser.go, engine/api/pipeline_import.go, engine/api/workflow_import.go, sdk/cdsclient/client_import.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(sdk): return error messages on ascode import

engine/api/project_integration.go, engine/api/project_integration_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): check name pattern on postProjectIntegrationHandler

engine/api/workflow/execute_node_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): inherit parent status for join and fork

engine/worker/internal/run.go, engine/worker/internal/start_test.go, engine/worker/internal/types.go, sdk/messages.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(worker): show running worker hooks in job spawn info

engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/kubernetes/kubernetes_test.go, engine/hatchery/kubernetes/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery:k8s): set memory and CPU limits for workers and services

ui/src/app/service/authentication/error.interceptor.ts, ui/src/app/views/project/show/project.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): redirect mfa on project pages

ui/src/app/shared/workflow/sidebar/run-list/workflow.sidebar.run.component.html, ui/src/app/views/application/show/application.html, ui/src/app/views/application/show/application.scss, ui/src/app/views/environment/show/environment.show.html, ui/src/app/views/environment/show/environment.show.scss, ui/src/app/views/pipeline/show/pipeline.show.component.ts, ui/src/app/views/pipeline/show/pipeline.show.html, ui/src/app/views/pipeline/show/pipeline.show.scss, ui/src/app/views/pipeline/show/workflow/pipeline.workflow.html, ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.component.ts, ui/src/app/views/settings/user/consumer-create-modal/consumer-create-modal.html, ui/src/app/views/settings/user/consumer-details-modal/consumer-details-modal.component.ts, ui/src/app/views/settings/user/consumer-details-modal/consumer-details-modal.html, ui/src/app/views/settings/user/edit/user.edit.component.ts, ui/src/app/views/settings/user/edit/user.edit.html, ui/src/app/views/workflow/run/workflow.run.html, ui/src/app/views/workflow/run/workflow.run.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(ui): remove consumer SUIModal + last suiPopup

cli/cdsctl/admin_database.go, sdk/cdsclient/client_admin.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
=> feat(cli): add verbosity to cdsctl admin database commands

engine/api/admin_test.go, engine/gorpmapper/dao.go
=> fix(engine): rollover encrypted map

sdk/cdsclient/client_template.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
Allow to pass request modifiers (query parameters) when applying a template
=> feat(sdk.cdsclient): allow to pass modifiers on template apply

engine/api/workflow_queue.go, engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/kubernetes/services_test.go, engine/hatchery/local/local.go, engine/hatchery/marathon/marathon.go, engine/hatchery/openstack/init.go, engine/hatchery/openstack/openstack.go, engine/hatchery/serve.go, engine/hatchery/swarm/swarm.go, engine/hatchery/swarm/swarm_util_logs_test.go, engine/hatchery/vsphere/hatchery.go, engine/hatchery/vsphere/init.go, engine/service/types.go, engine/worker/internal/action/builtin_artifact_download.go, engine/worker/internal/types.go, engine/worker/pkg/workerruntime/types.go, sdk/hatchery/hatchery.go, sdk/hatchery/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor(hatchery): add CDN configuration to Worker spawn args

sdk/interpolate/interpolate_helper.go, sdk/interpolate/interpolate_test.go
=> feat(interpolate): add helper

cli/cdsctl/workflow.go, cli/cdsctl/workflow_run.go, sdk/cdsclient/client_workflow.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(cli): add delete workflow run command

contrib/integrations/artifactory/artifactory.go, contrib/integrations/artifactory/plugin-artifactory-build-info/main.go, contrib/integrations/artifactory/plugin-artifactory-promote/main.go, contrib/integrations/artifactory/plugin-artifactory-release/main.go, engine/api/api.go, engine/api/workflow/workflow_run_results.go, engine/api/workflow_queue.go, engine/api/workflow_run_secrets.go, engine/worker/internal/action/builtin_promote.go, engine/worker/internal/action/builtin_release.go, sdk/cdsclient/client_queue.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go, sdk/workflow_run_result.go, tests/fixtures/ITSCWRKFLWRT1/push-artifact.pip.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api,worker): handle multiple release maturity

engine/repositories/dao.go
No need to set the lastAccessKey here, it's already done at the end of the process
=> fix(repositories): clean cache

engine/repositories/cleaner.go, engine/repositories/dao.go, engine/repositories/processor.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(repositories): remove Lock Access in unlockfunc

engine/api/auth_local.go, engine/api/workflow.go, engine/api/workflow/factory_dao.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): workflow search add ascode filter

cli/cdsctl/experimental.go, cli/cdsctl/experimental_organization.go, cli/cdsctl/experimental_region.go, engine/api/api_routes.go, engine/api/rbac/rule_global.go, engine/api/region/dao_region.go, engine/api/region/gorp_model.go, engine/api/v2_organization_test.go, engine/api/v2_region.go, engine/api/v2_region_test.go, engine/sql/api/254_region.sql, sdk/cdsclient/client_organization.go, sdk/cdsclient/client_region.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go, sdk/doc/route.go, sdk/rbac.go, sdk/rbac_global.go, sdk/region.go, tests/08_v2_analyze.yml, tests/08_v2_cli_organization.yml, tests/08_v2_cli_region.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api,cli): add CRUD v2 organization and region

engine/api/workflow/dao.go, engine/api/workflow_import.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): workflow push opts initialization

engine/api/workflow/workflow_run_results.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): do not lock workflow run on release and promote

engine/api/workflow.go, engine/api/workflow/dao.go, engine/api/workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): compute workflow v3 preview

sdk/exportentities/pipeline.go, sdk/exportentities/pipeline_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): avoid panic during import pipeline

sdk/exportentities/v1/workflow.go, sdk/exportentities/v1/workflow_test.go, sdk/exportentities/v2/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): avoid panic when parsing empty workflow

engine/api/purge/purge_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): inject git_branch_exists var in retention only if vcs info exists

engine/config.go, engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/kubernetes/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery:k8s): allow to add custom annotations

engine/api/api.go, engine/api/config.go, engine/api/repositories_manager.go, sdk/config.go, ui/src/app/model/config.service.ts, ui/src/app/views/project/show/admin/project.admin.component.ts, ui/src/app/views/project/show/admin/project.admin.html, ui/src/app/views/project/show/admin/repomanager/list/project.repomanager.list.component.ts, ui/src/app/views/project/show/admin/repomanager/list/project.repomanager.list.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api,ui): allow to disable vcs management on project

contrib/integrations/artifactory/artifactory.go, contrib/integrations/artifactory/plugin-artifactory-promote/main.go, contrib/integrations/artifactory/plugin-artifactory-release/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): artifactory promote always update artifacts

ui/src/app/shared/workflow/wizard/context/wizard.context.html
Fix router link for workflow mutex documentation
@ovh/cds
=> fix(ui): set correct doc link for mutex workflow

engine/vcs/gitea/client_branch.go
This fixes a dropped `err` variable in the gitea client.
@ovh/cds
=> fix(vcs): dropped gitea client error

engine/api/workflow/process_node.go, engine/api/workflow_run_test.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): on retryOnlyFailedJob, retrieve build variable

sdk/hatchery/hatchery.go, sdk/hatchery/starter.go, sdk/hatchery/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(sdk): hatchery step log delay numeric

engine/worker/internal/handler_artifacts.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(worker): worker cmd list all run results

engine/hatchery/kubernetes/kubernetes.go, engine/hatchery/swarm/swarm_util_create.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(hatchery): always pull image

docs/content/docs/concepts/variables.md
In the variables concepts page, the markdown was broken after YAML code (section "Git variables"). This patch fixes the markdown syntax.
@ovh/cds
=> docs(variables): fix markdown syntax for yaml code

ui/src/styles.scss
1. Description
Displays a pointer instead of a standard cursor when hovering an element inside a `[routerLink]`
For example, hovering a project in projects list now displays a pointer cursor.
No related issues founds
1. About tests
UI only
1. Mentions
@ovh/cds
=> feat(ui): cursor pointer on ng router link

sdk/exportentities/v2/workflow.go
Fix typo on workflow error message, replace `have` by `has`
@ovh/cds
=> Fix typo on workflow error message

contrib/integrations/artifactory/artifactory.go, contrib/integrations/artifactory/plugin-artifactory-build-info/main.go, engine/api/workflow/workflow_run_results.go
+ fix buildinfo on non docker artifact: build info missing link to artifact
=> fix(api): during promotion, get build module in parrallel

engine/api/workflow_export_test.go, sdk/exportentities/v2/workflow.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): export workflow hook

engine/api/api.go, engine/api/workflow_template_bulk.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): template bulk runner count for parallel apply

sdk/workflow_node.go
=> fix(api): skip missing integration error while loading workflow

contrib/integrations/arsenal/arsenal.go, contrib/integrations/arsenal/plugin-arsenal/main.go
Sometimes when Arsenal is trying to apply a deployment, we receive some 404 from Artifactory.
When it happens, Arsenal fails and send a 400 to CDS.
This PR add the possibility to retry when this happens.
CORDEV-2550
@Inozuma
@ovh/cds
=> feat(plugin-arsenal): add retry on 400 from arsenal

cli/cdsctl/experimental_project_repository_analyze.go, cli/cdsctl/experimental_project_vcs.go, contrib/grpcplugins/action/plugin-artifactory-release-bundle-create/main.go, engine/api/rbac/dao_rbac_test.go, engine/api/test/assets/assets.go, engine/service/http.go, go.mod, go.sum
The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. ~~[`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`.~~
~~The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.~~
EDIT: Replace `github.com/ghodss/yaml` with `github.com/rockbears/yaml`
=> refactor: replace `github.com/ghodss/yaml` with `github.com/rockbears/yaml`

engine/api/environment.go, engine/api/environment/dao_key.go, engine/api/environment/environment_importer.go, engine/api/environment/environment_importer_test.go, engine/worker/internal/plugin/socket.go, sdk/messages.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): manage variable deletion and env keys as code

engine/hatchery/vsphere/client.go, engine/hatchery/vsphere/hatchery.go, engine/hatchery/vsphere/hatchery_test.go, engine/hatchery/vsphere/init.go, engine/hatchery/vsphere/ip.go, engine/hatchery/vsphere/spawn.go, engine/hatchery/vsphere/types.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: improve hatchery vsphere provisionning

docs/content/docs/tutorials/service-requirement-nginx.md
1. Correct  typo Service Requirement NGINX
1. Related to [this page](https://ovh.github.io/cds/docs/tutorials/service-requirement-nginx/)
@ovh/cds
=> doc: typo Service Requirement NGINX

contrib/integrations/artifactory/artifactory.go, contrib/integrations/artifactory/plugin-artifactory-release/main.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(contrib): manage promote/release cargo crate

engine/api/workflow/dao_node_run_job.go, engine/api/workflow_queue.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): skip booked jobs in queue

engine/cdn/item_upload_test.go
This fixes a dropped test `err` variable in `engine/cdn`.
@ovh/cds
=> fix(engine): dropped cdn test error

ui/src/app/shared/workflow-template/apply-modal/workflow-template.apply-modal.component.ts, ui/src/app/shared/workflow-template/bulk-modal/workflow-template.bulk-modal.component.ts, ui/src/app/shared/workflow-template/bulk-modal/workflow-template.bulk-modal.html, ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.component.ts, ui/src/app/shared/workflow-template/param-form/workflow-template.param-form.html
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): template apply form

engine/api/event/event.go, engine/api/event_v2/event.go, engine/api/repositoriesmanager/events.go, engine/api/v2_workflow_run_engine.go, engine/cache/redis.go, engine/hatchery/serve.go, engine/repositories/processor.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> refactor: cancel dequeue events

engine/hooks/hooks_handlers.go, engine/hooks/kafka.go, engine/hooks/tasks.go, sdk/goroutine.go, sdk/goroutine_test.go, sdk/namesgenerator/namesgenerator.go, sdk/vcs/git/git_test.go, tests/Makefile, tests/test.sh
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(sdk): allow to stop goroutine

go.mod, go.sum
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(deps): upgrade gorepo

cli/cdsctl/admin_metadata.go, cli/cdsctl/config.go, cli/cdsctl/project.go, cli/cdsctl/workflow_init.go, engine/api/project_test.go, sdk/cdsclient/client_project.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): fill favorite project attribute

cli/cdsctl/Makefile
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(cdsctl): makefile

contrib/grpcplugins/action/dockerPush/main.go, contrib/grpcplugins/action/helmPush/main.go, contrib/grpcplugins/action/pythonPush/Makefile, contrib/grpcplugins/action/pythonPush/main.go, contrib/grpcplugins/action/pythonPush/pythonPush.yml, contrib/grpcplugins/action/script/main.go, contrib/grpcplugins/grpcplugins.go, contrib/grpcplugins/grpcplugins_script.go, contrib/integrations/artifactory/artifactory-build-info-plugin/go.mod, contrib/integrations/artifactory/artifactory-build-info-plugin/go.sum, contrib/integrations/artifactory/artifactory-promote-plugin/go.mod, contrib/integrations/artifactory/artifactory-promote-plugin/go.sum, contrib/integrations/artifactory/artifactory-release-plugin/go.mod, contrib/integrations/artifactory/artifactory-release-plugin/go.sum, go.mod, sdk/v2_workflow_run.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(contrib): add pythonPush plugin

ui/src/app/shared/tabs/tabs.component.ts, ui/src/app/views/project/show/project.component.ts
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(ui): tabs component navigation

engine/api/migrate/migrate_organization.go, engine/hooks/trigger_workflow.go
1. Description
I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.
see issues https://github.com/alingse/go-linter-runner/issues/1
and the github actions output  https://github.com/alingse/go-linter-runner/actions/runs/9242659719/job/25425759865
```
====================================================================================================
append to slice `userIds` with non-zero initialized length at https://github.com/ovh/cds/blob/master/engine/api/migrate/migrate_organization.go#L40:13
append to slice `mods` with non-zero initialized length at https://github.com/ovh/cds/blob/master/engine/hooks/trigger_workflow.go#L88:13
========================================================================================= …
```
=> fix: fix miss makezero bug

contrib/grpcplugins/grpcplugins.go, engine/api/v2_workflow_run_engine.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(contrib): add cdn download uri in run result

sdk/action_parser_funcs.go, sdk/action_parser_funcs_test.go
Adds basic string manipulation functions:
- `toLower`
- `toUpper`
- `totitle`
- `title`: This one uses the `strings.Tittle` func which is marked as deprecated, but the alternative is to use the more complex [`x/text/cases`](https://pkg.go.dev/golang.org/x/text/cases) package. For this usecase, I think we can accept the downside of the function (does not handle Unicode punctuation properly for word boundaries).
Tests have been added.
@ovh/cds
=> feat(sdk): add basic string manipulation functions

engine/api/rbac/dao_rbac.go, engine/api/rbac/dao_rbac_region_project.go, engine/api/rbac/dao_rbac_region_project_key.go, engine/api/rbac/gorp_model.go, engine/api/rbac/loader.go, engine/api/v2_rbac.go, engine/api/v2_rbac_test.go, engine/sql/api/304_v2_rbac_region_project.sql, sdk/rbac.go, sdk/rbac_region_project.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): add region_project rbac model

engine/worker/internal/handler_cache.go
1. Description
"worker pull" command on Windows crashes at deleting workercache.tar. The code forgets to close the file before deleting it.
2. Mentions
@ovh/cds
=> fix(engine): close the archive before deleting it

cli/cdsctl/experimental_workflow.go, cli/cdsctl/experimental_workflow_version.go, engine/api/api_routes.go, engine/api/v2_workflow_run_craft.go, engine/api/v2_workflow_run_craft_test.go, engine/api/v2_workflow_version.go, engine/api/workflow_v2/dao_version.go, engine/api/workflow_v2/gorp_model.go, engine/sql/api/305_v2_workflow_release.sql, engine/vcs/bitbucketserver/client_file.go, engine/vcs/bitbucketserver/types.go, sdk/cdsclient/client_workflowv2.go, sdk/cdsclient/interface.go, sdk/cdsclient/mock_cdsclient/interface_mock.go, sdk/contexts.go, sdk/v2_workflow.go, sdk/v2_workflow_semver.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): compute a cds version from a helm chart or a cargo file

contrib/grpcplugins/action/addRunResult/main.go, contrib/grpcplugins/action/downloadArtifact/main.go, contrib/grpcplugins/action/uploadArtifact/main.go, contrib/grpcplugins/action/uploadArtifact/main_test.go, contrib/grpcplugins/grpcplugins.go, engine/worker/internal/http_server.go, engine/worker/internal/runtime_v2.go, engine/worker/pkg/workerruntime/handlers_v2.go, engine/worker/pkg/workerruntime/types.go, sdk/v2_workflow_run.go, sdk/v2_workflow_run_detail.go, ui/libs/workflow-graph/src/lib/stages-graph.html, ui/libs/workflow-graph/src/lib/v2.workflow.run.model.ts, ui/src/app/views/projectv2/project.module.ts, ui/src/app/views/projectv2/run/run-job.scss, ui/src/app/views/projectv2/run/run-result.component.ts, ui/src/app/views/projectv2/run/run-result.html, ui/src/app/views/projectv2/run/run-result.scss, ui/src/app/views/projectv2/run/run-results.component.ts, ui/src/app/views/projectv2/run/run-results.html, ui/src/app/views/projectv2/run/run-results.scss, ui/src/app/views/projectv2/run/run.html, ui/src/app/views/projectv2/run/run.scss, ui/src/styles.scss
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat: display download link for run results

sdk/common.go
1. Description
Starting the API with a missing directory and/or permission issue wihle trying to create said directory generates a segfault error
This is preventing new cds users from swiftly standing up cds
https://github.com/ovh/cds/issues/7199
1. About tests
The compiled binary with this patch now clearly tells me I have a permission issue, this is what I expect
```
make[1]: Leaving directory '/home/gsalingu/github/ovh/cds/engine/worker'
gsalingu@cds:~/github/ovh/cds$ cp /home/gsalingu/github/ovh/cds/engine/dist/cds-engine-linux-amd64 ~/cds/cds-engine
gsalingu@cds:~/github/ovh/cds$ ~/cds/cds-engine start api --config ~/cds/conf.toml
Reading configuration file @ /home/gsalingu/cds/conf.toml
Starting service api
Unable to init service api: unable to create directory …
```
=> fix: local artifact directory creation error segfault

engine/api/v2_workflow_run_engine.go, tests/08_v2_workflow_job_template_with_stage.yml
1. Description
1. About tests
1. Mentions
@ovh/cds
=> fix(api): load plugins for job template jobs check

engine/api/router_middleware_rbac.go, engine/api/router_rbac_rule_admin.go, engine/api/router_rbac_rule_cdn.go, engine/api/router_rbac_rule_entity.go, engine/api/router_rbac_rule_entity_test.go, engine/api/router_rbac_rule_global.go, engine/api/router_rbac_rule_hatchery.go, engine/api/router_rbac_rule_hooks.go, engine/api/router_rbac_rule_plugin.go, engine/api/router_rbac_rule_project.go, engine/api/router_rbac_rule_project_test.go, engine/api/router_rbac_rule_queue.go, engine/api/router_rbac_rule_region.go, engine/api/router_rbac_rule_region_test.go, engine/api/router_rbac_rule_user.go, engine/api/router_rbac_rule_variableset.go, engine/api/router_rbac_rule_variableset_test.go, engine/api/router_rbac_rule_worker.go, engine/api/router_rbac_rule_workermodel.go, engine/api/router_rbac_rule_workflow.go, engine/api/router_rbac_rule_workflow_test.go, engine/api/v2_websocket.go, engine/service/http.go
1. Description
1. About tests
1. Mentions
@ovh/cds
=> feat(api): project mfa required for v2 routes

ui/src/app/views/projectv2/run/run-test.component.ts, ui/src/app/views/projectv2/run/run-test.html
The v2 ui is missing the systemerr tab
@ovh/cds
=> feat(v2/ui/run): add systemerr tab to ui

sdk/action_parser_funcs.go, sdk/action_parser_funcs_test.go
For simpler workflows and jobs, I would like to add `default` and `coalesce` functions to templating functions to avoid having shell scripts steps to fallback on empty values (mostly string, but I think it's OK to handle any type of input).
@ovh/cds
=> feat(cds v2): add coalesce and default functions for ${{ ... }} templating

docs/actions/builtin-script.part.md
1. Description
The section level should be better like that.
The section level was too high.
@ovh/cds
=> fix(docs): lower headings level in the builtin script action
